INSERT INTO exercises (id,club_id,name,description,body_parts,categories,video_url,tags,options,tracking_type,equipment) VALUES
('ex_1770810675233_16',NULL,'Stability Ball Dead Bug',NULL,ARRAY['Abdominals'],ARRAY['Core','Postural'],NULL,ARRAY['Anti-Extension','Compound','Supine','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675233_17',NULL,'Bodyweight Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675233_18',NULL,'Bodyweight Bird Dog',NULL,ARRAY['Abdominals'],ARRAY['Core','Postural'],NULL,ARRAY['Anti-Rotational','Compound','Quadruped','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675233_19',NULL,'Stability Ball Russian Twist',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Seated Floor','Neutral'],NULL,NULL,NULL),
('ex_1770810675233_20',NULL,'Stability Ball Feet Elevated Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Isolation','Supine','Head Supported'],NULL,NULL,NULL),
('ex_1770810675233_21',NULL,'Ring Hanging Knee Raise',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Spinal Flexion','Compound','Hanging','Pronated'],NULL,NULL,NULL),
('ex_1770810675233_22',NULL,'Parallette Mountain Climber',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Extension','Compound','Prone','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_23',NULL,'Parallette Push Up',NULL,ARRAY['Chest'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Horizontal Push','Compound','Prone','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_24',NULL,'Bodyweight Knee Hover Bird Dog',NULL,ARRAY['Abdominals'],ARRAY['Core','Postural'],NULL,ARRAY['Anti-Rotational','Compound','Knee Hover Quadruped','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_25',NULL,'Stability Ball V Up Pass',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Hip Flexion','Compound','Supine','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_26',NULL,'Bodyweight Dead Bug',NULL,ARRAY['Abdominals'],ARRAY['Core','Postural'],NULL,ARRAY['Anti-Extension','Compound','Supine','No Grip','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_27',NULL,'Bodyweight Alternating Heel Taps',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Lateral Flexion','Compound','Supine','No Grip','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_28',NULL,'Bodyweight Flutter Kicks',NULL,ARRAY['Hip Flexors'],ARRAY['Core','Unsorted'],NULL,ARRAY['Hip Flexion','Compound','Supine','No Grip','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_29',NULL,'Bodyweight Kneeling Forearm Plank',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Extension','Compound','Prone','Forearm'],NULL,NULL,NULL),
('ex_1770810675234_30',NULL,'Bodyweight Seated Ab Circles',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Seated Floor','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675234_31',NULL,'Ring Hanging Oblique Knee Raise',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Rotational','Compound','Hanging','Pronated'],NULL,NULL,NULL),
('ex_1770810675234_32',NULL,'Stability Ball Stir the Pot',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Extension','Compound','Prone','Forearm'],NULL,NULL,NULL),
('ex_1770810675234_33',NULL,'Bodyweight Alternating Lateral Kick Through',NULL,ARRAY['Abdominals'],ARRAY['Core','Animal Flow'],NULL,ARRAY['Rotational','Compound','Knee Hover Quadruped','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_34',NULL,'Ring Hanging L Sit Flutter Kicks',NULL,ARRAY['Hip Flexors'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Hip Flexion','Compound','Hanging','Pronated','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_35',NULL,'Slam Ball Russian Twist',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Seated Floor','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_36',NULL,'Dumbbell Crush Grip Otis Up',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','Crush Grip'],NULL,NULL,NULL),
('ex_1770810675234_37',NULL,'Single Arm Dumbbell Side Plank Reach Through',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Lateral Flexion','Compound','Side Plank','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_38',NULL,'Ab Wheel Kneeling Rollout',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Extension','Compound','Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675234_39',NULL,'Cable Seated Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Isolation','Seated','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_40',NULL,'Cable Kneeling Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Isolation','Kneeling','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_41',NULL,'Medicine Ball V Up',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_42',NULL,'Suspension Knee Tuck',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675234_43',NULL,'Suspension Lateral Knee Tuck',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675234_44',NULL,'Suspension Archer Row',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_45',NULL,'Single Arm Dumbbell Turkish Get Up',NULL,ARRAY['Abdominals'],ARRAY['Full Body','Grinds'],NULL,ARRAY['Rotational','Compound','Supine','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_46',NULL,'Bodyweight Bear Crawl',NULL,ARRAY['Abdominals'],ARRAY['Core','Animal Flow'],NULL,ARRAY['Unsorted*','Compound','Knee Hover Quadruped','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_47',NULL,'Stability Ball Knee Tuck',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675234_48',NULL,'Ring Hanging Leg Raise',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Hip Flexion','Compound','Hanging','Pronated'],NULL,NULL,NULL),
('ex_1770810675234_49',NULL,'Parallette L Sit',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Isometric Hold','Compound','L Sit','Neutral'],NULL,NULL,NULL),
('ex_1770810675234_50',NULL,'Bodyweight Standing Walkout Plank',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Extension','Compound','Standing','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675234_51',NULL,'Ring Eccentric Pull Up',NULL,ARRAY['Back'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Vertical Pull','Compound','Hanging','Pronated'],NULL,NULL,NULL),
('ex_1770810675234_52',NULL,'Barbell Climb',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Extension','Compound','Standing','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_53',NULL,'Bodyweight Ipsilateral Bird Dog',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Rotational','Compound','Quadruped','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_54',NULL,'Bodyweight Copenhagen Plank Knee to Elbow',NULL,ARRAY['Adductors'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip Adduction','Compound','Side Plank','Forearm'],NULL,NULL,NULL),
('ex_1770810675235_55',NULL,'Ring Eccentric Chin Up',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Vertical Pull','Compound','Hanging','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_56',NULL,'Single Arm Dumbbell Seated Shoulder External Rotation',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Isolation','Seated','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_57',NULL,'Double Dumbbell Seated Cuban Rotation',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Isolation','Seated','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_58',NULL,'Double Dumbbell Cuban Rotation',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_59',NULL,'Single Arm Cable Half Kneeling Contralateral Shoulder External Rotation 90 Degrees',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Isolation','Half Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_60',NULL,'Miniband Fire Hydrant',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip External Rotation','Isolation','Quadruped','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_61',NULL,'Medicine Ball Russian Twist',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Seated Floor','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_62',NULL,'Bodyweight Side Plank',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Lateral Flexion','Compound','Side Plank','Forearm'],NULL,NULL,NULL),
('ex_1770810675235_63',NULL,'Cable Reverse Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_64',NULL,'Cable Rope Half Kneeling High to Low Chop',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Half Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_65',NULL,'Cable Rope Half Kneeling Low to High Chop',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Half Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_66',NULL,'Slider Double Kettlebell Bottoms Up Overhead Lateral Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Bottoms Up'],NULL,NULL,NULL),
('ex_1770810675235_67',NULL,'Cable Rope Staggered Stance High to Low Chop',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Staggered Stance','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_68',NULL,'Cable Rope Staggered Stance Low to High Chop',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Staggered Stance','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_69',NULL,'Single Arm Dumbbell Windmill',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_70',NULL,'Slider Double Kettlebell Bottoms Up Front Rack Lateral Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Bottoms Up'],NULL,NULL,NULL),
('ex_1770810675235_71',NULL,'Slider Double Kettlebell Front Rack Lateral Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_72',NULL,'Bodyweight Feet On Wall Mountain Climber',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Extension','Compound','Prone','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_73',NULL,'Slider Double Kettlebell Suitcase Reverse Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_74',NULL,'Bodyweight Hollow Body Hold',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Isometric Hold','Compound','Supine','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_75',NULL,'Dumbbell Crush Grip Hollow Body Hold',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Isometric Hold','Compound','Supine','Crush Grip'],NULL,NULL,NULL),
('ex_1770810675235_76',NULL,'Bar Inverted Hanging Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Inverted','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_77',NULL,'Bodyweight Inverted Hanging Oblique Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Inverted','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_78',NULL,'Slider Double Kettlebell Front Rack Reverse Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_79',NULL,'Bodyweight Supine Alternating Single Leg Raise',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Hip Flexion','Compound','Supine','No Grip','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_80',NULL,'Bodyweight Supine Leg Raise',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Hip Flexion','Compound','Supine','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_81',NULL,'Miniband Bicycle Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Supine','Head Supported','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_82',NULL,'Bodyweight Side Plank Reach Through',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Lateral Flexion','Compound','Side Plank','Forearm'],NULL,NULL,NULL),
('ex_1770810675235_83',NULL,'Bodyweight Sit Up',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_84',NULL,'Bodyweight Butterfly Sit Up',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_85',NULL,'Slider Mountain Climber',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Extension','Compound','Prone','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_86',NULL,'Slider Pike',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_87',NULL,'Stability Ball Pike',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_88',NULL,'Slider Wide Mountain Climber',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Extension','Compound','Prone','Flat Palm','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_89',NULL,'Stability Ball Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Supine','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_90',NULL,'Stability Ball Feet Elevated Oblique Crunch',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Rotational','Compound','Supine','Head Supported'],NULL,NULL,NULL),
('ex_1770810675235_91',NULL,'Stability Ball Kneeling Rollout',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Extension','Compound','Kneeling','Forearm'],NULL,NULL,NULL),
('ex_1770810675235_92',NULL,'Stability Ball Single Leg Knee Tuck',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_93',NULL,'Stability Ball Single Leg Pike',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Spinal Flexion','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_94',NULL,'Double Dumbbell Z Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Seated Floor','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_95',NULL,'Slider Double Kettlebell Overhead Reverse Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_96',NULL,'Double Dumbbell Romanian Deadlift',NULL,ARRAY['Hamstrings'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Hinge','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_97',NULL,'Single Arm Dumbbell Side Plank',NULL,ARRAY['Abdominals'],ARRAY['Core','Unsorted'],NULL,ARRAY['Anti-Lateral Flexion','Compound','Side Plank','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_98',NULL,'Bodyweight Single Leg Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Single Leg Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_99',NULL,'Dumbbell Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_100',NULL,'Bodyweight Glute Bridge Isometric with Alternating Single Leg Extension',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Isometric Hold','Compound','Single Leg Bridge','No Grip','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_101',NULL,'Miniband Side Lying Clamshell',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip External Rotation','Isolation','Side Lying','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_102',NULL,'Miniband Ankle Side Lying Hip Abduction',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Isolation','Side Lying','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_103',NULL,'Miniband Bench Seated Hip Abduction',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Isolation','Seated','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_104',NULL,'Miniband Glute Bridge Hip Abduction',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_105',NULL,'Stability Ball Hip Thrust',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_106',NULL,'Stability Ball Dumbbell Hip Thrust',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_107',NULL,'Bodyweight Frog Pump',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip Extension','Compound','Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_108',NULL,'Dumbbell Frog Pump',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip Extension','Compound','Bridge','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_109',NULL,'Cable Glute Kickback',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Isolation','Standing','Hand Assisted'],NULL,NULL,NULL),
('ex_1770810675235_110',NULL,'Bodyweight Single Leg Foot Elevated Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Single Leg Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_111',NULL,'Suspension Feet Elevated Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_112',NULL,'Miniband Thigh Lateral Walk',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Compound','Walking','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_113',NULL,'Miniband Ankle Lateral Walk',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Compound','Walking','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_114',NULL,'Miniband Feet Lateral Walk',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Compound','Walking','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_115',NULL,'Miniband Standing Glute Kickback',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Isolation','Standing','Hand Assisted'],NULL,NULL,NULL),
('ex_1770810675235_116',NULL,'Barbell Hip Thrust',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Bridge','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_117',NULL,'Barbell Single Leg Hip Thrust',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Single Leg Bridge','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_118',NULL,'Stability Ball Single Leg Foot Elevated Glute Bridge',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Extension','Compound','Single Leg Bridge','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_119',NULL,'Miniband Standing Hip Abduction',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Isolation','Standing','Hand Assisted'],NULL,NULL,NULL),
('ex_1770810675235_120',NULL,'Miniband 3 Way Cha Cha',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Hip Abduction','Compound','Standing','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_121',NULL,'Slider Single Arm Kettlebell Suitcase Contralateral Reverse Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_122',NULL,'Cable Hip Abduction',NULL,ARRAY['Abductors'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip Abduction','Isolation','Standing','Hand Assisted'],NULL,NULL,NULL),
('ex_1770810675235_123',NULL,'Miniband Wall Sit Hip Abduction',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip Abduction','Compound','Wall Sit','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_124',NULL,'Slider Barbell Overhead Lateral Lunge',NULL,ARRAY['Quadriceps'],ARRAY['Lower Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_125',NULL,'Single Arm Dumbbell Half Kneeling Contralateral Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Half Kneeling','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_126',NULL,'Barbell Shrug',NULL,ARRAY['Trapezius'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Scapular Elevation','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_127',NULL,'Cable Face Pull',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_128',NULL,'Cable Seated Face Pull',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Seated Floor','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_129',NULL,'Cable Guillotine Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Supine','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_130',NULL,'Cable Supine Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Supine','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_131',NULL,'Cable Straight Bar High Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_132',NULL,'Double Dumbbell Spider Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Prone','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_133',NULL,'EZ Bar Spider Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Prone','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_134',NULL,'Stability Ball Cable Preacher Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Prone','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_135',NULL,'Single Arm Dumbbell Standing Concentration Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_136',NULL,'EZ Bar Wide Grip Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_137',NULL,'Single Arm Cable Standing High Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675235_138',NULL,'EZ Bar Seated Overhead Tricep Extension',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Isolation','Seated','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_139',NULL,'EZ Bar Overhead Tricep Extension',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_140',NULL,'Barbell Thruster',NULL,ARRAY['Quadriceps'],ARRAY['Full Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_141',NULL,'Bodyweight Diamond Push Up',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Horizontal Push','Compound','Prone','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675235_142',NULL,'EZ Bar Lying Tricep Extension',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Compound','Supine','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_143',NULL,'Cable Rope Overhead Tricep Extension',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Isolation','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_144',NULL,'Single Arm Cable Reverse Grip Tricep Pushdown',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_145',NULL,'EZ Bar Reverse Grip Bicep Curl',NULL,ARRAY['Forearms'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_146',NULL,'Stability Ball Single Arm Dumbbell Chest Press',NULL,ARRAY['Chest'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Push','Compound','Supine','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_147',NULL,'Suspension Face Pull',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_148',NULL,'Landmine V Grip Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_149',NULL,'Double Dumbbell Thruster',NULL,ARRAY['Quadriceps'],ARRAY['Full Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_150',NULL,'Single Arm Dumbbell Thruster',NULL,ARRAY['Quadriceps'],ARRAY['Full Body','Bodybuilding'],NULL,ARRAY['Knee Dominant','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_151',NULL,'Single Arm Landmine Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_152',NULL,'Superband Assisted Bar Pull Up',NULL,ARRAY['Back'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Vertical Pull','Compound','Hanging','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_153',NULL,'Stability Ball Prone Cobra',NULL,ARRAY['Back'],ARRAY['Upper Body','Postural'],NULL,ARRAY['Spinal Extension','Isolation','Prone','No Grip'],NULL,NULL,NULL),
('ex_1770810675235_154',NULL,'Single Arm Dumbbell Overhead Carry',NULL,ARRAY['Shoulders'],ARRAY['Full Body','Unsorted'],NULL,ARRAY['Loaded Carry','Compound','Walking','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675235_155',NULL,'Double Dumbbell Pendlay Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_156',NULL,'Cable Straight Bar Pullover',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675235_157',NULL,'Single Arm Cable Half Kneeling Lat Pulldown',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Half Kneeling','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_158',NULL,'Single Arm Cable Half Kneeling Low Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Half Kneeling','Neutral'],NULL,NULL,NULL),
('ex_1770810675235_159',NULL,'Single Arm Suspension Low Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_160',NULL,'Double Dumbbell Incline Bench Prone Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Prone','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_161',NULL,'Barbell Pendlay Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_162',NULL,'Barbell Bench Press',NULL,ARRAY['Chest'],ARRAY['Upper Body','Powerlifting'],NULL,ARRAY['Horizontal Push','Compound','Supine','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_163',NULL,'Cable Single Leg Standing Bent Knee Hip External Rotation',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip External Rotation','Isolation','Single Leg Standing Bent Knee','Hand Assisted'],NULL,NULL,NULL),
('ex_1770810675236_164',NULL,'Cable Hip Rotation',NULL,ARRAY['Glutes'],ARRAY['Lower Body','Unsorted'],NULL,ARRAY['Hip External Rotation','Isolation','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_165',NULL,'Barbell Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675236_166',NULL,'Barbell Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_167',NULL,'Barbell Push Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_168',NULL,'Barbell Bent Over Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_169',NULL,'Single Arm Landmine Meadows Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_170',NULL,'Cable Straight Bar Seated Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Seated','Supinated'],NULL,NULL,NULL),
('ex_1770810675236_171',NULL,'Cable Rope Skull Crusher',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Extension','Isolation','Supine','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_172',NULL,'Single Arm Dumbbell Seated Cuban Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Seated','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_173',NULL,'Bodyweight Wall Facing Handstand',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Isometric Hold','Compound','Inverted','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675236_174',NULL,'Parallette Close Grip Push Up',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Horizontal Push','Compound','Prone','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_175',NULL,'Parallette Wide Push Up',NULL,ARRAY['Chest'],ARRAY['Upper Body','Calisthenics'],NULL,ARRAY['Horizontal Push','Compound','Prone','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_176',NULL,'Barbell Front Raise',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Shoulder Flexion','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_177',NULL,'Single Arm Cable Front Raise',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Shoulder Flexion','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_178',NULL,'Parallette Side Plank',NULL,ARRAY['Abdominals'],ARRAY['Core','Calisthenics'],NULL,ARRAY['Anti-Lateral Flexion','Compound','Side Plank','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_179',NULL,'Cable Straight Bar Front Raise',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Shoulder Flexion','Isolation','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_180',NULL,'Barbell Close Grip Bench Press',NULL,ARRAY['Triceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Push','Compound','Supine','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_181',NULL,'Single Arm Cable Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Supinated'],NULL,NULL,NULL),
('ex_1770810675236_182',NULL,'Single Arm Cable Shotgun Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Staggered Stance','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_183',NULL,'Cable Half Kneeling Face Pull',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Half Kneeling','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_184',NULL,'Stability Ball Double Dumbbell W Raise',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Horizontal Pull','Isolation','Prone','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_185',NULL,'Single Arm Kettlebell Bent Over Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_186',NULL,'Double Kettlebell Gorilla Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675236_187',NULL,'Kettlebell Alternating Halo',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Mobility'],NULL,ARRAY['Rotational','Compound','Standing','Bottoms Up Horn Grip'],NULL,NULL,NULL),
('ex_1770810675236_188',NULL,'Single Arm Kettlebell Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_189',NULL,'Kettlebell Horn Grip Bicep Curl',NULL,ARRAY['Biceps'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Elbow Flexion','Isolation','Standing','Horn Grip'],NULL,NULL,NULL),
('ex_1770810675236_190',NULL,'Double Dumbbell Prone Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Prone','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_191',NULL,'Double Kettlebell Z Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Seated Floor','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_192',NULL,'Double Kettlebell Push Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_193',NULL,'Barbell Prone Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Prone','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_194',NULL,'Single Arm Dumbbell Cuban Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_195',NULL,'Single Arm Kettlebell Push Jerk',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_196',NULL,'Barbell Incline Bench Press',NULL,ARRAY['Chest'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Push','Compound','Seated','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_197',NULL,'Double Kettlebell Tall Kneeling Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Tall Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_198',NULL,'Double Dumbbell Incline Bench Prone Y Raise',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Postural'],NULL,ARRAY['Unsorted*','Pull','Prone','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_199',NULL,'Suspension Face Pull to Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_200',NULL,'Double Dumbbell Reverse Grip Bench Press',NULL,ARRAY['Chest'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Push','Compound','Supine','Supinated'],NULL,NULL,NULL),
('ex_1770810675236_201',NULL,'Single Arm Cable Seated Floor Lat Pulldown',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Pull','Compound','Seated Floor','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_202',NULL,'Double Dumbbell Suitcase Carry',NULL,ARRAY['Forearms'],ARRAY['Full Body','Unsorted'],NULL,ARRAY['Loaded Carry','Compound','Walking','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675236_203',NULL,'Single Arm Resistance Band Half Kneeling Cuban Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Half Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_204',NULL,'Double Dumbbell Cuban Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Shoulder External Rotation','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_205',NULL,'Double Kettlebell Pendlay Row',NULL,ARRAY['Back'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Horizontal Pull','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_206',NULL,'Double Kettlebell Half Kneeling Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Half Kneeling','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_207',NULL,'Single Arm Kettlebell Push Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_208',NULL,'Double Kettlebell Push Jerk',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_209',NULL,'Double Dumbbell Glute Bridge Isometric Floor Press',NULL,ARRAY['Chest'],ARRAY['Full Body','Bodybuilding'],NULL,ARRAY['Horizontal Push','Compound','Bridge','Pronated'],NULL,NULL,NULL),
('ex_1770810675236_210',NULL,'Double Kettlebell Seesaw Overhead Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Unsorted'],NULL,ARRAY['Vertical Push','Compound','Standing','Pronated','Alternating'],NULL,NULL,NULL),
('ex_1770810675236_211',NULL,'Alternating Double Kettlebell Z Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Seated Floor','Pronated','Alternating'],NULL,NULL,NULL),
('ex_1770810675236_212',NULL,'Bodyweight Burpee',NULL,ARRAY['Chest'],ARRAY['Full Body','Unsorted'],NULL,ARRAY['Horizontal Push','Compound','Standing','Flat Palm'],NULL,NULL,NULL),
('ex_1770810675236_213',NULL,'Double Dumbbell Devil Press',NULL,ARRAY['Shoulders'],ARRAY['Full Body','Unsorted'],NULL,ARRAY['Horizontal Push','Compound','Standing','Neutral'],NULL,NULL,NULL),
('ex_1770810675236_214',NULL,'Alternating Single Arm Dumbbell Devil Press',NULL,ARRAY['Shoulders'],ARRAY['Full Body','Unsorted'],NULL,ARRAY['Horizontal Push','Compound','Standing','Neutral','Alternating'],NULL,NULL,NULL),
('ex_1770810675236_215',NULL,'Double Kettlebell Seesaw Z Press',NULL,ARRAY['Shoulders'],ARRAY['Upper Body','Bodybuilding'],NULL,ARRAY['Vertical Push','Compound','Seated Floor','Pronated','Alternating'],NULL,NULL,NULL)
ON CONFLICT (id) DO NOTHING;