UPDATE exercises SET video_url = 'https://youtu.be/hcQJcKxc240' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/pjk0vGe9YRU' WHERE LOWER(TRIM(name)) = LOWER('Ring Straddle L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/VWnVBfRkLXE?si=AeN6Q9aAnShqxuIb' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/UiY-JIpmt24?si=ox4YNd9xIIVapyeB' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Half Kneeling Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/Lk0xszw7Tf8?si=GHtFcn5OVifRVyDQ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tall Kneeling Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/NP4p_SWAgnA?si=VoTKPhBbaaWrrYZH' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Half Kneeling Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/L_Y8osw78lA?si=3eK1QuOTlQjCzAxO' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/7L90imlW0es?si=gY7k7XVC43IRrv-N' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/j83lzC2E4Ss?si=PcoF092JVJRpg8T4' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Wide Grip Strict Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/6wyxpVY8PQ0' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/do1yf3NMXdg' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Hollow Body Hold');
UPDATE exercises SET video_url = 'https://youtu.be/xkCR2CkkL1g?si=Qy0YPAcCasZF6kNk' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/UW52u8OaWhw?si=WdEOpAR_PSB9x9bR' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Side Lying Hip Adduction');
UPDATE exercises SET video_url = 'https://youtu.be/8QRsSJ-Ny8M' WHERE LOWER(TRIM(name)) = LOWER('Superband Hollow Body Hold');
UPDATE exercises SET video_url = 'https://youtu.be/3FYYo6lP-dw' WHERE LOWER(TRIM(name)) = LOWER('Parallette Freestanding Handstand Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/yAOulKW0al4' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Leg Eccentric Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/aAErmRDDJKY' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Freestanding Handstand Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/CXVqHGLmb3Q' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Grip Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/JG0Ay2QDVbI' WHERE LOWER(TRIM(name)) = LOWER('Superband Side Plank Hanging Hip Adduction');
UPDATE exercises SET video_url = 'https://youtu.be/ZNCupJIYP6M' WHERE LOWER(TRIM(name)) = LOWER('Ring Strap Bulgarian Handstand Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Rc5e-DsD--M' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/HOQeoz3zQeo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Hollow Body Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/IU_0IBe4G9w' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/NAZ9uF9S_wk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/Gzz3ku70W3I' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bent Arm Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/2Tt0XZ2pZyE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Cyclist Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/ExJCssj4YV0' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Q3yDIeMfdNg' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/2Pk8jmse6vY' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/mYQAYnr2hlg?si=gqlNGvKWytXXQP1H' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Chest Roll to Straight Body Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/TxkC9nrvOho' WHERE LOWER(TRIM(name)) = LOWER('Ring Bent Arm Bent Body Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/1XyV5eNL1z0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Sumo Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/1cVT3ee9mgU' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Swing');
UPDATE exercises SET video_url = 'https://youtu.be/WK4ughYoUEI?si=2mvQ9x0jZEF2zzRA' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Swing');
UPDATE exercises SET video_url = 'https://youtu.be/dPN2mj5R2S8' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Clean');
UPDATE exercises SET video_url = 'https://youtu.be/0aq5EW0euvA' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/L2WY5gYUb1U' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Staggered Stance Swing');
UPDATE exercises SET video_url = 'https://youtu.be/Ss7KjOjCpVU' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Alternating Staggered Stance Swing');
UPDATE exercises SET video_url = 'https://youtu.be/QVvrdVbq9qs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Swing');
UPDATE exercises SET video_url = 'https://youtu.be/zrvtXpwVTOI' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Outside Swing');
UPDATE exercises SET video_url = 'https://youtu.be/Fx-qV1dHGi4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Outside Half Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/QtlvLhVFR40' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Outside Clean');
UPDATE exercises SET video_url = 'https://youtu.be/YBJnavxcbUA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Side Swing');
UPDATE exercises SET video_url = 'https://youtu.be/59_aq7COfts' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/wjYNzITBDqg' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/q1TuasYdM2M' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Skater Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-A7yvmUv8Cw' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JGY8VuvaEHc?si=LVWYZO5Qt-3WONJf' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Hollow Body Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/FRBr2pomeOM?si=15TQvL3xIskTVzVA' WHERE LOWER(TRIM(name)) = LOWER('Ring Back Lever Pullout');
UPDATE exercises SET video_url = 'https://youtu.be/5Fx69TRWARc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Overhead Press');