UPDATE exercises SET video_url = 'https://youtu.be/9ZxNf7ZyXNA?si=RYR75ThTJf8rKwxi' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/EtPb646Va9s?si=J7PWxe7OwlEdfLZW' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/2dw6SwEJlH4?si=UCaE7pKKJDaRm0lz' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Seated Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/K2AvS_4hjd4?si=WeXgOnAQd6Db4L-d' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet Elevated Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/B1brbzxGCqM?si=OdHzF3vTHn2YmADJ' WHERE LOWER(TRIM(name)) = LOWER('Miniband Feet Elevated Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/hKUOvDXVREw?si=RIjR5zIo0hOuYfY0' WHERE LOWER(TRIM(name)) = LOWER('Miniband Feet Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/_oFQ3G5iwtc?si=3F2p69DpOKAmGXoE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Reverse Plank');
UPDATE exercises SET video_url = 'https://youtu.be/fpUD0mcFp_0?si=Ymlmi7cDC_sfB1zE' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Toss');
UPDATE exercises SET video_url = 'https://youtu.be/Bio87vFoJW8?si=NJ1qbIlIwQxlLPYE' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Feet Elevated Russian Twist Lateral Toss');
UPDATE exercises SET video_url = 'https://youtu.be/R87xzEuBmlY?si=tsszJ0gQHwdhFaFH' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Lateral Toss');
UPDATE exercises SET video_url = 'https://youtu.be/mSSReQ1b9NQ?si=XbGTmB14_eldcuBz' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Sit Up Toss');
UPDATE exercises SET video_url = 'https://youtu.be/Rd3pRGf7fyQ?si=E19yq3x4ySAePC_i' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tall Kneeling Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/15EmaPxPbe4?si=K_IYnXhJNu1WAP8c' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/EeNk8sLr9z8?si=kN5JtBlDa5WiKxzK' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/o_M9wYTtIBA?si=BXIV9tiqPcpzzreB' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Xv7xtX-iHXw?si=Tr0jv2-w6qpFctJh' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/WQUXh0Zk1XU?si=nWvh_443nHiOu2bH' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/7obV55SSiaw?si=S805NWBkc0FbMt7c' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/h_S_Bb9rWCE?si=Dr_V3tDtxcRysPGX' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JlcQSTjIpk8?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/H5KGoSK1TMw?si=wfO6lfzcy7AhIt-M' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/FpwomyrCcCk?si=JJyauhDa3bMzRSkq' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Foot Elevated Contralateral Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/yw2PSqN1ELo?si=2h_po3eQI5bN1T8l' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Z-9VnaY1F7k?si=NW_jj2yOwfUGesC3' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/IgatQ8Mh6nM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Vl3Gb37CyMI?si=claxpb93HZUyctUA' WHERE LOWER(TRIM(name)) = LOWER('Suspension Alternating Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/eT5ol-m5gQU?si=1yRDnXPgi913NC1Q' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/PL3rLZbBgZQ?si=NevvL1vzasNBOgVT' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Bf4HVTwMjkc?si=j0OgjVc5PW-T2bs6' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/nogkCbiduHI?si=5gA5NaZqt_y4a8ir' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Fc6I5y692zE?si=WC2rmdrASF2eyb71' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/c9SSkKRR_fc?si=MOjZ2orbxCB5hdiO' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/jmgelOGoxE8?si=dRdbKJvwm7kJy_Fs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/XpcDH-_hkD8?si=ZolNMoUBWOAc0Xms' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/EUHaKY3aA1Q?si=H2a-9iB71twMingb' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/w0CTy_eIIcM?si=RtrXOHk6gyF6NsFi' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/0DwFec0Aeog?si=bohJ8yWsahjfyyVf' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/VI6qhpokyPI?si=vlQYMvQBOEZ4sjof' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/p3aoeo0dbZg?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/EDEgJ8gSJHo?si=tuk25VgOk61zTjT4' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ayWcRkvxO-I?si=AtCYmB8SJA-QD071' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/h1IDfUy9JCg?si=8aLbq-QZwId9tfAE' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/b0rzm8OUjAc?si=Rz4zXBOgcisU6tEb' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/oMbi7Tppy-Y?si=xztRuodoUOeyiGKn' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Tall Kneeling Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/IfR7ezW6Oxc?si=-Zb29PMa_gZ8yJr9' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/kZKDLL-1IXw?si=wnx7XbsDFO37wHb3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Front Rack Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/rD7QCqe4g0k?si=13maugTiL5P1XI6m' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Suitcase Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/spmQS--R39Q?si=CXJgE_ppmc8oU7i4' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Gunslinger');
UPDATE exercises SET video_url = 'https://youtu.be/Xy9DrXmYIdw?si=e3qLZQjQ9a0RnC4q' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/NH32TQinW94?si=UfgmRs54Foklrrlw' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Split Squat');