UPDATE exercises SET video_url = 'https://youtu.be/lbnYFCHrjvk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/Lcm7DcXbm-U' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Dead Clean');
UPDATE exercises SET video_url = 'https://youtu.be/FAtcUX6VxWo' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Dead Clean');
UPDATE exercises SET video_url = 'https://youtu.be/O1mck-Oil5Y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Bird Dog Row');
UPDATE exercises SET video_url = 'https://youtu.be/U6kn-AypL7c' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Half Kneeling Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/U_kv9LRu6_I?si=o6wONfSHOO4nrgpy' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Renegade Row');
UPDATE exercises SET video_url = 'https://youtu.be/LMQIG45Wwd8' WHERE LOWER(TRIM(name)) = LOWER('Ring Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/or7xH0BirKw?si=5oL6x2NsxvCfWaBo' WHERE LOWER(TRIM(name)) = LOWER('Ring Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/5Cs27w8WVz4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/owbzzfb-0PQ' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Landmine Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/xO7fmvTpy3M' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bent Press');
UPDATE exercises SET video_url = 'https://youtu.be/sBuAJggOIxE?si=CST2KlC-8f_fnogp' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/j9sFzOeMmxY?si=i2yJV3WJb2pBCf0X' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Low Switch Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ORoOn93dnh4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Half Kneeling Contralateral Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/kBQ1krvKFBU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/vjAjAERSkIk' WHERE LOWER(TRIM(name)) = LOWER('Plate Otis Up');
UPDATE exercises SET video_url = 'https://youtu.be/WPIrFREyNaw' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/NqZPSUqSJlA' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/TVTHezj2ZLg' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Tall Kneeling Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/app94pzXOuU' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/D73Oy2m-Uoc' WHERE LOWER(TRIM(name)) = LOWER('Barbell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/gn5Uy0z5DyY?si=cNwcH7q0lucOSGDX' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/qTD9lWjff84' WHERE LOWER(TRIM(name)) = LOWER('Suspension Atomic Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/J6xUudO95Gc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/_Qbz_54_9Sw' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Archer Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Wg2mF-GjD10' WHERE LOWER(TRIM(name)) = LOWER('Parallette Archer Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/PenQnEuayM4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/ABSpTs17ObA' WHERE LOWER(TRIM(name)) = LOWER('Ring Skin the Cat');
UPDATE exercises SET video_url = 'https://youtu.be/DGzBcpLm8T4?si=VFc6IG7H7vAlBgxV' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/2mDqNOd-Pco?si=MiZ8nJsVAje_rZfb' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/u3XIZSv2Npw' WHERE LOWER(TRIM(name)) = LOWER('Ring Feet Elevated Row');
UPDATE exercises SET video_url = 'https://youtu.be/k84lpDtf5kQ' WHERE LOWER(TRIM(name)) = LOWER('Ring Feet Elevated Bulgarian Row');
UPDATE exercises SET video_url = 'https://youtu.be/u8tOhNwiL70' WHERE LOWER(TRIM(name)) = LOWER('Ring Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/ytAxGbZ7g80' WHERE LOWER(TRIM(name)) = LOWER('Ring Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/kw3ht7nZbXs?si=9ZaHvZoUYJK9H_2w' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Feet Elevated Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/DrpIWrG7rl8' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Half Kneeling Contralateral Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/NENoxvoyaTw' WHERE LOWER(TRIM(name)) = LOWER('Parallette Alternating Shoulder Tap Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/tpCOg3ZKn3w?si=e_92TbjIAIy3thZh' WHERE LOWER(TRIM(name)) = LOWER('Parallette Dive Bomber Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/kz5dpeSigAI' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/CeNiZ52DzU0' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/QB9bEZQl6Mg' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/LXmJg15hurY?si=kuUaXsoiL3fnTOE7' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Dragon Flag');
UPDATE exercises SET video_url = 'https://youtu.be/y94uWhVJ3D4?si=TIKacdZm8d8i5e6M' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Dive Bomber Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/v6oj7ImoVP4?si=F3GtqX0vk8YHIyZm' WHERE LOWER(TRIM(name)) = LOWER('Parallette Full Planche');
UPDATE exercises SET video_url = 'https://youtu.be/731lQp2shpY' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Renegade Row to Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/qO5ZqLJD_ZQ' WHERE LOWER(TRIM(name)) = LOWER('Ring Inverted Iron Cross');
UPDATE exercises SET video_url = 'https://youtu.be/b2ELsjM9KQQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/ch0kaD--kIA' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Planche');
UPDATE exercises SET video_url = 'https://youtu.be/hTpQCPjYZ3w?si=jlVsTRhe4TDGXMhx' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Full Planche');
UPDATE exercises SET video_url = 'https://youtu.be/MZi0M3OJEVw' WHERE LOWER(TRIM(name)) = LOWER('Cable Quadruped Hip Abduction');