UPDATE exercises SET video_url = 'https://youtu.be/iMjJRSR2VjU?si=aNlEfyCdPcY-CarB' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/JFAHbtg7yGo?si=D0wQ8DZcL7yrM3kB' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Half Kneeling Ipsilateral Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/-2epiOMX6MA?si=uVZg_03GZULcCJ7F' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/8iDWbo_j5v0?si=sHXK18f-6Tt7DZDW' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Gorilla Clean');
UPDATE exercises SET video_url = 'https://youtu.be/4PEb0vOgK-c?si=VnLjpuKoW3QEQjAS' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/P6etpDUfGWE?si=PNWuo_7oxajSyVST' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/8ZojxSRyeSc?si=VyMvt77RkP4-J8_Z' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/vYpsixm7ETY?si=OnSWh63rxbrpvpV9' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/SDe0leCDjKA?si=GubJDQVVx4IoBbJa' WHERE LOWER(TRIM(name)) = LOWER('Suspension Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/5mF3RrwkX-M?si=sDX18PL3XzhLlBhu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Bent Knee Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/LgDDIt6oXkM?si=KauCb0BONYq4Old8' WHERE LOWER(TRIM(name)) = LOWER('Suspension Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/tW2C6Lo__Yk?si=Yp5YaQGXIq81DkOp' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/iwRRckk8aSg?si=JM8g4iDrUB-VdtU4' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Half Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/-W0wS5W_PVw?si=5DGjI1VND3VVMHPC' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/brZSl8Vvn1k?si=5ow9W6khPHpplZlE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/f3LvSVbDINk?si=fJJqDtL6UzxX6HF2' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/KKoE4bpJFHg?si=w_Jg92Al0uWTHBrc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Incline Bench Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/gXoD6NsVG6A?si=T_xS8jfGx-kpADhE' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/JfCsmOJVVZY?si=RffYK1zASlVfYN1a' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/hGE3lxAF2Ew?si=MwJzQO_RzHV8FcbT' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/UtdszXND3fg?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Half Kneeling Concentration Curl');
UPDATE exercises SET video_url = 'https://youtu.be/MbQWu3GdWfc?si=KbIZoybRZD3g6-FW' WHERE LOWER(TRIM(name)) = LOWER('Sled Push');
UPDATE exercises SET video_url = 'https://youtu.be/gdtO9qeaiCE?si=S9DCMUsrnQHGFG6p' WHERE LOWER(TRIM(name)) = LOWER('Sled Rope Pull');
UPDATE exercises SET video_url = 'https://youtu.be/2E_kPuk5hvE?si=S5YhKa1bP3YcStRr' WHERE LOWER(TRIM(name)) = LOWER('Sled Rope Seated Pull');
UPDATE exercises SET video_url = 'https://youtu.be/r5cW_epFjIw?si=VKB6obgn3EIvcAkZ' WHERE LOWER(TRIM(name)) = LOWER('Sled Forward Drag');
UPDATE exercises SET video_url = 'https://youtu.be/Lfra9QN-CEY?si=8LJ2F_o_hqib0dW7' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/VqGvsMrYawU?si=Ori5Rji8qPy2ADXI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tactical Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/jygDw93Kpec?si=9DxPSP8Q1CPy0yy6' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Incline Bench Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/TIwtTz5DX30?si=V3tF_pgDukqaKglY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Bayesian Curl');
UPDATE exercises SET video_url = 'https://youtu.be/WT7TZA3xBHA?si=15gqGEo-GBZLm2qa' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Incline Bench Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/cMTMeVuzxrc?si=APyA08cxZpcn68qE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Kneeling Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/E7vYUfMcFhs?si=bti9p5lCqTpD-Y-q' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Suitcase Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/29MJct32_6Y?si=ItNGT0m2qUZTy4_O' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/OzrufXl0b4g?si=Oc_ebRjhZGfC10tB' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tall Kneeling Lateral Raise');
UPDATE exercises SET video_url = 'https://youtu.be/-L-M4f3qHZA?si=9IPQGch1yER949WQ' WHERE LOWER(TRIM(name)) = LOWER('Sled Reverse Drag');
UPDATE exercises SET video_url = 'https://youtu.be/bvCa5-w0hvo?si=FdCVlFz1TmRP9LXb' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/0eQnBZCrwVM?si=pY5IcCp4BNxSyhZL' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/oAaAFOKIojs?si=zUlHomJXt3sLWs_Q' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Tall Kneeling Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/FMnsYQaeICE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/FxVNp1EAcvo?si=XUiRmuJ_4P8w8nEj' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Incline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/-ngqbDJP-QE?si=onuXRsIy65F_bbPM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/88FvxU3txl4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Decline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/vlASvQCD4lY?si=H4b5rDHWlAXSfLEz' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Bar Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/Cz7-hfa1UG8?si=cU9RS2gcX9ME3VFs' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/Uhi9c2SDl6o?si=hootzYYWD4d2powE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Feet Elevated Pike Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/PvvNgvRwqXI?si=UMeSCbCrmSwbFJre' WHERE LOWER(TRIM(name)) = LOWER('Sled Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/tKZ_IjDX7fA?si=ymbKZ_6m6CiddaOL' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Bar Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/MTpg2fM-_F4?si=oQ-nElz0soKFgFHT' WHERE LOWER(TRIM(name)) = LOWER('Bar Commando Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/qUzqwzTWLoc?si=t4nKfRciAYbHRJyr' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Bar Commando Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/YPIv3MogGgo?si=W46_DHRaS-ROfgcb' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope L Sit Pull Up');