UPDATE exercises SET video_url = 'https://youtu.be/CKKfNBe687Q' WHERE LOWER(TRIM(name)) = LOWER('Barbell Incline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/TBpk09QuVN8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Kneeling Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/cp_Hl7qd7CI?si=Tw8VVXnhtyW9vra4' WHERE LOWER(TRIM(name)) = LOWER('Suspension Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/ELmdfR9JvEA' WHERE LOWER(TRIM(name)) = LOWER('Suspension Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/pHsw9uHVXWA?si=0LlXNPKcyTKyfgU4' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Double Dumbbell Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/TI1gb3GFUVA' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Dumbbell Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/JSDpq14vCZ8?si=DX2UhxTVlOLFkyF3' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/hULU2N_9qjk?si=XmozOzBr-Uny0t4A' WHERE LOWER(TRIM(name)) = LOWER('Suspension Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/44E5KRVFWVQ?si=M9W-NS9JbwJV8hDU' WHERE LOWER(TRIM(name)) = LOWER('Tire Flip');
UPDATE exercises SET video_url = 'https://youtu.be/4h3cIxkFwlI?si=s_iXYmvt1ljfSFML' WHERE LOWER(TRIM(name)) = LOWER('Tire In and Out Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/wkMhmQ5wVWY?si=kFZCkvoaBfUNdjvU' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/UCfMPCfug60?si=hzjhqnpt1-9bHCWt' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/wsOcmGYOn3M?si=2w1Cs0RdcdjnHLYG' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/W-nnq0Ks1A0' WHERE LOWER(TRIM(name)) = LOWER('Suspension Mid Row');
UPDATE exercises SET video_url = 'https://youtu.be/3ZRe_QpvRPg?si=X5ees0OsHDogPrA9' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/hv00OCqm0HI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/JUDbOvgH6AQ?si=p3CkDDLIlKjuufVF' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/HwG4_WIMB7g?si=ly2SGRWM5lHuzOHF' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/tg3HcGWhGN8?si=i7ZBKBUTgTovDmeO' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/5hkhz_nMuws?si=gPxN6_F1w9qQdHvy' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Foot Elevated Single Leg Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/5hkhz_nMuws?si=M_cdEJeEYZLJJD6j' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Single Leg Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/AWBGE0PlYkI?si=INJvlHfbZ6BpG0RT' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/Q8s5KVgRjsI?si=LU2DAUzkwtjOm87N' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/bNmYhWaTtDE?si=0pRJsSgsFQN8tX9D' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell L Sit Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/nDJ9cjw2J7Y?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/-zJsdaS13fk' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/-ouYHaP9g9g?si=qc9f_XLeK0tBdsDc' WHERE LOWER(TRIM(name)) = LOWER('Tire Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/nQKgHwi8W9E?si=h2cdsN6y8_YWkxWd' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Supported Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/XPrwraNV8zU?si=uYKDsDSy6F1lqx7L' WHERE LOWER(TRIM(name)) = LOWER('Cable Seated Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/tSDRe05L18Q?si=tzWWp_aDlp6K7_QS' WHERE LOWER(TRIM(name)) = LOWER('Cable Seated Single Leg Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/oV97EckMQlo?si=-UB0G60JaIQ6f-4v' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/2amvxbpU20c?si=ymK8PzcHyFCMv-oX' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Seated Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/hP0wET7bCog?si=trU9Rde7VACKCuEn' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/w6vfiCgfbXA?si=RhaJhv_PYjW4LLj5' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Low Hold Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/W5FNgQSaDfU?si=mrb4anmAuXMyWfuC' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/TyJOknODp8g?si=lIKKdyiWkncjpZtZ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/fZeR04SyMnM?si=PcC3GMitpRy-d_N5' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/YtKIXuPCj1M?si=ng5HKT4Y_EUFLk95' WHERE LOWER(TRIM(name)) = LOWER('Tire Leg Press');
UPDATE exercises SET video_url = 'https://youtu.be/zMR-P_9GGKE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Cable Isometric Split Squat Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/pM_ycFCgDxU?si=YT2fo22-rIu4kKPM' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Isometric Split Squat Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/mdl2K7zkcQ8?si=HIQ62ZGgxGxvMCfb' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Isometric Split Squat Foot Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/hn0H9wrT7I0?si=2puOZbS5dzRQTGh6' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/d7cVOMtyjS8?si=-LwL939gyb_zs3lu' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/xASrMCHjL4M?si=-Ue1QOKJH5pRPoTH' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/YGGq0AE5Uyc?si=or6Xddi0YaAkHuXV' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/R61TjoYofDE?si=sA8kbakWIt24ow1A' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/hKLIHPXmPA4?si=mk9hkktF_4qw0okV' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/EhAho9Szp-0' WHERE LOWER(TRIM(name)) = LOWER('Cable V Grip Seated Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/pxnaBaRRZiY' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Half Kneeling Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/NZSBjpVpvw8?si=lyk8zIAtzX2ETUc_' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Prone Cobra');