UPDATE exercises SET video_url = 'https://youtu.be/wo-YhhSpEJI' WHERE LOWER(TRIM(name)) = LOWER('Cable V Grip Seated Floor Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/ZujykKeVZpM' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/fjYbHu5oXn0?si=h7OFn1fToKpfmC3B' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Tall Kneeling Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/VuvZCiSMw_A?si=wJFjWj_7127inskf' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/ujcZZ0kLEmY?si=Vb7GDY3_NgNICWqW' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Reverse Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/zH8QN413Vuo?si=htM_QtEmupefpV2z' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Frog Reverse Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/UP44YFNMF4A?si=ymXfKPXP3jXmkT4j' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Reverse Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/dz0OxCiLkjI?si=-FrxaHRLjT-KzMPb' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Tall Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/7UVgs18Y1P4?si=o0GvxxE-1wAYvgfE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight V Up');
UPDATE exercises SET video_url = 'https://youtu.be/svmnL4VOmdQ?si=LsXy5ZYYQ72FtD7F' WHERE LOWER(TRIM(name)) = LOWER('Slider Barbell Back Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/X9swqObTGJw?si=Qpxrkq0cR0xf5eiU' WHERE LOWER(TRIM(name)) = LOWER('Slider Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/VrHNJXoSyXw' WHERE LOWER(TRIM(name)) = LOWER('Barbell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/LtoksZKesMA?si=rSvsSk9ilVqlS937' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/GqAEuwXQXRU?si=a2lQdD8ZT7OeBRNX' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/sEerteQ9q8Y?si=eO7tUCscpuCkcIez' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Outside Swing');
UPDATE exercises SET video_url = 'https://youtu.be/61BWrwBMUlk?si=zXjflLRvn7EaFnuR' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Alternating Forward Lunge Pass Through');
UPDATE exercises SET video_url = 'https://youtu.be/6flBwO_bKB8?si=_cijIvoTOn2fDR7y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Alternating Reverse Lunge Pass Through');
UPDATE exercises SET video_url = 'https://youtu.be/T6QWzXtiHVk?si=6Qx4S0Y9YS8kR-E8' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Contralateral Forward Lunge Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/yVbXFUpxZDo?si=fGc1RAIfM6JUdZ4B' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Alternating Forward Lunge Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/IfGxPcgiTmY' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/F3Y03RnVY8Y?si=8uzaga9fPI14rc9M' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/hEEUpEwRE7g?si=x48upd1YMj1w_xrR' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Glute Bridge Isometric Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/MAiTY-4x82Q?si=zKIXO7qWRH9Fp9yh' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Dumbbell Suitcase Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/RoS53TjR2QY?si=6bemyT1DeK6D_ziA' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Dumbbell Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/jo1G9aygVIY?si=rDCyU7nAR0DQrhQr' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Dumbbell Suitcase Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/t27p0HCStHg?si=P5VidxzYpMaxRdyY' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Dumbbell Overhead Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/fM0TQLoesLs?si=Jdgh0xyXpZA-KwyM' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/-umNkuKth1U?si=17upb868pBHT1MIg' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/EKtY3UJFmTg?si=_1L9MCgCQ4f1c_fB' WHERE LOWER(TRIM(name)) = LOWER('Slider Landmine Shoulder Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/XUrqwdRtU54?si=i9PTTagf_EVKwx0j' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Landmine Suitcase Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/NcyZj45wcnY?si=cwEgFB3aBkfIjMQy' WHERE LOWER(TRIM(name)) = LOWER('Suspension Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/xt1UdzhkMfY?si=OIM1LWctboVJi66d' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/XuYszvlq1Zk?si=cRt_Xb7fwOGFU40U' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/Zr2RLjIjCN0?si=CFxCFwgSlgd_2sCv' WHERE LOWER(TRIM(name)) = LOWER('Miniband Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/LD5vanDs9G4?si=beAWPFWY1Y8shTBO' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Top Down Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/oPk0SGlvX98?si=AjZmhQyk03HHYgPO' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Top Down Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/Ztg7B04oVXU?si=KGYDSnNrZiBMfVab' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Top Down Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/4RqNGRVaTUQ?si=geYUBIdFOo8AzeHT' WHERE LOWER(TRIM(name)) = LOWER('Bar Dead Hang');
UPDATE exercises SET video_url = 'https://youtu.be/FYx76NSijfU?si=SQ4p_SUWbJGUlk0N' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/UfCzhPWBmhU?si=PEQal1FTSXhdUQED' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Staggered Stance Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/E-6iFVLC66I?si=HTrleCkD1HyCvWuq' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Alternating Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/XLnOFLtWCaU?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/VrOZZjPvj84?si=nwwNU54x-itcb4Ha' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/zUV4jRr6DPk?si=WdsGqclPVPcWvX9C' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/-CSU1ZIDcRs?si=r1puJp7Mv2H5UpDs' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/df-MeZsxCAM?si=DWozx3zEr924L2oN' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/2L_LpH_IIbc?si=bI9uPdiltgD6G9Mf' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/xE20IwkSELc?si=FM0m4qOgocoDEdDz' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/Rn-hf5iauTc?si=9JMXffEInfAmWfNH' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Chest Press');
UPDATE exercises SET video_url = 'https://youtu.be/m3wEZExvGCY?si=qPi52D7LtCC72Ccj' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Alternating Chest Press');