UPDATE exercises SET video_url = 'https://youtu.be/N1NCIgaCbmo?si=50uKC_L4pEPyhR7m' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Seated L Sit Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/X91DSVDBT1s?si=UevmYNdSAy0aA49t' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Hanging L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/ul8G6NfwcKE?si=bP1jwilThrtCP37m' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Hanging L Sit Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/ZuDgEhPspvo?si=BndR3kA8YnLxuZxN' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope L Sit Climb');
UPDATE exercises SET video_url = 'https://youtu.be/rfr-Tw3Pxh8?si=qrQ6_5_lPNIjF4eo' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Legless Climb');
UPDATE exercises SET video_url = 'https://youtu.be/Pa4QUC9AvuA?si=_elyMb15TpqfSXja' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope J Hook Climb');
UPDATE exercises SET video_url = 'https://youtu.be/zBoTgBpkn7o?si=3Ix0hv2wZwd-m2Co' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope S Wrap Climb');
UPDATE exercises SET video_url = 'https://youtu.be/P8Wv46CjIs4?si=z2T1LOoTqom5vyKi' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Single Leg Standing Bent Knee Alternating Halo');
UPDATE exercises SET video_url = 'https://youtu.be/05ABqEEgasA?si=8BF9AxQrgT3OY5u_' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher March');
UPDATE exercises SET video_url = 'https://youtu.be/3Lc1n1iXM7s?si=7mcqsAivpC6eUgMu' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight March');
UPDATE exercises SET video_url = 'https://youtu.be/UFgykifRSvQ?si=lUaVB8ZhF8ACrc4h' WHERE LOWER(TRIM(name)) = LOWER('Suspension Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/1kfxGBCXvrk?si=8pQzSrl0T2_7bVLw' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Dead Hang');
UPDATE exercises SET video_url = 'https://youtu.be/yFt5UltkFCA?si=o0SXv0YEikxLTThg' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/duhPBZkq0xg?si=K4QIb8cjoQDdU-dJ' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Reverse Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/k9W6g9LvXDI?si=r2ny_BUMtle93fEw' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Overhead Slam');
UPDATE exercises SET video_url = 'https://youtu.be/LhCS360FBvA?si=NOWK4R-Br_tSVldj' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Tall Kneeling Overhead Slam');
UPDATE exercises SET video_url = 'https://youtu.be/LcgWDIYgnhg?si=OWBjxnU5ZUG1gCzK' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Squat Jump Overhead Slam');
UPDATE exercises SET video_url = 'https://youtu.be/UwWVqgePy2w?si=r4YTnAupde84IgyA' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Tall Kneeling Alternating Rotational Overhead Slam');
UPDATE exercises SET video_url = 'https://youtu.be/rNsE0g9PeeA?si=zcNMA2u1Mkdf3Opf' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Shrimp Squat');
UPDATE exercises SET video_url = 'https://youtu.be/c-g9fmlQ5l4?si=-RKC_mk2P8oIA0kz' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Shrimp Squat');
UPDATE exercises SET video_url = 'https://youtu.be/8A53W4ABe5I?si=PlVzkrowfJy1WXF1' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Bayesian Curl');
UPDATE exercises SET video_url = 'https://youtu.be/fovEGjXSYj4?si=R3fPoSd5ejZCgKll' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/q-5xzuVDZ0o?si=5L3fg2tvxhgRuWIr' WHERE LOWER(TRIM(name)) = LOWER('Bar Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/3pZ6wfIz08Y?si=5fpjOOF_aj7Rqkva' WHERE LOWER(TRIM(name)) = LOWER('Ring Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/XXcRdXIw0go?si=y-Sh6yOZyvTpiN50' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/8ruEIfBzLrw?si=smM0Bo6E_xDv-x1e' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bent Knee Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/eNxGGePOIKc?si=7JyPr9YGL-PaAxUu' WHERE LOWER(TRIM(name)) = LOWER('Barbell Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/3fg-hQVEplQ?si=XEmrtzkwGBxeHlH4' WHERE LOWER(TRIM(name)) = LOWER('Bar Bent Knee Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/rGtYmX2aeAA?si=vGnxKaVzGlUTMmmQ' WHERE LOWER(TRIM(name)) = LOWER('Sled Lateral Drag');
UPDATE exercises SET video_url = 'https://youtu.be/zjBV2T7K0Rg?si=_bwLTITNdt5K9Gvl' WHERE LOWER(TRIM(name)) = LOWER('Slider Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/zVYCZvgemlg?si=-a8bJrHDZxw6HPUH' WHERE LOWER(TRIM(name)) = LOWER('Slider Kneeling Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/uKKoLcOJKB8?si=-OlEu2pk86XR-Gs7' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Clean to Squat Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/g-XhUMB6_wk?si=7RXzbNpwkvoBKK88' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean to Squat Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/ELozuUa8rjk?si=pfjkNnOsw1MmdI5_' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Close Grip Strict Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/fzuxbZSW3UA?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/cC3nItw-szY?si=-UBQr2PgbT6bRuKh&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Slider Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/lmtz6T204No?si=jbae97NKFny9b463' WHERE LOWER(TRIM(name)) = LOWER('Slider Parallette Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/67HLZ2-3_v0?si=57cdzDwX0TrSRLYm' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Feet Elevated Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/cdvQmb5iNdc?si=WU6MMMqGPXHZwOf9' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/u8BCm4GkOSY?si=mivk-6ghBacHbVR9' WHERE LOWER(TRIM(name)) = LOWER('Suspension Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/ENZjCX9HjVI?si=gdLZCVhHGqq16S_R' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Box Jump');
UPDATE exercises SET video_url = 'https://youtu.be/7rkzWjwrazQ?si=poAx5_jLTfV0N0Up' WHERE LOWER(TRIM(name)) = LOWER('Miniband March');
UPDATE exercises SET video_url = 'https://youtu.be/QU0tbSNu0-8?si=KcVtyY0N6KP7lrb_' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/P_coucNMiK0?si=6WAs2e4x_zEuxZLz' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Shoulder March');
UPDATE exercises SET video_url = 'https://youtu.be/pCO1EJ0WL30?si=y4xIpqM8QUMlG_ia' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/-s80JT1GZRs?si=qKXPOlVNn8DU_o2f' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/-Am9J90oDK4?si=DzyEzfiwzZAs3ckF' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/Zw0q4TYy8eI?si=-MWyXSvjBoei8Mmn' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/OZT20vP92ls?si=msixASyZYFzp43En' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/y6k_0YpUP44?si=QEPu230wf0aPiJsJ' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Half Kneeling Overhead Press');