UPDATE exercises SET video_url = 'https://youtu.be/5jDEulwWs04' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/ncpMkhXAykg?si=a_b3ot2rsThtz4DE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/tU-WZsouVjo?si=Ti1JUU03OqgnmtX6' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bird Dog');
UPDATE exercises SET video_url = 'https://youtu.be/2rbbUJR-Nx4?si=aAPlfM1RYBeErvZk' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/ByXVlY2L3nw' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/RPBH_Dw5hUo?si=SqKs_FnqsPMuLdq0' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging Knee Raise');
UPDATE exercises SET video_url = 'https://youtu.be/W0RoAqlFzrA' WHERE LOWER(TRIM(name)) = LOWER('Parallette Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/Kbhl_O1N4aw' WHERE LOWER(TRIM(name)) = LOWER('Parallette Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/fGaqVUHB1aA' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Knee Hover Bird Dog');
UPDATE exercises SET video_url = 'https://youtu.be/n4UPDi5BuL0' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball V Up Pass');
UPDATE exercises SET video_url = 'https://youtu.be/jbWmbhElf3Q' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/URWXz0DmE7s' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Heel Taps');
UPDATE exercises SET video_url = 'https://youtu.be/e_s7uBNPnow' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/Ns1NS9ThNhI' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Kneeling Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/GflQ_ymx9Nw' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Seated Ab Circles');
UPDATE exercises SET video_url = 'https://youtu.be/IfOtFv6zz8I' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Stir the Pot');
UPDATE exercises SET video_url = 'https://youtu.be/1jCudOtlLsc' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Lateral Kick Through');
UPDATE exercises SET video_url = 'https://youtu.be/Y7Ua1YRsqd0' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging L Sit Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/qyZ0pAtgo_Y' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/Ec9Ymqhe5i4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Side Plank Reach Through');
UPDATE exercises SET video_url = 'https://youtu.be/QB2Gj1QGfjQ' WHERE LOWER(TRIM(name)) = LOWER('Ab Wheel Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/gQT76pz_X9Y' WHERE LOWER(TRIM(name)) = LOWER('Cable Seated Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/ToJeyhydUxU' WHERE LOWER(TRIM(name)) = LOWER('Cable Kneeling Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/E0WFCTnN728?si=YvTVZvOCRm_hjh2B' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball V Up');
UPDATE exercises SET video_url = 'https://youtu.be/z2tctrNfTrY' WHERE LOWER(TRIM(name)) = LOWER('Suspension Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/nedEXGnhHak' WHERE LOWER(TRIM(name)) = LOWER('Suspension Lateral Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/O0wf46CgVZg' WHERE LOWER(TRIM(name)) = LOWER('Suspension Archer Row');
UPDATE exercises SET video_url = 'https://youtu.be/saYKvqSscuY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/8y-C1wUb-3c' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bear Crawl');
UPDATE exercises SET video_url = 'https://youtu.be/Q8MnsYG5sbk?si=8Aln2doES1PVTKQP' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/IMWzJ7zkklA' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging Leg Raise');
UPDATE exercises SET video_url = 'https://youtu.be/lLu9U0G7Ogw' WHERE LOWER(TRIM(name)) = LOWER('Parallette L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/R6SMJ-TzgZo' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Standing Walkout Plank');
UPDATE exercises SET video_url = 'https://youtu.be/4vEoBieXyKk' WHERE LOWER(TRIM(name)) = LOWER('Ring Eccentric Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/8e1m4FNO7t8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Ipsilateral Bird Dog');
UPDATE exercises SET video_url = 'https://youtu.be/QvgPN5XfDX8?si=0U64Q99rkmh8yNmO' WHERE LOWER(TRIM(name)) = LOWER('Ring Eccentric Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/HeY0G79zbGA?si=qV6g26pqatUMpDew' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Shoulder External Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/oYGHjG0jZuA' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Cuban Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/_Cfrbn8dxH4' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Cuban Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/Ff4Dg3T4pNQ?si=xU9cm-kpyPdrIwA0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Half Kneeling Contralateral Shoulder External Rotation 90 Degrees');
UPDATE exercises SET video_url = 'https://youtu.be/gnzypKUFU6Y' WHERE LOWER(TRIM(name)) = LOWER('Miniband Fire Hydrant');
UPDATE exercises SET video_url = 'https://youtu.be/vT8p57mXVDo?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/_R389Jk0tIo' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/3Mn_4KTDTi0?si=3zBBQ33AQDN7XPp4' WHERE LOWER(TRIM(name)) = LOWER('Cable Reverse Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/hUbRkz4AxkE' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Half Kneeling High to Low Chop');
UPDATE exercises SET video_url = 'https://youtu.be/48LIxDpby_E?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/FFaeQW7hwYs?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Staggered Stance High to Low Chop');
UPDATE exercises SET video_url = 'https://youtu.be/EVLXzqAzAHI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/jGwHfj957eU?si=i-ZtryUkm2Geud9J' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet On Wall Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/1SlpUMsiiiw?si=WnEVv0WTROHdU4eR' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Kettlebell Suitcase Reverse Lunge');