UPDATE exercises SET video_url = 'https://youtu.be/odS65TnXgU0?si=l3QM9Nb4wHNt_JgK' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Sumo Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/sgd8n917Zv0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/f-Vf2yRRqOg' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Squat');
UPDATE exercises SET video_url = 'https://youtu.be/nrfDq0DUhrE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/vcMZNgn5G9c' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/NIytPzrQ460?si=hBsVxzSTE6ddOTCD' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/KpufjJRtyPc' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/RttCwCerCiM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/UcLpNnWX8vE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Turkish Sit Up to Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/aJGPHYsiyTM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/fOPqk1FA4HU' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Swing');
UPDATE exercises SET video_url = 'https://youtu.be/JoT4bHnzTMw?si=i8z5wbuObKGVIl4_' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Wqg4NY5XAkU' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-Z8NXAi59SE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/M39871Puz6c' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/FZ8mMUwnCQs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/hUG_dolsaPE?si=_fw03cFT8VfLVtzo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/0i2Aa8gV-VY?si=Z7AGqRY1Hod9Fwti' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/F19T2zGlPGA' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/FvSL8slKKHY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/OD7URB1yHAo?si=UX_3VmEfO_WpeiuT' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/JkKxFADvLvk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/Xa8hHIwOHe4' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/9u_Fccgk9Ys' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Contralateral Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/j0aAMnMp0yU' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/QSbH7gNkBtc?si=ngxTS90XoTuvQDxs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/3WVToPNWjVk' WHERE LOWER(TRIM(name)) = LOWER('Parallette Tuck Planche');
UPDATE exercises SET video_url = 'https://youtu.be/xkyQtEH8fxM?si=Zh1mTKcYEFs382Sk' WHERE LOWER(TRIM(name)) = LOWER('Macebell Offset Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/NUvTsZxo5nk' WHERE LOWER(TRIM(name)) = LOWER('Parallette L Sit to Tuck Planche');
UPDATE exercises SET video_url = 'https://youtu.be/4dGj7rES9pY' WHERE LOWER(TRIM(name)) = LOWER('Landmine Standing Oblique Twist');
UPDATE exercises SET video_url = 'https://youtu.be/h-af-afj-Xg' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Tall Kneeling High to Low Chop');
UPDATE exercises SET video_url = 'https://youtu.be/NrkFLTzLuSM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Parallette Plank');
UPDATE exercises SET video_url = 'https://youtu.be/hetklTC7y4M?si=gHU6ufU8oAcg21Jv' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Plank');
UPDATE exercises SET video_url = 'https://youtu.be/_-kclLM0Mak' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/1v4_Vsvk3gc' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bird Dog Knee to Elbow');
UPDATE exercises SET video_url = 'https://youtu.be/W1FXse115qs' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/IdEocZzdUNY' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/Ry9HwpfUbd8?si=oY89SBibCyKMJ7CT' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/A_JgZzr6o-k' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Forearm Plank Alternating Knee to Elbow');
UPDATE exercises SET video_url = 'https://youtu.be/lhh2tGD_47g' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Loaded Beast to Alternating Kick Through');
UPDATE exercises SET video_url = 'https://youtu.be/-fuxiCQvMxQ?si=lCRmzsfrTeNaP0Gk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/8tFmEJ9ElaM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean');
UPDATE exercises SET video_url = 'https://youtu.be/5WNcWPHXRZ0' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/XdKaa2lHuic' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/wCwn7-Z-XjE' WHERE LOWER(TRIM(name)) = LOWER('Superband Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/oBmFzeay6Z8?si=dliVO8cgoAWNKwT3' WHERE LOWER(TRIM(name)) = LOWER('Parallette V Sit');
UPDATE exercises SET video_url = 'https://youtu.be/6sbNXcg-R0Y' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/zfWpy9oMOqc?si=8gZawgsKgTeeGHck&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell High Pull');
UPDATE exercises SET video_url = 'https://youtu.be/TvPRtxN8uoA' WHERE LOWER(TRIM(name)) = LOWER('Superband Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/V-SoYj9uQV8' WHERE LOWER(TRIM(name)) = LOWER('Superband Half Kneeling Pallof Press');