UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Kettlebell Alternating Halo to Horn Grip Bottoms Up Squat', 'https://youtu.be/-0FIWmBbo9U'),
  ('Ring German Hang Pullout', 'https://youtu.be/J34xkKOc9GI'),
  ('Single Arm Kettlebell Bottoms Up Turkish Get Up', 'https://youtu.be/jpgvV6wdXVw'),
  ('Single Arm Kettlebell Thruster', 'https://youtu.be/vBkzGpZSEF4'),
  ('Alternating Double Kettlebell Thruster', 'https://youtu.be/AeK6i-5gvJ0'),
  ('Single Arm Kettlebell Bottoms Up Dead Clean to Overhead Press', 'https://youtu.be/EF4ep3h5Olk'),
  ('Single Arm Kettlebell Tactical Snatch', 'https://youtu.be/lWVxdK_AT2s?si=lgWC5CSMGVpQHo9t'),
  ('Single Arm Kettlebell Snatch to Overhead Contralateral Reverse Lunge', 'https://youtu.be/oReUJtUlMGU'),
  ('Double Kettlebell Snatch to Overhead Alternating Reverse Lunge', 'https://youtu.be/VpURrAKPhcE?si=gSYbC8kpIa5xMxr8'),
  ('Single Arm Kettlebell Clean to Front Rack Contralateral Reverse Lunge', 'https://youtu.be/oqjLx5Injps'),
  ('Single Arm Kettlebell Split Jerk', 'https://youtu.be/DeoexkyNuns?si=WrruI69jETw4SBe-'),
  ('Single Arm Ring Chin Up', 'https://youtu.be/S22n8oqcDSY?si=GFs-J_IAwjttVe0y'),
  ('Double Kettlebell Bottoms Up Overhead Squat', 'https://youtu.be/kSlZIksA8XQ'),
  ('Double Kettlebell Bottoms Up Thruster', 'https://youtu.be/ZjNbjnGz1Cg'),
  ('Ring Iron Cross', 'https://youtu.be/HZbee93OIdo'),
  ('Barbell Overhead Bulgarian Split Squat', 'https://youtu.be/F_t7_XRdLbs?si=moBf8_s1adbBBwRY'),
  ('Bodyweight Straddle Planche Push Up', 'https://youtu.be/qgNYrUdn1Oo?si=66l491gj5kmLLjA0'),
  ('Bodyweight Two Finger Full Planche Push Up', 'https://youtu.be/CGeBvG5XP7U?si=nGM9dXX2v8dyqJA_'),
  ('Bodyweight Push Up to Alternating Kick Through', 'https://youtu.be/wcBXDGhqnBU'),
  ('Bodyweight Standing Walkout Push Up', 'https://youtu.be/zR7oQp1Ucq8'),
  ('Ring Pull Up', 'https://youtu.be/cLqkGqiva1M'),
  ('Single Arm Plate Windmill', 'https://youtu.be/P-dqLz-r5po'),
  ('Single Arm Plate Turkish Get Up', 'https://youtu.be/4_RrnWT847k'),
  ('Bodyweight Pike Push Up', 'https://youtu.be/QIZ6RXq72ZI'),
  ('Parallette Feet Elevated Pike Push Up', 'https://youtu.be/EqXFl_YxF8k'),
  ('Barbell Sots Press', 'https://youtu.be/eJ9MLnNV6FY'),
  ('Double Kettlebell Bottoms Up Snatch', 'https://youtu.be/jcC9NyGLGyg'),
  ('Single Arm Kettlebell Around the World', 'https://youtu.be/6AzrdFj3Qfc?si=52vAx7-XXfvkSz_l'),
  ('Single Arm Dumbbell Z Press', 'https://youtu.be/Ib-8BOyAgTQ'),
  ('Parallette Feet Elevated Push Up', 'https://youtu.be/JtBPG6VeJ9Q'),
  ('Stability Ball Feet Elevated Diamond Push Up', 'https://youtu.be/-2fkjhJfcP8'),
  ('Bodyweight Tricep Extension', 'https://youtu.be/O8WGl4_aYTQ?si=eq7Ylf5fkEliBcxD'),
  ('Alternating Single Arm Kettlebell Around the World', 'https://youtu.be/ekR7MDSWwEQ'),
  ('Single Arm Kettlebell Tall Kneeling Around the World', 'https://youtu.be/9vZ0CU0dHcE'),
  ('Single Arm Kettlebell Waiter Clean', 'https://youtu.be/fLXYRpxW4FI?si=AjNKRKLLVjzA8Uow'),
  ('Alternating Single Arm Kettlebell Waiter Clean', 'https://youtu.be/eH7w5psLPpk?si=XnO0PygbF5fzKCsm'),
  ('Double Kettlebell Waiter Clean', 'https://youtu.be/K8atAt0LaTU?si=9XbtgY4Ntm5G8h7v'),
  ('Double Kettlebell Waiter Clean to Overhead Press', 'https://youtu.be/6yF_kl-76jw?si=rsxf0dRezcQc83ke'),
  ('Double Kettlebell Waiter Clean to Alternating Overhead Press', 'https://youtu.be/0WjMjA_4SoE?si=J46etYGhA2sshEat'),
  ('Barbell Seated Wrist Curl', 'https://youtu.be/k6F6ugHyTcA?si=XfnVnbcVgnDkbrFv'),
  ('Single Arm Dumbbell Hollow Body Chest Press', 'https://youtu.be/D82M_YDEGJ8'),
  ('Double Kettlebell Waiter Clean to Thruster', 'https://youtu.be/PX80lILLVhw?si=vmOhrWhU-xCpO4kr'),
  ('Kettlebell Start Stop Swing', 'https://youtu.be/cZSh_cYNXTw'),
  ('Double Kettlebell Dead Clean', 'https://youtu.be/qdMDbLUg9_w?si=9t5V4loMJW5VI5mV'),
  ('Bodyweight Windmill', 'https://youtu.be/87I2gbRgtUI?si=4hUJ0N3X8wu8MMKC'),
  ('Superband Isometric Split Squat Pallof Press', 'https://youtu.be/a4ctQ6GYixo?si=WP2e4CVK5KsFEluY'),
  ('Single Arm Barbell Turkish Get Up', 'https://youtu.be/VAFM8kbz8uA?si=UAPSMjiSnRLN3jl3'),
  ('Bodyweight Plate Plyometric Push Up', 'https://youtu.be/jmzZ2wQdXao'),
  ('Single Arm Dumbbell Single Leg Contralateral Bent Over Row', 'https://youtu.be/KsEBTYuqemI'),
  ('Double Dumbbell Single Leg Bent Over Row', 'https://youtu.be/LrbAy459jkg?si=UDFXUQgUuwN4hkBz'),
  ('Single Arm Kettlebell Bottoms Up Thruster', 'https://youtu.be/lbnYFCHrjvk'),
  ('Single Arm Kettlebell Dead Clean', 'https://youtu.be/Lcm7DcXbm-U'),
  ('Alternating Single Arm Kettlebell Dead Clean', 'https://youtu.be/FAtcUX6VxWo'),
  ('Single Arm Dumbbell Bird Dog Row', 'https://youtu.be/O1mck-Oil5Y'),
  ('Single Arm Kettlebell Bottoms Up Half Kneeling Windmill', 'https://youtu.be/U6kn-AypL7c'),
  ('Double Dumbbell Renegade Row', 'https://youtu.be/U_kv9LRu6_I?si=o6wONfSHOO4nrgpy'),
  ('Ring Kneeling Rollout', 'https://youtu.be/LMQIG45Wwd8'),
  ('Ring Standing Rollout', 'https://youtu.be/or7xH0BirKw?si=5oL6x2NsxvCfWaBo'),
  ('Single Arm Landmine Shoulder Press', 'https://youtu.be/5Cs27w8WVz4'),
  ('Alternating Single Arm Landmine Shoulder Press', 'https://youtu.be/owbzzfb-0PQ'),
  ('Single Arm Kettlebell Bent Press', 'https://youtu.be/xO7fmvTpy3M'),
  ('Double Kettlebell Front Rack Cossack Squat', 'https://youtu.be/sBuAJggOIxE?si=CST2KlC-8f_fnogp'),
  ('Double Kettlebell Front Rack Low Switch Cossack Squat', 'https://youtu.be/j9sFzOeMmxY?si=i2yJV3WJb2pBCf0X'),
  ('Single Arm Landmine Half Kneeling Contralateral Shoulder Press', 'https://youtu.be/ORoOn93dnh4'),
  ('Bodyweight Bulgarian Split Squat', 'https://youtu.be/kBQ1krvKFBU'),
  ('Plate Otis Up', 'https://youtu.be/vjAjAERSkIk'),
  ('Double Kettlebell Bottoms Up Front Rack Pistol Squat', 'https://youtu.be/WPIrFREyNaw'),
  ('Double Kettlebell Clean to Sots Press', 'https://youtu.be/NqZPSUqSJlA'),
  ('Single Arm Landmine Tall Kneeling Shoulder Press', 'https://youtu.be/TVTHezj2ZLg'),
  ('Single Arm Landmine Z Press', 'https://youtu.be/app94pzXOuU'),
  ('Barbell Z Press', 'https://youtu.be/D73Oy2m-Uoc'),
  ('Single Arm Suspension Bicep Curl', 'https://youtu.be/gn5Uy0z5DyY?si=cNwcH7q0lucOSGDX'),
  ('Suspension Atomic Push Up', 'https://youtu.be/qTD9lWjff84'),
  ('Double Kettlebell Clean to Thruster', 'https://youtu.be/J6xUudO95Gc'),
  ('Bodyweight Archer Push Up', 'https://youtu.be/_Qbz_54_9Sw'),
  ('Parallette Archer Push Up', 'https://youtu.be/Wg2mF-GjD10'),
  ('Single Arm Suspension Push Up', 'https://youtu.be/PenQnEuayM4'),
  ('Ring Skin the Cat', 'https://youtu.be/ABSpTs17ObA'),
  ('Single Arm Kettlebell Suitcase Contralateral Bulgarian Split Squat', 'https://youtu.be/DGzBcpLm8T4?si=VFc6IG7H7vAlBgxV'),
  ('Double Kettlebell Suitcase Bulgarian Split Squat', 'https://youtu.be/2mDqNOd-Pco?si=MiZ8nJsVAje_rZfb'),
  ('Ring Feet Elevated Row', 'https://youtu.be/u3XIZSv2Npw'),
  ('Ring Feet Elevated Bulgarian Row', 'https://youtu.be/k84lpDtf5kQ'),
  ('Ring Push Up', 'https://youtu.be/u8tOhNwiL70'),
  ('Ring Chest Fly', 'https://youtu.be/ytAxGbZ7g80'),
  ('Double Kettlebell Feet Elevated Push Up', 'https://youtu.be/kw3ht7nZbXs?si=9ZaHvZoUYJK9H_2w'),
  ('Single Arm Kettlebell Bottoms Up Half Kneeling Contralateral Overhead Press', 'https://youtu.be/DrpIWrG7rl8'),
  ('Parallette Alternating Shoulder Tap Push Up', 'https://youtu.be/NENoxvoyaTw'),
  ('Parallette Dive Bomber Push Up', 'https://youtu.be/tpCOg3ZKn3w?si=e_92TbjIAIy3thZh'),
  ('Barbell Front Rack Bulgarian Split Squat', 'https://youtu.be/kz5dpeSigAI'),
  ('Barbell Back Rack Bulgarian Split Squat', 'https://youtu.be/CeNiZ52DzU0'),
  ('Barbell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/QB9bEZQl6Mg'),
  ('Bodyweight Dragon Flag', 'https://youtu.be/LXmJg15hurY?si=kuUaXsoiL3fnTOE7'),
  ('Bodyweight Dive Bomber Push Up', 'https://youtu.be/y94uWhVJ3D4?si=TIKacdZm8d8i5e6M'),
  ('Parallette Full Planche', 'https://youtu.be/v6oj7ImoVP4?si=F3GtqX0vk8YHIyZm'),
  ('Double Dumbbell Renegade Row to Push Up', 'https://youtu.be/731lQp2shpY'),
  ('Ring Inverted Iron Cross', 'https://youtu.be/qO5ZqLJD_ZQ'),
  ('Barbell Reverse Grip Front Raise', 'https://youtu.be/b2ELsjM9KQQ'),
  ('Ring Tuck Planche', 'https://youtu.be/ch0kaD--kIA'),
  ('Bodyweight Full Planche', 'https://youtu.be/hTpQCPjYZ3w?si=jlVsTRhe4TDGXMhx'),
  ('Cable Quadruped Hip Abduction', 'https://youtu.be/MZi0M3OJEVw'),
  ('Barbell Reverse Grip Bench Press', 'https://youtu.be/a9IZD74jAfw?si=-nGBSNLL5nllir0b'),
  ('Double Kettlebell Turkish Get Up', 'https://youtu.be/q4JSQU9lyfs'),
  ('Single Arm Kettlebell Rotational Overhead Press', 'https://youtu.be/jtOoPLn8OEQ'),
  ('Single Arm Kettlebell Z Press', 'https://youtu.be/ygiRarZWXHw'),
  ('Parallette Straddle Planche', 'https://youtu.be/2qWMe_2rlFk?si=MrPXRqDAKW9xxM_5'),
  ('Single Arm Kettlebell Sots Press', 'https://youtu.be/1znq_EvBvCg'),
  ('Double Kettlebell Renegade Row', 'https://youtu.be/SUqsBTSldyk'),
  ('Barbell Turkish Sit Up', 'https://youtu.be/zCBlmAdxfI0'),
  ('Plate Turkish Sit Up', 'https://youtu.be/A7sXEmRwTQQ'),
  ('Double Kettlebell Renegade Row to Push Up', 'https://youtu.be/i8VL6OjVlCY'),
  ('Dumbbell Crush Grip Romanian Deadlift', 'https://youtu.be/SozT7TcG-p0?si=8DX3-uViiOfh2BvX'),
  ('Single Arm Kettlebell Half Kneeling Contralateral Overhead Press', 'https://youtu.be/wlAJN3GzJWA'),
  ('Single Arm Kettlebell Bottoms Up Z Press', 'https://youtu.be/XFxoHtiGZtw'),
  ('Double Kettlebell Bottoms Up Z Press', 'https://youtu.be/s2hAm9S-6fY'),
  ('Double Kettlebell Sots Press', 'https://youtu.be/D6UYO_ZbLJ8'),
  ('Alternating Double Kettlebell Sots Press', 'https://youtu.be/_Q2mHbn6ggA?si=QGGePHfV1X7MFEdF'),
  ('Double Kettlebell Seesaw Sots Press', 'https://youtu.be/L0DwNTS4psM'),
  ('Dumbbell Crush Grip Hollow Body Flutter Kicks', 'https://youtu.be/Btp-pKPfvEU'),
  ('Double Kettlebell Bottoms Up Seesaw Overhead Press', 'https://youtu.be/HDzbviKeH8A'),
  ('Parallette Crow Pose', 'https://youtu.be/JHYVvhWqNzE'),
  ('Barbell Overhead March', 'https://youtu.be/NJ4t_HAgJ0M'),
  ('Single Arm Kettlebell Half Kneeling Clean', 'https://youtu.be/2LM9Y67n6Aw'),
  ('Single Arm Kettlebell Half Kneeling Snatch', 'https://youtu.be/Ak5wI3oLbjA?si=ZcxpayHQ4EbHkxWD'),
  ('Double Kettlebell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/UnevKvSIDLo?si=Y2g3UwUxqNMlZHdo'),
  ('Slider Lateral Lunge', 'https://youtu.be/Gj12f62lLeM?si=VhTsZJu7DxtPvx73'),
  ('Double Kettlebell Dead Clean to Overhead Press', 'https://youtu.be/8xYUgNA1Hi0?si=B1HQJvZslYYHAgLt'),
  ('Double Kettlebell Dead Clean to Thruster', 'https://youtu.be/3p8swLoH5no'),
  ('Single Arm Kettlebell Dead Snatch', 'https://youtu.be/VfKFRnS5FDY'),
  ('Alternating Single Arm Kettlebell Dead Snatch', 'https://youtu.be/z0tHucwkYgM?si=VThu2f_wRIcFlNP3'),
  ('Double Kettlebell Dead Half Snatch', 'https://youtu.be/t8Z9LTj5b6Y'),
  ('Double Dumbbell Staggered Stance Romanian Deadlift', 'https://youtu.be/RFuCfiMfJ1w'),
  ('Barbell Staggered Stance Romanian Deadlift', 'https://youtu.be/UDKuhQqMIBs'),
  ('Ring Hanging Knees to Elbows', 'https://youtu.be/SxLuhaSaPM4'),
  ('Superband Assisted Nordic Hamstring Curl', 'https://youtu.be/4u74sLMSObs'),
  ('Bodyweight Alternating Shin Box Hip Extension', 'https://youtu.be/UZLEwSROzyQ?si=Pk3NabO_4gvYWivn'),
  ('Single Arm Kettlebell Turkish Sit Up to Z Press', 'https://youtu.be/FOdI5tm_JZs?si=-JnXwtZzA1jDzCcB'),
  ('Ring Chin Up', 'https://youtu.be/rJiYA9jn3YI'),
  ('Single Arm Kettlebell Rotational Thruster', 'https://youtu.be/jkbJFWzllH4'),
  ('Single Arm Dumbbell Suitcase Carry', 'https://youtu.be/mKfCI8ADAjQ?si=ZGUBS2ZPrlbJQKmA'),
  ('Double Dumbbell Glute Bridge Isometric Bench Press', 'https://youtu.be/CyHxva5XYYY'),
  ('Bodyweight Foot Elevated Cossack Squat', 'https://youtu.be/DgJtQJxYVTk'),
  ('Barbell Feet Elevated Inverted Row', 'https://youtu.be/6AptmglPQ30'),
  ('Double Kettlebell Windmill', 'https://youtu.be/t9S2E15cyTg?si=pUmpNP-D71uC7XAL'),
  ('Double Kettlebell Dragon Flag', 'https://youtu.be/8i1-ngFRLLs'),
  ('Barbell Staggered Stance Overhead Press', 'https://youtu.be/dnLBRh6bQJQ'),
  ('Kettlebell Dead Bug', 'https://youtu.be/pXcG0IH2Nkg'),
  ('Superband Standing Hip Adduction', 'https://youtu.be/O2fzFpGvDWI'),
  ('Superband Lateral Step Hip Adduction', 'https://youtu.be/9Ryl38GZHiI'),
  ('Kettlebell Dead Clean to Horn Grip Squat', 'https://youtu.be/Xo9kEM4A6ao?si=RzutoHlEo0zoz1LZ'),
  ('Double Kettlebell Bottoms Up Front Rack March', 'https://youtu.be/mLc2zI4rkMQ?si=bYMHmbsvqyX3__ZV'),
  ('Suspension Alternating Cossack Squat', 'https://youtu.be/ThQT_AIqcNU?si=Y06NKpeBBOkHRplH'),
  ('Battle Rope Single Leg Standing Alternating Wave', 'https://youtu.be/ynczWiOjUqE?si=TWU55ZzVAfcrcb5B'),
  ('Superband Assisted Dips', 'https://youtu.be/QjzY6vf495U?si=dG_1Ixlx0Man-AIC'),
  ('Alternating Single Arm Kettlebell Ballistic Row', 'https://youtu.be/ey7YgyPONOk'),
  ('Double Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/Pt-6EI8mcEU?si=Lxresx17SBitLvtO'),
  ('Suspension Split Squat', 'https://youtu.be/sng5EOSZSSo'),
  ('Single Arm Kettlebell Tactical Clean', 'https://youtu.be/dLyfCN_7JHw'),
  ('Suspension Cyclist Squat', 'https://youtu.be/dzbJzUQjDYA?feature=shared'),
  ('Macebell 360', 'https://youtu.be/WMog8YuuVaM?si=WsH2sh1FFH3SBamT'),
  ('Single Arm Suspension Contralateral Skater Squat', 'https://youtu.be/8pe73RwDAzY?si=ASSfIEGoxhWjeAi_'),
  ('Single Arm Macebell 360', 'https://youtu.be/ITUpuwk3odY?si=KGOrc3k9Flt-oF1v'),
  ('Bodyweight Cyclist Squat', 'https://youtu.be/BAlXJ5lLMAA?si=H1cfMWF52YWOMraL'),
  ('Kettlebell Half Kneeling Rotational Swing', 'https://youtu.be/_ChDukjxUag'),
  ('Double Kettlebell Clean to Push Jerk', 'https://youtu.be/_A6K7V6FHSM?si=uMrzYlHgGYbenNf1'),
  ('Kettlebell Isometric Split Squat Low to High Chop', 'https://youtu.be/ECAIMMQDUC4?si=WgJIciK_Kd14WYVj'),
  ('Double Kettlebell Front Rack March', 'https://youtu.be/aAbVFCqY4Ac'),
  ('Double Kettlebell Suitcase March', 'https://youtu.be/i-q8SKGy--Q'),
  ('Single Arm Kettlebell Rotational Half Snatch', 'https://youtu.be/KpDxyxOCjCE'),
  ('Slider Single Leg Hamstring Curl', 'https://youtu.be/MBoaZQwukmw?si=uMFzO0l7TuqVArPp'),
  ('Kettlebell Staggered Stance Rotational Swing', 'https://youtu.be/4SXAEL7ZdSk?feature=shared'),
  ('Barbell Low Bar Pause Back Squat', 'https://youtu.be/nknf16JJTZo?si=h2lVyRQ8npFOB0v4'),
  ('Barbell Front Rack Pause Squat', 'https://youtu.be/mN5Z5GH7ofM?si=5wK63ZJAw0Zc5Wti'),
  ('Single Arm Kettlebell Suitcase Walking Lunge Pass Through', 'https://youtu.be/yXwmVzRHPPw?si=K_LXsBOKmt9dza3B'),
  ('Macebell 10 to 2', 'https://youtu.be/6FjCQJRBNlo?si=RBXNRNqOkwVOMCGq'),
  ('Dumbbell Goblet Cyclist Squat', 'https://youtu.be/2WxpkosHXLg?si=kPBJD_6N8w568qJ-'),
  ('Barbell Overhead Alternating Cossack Squat', 'https://youtu.be/ulzoZOHicyU?si=OfrqYrKBRnV6RCrc'),
  ('Barbell Overhead Alternating Reverse Lunge', 'https://youtu.be/eqaz6nCxF8k?si=OEXiCUefeX011B_I'),
  ('Double Kettlebell Suitcase Carry', 'https://youtu.be/kaQWccrfY40'),
  ('Single Arm Kettlebell Suitcase Carry', 'https://youtu.be/HNgMpdUEpgw'),
  ('Double Kettlebell Bottoms Up Front Rack Cossack Squat', 'https://youtu.be/hTNWWqL9oc8?si=cTXB5vGf2EIHhx3r'),
  ('Alternating Single Arm Kettlebell Knee Hover Quadruped Pull Through', 'https://youtu.be/WQyNCzqNqso'),
  ('Single Arm Kettlebell High Pull', 'https://youtu.be/mP1BHxBeAEM'),
  ('Double Indian Club Outer Heart Shaped Swing', 'https://youtu.be/52D7xnpFFGY?si=UBcZ3G1BNtRbk97O'),
  ('Suspension Alternating Curtsy Lunge', 'https://youtu.be/jNjDO9lEenw?si=Ci4DITj3193GY1tI'),
  ('Single Arm Kettlebell Single Leg Balance Transfer', 'https://youtu.be/_uJQvQG57Y8'),
  ('Barbell Front Rack Alternating Forward Lunge', 'https://youtu.be/whSju0ip_78?si=emNV0JUVUhF8Qrf1'),
  ('Barbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/dpBy5qAG2Hs?si=x6xfYJbZr1Bols2r'),
  ('Barbell Overhead Alternating Forward Lunge', 'https://youtu.be/9eDpB8LJLgQ?si=CKsCerZuXFHay_Dr'),
  ('Single Arm Clubbell Shield Cast', 'https://youtu.be/W2slZ8Mmyvs?si=CDhf0Oi-nPW136Jx'),
  ('Macebell Barbarian Squat', 'https://youtu.be/Gj3ancpDFKU?si=TKfk3RmqTwztmb1j'),
  ('Alternating Double Clubbell Shield Cast', 'https://youtu.be/L1pxDgvsT9s?si=ajAmx9ThwNQY_hj2'),
  ('Clubbell Mill', 'https://youtu.be/uIqkGCpjsx8?si=_GzAaZAVU4-bAgla'),
  ('Double Clubbell Iron Cross', 'https://youtu.be/ekVV4qI2q9A?si=E3yTJpSwWDur0p82'),
  ('Double Clubbell Side Flag Press', 'https://youtu.be/_bnWJymK0tU?si=vYh91PF76xgOyPll'),
  ('Single Arm Kettlebell Suitcase Contralateral Knee Over Toe Split Squat', 'https://youtu.be/eGYP6B7LKtY?si=OkQLiBCrooH2qA67'),
  ('Double Indian Club Inner Heart Shaped Swing', 'https://youtu.be/If9fXNTF4wI?si=Lk9xqqbULe2D5Xbs'),
  ('Alternating Double Indian Club Inner Heart Shaped Swing', 'https://youtu.be/M_uslqzI28g?si=0zmBqTp2C8IMe5gJ'),
  ('Single Arm Clubbell Side Flag Press', 'https://youtu.be/uuLZZUozsdM?si=IcPMq75KQuzVIQM5'),
  ('Single Arm Clubbell Inside Circle', 'https://youtu.be/n8S_z0p25jA?si=fak8MwjeEUMtDoZ2'),
  ('Barbell Reverse Grip Bicep Curl', 'https://youtu.be/TUX58GM5fRQ?si=D4ei3VOcTd3GzGQn')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);