UPDATE exercises SET video_url = 'https://youtu.be/a9IZD74jAfw?si=-nGBSNLL5nllir0b' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/q4JSQU9lyfs' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/jtOoPLn8OEQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Rotational Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/ygiRarZWXHw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/2qWMe_2rlFk?si=MrPXRqDAKW9xxM_5' WHERE LOWER(TRIM(name)) = LOWER('Parallette Straddle Planche');
UPDATE exercises SET video_url = 'https://youtu.be/1znq_EvBvCg' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/SUqsBTSldyk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Renegade Row');
UPDATE exercises SET video_url = 'https://youtu.be/zCBlmAdxfI0' WHERE LOWER(TRIM(name)) = LOWER('Barbell Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/A7sXEmRwTQQ' WHERE LOWER(TRIM(name)) = LOWER('Plate Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/i8VL6OjVlCY' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Renegade Row to Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/SozT7TcG-p0?si=8DX3-uViiOfh2BvX' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/wlAJN3GzJWA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Contralateral Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/XFxoHtiGZtw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/s2hAm9S-6fY' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/D6UYO_ZbLJ8' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/_Q2mHbn6ggA?si=QGGePHfV1X7MFEdF' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/L0DwNTS4psM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/Btp-pKPfvEU' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Hollow Body Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/HDzbviKeH8A' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/JHYVvhWqNzE' WHERE LOWER(TRIM(name)) = LOWER('Parallette Crow Pose');
UPDATE exercises SET video_url = 'https://youtu.be/NJ4t_HAgJ0M' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/2LM9Y67n6Aw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Clean');
UPDATE exercises SET video_url = 'https://youtu.be/Ak5wI3oLbjA?si=ZcxpayHQ4EbHkxWD' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/UnevKvSIDLo?si=Y2g3UwUxqNMlZHdo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Gj12f62lLeM?si=VhTsZJu7DxtPvx73' WHERE LOWER(TRIM(name)) = LOWER('Slider Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/8xYUgNA1Hi0?si=B1HQJvZslYYHAgLt' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/3p8swLoH5no' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/VfKFRnS5FDY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Dead Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/z0tHucwkYgM?si=VThu2f_wRIcFlNP3' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Dead Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/t8Z9LTj5b6Y' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Half Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/RFuCfiMfJ1w' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Staggered Stance Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/UDKuhQqMIBs' WHERE LOWER(TRIM(name)) = LOWER('Barbell Staggered Stance Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/SxLuhaSaPM4' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging Knees to Elbows');
UPDATE exercises SET video_url = 'https://youtu.be/4u74sLMSObs' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Nordic Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/UZLEwSROzyQ?si=Pk3NabO_4gvYWivn' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Shin Box Hip Extension');
UPDATE exercises SET video_url = 'https://youtu.be/FOdI5tm_JZs?si=-JnXwtZzA1jDzCcB' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Turkish Sit Up to Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/rJiYA9jn3YI' WHERE LOWER(TRIM(name)) = LOWER('Ring Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/jkbJFWzllH4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Rotational Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/mKfCI8ADAjQ?si=ZGUBS2ZPrlbJQKmA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/CyHxva5XYYY' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Glute Bridge Isometric Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/DgJtQJxYVTk' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Foot Elevated Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6AptmglPQ30' WHERE LOWER(TRIM(name)) = LOWER('Barbell Feet Elevated Inverted Row');
UPDATE exercises SET video_url = 'https://youtu.be/t9S2E15cyTg?si=pUmpNP-D71uC7XAL' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/8i1-ngFRLLs' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dragon Flag');
UPDATE exercises SET video_url = 'https://youtu.be/dnLBRh6bQJQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Staggered Stance Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/pXcG0IH2Nkg' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/O2fzFpGvDWI' WHERE LOWER(TRIM(name)) = LOWER('Superband Standing Hip Adduction');
UPDATE exercises SET video_url = 'https://youtu.be/9Ryl38GZHiI' WHERE LOWER(TRIM(name)) = LOWER('Superband Lateral Step Hip Adduction');
UPDATE exercises SET video_url = 'https://youtu.be/Xo9kEM4A6ao?si=RzutoHlEo0zoz1LZ' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Dead Clean to Horn Grip Squat');
UPDATE exercises SET video_url = 'https://youtu.be/mLc2zI4rkMQ?si=bYMHmbsvqyX3__ZV' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack March');