UPDATE exercises SET video_url = 'https://youtu.be/TzuHADj8h4M?si=tAyLqN0pCIXqxity' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/KIDRnwRAKAY?si=b00pYocO2xqWBGiJ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/JKk87eVdbG8?si=Est-myfua9sI06NN' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/A4SnLhdMKu4?si=AWoi6qQOHivzUZeZ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/GkgTBlp417A?si=2RKL7GSC-wlwXQrE' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/V-crv5-Tqbg?si=k00dfu1tLmH4-h3a' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Ambx6K-_AfY?si=2pUqPVUnlmZLMMwH' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1iT74xBv0LA?si=vNMiZEtQ8W3QCkqc' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/8OZUh9sHk-8?si=euVM8-cldcw4zaJf' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/eK7AzF0-rt4?si=0L-vfrm5QmGhcV2l' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/DbANzYj8EWQ?si=NULTCgfWBvm6vNpX' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/kTfl5mhcwso?si=iDo9iOmHhKSZIQlN' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/b3ewFBSqc9k?si=l6I7tV4HN4z6vcCS' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1uuCmY9bVao?si=0iam54INq6LqKgrV' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/RNdGRLDFZ_E?si=ViWm3Cym-_kPAyPr' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/y6Z1csYJqI8?si=VJQkALrooI76ZWQ9' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/iPBOqxEBcto?si=yJqaSgMnybSQX6Oy' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/HFjBFM1Fswo?si=BiUd6crmcvrtRZx2' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/xFvob3P7I74?si=o6y90mzLlkb5kjLo' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/MjHkEW-AMQI?si=EyW7vqzwyfCJv1bN' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/YidVOnuiDfc?si=ECuN-ZTMBkyH_maZ' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/-hWgE1P2aAA?si=7mOaE_-aBxpQNBSX' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/VI0GDe_doBk?si=U14f8Dk6Ly1aMzBr' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/aopAoW1cmUk?si=EyVEsJC9bLaQC6ND' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/QV4DL31Ch94?si=6O9QTMoEB9MtwsZY' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/eGKpS3AxCVA?si=-uyv4kyU-FY0yBfB' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Fm-EgA1xP4g?si=TXFdciSwYJ3flVng' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/FvJS_MSN4Lo?si=Z7h-t5HEEQC6trw6' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/0RqJM6GM5bg?si=eL5TvNrMzUaI1oOW' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/OX0fKkaY6_c?si=T0Ta2iyvXrGIGA7w' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/iGLwbS5aHY4?si=f7TNizeYPw8xX1xR' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/SokWJEUYgfc?si=OWsmg8u6_2Xz09z9' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6DO1p1pOAwM?si=zeLSk3SSoVkoP_B9' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/7rGFnvK6KkE?si=SL3VLXM4o_8TDV_0' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/iylKd9ymBQE?si=D_mNdhDHgU7B8xbD' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/7oQoOglG_cA?si=JLNoB9O2s2KyOAf1' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Ipsilateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-vKdvtdkRRc?si=CPo0dP5KaIc0TJu5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/pEZWYmpCzu8?si=i70Ip_o4npwew5bY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/0bqrj4BimaI?si=03pxBE_5_ozxIivb' WHERE LOWER(TRIM(name)) = LOWER('Suspension Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/fJePN1sD5ok?si=g-YYXG1x8L53Vuv-' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/FNr5JBGrJTU?si=bn24rl-sBOt5WTfx' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/a8y1Qwir7YQ?si=izeBmxPLl4E0ekvy' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/0el8H9fy3g0?si=BdlZ75xoh6Xq1wpJ' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/mGwXPP-QKko?si=pUfEZOZPOOYaTV3n' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1L2HnCKmsRs?si=fIVyc7oXYDkkRzgJ' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/SJe_O4NPU-E?si=OKoj1OGsurlSWTEA' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/hVIaVvyY-H8?si=HsyRlDh-j--gHbsk' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/k6pHuYm2nV8?si=ttotAgiXtgPihuX3' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/X5UicuSpd-g?si=vkWg2RXcC-HFi6Pk' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/VFYZh24e0RI?si=_Vjvy9tWBn4nc7l_' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Tuck Planche');