UPDATE exercises SET video_url = 'https://youtu.be/dsTU2qm4ef0?si=sT2aw7NxeFtfYYNV' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/HZM84steEyw?si=wN3l2SpjKBFPTIbD' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/y0t2PFFwSe4?si=VjtJz1Dg61jGQIZ9' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/UhOs_Wvckvs?si=FqNmpb8ECh_Y-9rl' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/12MxAGiIgK8?si=pO89QghXz2Ykj1lb' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/QVFklRHtJxY?si=D_kiEaZg-5pSrfHL' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/VHeZJHEj6ic?si=DTfOrwFveTP-memt' WHERE LOWER(TRIM(name)) = LOWER('Double Plate Incline Bench Prone Y Raise');
UPDATE exercises SET video_url = 'https://youtu.be/VOmnhGvccZ0?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/YdiVxhxufG8?si=pMAxf531BcAPvatO' WHERE LOWER(TRIM(name)) = LOWER('Barbell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/p3zS2AMqGlg' WHERE LOWER(TRIM(name)) = LOWER('Ring Plank');
UPDATE exercises SET video_url = 'https://youtu.be/_Iev7PLP6QY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Plank');
UPDATE exercises SET video_url = 'https://youtu.be/O2HVcPD3wKQ?si=CFVI8GpHxTsirv6u' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Outward Circle');
UPDATE exercises SET video_url = 'https://youtu.be/kONbxg4kzkE' WHERE LOWER(TRIM(name)) = LOWER('Ring Support Hold');
UPDATE exercises SET video_url = 'https://youtu.be/PQ3Vz8fp73k' WHERE LOWER(TRIM(name)) = LOWER('Ring Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/cZvQNvTUUu0?si=SqA3lYAZBc0jOnvn' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/OXl94TQd_vw?si=AMXpvOM-H382GJoz' WHERE LOWER(TRIM(name)) = LOWER('Macebell Offset Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/igNnqZZ69JM?si=xaqrnAFrW4r7NuVR' WHERE LOWER(TRIM(name)) = LOWER('Macebell Reverse Grip Offset Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/p7j02V1fIzU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hollow Body Rock');
UPDATE exercises SET video_url = 'https://youtu.be/3mlhF3dptAo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Power Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/OktkfRlGcns' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Power Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/etK3OPjM3S4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Squat Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/T0_a2xijJBE' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Squat Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/OC_7QIo0uk4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/6caQpfXMvyw?si=WY0XcdcIUuE20g-o' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/AlxuA22ymwg?si=-tgz7djxN0QKxXfA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/wcnuhd6RHwE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/jHpBzpxK16c?si=3sB9wGkke_B632ad' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/4Bv94e_ufjo?si=8V5SPIIuNai7zUm3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/Ew2ZzKqICfA?si=Irq2jLSDxKiagY3F' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/STeIzkHm6tE?si=BxEJOKh_KtwNSMK_' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/x5nnk8hUBo4' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Good Morning');
UPDATE exercises SET video_url = 'https://youtu.be/OAhvIWLC0rc' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/SoVCwno_9z8?si=BCvfBOVPW_aHbvZ_' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/rAoi4_AI7VA?si=b6KXmXEYoxIPmTt2' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/gPX8OmnYmQY?si=UgQnJkh9n3OobTcZ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/z7rygloAW30?si=p4kPPZcAKammq1Vv' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/3HUEab31fks?si=B2OmGKfwSuXhts1z' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/lMADALbx1eM?si=wJjWrYeLHPKqVgHh' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/eKUmMljLcKw?si=ocsvBon7ivrRziM6' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/wPXdGwc0NTs' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/3rtUK_jUv4s' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/59_aq7COfts' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/fKbu_2L94x8' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Plank Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/kneGICiz30g' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Swing');
UPDATE exercises SET video_url = 'https://youtu.be/bIzD1Z_C0cA' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/1hcAoywwuRI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/TQT7hBXVcOo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean');
UPDATE exercises SET video_url = 'https://youtu.be/JtlYyc5MaAc' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/7zKQ79awAvY?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/VdNC_xicfyg' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Snatch');