UPDATE exercises SET video_url = 'https://youtu.be/ma__uqUlYmE?si=Yw6Iw4KOA3T7mJeL' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/ZRSGpBUVcNw?si=x3MRv2xRNjCc6s42' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Knee Supported Row');
UPDATE exercises SET video_url = 'https://youtu.be/owr5y-s6-Qk?si=gd2Nfg1PVMbahXjx' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/LQEag7MKXSs?si=vVcujNN4QVFLQ71H' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Incline Bench Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/sYpuz37bK2k?si=UpMtMbHU8GOboER_' WHERE LOWER(TRIM(name)) = LOWER('Tire Incline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/4JJB2m4AuO8?si=NqYITu6_1fcaAbn7' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Eccentric Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/HnHuhf4hEWY?si=WSqsCA9Khdbz3ag0' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/aG7CXiKxepw?si=FH8eUTIYzp_z04m0' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/4hKyhFBeclI?si=OrpNWuwGzVfolESP' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/YW9citXbrQc?si=5VFsuGIAvF6WHm17' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Seated Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/1Z6XiaBxwHQ?si=Da0lptFOFg_s0tyV' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/c0LP3YIO4vY?si=w_DOEV2ERQmctiSb' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Half Kneeling Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/Z_oWLq9uQZI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/qoswYkyJG-I?si=Jigh3MmNt7IIj-BA' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Cyclist Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/JS5HxlkWZzU?si=gKhPydrLwgHeGTcO' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/WGCrIXBHteQ?si=lcLSwZ_90St3r6W4' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/4cCItXCsEDo?si=xrvm1LxY3e8jhStd' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Bent Press');
UPDATE exercises SET video_url = 'https://youtu.be/FG6Y_r6-DJM?si=2qExXvynTbOnna2u' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/LXkCrxn3caQ?si=24dygODdgdRhEqJK' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/GqK6WrZEyEk?si=JPCXXCLg2YG3rQa7' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Reverse Grip Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/2IBxr91kSI8?si=NutPVlDJSpcDczLP' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/GIGFFYAKG6M?si=5QEN9x3BJwkxTal7' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Seated Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/9kib4kUJJ1A?si=KTQ4D8iMokjT6LqW' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Tall Kneeling Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/156_Z9969FQ?si=bmP-isrzfk-iAjdj' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/9DB2kibw0os?si=-BYlQ8gHAlszJaDo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/40w4sx4FAVU?si=i0K5ruXclQupBuxc' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/o9w3-CMPRxQ?si=nSVQxRbx2GvgZi-u' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/Xakexn9Y5Oo?si=YY664vMjXBLBT2Ha' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/Z4fmeY-GQ8o?si=jZD1QoPzdXBx4Hd8' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/GC0TS5XuuAA?si=1gRhkWItRmgaTYmb' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/P_ijh09h23s?si=U9pK9AQYG1xx2yxE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/Uf1jY-575lo?si=pKedIxKhmO0-sY6O' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/S1-SPv3YXG8?si=QCE1ikc3-Mg60u3x' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/o_3RHmSwIgE?si=jrBjCATOeTuvtWzq' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/jdx2kl5K0Ps?si=ABHltAh0E_8BUz7i' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/mTZENozi5x4?si=Us7_yx5MJoQLZHhO' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Double Wave');
UPDATE exercises SET video_url = 'https://youtu.be/67-J94MVJUg?si=TUVKne9uaJdYMy3x' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/e8K9KPGcwr8?si=HpsrB1akXMIU8ANX' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Lateral Raise');
UPDATE exercises SET video_url = 'https://youtu.be/xZKMteV7T6I?si=r_V-HvZTiORRBmxM' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/P-QvV7zOHjw?si=suRdks_sCJLNPIKX' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/N_eGFKGR7ZQ?si=J-4OOQpNwgwM0LrL' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Prone Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/1RdiI_ta3CY?si=ELtb0jc2iPVUiqNN' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/SisxAKThq70?si=tJqclsa9iiqndA6R' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/l2Hu2D3z84w?si=H3JslwI5uQK49RTu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/3u2DR9HL0tY?si=3Bcig3xQ4BI89qLa' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/hyb1jJ98ORU?si=UKrLCDD8rhcoKu0p' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/kIRvGGD21Zw?si=nBLhNjFMITgsl7fd' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Seated Single Leg Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/trgsU9LSHcM?si=LkOOKLtsyEAMWIWJ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seated Feet Elevated Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/NDA72gV21vM?si=nr1ibCzWJfLIYTXz' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/0S0pPgQXWNk?si=sd5taBTsE1Qux9Er' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Floor Press');