UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/DS-pvuh8VEo?si=KEDC31EUxCubFjGj'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/iRHrBseKm0k?si=X-TqbB38SGkCSqnE'),
  ('Ring Bulgarian Row', 'https://youtu.be/5CxPrNkhm2k'),
  ('Alternating Double Kettlebell Rotational Overhead Press', 'https://youtu.be/VQKcF1HfsYk'),
  ('Alternating Double Kettlebell Push Press', 'https://youtu.be/kUgzuCAvO3A'),
  ('Macebell Ballistic Curl', 'https://youtu.be/e8aZdfRK4FE?si=VtO52sSIMj0T-KCF'),
  ('Single Arm Clubbell Pullover', 'https://youtu.be/JJgOmmqZneM?si=v93qv5Poy03NJqj_'),
  ('Double Clubbell Pullover', 'https://youtu.be/2ZYphWzJedw?si=f5GGOhThihsKqIds'),
  ('Clubbell Pullover', 'https://youtu.be/0sRFLvzcqxw?si=cqK8W0uEQdEUfDAy'),
  ('Clubbell Front Flag Press', 'https://youtu.be/3_F4oUpYY7Q?si=qgoqjkcK33CSqmX4'),
  ('Single Arm Ring Dead Hang', 'https://youtu.be/7J_x9uMtr-o?si=2tga8qG4urWcSCMT'),
  ('Single Arm Dumbbell Suitcase Deadlift', 'https://youtu.be/yMRbcOd51pA?si=7Hc1xBgOqKKuKw3C'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/7wCLqLLyHh0?si=hFc7L_yPlG-KnZVg'),
  ('Clubbell Torch Press', 'https://youtu.be/REUDhFnYMYc?si=13Shwx4VKvuvNLZh'),
  ('Single Arm Clubbell Torch Press', 'https://youtu.be/UU4WhE25JfI?si=6sinMuju_2nUhgZK'),
  ('Barbell Conventional Deadlift', 'https://youtu.be/op9kVnSso6Q'),
  ('Barbell Sumo Deadlift', 'https://youtu.be/wQHSYDSgDn8'),
  ('Barbell Rack Pull', 'https://youtu.be/zdaEWO0S5HU'),
  ('Barbell Snatch Grip Deadlift', 'https://youtu.be/0Ah-ol5EGlo'),
  ('Stability Ball Hyperextension', 'https://youtu.be/bmRTtzOOiVM'),
  ('Barbell Seated Good Morning', 'https://youtu.be/ZPeJ0s8X6Gs'),
  ('Barbell Good Morning', 'https://youtu.be/F8dCjzbed-4'),
  ('Bodyweight Wall Sit', 'https://youtu.be/SszDMOZvFuw'),
  ('Bodyweight Wall Slide Squat', 'https://youtu.be/3J99J5NxNSQ?si=Xv_W-o9GzT-nvtVQ'),
  ('Stability Ball Wall Slide Squat', 'https://youtu.be/lWJ6BujsDYY?si=Hl4kTZutf9b6tDUi'),
  ('Suspension Squat', 'https://youtu.be/MafftY-3lC0?si=bGTlr29qg0ZvBtT_'),
  ('Suspension Alternating Reverse Lunge', 'https://youtu.be/oRO4ailwZb4'),
  ('Bodyweight Squat to Bench', 'https://youtu.be/93l0NGCosAE'),
  ('Bodyweight Squat', 'https://youtu.be/C_VtOYc6j5c'),
  ('Bodyweight Hand Assisted Split Squat', 'https://youtu.be/WRCsxtCfrEE'),
  ('Bodyweight Walking Lunge', 'https://youtu.be/tlbTz6IamaE'),
  ('Dumbbell Goblet Squat', 'https://youtu.be/a-dqF4NL2K4'),
  ('Miniband Romanian Deadlift', 'https://youtu.be/N5lBa2zMAPI?si=Eth4HWtKMOXBXNx6'),
  ('Superband Resisted Skater Jump', 'https://youtu.be/VHBOyCCupJ4?feature=shared'),
  ('Cable Prone Single Leg Hamstring Curl', 'https://youtu.be/k6Vo8hBLypQ'),
  ('Bodyweight Candlestick Roll Up Tuck Jump', 'https://youtu.be/BpwGQP8k7aY'),
  ('Barbell Block Pull Deadlift', 'https://youtu.be/iVpVk8x-VDQ'),
  ('Barbell Box Back Squat', 'https://youtu.be/dLG78_Z9rjM'),
  ('Barbell Deficit Deadlift', 'https://youtu.be/PzoxegwRlOw'),
  ('Barbell Front Rack Squat', 'https://youtu.be/uYumuL_G_V0'),
  ('Barbell Glute Bridge', 'https://youtu.be/6EhYj5eSngY'),
  ('Barbell High Bar Back Squat', 'https://youtu.be/ultWZbUMPL8'),
  ('Barbell Power Clean', 'https://youtu.be/KwYJTpQ_x5A'),
  ('Barbell Power Snatch', 'https://youtu.be/TL8SMp7RdXQ'),
  ('Barbell Romanian Deadlift', 'https://youtu.be/LURGDIX3adY?si=fHh3AAX-mZB09HXi'),
  ('Barbell Back Rack Split Squat', 'https://youtu.be/KXUJxb8hO8U'),
  ('Barbell Stiff Legged Deadlift', 'https://youtu.be/5_t0SsovgW8?si=5Zg1x855TTmrp1cL'),
  ('Barbell Sumo Back Squat', 'https://youtu.be/qiQAsB0x-7k?si=OlWu0ou6Vr0NnuvE'),
  ('Bodyweight Pistol Squat', 'https://youtu.be/qDcniqddTeE?si=G4KPahZUmlQQChZ_'),
  ('Bodyweight Skater Squat', 'https://youtu.be/kRnLZadW5Q0'),
  ('Cable Pull Through', 'https://youtu.be/NEDrQPoITMc?si=ZeJ1LOUbzrjgk-_8'),
  ('Double Dumbbell Suitcase Bulgarian Split Squat', 'https://youtu.be/G0Mo2LF8uLU'),
  ('Double Dumbbell Suitcase Step Up', 'https://youtu.be/37tVohr7LcE'),
  ('Double Dumbbell Suitcase Deficit Split Squat', 'https://youtu.be/jqWAqPQvqAk'),
  ('Double Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/t7DBjlOTwAk'),
  ('Double Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/Lsen4vH1nm8'),
  ('Double Dumbbell Suitcase Split Squat', 'https://youtu.be/yqH8u037IjM'),
  ('Double Dumbbell Front Rack Alternating Step Up', 'https://youtu.be/anHX8Zp67C8?si=qbb7ETCqekLaflB_'),
  ('Bodyweight Face the Wall Squat', 'https://youtu.be/pktIjwNiuYE?si=fWFt85clM0T2gopP'),
  ('Bodyweight Feet Elevated Glute Bridge', 'https://youtu.be/kFvF6ZHv-KI'),
  ('Slider Kettlebell Goblet Reverse Lunge', 'https://youtu.be/8k08cvYq-n8?si=bbPqV1XKB99kPfpP'),
  ('Miniband Thigh Monster Walk', 'https://youtu.be/po3I8qoRC2c?si=XeJ7Tq5PXt3WLJfl'),
  ('Bodyweight Quadruped Hip Extension', 'https://youtu.be/1UwyzWjFx5k'),
  ('Suspension Pistol Squat', 'https://youtu.be/K7qfUjKf9rU'),
  ('Suspension Skater Squat', 'https://youtu.be/YyBeT4WWBk4'),
  ('Bodyweight Tuck Jump', 'https://youtu.be/vgB_eWuvGW8?si=anQ4gfG2ik-Y_uU9'),
  ('Bodyweight Alternating Single Leg Wall Sit', 'https://youtu.be/eYGszeFcI7Y?si=jFOFuzza1JQMYuVE'),
  ('Bodyweight Single Leg Romanian Deadlift Jump', 'https://youtu.be/EmmP-jsvVJE'),
  ('Double Dumbbell Overhead Walking Lunge', 'https://youtu.be/TBw3mPrKAIs'),
  ('Bodyweight Reverse Nordic', 'https://youtu.be/GbpDfXXKuk0?si=IsPMd_J3d72xrMcZ'),
  ('Bodyweight Alternating Lateral Bench Jump', 'https://youtu.be/pVoOtkGBN6s'),
  ('Single Arm Dumbbell Front Rack Squat', 'https://youtu.be/1VzKnqCcUJ4'),
  ('Bodyweight Skater Jump', 'https://youtu.be/CaN4zfIPyXU'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/t8OkcdLjRFQ'),
  ('Cable Prone Bench Hamstring Curl', 'https://youtu.be/IalP0lgYPnc'),
  ('Bodyweight Bulgarian Split Squat Jump', 'https://youtu.be/CWTu90BUTIY?si=9JSuKmfFRaalZ6er'),
  ('Cable Standing Single Leg Hamstring Curl', 'https://youtu.be/tkh43Yc0tEs'),
  ('Bodyweight Nordic Hamstring Curl', 'https://youtu.be/kjv4WQXWl_A'),
  ('Superband Assisted Pistol Squat', 'https://youtu.be/szRINrcALyI'),
  ('Double Dumbbell Front Rack Squat', 'https://youtu.be/B86Zj72LwzA'),
  ('Double Dumbbell Suitcase Walking Lunge', 'https://youtu.be/KdE6b_r7wxA'),
  ('Barbell Back Rack Walking Lunge', 'https://youtu.be/ZPoMxOrIeO4'),
  ('Bodyweight Box Pistol Squat', 'https://youtu.be/Ly71LeprFKQ'),
  ('Barbell Overhead Squat', 'https://youtu.be/pn8mqlG0nkE'),
  ('Landmine Goblet Squat', 'https://youtu.be/oTRl7p13XtY'),
  ('Stability Ball Hamstring Curl', 'https://youtu.be/d-FBclT8W0g?si=wl1sJCzk2Z5PCnwx'),
  ('Slider Hamstring Curl', 'https://youtu.be/UaecXxAgsKA'),
  ('Bodyweight Hamstring Walkout', 'https://youtu.be/GcV2LB0qqnY?si=PoIiYCAOL0uaDuPR'),
  ('Slider Dumbbell Goblet Reverse Lunge', 'https://youtu.be/tWmzgpoOUls?si=Fmrp6-y_e5qk2SNJ'),
  ('Bodyweight Dragon Squat', 'https://youtu.be/bQY7fLEkZqU'),
  ('Stability Ball Single Leg Hamstring Curl', 'https://youtu.be/cuM7OBHSVow'),
  ('Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/HLDhxSqMQyE'),
  ('Barbell Overhead Walking Lunge', 'https://youtu.be/m6MczOv_Ayg'),
  ('Barbell Squat Clean', 'https://youtu.be/EKRiW9Yt3Ps'),
  ('Single Arm Landmine Hack Squat', 'https://youtu.be/hwd_6Y9YKvI'),
  ('Resistance Band Shoulder Dislocates', 'https://youtu.be/5yPvjJOqbg4?si=1OYvLb1R7Zq_hl94'),
  ('Suspension Reverse Grip Bicep Curl', 'https://youtu.be/yewf3adybcc?si=-PZ9RsGl7FC8vp7J'),
  ('Cable Straight Bar Reverse Grip Bicep Curl', 'https://youtu.be/RLlT3qbVS3Q?si=SYASKBhplBkTNYee'),
  ('Single Arm Cable Reverse Grip Bicep Curl', 'https://youtu.be/SIuDkLLlL6E?si=_Y_P-I5PU4GP5LRy'),
  ('Bar Eccentric Chin Up', 'https://youtu.be/B1nRr__KiNk?si=5PGKtxdEbPpVW1Ds'),
  ('Bar Eccentric Pull Up', 'https://youtu.be/T4Jv__fWjZ8?si=sbUarOu5VD7qBK4s'),
  ('Landmine Half Kneeling Oblique Twist', 'https://youtu.be/HGzu8tvh79U'),
  ('Single Arm Bar Dead Hang', 'https://youtu.be/uyNR71ZCrho?si=blbw-wn6NHBGbR9y'),
  ('Single Arm Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/UF_oINIojVQ?si=nyrZ0y91pz4IIfOs'),
  ('Alternating Double Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/2kWWWRpk6Co?si=gy0bI1KIAsGs2hhI'),
  ('Alternating Double Kettlebell Half Kneeling Overhead Press', 'https://youtu.be/V3wxOSo53mQ?si=cM14QdTRQfd_FXUt'),
  ('Stability Ball Single Arm Forearm Plank', 'https://youtu.be/J3JZR2SFknM'),
  ('Stability Ball Feet Elevated Single Arm Forearm Plank', 'https://youtu.be/PAFvOAPjKwk'),
  ('Landmine Zercher Skater Squat', 'https://youtu.be/avCA3xXb9hg'),
  ('Single Arm Landmine Front Rack Contralateral Reverse Lunge to Shoulder Press', 'https://youtu.be/h2bPSv9ka_o'),
  ('Landmine Thruster', 'https://youtu.be/jLvQenjeus8'),
  ('Landmine Romanian Deadlift', 'https://youtu.be/x5wWyQ-2k2E?feature=shared'),
  ('Single Arm Landmine Single Leg Romanian Deadlift', 'https://youtu.be/rzJse5Ds98k'),
  ('Landmine Tall Kneeling Oblique Twist', 'https://youtu.be/OCMcVEdK5vw'),
  ('Landmine Feet Elevated Russian Twist', 'https://youtu.be/Zb-l68-4KFM'),
  ('Single Arm Landmine Thruster', 'https://youtu.be/EcUficjayCY'),
  ('Double Kettlebell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Ke5Erzd3NjE?si=fOzgTGBaC6CMWfE6'),
  ('Landmine Zercher Curtsy Lunge', 'https://youtu.be/e7jkuKuWcZ0'),
  ('Barbell Back Rack Alternating Cossack Squat', 'https://youtu.be/YZQP6D9LP4E'),
  ('Barbell Front Rack Alternating Cossack Squat', 'https://youtu.be/_AEuTTkYzjg'),
  ('Dumbbell Goblet Alternating Cossack Squat', 'https://youtu.be/glbP_VzHNkw?si=1k1fGSYRRORQv7W8'),
  ('Bodyweight Alternating Cossack Squat', 'https://youtu.be/dhDjKmTX8tU'),
  ('Bodyweight Knee Over Toe Split Squat', 'https://youtu.be/ufsoFnFCqA4'),
  ('Barbell Back Rack Knee Over Toe Split Squat', 'https://youtu.be/RBcrPYSWQb8'),
  ('Barbell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/q7zJZAexRmc'),
  ('EZ Bar Incline Bench Lying Tricep Extension', 'https://youtu.be/vJuyPyyEdTs?si=_MMem5dVaaarfRRu'),
  ('EZ Bar Skull Crusher', 'https://youtu.be/eiCMrII3j9k?si=J2G1ZmeiFQDhnfxT'),
  ('Slider Knee Tuck', 'https://youtu.be/vx9j9l18pyE?si=U7boXKing8U74cQZ'),
  ('EZ Bar Incline Bench Skull Crusher', 'https://youtu.be/9VtEoirFmT8?si=B904_aTFyPDoEqMp'),
  ('EZ Bar Decline Bench Skull Crusher', 'https://youtu.be/XFBsHDastRI?si=rP6H63ZVPOndCThK'),
  ('EZ Bar Front Raise', 'https://youtu.be/N4HLFIr5H4A?si=l2WKwgNX9fExG7xF'),
  ('Suspension Pike', 'https://youtu.be/MkmpHj0T3OQ'),
  ('Suspension Side Plank Reach Through', 'https://youtu.be/9PiqAsdkh6Q'),
  ('Bodyweight Cocoon Crunch', 'https://youtu.be/BZWoijzyF_4?si=2gKtoX0oa_Lef7o8'),
  ('Ab Wheel Standing Rollout', 'https://youtu.be/SFTn_VON9qw'),
  ('Cable Fire Hydrant', 'https://youtu.be/P4cP-juNM1Q'),
  ('Cable Tall Kneeling Pull Through', 'https://youtu.be/5mkpuBI-2Ls'),
  ('Bodyweight Bent Knee Reverse Hyperextension', 'https://youtu.be/RbkVHCMU3xU'),
  ('Parallette Tuck L Sit', 'https://youtu.be/VhqEdeeAyvg'),
  ('EZ Bar Close Grip Bicep Curl', 'https://youtu.be/o1c9wFYt6FA?feature=shared'),
  ('EZ Bar Overhead Press', 'https://youtu.be/_5VJKCjn8YE?feature=shared'),
  ('Parallette Single Leg L Sit', 'https://youtu.be/V3hnphPbiAg'),
  ('Stability Ball Windshield Wiper', 'https://youtu.be/tVfP2_HkXEc'),
  ('Stability Ball Tall Kneeling Balance', 'https://youtu.be/wIkwr6LV9E8?si=WttWmNStYjInstEN'),
  ('Stability Ball Forearm Plank', 'https://youtu.be/4xODTD0UL-o?si=TSlUT4Fa309FslEb'),
  ('Slider Double Kettlebell Suitcase Lateral Lunge', 'https://youtu.be/bAaaXP2xb8E?si=AOaxE4RzaGKjiq0h'),
  ('Slider Kettlebell Horn Grip Lateral Lunge', 'https://youtu.be/OsP6_mqxBDI?si=Kdp1ECOmqjUFcNM9'),
  ('Single Arm Dumbbell Turkish Sit Up', 'https://youtu.be/h9OYpweuJEc'),
  ('Single Arm Landmine Turkish Sit Up', 'https://youtu.be/EhYVfy1KUUA'),
  ('Double Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/xkL1f4yewf0'),
  ('Double Dumbbell Turkish Sit Up', 'https://youtu.be/SreLOxzaIX4'),
  ('Single Arm Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/_FjMUe0AhTY'),
  ('Single Arm Kettlebell Overhead Cyclist Squat', 'https://youtu.be/PSRoSLw3GME'),
  ('Double Dumbbell Front Rack Alternating Cossack Squat', 'https://youtu.be/JFeG8YiLYmk'),
  ('Kettlebell Horn Grip Cyclist Squat', 'https://youtu.be/TysYZ7rKhpM'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Cyclist Squat', 'https://youtu.be/x8bLCSXTChA'),
  ('EZ Bar Seated Overhead Press', 'https://youtu.be/-MwL_9KOv7U?si=z-KgUayvNC37N78i'),
  ('Double Dumbbell Suitcase Knee Over Toe Split Squat', 'https://youtu.be/2U58iHm7oSM'),
  ('EZ Bar Close Grip Bench Press', 'https://youtu.be/yoS-cVxq28Q?si=hPjefaZ8jY6Ugoh_'),
  ('EZ Bar Close Grip Incline Bench Press', 'https://youtu.be/PEH5Ncie81g?si=F2eXxzjoehGGc9Bb'),
  ('EZ Bar Close Grip Decline Bench Press', 'https://youtu.be/K40CGYdAysc?si=AY-3wTXsp03-uRQ_'),
  ('Cable Half Kneeling Pallof Press', 'https://youtu.be/7JBR6JGE1hY'),
  ('Barbell Kneeling Rollout', 'https://youtu.be/AEfj6Lnn0Ao'),
  ('Barbell Reverse Grip Overhead Press', 'https://youtu.be/ZO_ALQcMaq4?si=Sv5NmxfQj3aIKU84'),
  ('Cable Tall Kneeling Pallof Press', 'https://youtu.be/EtEPKajf0PE'),
  ('Tire Sledge Hammer Staggered Stance Slam', 'https://youtu.be/ykhGpORlJ4Y?si=6hFSwmMbG1lGLXki'),
  ('Barbell Hang Power Clean', 'https://youtu.be/0aP3tgKZcHQ'),
  ('Landmine Goblet Alternating Cossack Squat', 'https://youtu.be/N549md2Wu2A'),
  ('Landmine Low Hold Alternating Cossack Squat', 'https://youtu.be/PnBI0wLBZIg'),
  ('Bodyweight Push Up', 'https://youtu.be/_l3ySVKYVJ8?si=PZh3DAAcRNF9txaZ'),
  ('Barbell Close Grip Incline Bench Press', 'https://youtu.be/wbI4qof1454?si=WRjRCDTcll5n5uKu'),
  ('Double Dumbbell Push Press', 'https://youtu.be/JqztIwOb4Hs?si=89lHhxGXew7SEPqj'),
  ('Single Arm Dumbbell Push Press', 'https://youtu.be/-TVuoR8URxg?si=RsWhCdjyNahveL9y'),
  ('Alternating Double Dumbbell Push Press', 'https://youtu.be/Kn3oZ9MNAhg?si=j1DYyyohu1ImlWt4'),
  ('Cable Rope Tall Kneeling Overhead Tricep Extension', 'https://youtu.be/cDMXXH7Y9AM?si=pObK3p_2FqS0HqbC'),
  ('Alternating Double Kettlebell Push Jerk', 'https://youtu.be/4wXnxXq4hX4?si=21E2nrYJROeQgBUm'),
  ('Double Dumbbell Push Jerk', 'https://youtu.be/oWfLP7JFwTg?si=UbP4KHHXrg5hVRnc'),
  ('Alternating Double Kettlebell Overhead Press', 'https://youtu.be/KMKqAY-T3wE?si=DccwyejeKVDgXRV-'),
  ('Single Arm Dumbbell Push Jerk', 'https://youtu.be/r-yDtVg8Yf0?si=XQ5L1OU_VTCHZWRf'),
  ('Alternating Double Dumbbell Push Jerk', 'https://youtu.be/ZQ653_FImKw?si=O2ttj0r4a_Nbkwq1'),
  ('Double Kettlebell Bottoms Up Floor Press', 'https://youtu.be/BDCAkIEOPvE?si=ouPFKCSuMS-REkBT'),
  ('Single Arm Kettlebell Bottoms Up Floor Press', 'https://youtu.be/uk39UR9K25Y?si=s6ejJf9GtQ4llbjw'),
  ('Trap Bar Bent Over Row', 'https://youtu.be/aNllFax4shk?si=J0w79P4ud8wpm67U'),
  ('Trap Bar Pendlay Row', 'https://youtu.be/d5rLWfIN9fo?si=iiKqMHW4Xr9OMyaR'),
  ('Trap Bar Shrug', 'https://youtu.be/DjFdFkeXSDM?si=RIA3ok7NhzuAj8LK'),
  ('Bodyweight Tuck L Sit', 'https://youtu.be/U9Z7WWNm1d4?si=pWSS4MOr8iZXWiNj'),
  ('Parallette Straddle L Sit', 'https://youtu.be/F6o417SxU1g'),
  ('Battle Rope Power Slam', 'https://youtu.be/7wDx6mZDxA8?si=rDE21yzc81AXz5sw'),
  ('Bodyweight Manna', 'https://youtu.be/L7reIo5f6uo'),
  ('Ring Tuck Back Lever', 'https://youtu.be/SZV1-ts76CM'),
  ('Ring Full Back Lever', 'https://youtu.be/ZFEy1s_N820'),
  ('Trap Bar Floor Press', 'https://youtu.be/4C4LDf-eZ5A?si=Uh-L_Lu-0xta0H-S'),
  ('Trap Bar Overhead Press', 'https://youtu.be/Vorw1hVd_Dc?si=CRIVCwpCzzeBwN26'),
  ('Ring Tuck Front Lever', 'https://youtu.be/JxlKAuD9gkA'),
  ('Ring Straddle Front Lever', 'https://youtu.be/eI-15uPc0yE'),
  ('Ring Full Front Lever', 'https://youtu.be/rB9EcLohiVs'),
  ('Ring Inverted Hang', 'https://youtu.be/txtXtF2-4S0'),
  ('Single Arm Barbell Kneeling Rollout', 'https://youtu.be/i-JO6pBsKWk'),
  ('Trap Bar Tall Kneeling Overhead Press', 'https://youtu.be/ILFSDv6TaiY?si=0iUQUtwUMsGFbVuI'),
  ('Trap Bar Bench Press', 'https://youtu.be/8TIFsF_HU_8?feature=shared')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);