import json

exercises = []

# ============================================================
# CATEGORY 1: MACHINE EXERCISES
# ============================================================

# --- Leg Machines ---
exercises.append({"name":"Machine Leg Extension","description":"Seated leg extension on a pin-loaded machine targeting the quadriceps.","body_parts":["Quadriceps"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple","quad-isolation"]})
exercises.append({"name":"Machine Single Leg Extension","description":"Unilateral seated leg extension on a pin-loaded machine.","body_parts":["Quadriceps"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":True},"equipment":["Machine"],"tags":["machine","unilateral"]})
exercises.append({"name":"Machine Seated Leg Curl","description":"Seated hamstring curl on a pin-loaded machine.","body_parts":["Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Lying Leg Curl","description":"Prone hamstring curl on a plate-loaded or pin-loaded machine.","body_parts":["Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Single Leg Lying Curl","description":"Unilateral prone hamstring curl on a machine.","body_parts":["Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":True},"equipment":["Machine"],"tags":["machine","unilateral"]})
exercises.append({"name":"Machine Leg Press","description":"Compound lower-body press on a 45-degree sled machine.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple","compound"]})
exercises.append({"name":"Machine Horizontal Leg Press","description":"Horizontal seated leg press machine.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","compound"]})
exercises.append({"name":"Machine Single Leg Press","description":"Unilateral leg press on a 45-degree sled machine.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Machine"],"tags":["machine","unilateral"]})
exercises.append({"name":"Machine Leg Press Calf Raise","description":"Calf raise performed at the bottom of a leg press machine.","body_parts":["Calves"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Machine"],"tags":["machine","calf"]})
exercises.append({"name":"Machine Hack Squat","description":"Angled squat on a hack squat sled machine.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple","compound"]})
exercises.append({"name":"Machine Reverse Hack Squat","description":"Facing-in hack squat emphasising glutes and hamstrings.","body_parts":["Glutes","Hamstrings","Quadriceps"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","compound"]})
exercises.append({"name":"Machine Pendulum Squat","description":"Pendulum-lever squat machine for quad-dominant squatting.","body_parts":["Quadriceps","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","compound"]})
exercises.append({"name":"Machine Belt Squat","description":"Belt-loaded squat machine that removes spinal loading.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","compound","spine-friendly"]})
exercises.append({"name":"Machine V Squat","description":"V-squat machine with shoulder pads for quad emphasis.","body_parts":["Quadriceps","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Machine"],"tags":["machine","compound"]})
exercises.append({"name":"Machine Standing Calf Raise","description":"Standing calf raise on a shoulder-pad loaded machine.","body_parts":["Calves"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Seated Calf Raise","description":"Seated calf raise with knee pad targeting the soleus.","body_parts":["Calves"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Donkey Calf Raise","description":"Bent-over calf raise on a donkey calf machine.","body_parts":["Calves"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Other","grip":"No Grip","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Hip Abduction","description":"Seated hip abduction machine targeting the outer glutes.","body_parts":["Abductors","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Abduction","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Hip Adduction","description":"Seated hip adduction machine targeting the inner thighs.","body_parts":["Adductors"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Adduction","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Glute Kickback","description":"Standing or kneeling glute kickback on a dedicated machine.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Extension","alternating":True},"equipment":["Machine"],"tags":["machine","glute-isolation"]})
exercises.append({"name":"Machine Hip Thrust","description":"Hip thrust on a dedicated hip thrust machine.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Other","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Extension","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Glute Drive","description":"Plate-loaded glute drive machine for hip extension.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Other","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Extension","alternating":False},"equipment":["Machine"],"tags":["machine"]})

# --- Smith Machine ---
exercises.append({"name":"Smith Machine Back Squat","description":"Back squat performed on a guided Smith machine bar path.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Front Squat","description":"Front squat on a Smith machine.","body_parts":["Quadriceps","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Bench Press","description":"Flat bench press on a Smith machine.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Incline Bench Press","description":"Incline bench press on a Smith machine.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Decline Bench Press","description":"Decline bench press on a Smith machine.","body_parts":["Chest","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Close Grip Bench Press","description":"Close-grip bench press on a Smith machine targeting triceps.","body_parts":["Triceps","Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Overhead Press","description":"Standing overhead press on a Smith machine.","body_parts":["Shoulders","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Seated Overhead Press","description":"Seated overhead press on a Smith machine.","body_parts":["Shoulders","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Behind the Neck Press","description":"Behind-the-neck overhead press on a Smith machine.","body_parts":["Shoulders","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine"]})
exercises.append({"name":"Smith Machine Bent Over Row","description":"Bent-over barbell row on a Smith machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Upright Row","description":"Upright row on a Smith machine.","body_parts":["Shoulders","Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Scapular Elevation","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine"]})
exercises.append({"name":"Smith Machine Shrug","description":"Shrug on a Smith machine targeting the trapezius.","body_parts":["Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Scapular Elevation","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine"]})
exercises.append({"name":"Smith Machine Lunge","description":"Forward or reverse lunge on a Smith machine.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Bulgarian Split Squat","description":"Rear-foot-elevated split squat on a Smith machine.","body_parts":["Quadriceps","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Calf Raise","description":"Standing calf raise using a Smith machine bar.","body_parts":["Calves"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine"]})
exercises.append({"name":"Smith Machine Romanian Deadlift","description":"Romanian deadlift on a Smith machine.","body_parts":["Hamstrings","Glutes","Back"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine","compound"]})
exercises.append({"name":"Smith Machine Hip Thrust","description":"Hip thrust using a Smith machine bar across the hips.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Other","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Extension","alternating":False},"equipment":["Smith Machine"],"tags":["smith-machine"]})

# --- Chest Machines ---
exercises.append({"name":"Machine Chest Press","description":"Seated chest press on a pin-loaded or plate-loaded machine.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Incline Chest Press","description":"Incline chest press on a machine.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Decline Chest Press","description":"Decline chest press on a machine.","body_parts":["Chest","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Pec Deck Fly","description":"Seated chest fly on a pec deck machine.","body_parts":["Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Chest Fly","description":"Seated chest fly on a converging-arm machine.","body_parts":["Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Machine"],"tags":["machine"]})

# --- Back Machines ---
exercises.append({"name":"Machine Lat Pulldown","description":"Wide-grip lat pulldown on a cable machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Close Grip Lat Pulldown","description":"Close-grip lat pulldown targeting the lats and biceps.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Supinated Lat Pulldown","description":"Underhand-grip lat pulldown emphasising biceps.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Seated Row","description":"Seated cable or lever row targeting the mid-back.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Wide Grip Seated Row","description":"Wide-grip seated row for rear delts and upper back.","body_parts":["Back","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Chest Supported Row","description":"Chest-supported lever row machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Single Arm Row","description":"Unilateral machine row for back development.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":True},"equipment":["Machine"],"tags":["machine","unilateral"]})
exercises.append({"name":"Machine Straight Arm Pulldown","description":"Straight-arm lat pulldown on a cable machine.","body_parts":["Back"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Shoulder Flexion","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Assisted Pull Up","description":"Pull-up on a counterweighted assisted machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body","Calisthenics"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Machine"],"tags":["machine","assisted"]})
exercises.append({"name":"Machine Assisted Chin Up","description":"Chin-up on a counterweighted assisted machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body","Calisthenics"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Supinated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Machine"],"tags":["machine","assisted"]})
exercises.append({"name":"Machine Assisted Dip","description":"Dip on a counterweighted assisted machine.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body","Calisthenics"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Machine"],"tags":["machine","assisted"]})
exercises.append({"name":"Machine T-Bar Row","description":"T-bar row on a plate-loaded lever machine.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple","compound"]})
exercises.append({"name":"Machine Pullover","description":"Pullover on a dedicated Nautilus-style machine.","body_parts":["Back","Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Shoulder Flexion","alternating":False},"equipment":["Machine"],"tags":["machine"]})

# --- Shoulder Machines ---
exercises.append({"name":"Machine Shoulder Press","description":"Seated overhead shoulder press on a machine.","body_parts":["Shoulders","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Lateral Raise","description":"Lateral raise on a lever or pad machine.","body_parts":["Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Shoulder Abduction","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Reverse Pec Deck","description":"Reverse fly on a pec deck machine targeting rear delts.","body_parts":["Shoulders","Back"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple","rear-delt"]})

# --- Arm Machines ---
exercises.append({"name":"Machine Preacher Curl","description":"Preacher curl on a dedicated machine.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Bicep Curl","description":"Seated bicep curl on a lever machine.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Tricep Extension","description":"Seated overhead or pushdown tricep extension on a machine.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Tricep Dip","description":"Seated tricep dip on a lever machine.","body_parts":["Triceps","Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Elbow Extension","alternating":False},"equipment":["Machine"],"tags":["machine"]})

# --- Core Machines ---
exercises.append({"name":"Machine Ab Crunch","description":"Seated abdominal crunch on a resistance machine.","body_parts":["Abdominals"],"categories":["Bodybuilding","Core"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Machine Torso Rotation","description":"Seated torso rotation machine for obliques.","body_parts":["Abdominals"],"categories":["Bodybuilding","Core"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Rotational","alternating":False},"equipment":["Machine"],"tags":["machine"]})
exercises.append({"name":"Machine Back Extension","description":"Back extension on a lever or pin-loaded machine.","body_parts":["Back","Glutes"],"categories":["Bodybuilding","Core"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Extension","alternating":False},"equipment":["Machine"],"tags":["machine"]})

# --- Cable Extras ---
exercises.append({"name":"Cable Crossover","description":"Standing cable fly with high or mid pulley for chest.","body_parts":["Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Cable"],"tags":["cable","gym-staple"]})
exercises.append({"name":"Cable Low Crossover","description":"Low-to-high cable fly targeting upper chest.","body_parts":["Chest","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Upright Row","description":"Upright row using a cable machine.","body_parts":["Shoulders","Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Scapular Elevation","alternating":False},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Lateral Raise","description":"Lateral raise using a low cable pulley.","body_parts":["Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Shoulder Abduction","alternating":True},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Reverse Fly","description":"Rear delt fly using cable pulleys.","body_parts":["Shoulders","Back"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Cable"],"tags":["cable","rear-delt"]})
exercises.append({"name":"Cable Overhead Tricep Extension","description":"Overhead tricep extension using a cable rope attachment.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":False},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Kickback","description":"Single-arm tricep kickback using a low cable pulley.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":True},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Woodchop","description":"Standing rotational cable woodchop for core.","body_parts":["Abdominals"],"categories":["Core","Full Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Rotational","alternating":False},"equipment":["Cable"],"tags":["cable","core"]})
exercises.append({"name":"Cable Pallof Press","description":"Anti-rotation press using a cable for core stability.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Anti-Rotational","alternating":False},"equipment":["Cable"],"tags":["cable","core","anti-rotation"]})
exercises.append({"name":"Cable Pull Through","description":"Cable pull-through for glute and hamstring activation.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Cable"],"tags":["cable"]})
exercises.append({"name":"Cable Crunch","description":"Kneeling cable crunch for abdominals.","body_parts":["Abdominals"],"categories":["Bodybuilding","Core"],"tracking_type":"weight_reps","options":{"posture":"Kneeling","grip":"Neutral","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Cable"],"tags":["cable","core"]})

# ============================================================
# CATEGORY 2: COMMON NAME ALIASES
# ============================================================
exercises.append({"name":"Squat","description":"General barbell back squat — common alias.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Barbell"],"tags":["alias","powerlifting-staple"]})
exercises.append({"name":"Deadlift","description":"Conventional deadlift — common alias.","body_parts":["Back","Glutes","Hamstrings","Quadriceps"],"categories":["Powerlifting","Full Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Mixed Grip","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Barbell"],"tags":["alias","powerlifting-staple"]})
exercises.append({"name":"Bench Press","description":"Flat barbell bench press — common alias.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Barbell"],"tags":["alias","powerlifting-staple"]})
exercises.append({"name":"Overhead Press","description":"Standing barbell overhead press — common alias.","body_parts":["Shoulders","Triceps"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Military Press","description":"Strict standing barbell overhead press with feet together.","body_parts":["Shoulders","Triceps"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Barbell Row","description":"Barbell bent-over row — common alias.","body_parts":["Back","Biceps"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Pull Up","description":"Bodyweight pull-up — common alias.","body_parts":["Back","Biceps"],"categories":["Calisthenics","Upper Body"],"tracking_type":"reps_only","options":{"posture":"Hanging","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Pull Up Bar"],"tags":["alias","bodyweight"]})
exercises.append({"name":"Chin Up","description":"Bodyweight chin-up — common alias.","body_parts":["Back","Biceps"],"categories":["Calisthenics","Upper Body"],"tracking_type":"reps_only","options":{"posture":"Hanging","grip":"Supinated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Pull Up Bar"],"tags":["alias","bodyweight"]})
exercises.append({"name":"Dip","description":"Bodyweight parallel bar dip — common alias.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Calisthenics","Upper Body"],"tracking_type":"reps_only","options":{"posture":"Other","grip":"Neutral","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Dip Bar"],"tags":["alias","bodyweight"]})
exercises.append({"name":"Push Up","description":"Standard bodyweight push-up — common alias.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Calisthenics","Upper Body"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Bodyweight"],"tags":["alias","bodyweight"]})
exercises.append({"name":"Lunge","description":"Bodyweight or loaded forward lunge — common alias.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Bodyweight"],"tags":["alias"]})
exercises.append({"name":"Romanian Deadlift","description":"Barbell Romanian deadlift — common alias.","body_parts":["Hamstrings","Glutes","Back"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Sumo Deadlift","description":"Wide-stance barbell deadlift — common alias.","body_parts":["Quadriceps","Glutes","Hamstrings","Back"],"categories":["Powerlifting","Full Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Mixed Grip","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Barbell"],"tags":["alias","powerlifting-staple"]})
exercises.append({"name":"Front Squat","description":"Barbell front squat — common alias.","body_parts":["Quadriceps","Glutes"],"categories":["Olympic Weightlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Incline Bench Press","description":"Barbell incline bench press — common alias.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Skull Crusher","description":"Lying barbell or EZ bar tricep extension — common alias.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":False},"equipment":["Barbell"],"tags":["alias"]})
exercises.append({"name":"Hammer Curl","description":"Dumbbell hammer curl — common alias.","body_parts":["Biceps","Forearms"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Dumbbell"],"tags":["alias"]})
exercises.append({"name":"Bicep Curl","description":"Dumbbell or barbell bicep curl — common alias.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Dumbbell"],"tags":["alias"]})
exercises.append({"name":"Lateral Raise","description":"Dumbbell lateral raise — common alias.","body_parts":["Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Shoulder Abduction","alternating":False},"equipment":["Dumbbell"],"tags":["alias"]})
exercises.append({"name":"Tricep Pushdown","description":"Cable rope or bar tricep pushdown — common alias.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":False},"equipment":["Cable"],"tags":["alias"]})
exercises.append({"name":"Face Pull","description":"Cable face pull — common alias.","body_parts":["Shoulders","Back"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Cable"],"tags":["alias"]})
exercises.append({"name":"Lat Pulldown","description":"Cable lat pulldown — common alias.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Cable"],"tags":["alias"]})
exercises.append({"name":"Seated Row","description":"Cable seated row — common alias.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Cable"],"tags":["alias"]})
exercises.append({"name":"Hip Thrust","description":"Barbell hip thrust — common alias.","body_parts":["Glutes","Hamstrings"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Other","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Extension","alternating":False},"equipment":["Barbell"],"tags":["alias"]})

# ============================================================
# CATEGORY 3: MISSING COMMON FREE WEIGHT EXERCISES
# ============================================================
exercises.append({"name":"Barbell Upright Row","description":"Barbell upright row targeting shoulders and traps.","body_parts":["Shoulders","Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Scapular Elevation","alternating":False},"equipment":["Barbell"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Upright Row","description":"Dumbbell upright row for shoulders and traps.","body_parts":["Shoulders","Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Scapular Elevation","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight"]})
exercises.append({"name":"EZ Bar Preacher Curl","description":"Preacher curl using an EZ curl bar for bicep isolation.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["EZ Bar","Preacher Bench"],"tags":["free-weight","gym-staple"]})
exercises.append({"name":"EZ Bar Upright Row","description":"Upright row using an EZ curl bar.","body_parts":["Shoulders","Trapezius"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Scapular Elevation","alternating":False},"equipment":["EZ Bar"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Preacher Curl","description":"Preacher curl using a straight barbell.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Barbell","Preacher Bench"],"tags":["free-weight"]})
exercises.append({"name":"T-Bar Row","description":"Landmine-style T-bar row for thick back development.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Barbell","Landmine"],"tags":["free-weight","gym-staple"]})
exercises.append({"name":"Dumbbell Rear Delt Fly","description":"Bent-over dumbbell fly targeting the rear deltoids.","body_parts":["Shoulders","Back"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Incline Bench Curl","description":"Incline bench dumbbell curl for stretched bicep position.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Wrist Curl","description":"Seated dumbbell wrist curl for forearm flexors.","body_parts":["Forearms"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Wrist Flexion","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Reverse Wrist Curl","description":"Seated dumbbell reverse wrist curl for forearm extensors.","body_parts":["Forearms"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Isolation","movementPattern":"Wrist Extension","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Wrist Curl","description":"Seated barbell wrist curl for forearm development.","body_parts":["Forearms"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Wrist Flexion","alternating":False},"equipment":["Barbell"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Reverse Wrist Curl","description":"Seated barbell reverse wrist curl for forearm extensors.","body_parts":["Forearms"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Pronated","mechanics":"Isolation","movementPattern":"Wrist Extension","alternating":False},"equipment":["Barbell"],"tags":["free-weight"]})
exercises.append({"name":"Trap Bar Carry","description":"Loaded carry using a trap/hex bar.","body_parts":["Trapezius","Forearms","Quadriceps","Glutes"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Loaded Carry","alternating":False},"equipment":["Trap Bar"],"tags":["free-weight","carry"]})
exercises.append({"name":"Trap Bar Jump","description":"Explosive jump squat using a trap/hex bar.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Plyometric","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Trap Bar"],"tags":["free-weight","explosive"]})
exercises.append({"name":"Dumbbell Concentration Curl","description":"Seated single-arm concentration curl for bicep peak.","body_parts":["Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Supinated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":True},"equipment":["Dumbbell"],"tags":["free-weight","gym-staple"]})
exercises.append({"name":"Dumbbell Tate Press","description":"Dumbbell Tate press for tricep isolation.","body_parts":["Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Extension","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Reverse Curl","description":"Standing barbell curl with overhand grip for forearms and biceps.","body_parts":["Forearms","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Barbell"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Reverse Curl","description":"Standing dumbbell curl with overhand grip.","body_parts":["Forearms","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Elbow Flexion","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight"]})
exercises.append({"name":"Farmer Walk","description":"Heavy loaded carry with dumbbells or farmer handles.","body_parts":["Trapezius","Forearms","Quadriceps","Glutes"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Walking","grip":"Neutral","mechanics":"Compound","movementPattern":"Loaded Carry","alternating":False},"equipment":["Dumbbell"],"tags":["free-weight","carry","gym-staple"]})
exercises.append({"name":"Dumbbell Fly","description":"Flat bench dumbbell fly for chest isolation.","body_parts":["Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight","alias"]})
exercises.append({"name":"Dumbbell Incline Fly","description":"Incline bench dumbbell fly for upper chest.","body_parts":["Chest","Shoulders"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Neutral","mechanics":"Isolation","movementPattern":"Horizontal Push","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Landmine Press","description":"Single-arm landmine press for shoulders.","body_parts":["Shoulders","Chest","Triceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Vertical Push","alternating":True},"equipment":["Barbell","Landmine"],"tags":["free-weight"]})
exercises.append({"name":"Barbell Landmine Row","description":"Single-arm landmine row for back thickness.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":True},"equipment":["Barbell","Landmine"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Pullover","description":"Dumbbell pullover on a flat bench for lats and chest.","body_parts":["Back","Chest"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Neutral","mechanics":"Isolation","movementPattern":"Shoulder Flexion","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight","alias"]})
exercises.append({"name":"Barbell Good Morning","description":"Barbell good morning for hamstring and lower back.","body_parts":["Hamstrings","Back","Glutes"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Barbell"],"tags":["free-weight","powerlifting"]})
exercises.append({"name":"Barbell Pause Squat","description":"Back squat with a deliberate pause at the bottom.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Barbell"],"tags":["powerlifting"]})
exercises.append({"name":"Barbell Tempo Squat","description":"Back squat with controlled eccentric tempo.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Barbell"],"tags":["powerlifting"]})
exercises.append({"name":"Barbell Pin Squat","description":"Squat from pins in a power rack for concentric strength.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Powerlifting","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Barbell","Power Rack"],"tags":["powerlifting"]})
exercises.append({"name":"Barbell Board Press","description":"Bench press to a board for lockout strength.","body_parts":["Chest","Triceps"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Barbell","Board"],"tags":["powerlifting"]})
exercises.append({"name":"Barbell Spoto Press","description":"Bench press paused 1 inch above chest.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Powerlifting","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Supine","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Barbell"],"tags":["powerlifting"]})
exercises.append({"name":"Barbell Seal Row","description":"Chest-supported barbell row on an elevated bench.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Barbell","Bench"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Seal Row","description":"Chest-supported dumbbell row on an elevated bench.","body_parts":["Back","Biceps"],"categories":["Bodybuilding","Upper Body"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Dumbbell","Bench"],"tags":["free-weight"]})
exercises.append({"name":"Dumbbell Bulgarian Split Squat","description":"Rear-foot-elevated split squat holding dumbbells.","body_parts":["Quadriceps","Glutes"],"categories":["Bodybuilding","Lower Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Dumbbell","Bench"],"tags":["free-weight","gym-staple"]})

# ============================================================
# CATEGORY 4: MISSING BODYWEIGHT STAPLES
# ============================================================
exercises.append({"name":"Jumping Jack","description":"Full-body calisthenic jumping jack for warm-up and cardio.","body_parts":["Quadriceps","Calves","Shoulders"],"categories":["Full Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","warm-up","cardio"]})
exercises.append({"name":"Depth Jump","description":"Plyometric jump stepping off a box and immediately jumping.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Plyometric","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Box"],"tags":["plyometric","explosive"]})
exercises.append({"name":"Tuck Jump","description":"Explosive vertical jump bringing knees to chest.","body_parts":["Quadriceps","Glutes","Calves","Abdominals"],"categories":["Plyometric","Full Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Bodyweight"],"tags":["plyometric","explosive"]})
exercises.append({"name":"Bear Crawl","description":"Quadruped crawling pattern for full-body conditioning.","body_parts":["Shoulders","Quadriceps","Abdominals"],"categories":["Full Body","Calisthenics"],"tracking_type":"distance","options":{"posture":"Quadruped","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","conditioning"]})
exercises.append({"name":"Crab Walk","description":"Supine crawling movement for shoulders and triceps.","body_parts":["Triceps","Shoulders","Glutes"],"categories":["Full Body","Calisthenics"],"tracking_type":"distance","options":{"posture":"Other","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","conditioning"]})
exercises.append({"name":"Army Crawl","description":"Prone crawling movement using forearms.","body_parts":["Shoulders","Abdominals","Hip Flexors"],"categories":["Full Body","Calisthenics"],"tracking_type":"distance","options":{"posture":"Prone","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","conditioning"]})
exercises.append({"name":"Superman Hold","description":"Prone back extension hold with arms and legs raised.","body_parts":["Back","Glutes"],"categories":["Core","Calisthenics"],"tracking_type":"time","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Extension","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","isometric"]})
exercises.append({"name":"Superman","description":"Prone back extension raising arms and legs dynamically.","body_parts":["Back","Glutes"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Extension","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"High Plank","description":"Plank held on extended arms in push-up position.","body_parts":["Abdominals","Shoulders"],"categories":["Core","Calisthenics"],"tracking_type":"time","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Anti-Extension","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","isometric"]})
exercises.append({"name":"Side Plank","description":"Lateral plank hold on one forearm.","body_parts":["Abdominals"],"categories":["Core","Calisthenics"],"tracking_type":"time","options":{"posture":"Side Lying","grip":"No Grip","mechanics":"Isolation","movementPattern":"Anti-Rotational","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","isometric"]})
exercises.append({"name":"Bodyweight Glute Bridge","description":"Basic bodyweight glute bridge for glute activation.","body_parts":["Glutes","Hamstrings"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Bridge","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Extension","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","activation"]})
exercises.append({"name":"Bodyweight Single Leg Glute Bridge","description":"Single-leg bodyweight glute bridge.","body_parts":["Glutes","Hamstrings"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Bridge","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Extension","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","unilateral"]})
exercises.append({"name":"Sit Up","description":"Basic sit-up for abdominal training.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","gym-staple"]})
exercises.append({"name":"Crunch","description":"Basic abdominal crunch.","body_parts":["Abdominals"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","gym-staple"]})
exercises.append({"name":"Bicycle Crunch","description":"Alternating elbow-to-knee crunch targeting obliques.","body_parts":["Abdominals"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Rotational","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"V Up","description":"Simultaneous raise of legs and torso to form a V shape.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Compound","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Flutter Kicks","description":"Supine alternating leg flutter kicks for lower abs.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Dominant","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Scissor Kicks","description":"Supine alternating crossing leg kicks.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Dominant","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Reverse Crunch","description":"Crunch bringing knees toward chest for lower abs.","body_parts":["Abdominals"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Dead Bug","description":"Anti-extension core exercise with alternating limb lowering.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Anti-Extension","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","rehab","core"]})
exercises.append({"name":"Bird Dog","description":"Quadruped alternating arm and leg extension for core stability.","body_parts":["Abdominals","Back","Glutes"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Quadruped","grip":"No Grip","mechanics":"Compound","movementPattern":"Anti-Rotational","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","rehab","core"]})
exercises.append({"name":"Plank to Push Up","description":"Transition from forearm plank to high plank position.","body_parts":["Abdominals","Triceps","Shoulders"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Compound","movementPattern":"Anti-Extension","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Inchworm","description":"Standing fold to walkout to plank and back.","body_parts":["Abdominals","Shoulders","Hamstrings"],"categories":["Full Body","Mobility"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","warm-up"]})
exercises.append({"name":"Squat Jump","description":"Explosive bodyweight squat jump.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Plyometric","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","plyometric"]})
exercises.append({"name":"Split Squat Jump","description":"Explosive alternating lunge jump.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Plyometric","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","plyometric"]})
exercises.append({"name":"Lateral Bound","description":"Single-leg lateral hop for power and stability.","body_parts":["Quadriceps","Glutes","Abductors"],"categories":["Plyometric","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Abduction","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight","plyometric"]})
exercises.append({"name":"Bodyweight Reverse Lunge","description":"Bodyweight reverse lunge for lower-body training.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Bodyweight Lateral Lunge","description":"Bodyweight side lunge for adductors and quads.","body_parts":["Quadriceps","Adductors","Glutes"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Adduction","alternating":True},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Bodyweight Step Up","description":"Basic bodyweight step-up onto a box or bench.","body_parts":["Quadriceps","Glutes"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Box"],"tags":["bodyweight"]})
exercises.append({"name":"Bodyweight Calf Raise","description":"Standing bodyweight calf raise.","body_parts":["Calves"],"categories":["Lower Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Ankle Plantar Flexion","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight"]})
exercises.append({"name":"Bodyweight Hip Hinge","description":"Bodyweight hip hinge / good morning movement.","body_parts":["Hamstrings","Glutes","Back"],"categories":["Lower Body","Mobility"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Bodyweight"],"tags":["bodyweight","warm-up"]})

# ============================================================
# CATEGORY 5: CARDIO / CONDITIONING EQUIPMENT
# ============================================================
exercises.append({"name":"Rowing Machine","description":"Indoor rowing ergometer for full-body cardio.","body_parts":["Back","Quadriceps","Shoulders","Biceps"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Seated","grip":"Pronated","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Rowing Machine"],"tags":["cardio","conditioning","gym-staple"]})
exercises.append({"name":"Assault Bike","description":"Fan-driven air bike for full-body high-intensity cardio.","body_parts":["Quadriceps","Shoulders","Hamstrings"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Assault Bike"],"tags":["cardio","conditioning","gym-staple"]})
exercises.append({"name":"Ski Erg","description":"Standing ski ergometer pulling motion for upper-body cardio.","body_parts":["Back","Shoulders","Triceps","Abdominals"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":False},"equipment":["Ski Erg"],"tags":["cardio","conditioning"]})
exercises.append({"name":"Treadmill Run","description":"Steady-state or interval running on a treadmill.","body_parts":["Quadriceps","Hamstrings","Calves","Glutes"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Running","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Treadmill"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Treadmill Walk","description":"Walking on a treadmill for low-intensity cardio.","body_parts":["Quadriceps","Hamstrings","Calves","Glutes"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Walking","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Treadmill"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Treadmill Incline Walk","description":"Inclined treadmill walking for glute and cardio emphasis.","body_parts":["Glutes","Hamstrings","Calves","Quadriceps"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Walking","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Treadmill"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Treadmill Sprint","description":"High-intensity sprint intervals on a treadmill.","body_parts":["Quadriceps","Hamstrings","Calves","Glutes"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Running","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Treadmill"],"tags":["cardio","conditioning"]})
exercises.append({"name":"Stairmaster","description":"Stair-climbing machine for lower-body cardio.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Lower Body"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Stairmaster"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Elliptical","description":"Elliptical trainer for low-impact full-body cardio.","body_parts":["Quadriceps","Glutes","Hamstrings"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Elliptical"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Stationary Bike","description":"Upright or recumbent stationary cycling.","body_parts":["Quadriceps","Hamstrings","Calves"],"categories":["Lower Body"],"tracking_type":"distance","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Stationary Bike"],"tags":["cardio","gym-staple"]})
exercises.append({"name":"Spin Bike","description":"Indoor cycling on a spin bike for intense cardio.","body_parts":["Quadriceps","Hamstrings","Calves","Glutes"],"categories":["Lower Body"],"tracking_type":"distance","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Spin Bike"],"tags":["cardio"]})
exercises.append({"name":"Jump Rope","description":"Skipping rope for cardio and coordination.","body_parts":["Calves","Shoulders","Quadriceps"],"categories":["Full Body","Calisthenics"],"tracking_type":"time","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":False},"equipment":["Jump Rope"],"tags":["cardio","conditioning","gym-staple"]})
exercises.append({"name":"Double Under","description":"Jump rope with two passes per jump.","body_parts":["Calves","Shoulders","Quadriceps"],"categories":["Full Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":False},"equipment":["Jump Rope"],"tags":["cardio","conditioning"]})
exercises.append({"name":"Sled Pull","description":"Heavy sled pull using a harness or rope for conditioning.","body_parts":["Back","Glutes","Hamstrings","Quadriceps"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":True},"equipment":["Sled"],"tags":["conditioning","gym-staple"]})
exercises.append({"name":"Sled Drag","description":"Backward sled drag for quad and conditioning work.","body_parts":["Quadriceps","Glutes","Calves"],"categories":["Full Body","Lower Body"],"tracking_type":"distance","options":{"posture":"Walking","grip":"Neutral","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Sled"],"tags":["conditioning"]})
exercises.append({"name":"Prowler Push","description":"Low-handle prowler sled push for conditioning.","body_parts":["Quadriceps","Glutes","Shoulders","Chest"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":True},"equipment":["Sled"],"tags":["conditioning","gym-staple"]})
exercises.append({"name":"Wattbike","description":"Wattbike cycling for power-based cardio training.","body_parts":["Quadriceps","Hamstrings","Calves"],"categories":["Lower Body"],"tracking_type":"distance","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Wattbike"],"tags":["cardio","conditioning"]})

# ============================================================
# CATEGORY 6: SPORT-SPECIFIC & REHABILITATION
# ============================================================
exercises.append({"name":"Bosu Ball Squat","description":"Squat performed on a Bosu ball for balance challenge.","body_parts":["Quadriceps","Glutes"],"categories":["Balance","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Bosu Ball"],"tags":["balance","rehab"]})
exercises.append({"name":"Bosu Ball Push Up","description":"Push-up with hands on a Bosu ball for stability.","body_parts":["Chest","Triceps","Shoulders","Abdominals"],"categories":["Balance","Upper Body"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Bosu Ball"],"tags":["balance","rehab"]})
exercises.append({"name":"Bosu Ball Plank","description":"Forearm plank with forearms on a Bosu ball.","body_parts":["Abdominals","Shoulders"],"categories":["Balance","Core"],"tracking_type":"time","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Anti-Extension","alternating":False},"equipment":["Bosu Ball"],"tags":["balance","core"]})
exercises.append({"name":"Bosu Ball Lunge","description":"Lunge with front foot on a Bosu ball for stability.","body_parts":["Quadriceps","Glutes"],"categories":["Balance","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Bosu Ball"],"tags":["balance","rehab"]})
exercises.append({"name":"Bosu Ball Single Leg Balance","description":"Single-leg balance on a Bosu ball.","body_parts":["Calves","Quadriceps"],"categories":["Balance"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Isometric Hold","alternating":True},"equipment":["Bosu Ball"],"tags":["balance","rehab"]})
exercises.append({"name":"Swiss Ball Crunch","description":"Crunch performed on a stability ball.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Swiss Ball"],"tags":["core","rehab"]})
exercises.append({"name":"Swiss Ball Plank","description":"Forearm plank with forearms on a Swiss ball.","body_parts":["Abdominals","Shoulders"],"categories":["Core","Balance"],"tracking_type":"time","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Anti-Extension","alternating":False},"equipment":["Swiss Ball"],"tags":["core","balance"]})
exercises.append({"name":"Swiss Ball Hamstring Curl","description":"Supine hamstring curl rolling a Swiss ball with feet.","body_parts":["Hamstrings","Glutes"],"categories":["Core","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Knee Dominant","alternating":False},"equipment":["Swiss Ball"],"tags":["core","rehab"]})
exercises.append({"name":"Swiss Ball Pike","description":"Pike movement with feet on a Swiss ball.","body_parts":["Abdominals","Shoulders"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Compound","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Swiss Ball"],"tags":["core"]})
exercises.append({"name":"Swiss Ball Back Extension","description":"Back extension over a Swiss ball.","body_parts":["Back","Glutes"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Extension","alternating":False},"equipment":["Swiss Ball"],"tags":["core","rehab"]})
exercises.append({"name":"Swiss Ball Russian Twist","description":"Seated Russian twist on a Swiss ball.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Rotational","alternating":True},"equipment":["Swiss Ball"],"tags":["core"]})
exercises.append({"name":"Foam Roller Thoracic Extension","description":"Thoracic spine extension stretch over a foam roller.","body_parts":["Back"],"categories":["Mobility"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Extension","alternating":False},"equipment":["Foam Roller"],"tags":["mobility","rehab"]})
exercises.append({"name":"Foam Roller IT Band Roll","description":"Self-myofascial release of the IT band using a foam roller.","body_parts":["Quadriceps","Abductors"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Side Lying","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":True},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Foam Roller Quad Roll","description":"Self-myofascial release of the quadriceps.","body_parts":["Quadriceps"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":False},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Foam Roller Lat Roll","description":"Self-myofascial release of the lats.","body_parts":["Back"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Side Lying","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":True},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Foam Roller Hamstring Roll","description":"Self-myofascial release of the hamstrings.","body_parts":["Hamstrings"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":False},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Foam Roller Calf Roll","description":"Self-myofascial release of the calves.","body_parts":["Calves"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":False},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Foam Roller Glute Roll","description":"Self-myofascial release of the glutes using a foam roller.","body_parts":["Glutes"],"categories":["Mobility"],"tracking_type":"time","options":{"posture":"Seated","grip":"No Grip","mechanics":"Isolation","movementPattern":"Other","alternating":True},"equipment":["Foam Roller"],"tags":["mobility","recovery"]})
exercises.append({"name":"Resistance Band Pull Apart","description":"Band pull-apart for rear delt and upper back activation.","body_parts":["Shoulders","Back"],"categories":["Upper Body","Postural"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Pronated","mechanics":"Isolation","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Resistance Band"],"tags":["band","warm-up","rehab"]})
exercises.append({"name":"Resistance Band Monster Walk","description":"Lateral banded walk for glute activation.","body_parts":["Glutes","Abductors"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Abduction","alternating":True},"equipment":["Resistance Band"],"tags":["band","activation"]})
exercises.append({"name":"Resistance Band Clamshell","description":"Side-lying banded clamshell for glute medius activation.","body_parts":["Glutes","Abductors"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Side Lying","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Abduction","alternating":True},"equipment":["Resistance Band"],"tags":["band","activation","rehab"]})
exercises.append({"name":"Resistance Band External Rotation","description":"Banded shoulder external rotation for rotator cuff.","body_parts":["Shoulders"],"categories":["Upper Body","Postural"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Isolation","movementPattern":"Shoulder External Rotation","alternating":True},"equipment":["Resistance Band"],"tags":["band","rehab","warm-up"]})
exercises.append({"name":"Resistance Band Overhead Press","description":"Standing overhead press using a resistance band.","body_parts":["Shoulders","Triceps"],"categories":["Upper Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Pronated","mechanics":"Compound","movementPattern":"Vertical Push","alternating":False},"equipment":["Resistance Band"],"tags":["band"]})
exercises.append({"name":"Resistance Band Squat","description":"Banded squat for lower-body resistance.","body_parts":["Quadriceps","Glutes"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Resistance Band"],"tags":["band"]})
exercises.append({"name":"Resistance Band Deadlift","description":"Banded deadlift for hip hinge patterning.","body_parts":["Hamstrings","Glutes","Back"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Resistance Band"],"tags":["band"]})
exercises.append({"name":"Resistance Band Row","description":"Seated or standing banded row.","body_parts":["Back","Biceps"],"categories":["Upper Body"],"tracking_type":"reps_only","options":{"posture":"Seated","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Pull","alternating":False},"equipment":["Resistance Band"],"tags":["band"]})
exercises.append({"name":"Agility Ladder Drill","description":"General agility ladder footwork drill for speed and coordination.","body_parts":["Calves","Quadriceps"],"categories":["Full Body","Plyometric"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Agility Ladder"],"tags":["sport-specific","conditioning"]})
exercises.append({"name":"Agility Ladder In-Out","description":"In-and-out lateral footwork through agility ladder.","body_parts":["Calves","Quadriceps","Abductors"],"categories":["Plyometric"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Agility Ladder"],"tags":["sport-specific","conditioning"]})
exercises.append({"name":"Agility Ladder Ickey Shuffle","description":"Ickey shuffle pattern through agility ladder.","body_parts":["Calves","Quadriceps"],"categories":["Plyometric"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Locomotion","alternating":True},"equipment":["Agility Ladder"],"tags":["sport-specific","conditioning"]})
exercises.append({"name":"Balance Board Squat","description":"Squat on a balance board for proprioceptive challenge.","body_parts":["Quadriceps","Glutes"],"categories":["Balance","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Balance Board"],"tags":["balance","rehab"]})
exercises.append({"name":"Balance Board Single Leg Stand","description":"Single-leg balance on a wobble board.","body_parts":["Calves","Quadriceps"],"categories":["Balance"],"tracking_type":"time","options":{"posture":"Standing","grip":"No Grip","mechanics":"Isolation","movementPattern":"Isometric Hold","alternating":True},"equipment":["Balance Board"],"tags":["balance","rehab"]})
exercises.append({"name":"GHD Sit Up","description":"Glute-ham developer sit-up for hip flexors and abs.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Compound","movementPattern":"Spinal Flexion","alternating":False},"equipment":["GHD"],"tags":["gym-staple"]})
exercises.append({"name":"GHD Back Extension","description":"Back extension on a glute-ham developer.","body_parts":["Back","Glutes","Hamstrings"],"categories":["Core","Lower Body"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Compound","movementPattern":"Spinal Extension","alternating":False},"equipment":["GHD"],"tags":["gym-staple"]})
exercises.append({"name":"GHD Hip Extension","description":"Hip extension on a glute-ham developer.","body_parts":["Glutes","Hamstrings"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Extension","alternating":False},"equipment":["GHD"],"tags":["gym-staple"]})
exercises.append({"name":"GHD Glute Ham Raise","description":"Glute-ham raise for posterior chain development.","body_parts":["Hamstrings","Glutes"],"categories":["Lower Body"],"tracking_type":"reps_only","options":{"posture":"Prone","grip":"No Grip","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["GHD"],"tags":["gym-staple"]})
exercises.append({"name":"Reverse Hyper","description":"Reverse hyperextension for glutes and hamstrings.","body_parts":["Glutes","Hamstrings","Back"],"categories":["Lower Body","Core"],"tracking_type":"weight_reps","options":{"posture":"Prone","grip":"No Grip","mechanics":"Isolation","movementPattern":"Hip Extension","alternating":False},"equipment":["Reverse Hyper Machine"],"tags":["machine","gym-staple"]})
exercises.append({"name":"Russian Twist","description":"Seated rotational twist with or without weight for obliques.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Seated","grip":"Neutral","mechanics":"Isolation","movementPattern":"Rotational","alternating":True},"equipment":["Bodyweight"],"tags":["core"]})
exercises.append({"name":"Weighted Russian Twist","description":"Seated Russian twist holding a plate or dumbbell.","body_parts":["Abdominals"],"categories":["Core"],"tracking_type":"weight_reps","options":{"posture":"Seated","grip":"Neutral","mechanics":"Isolation","movementPattern":"Rotational","alternating":True},"equipment":["Dumbbell"],"tags":["core"]})
exercises.append({"name":"Medicine Ball Slam","description":"Overhead medicine ball slam for power and conditioning.","body_parts":["Abdominals","Shoulders","Back"],"categories":["Full Body","Plyometric"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Medicine Ball"],"tags":["conditioning","explosive"]})
exercises.append({"name":"Medicine Ball Chest Pass","description":"Two-handed chest pass with a medicine ball.","body_parts":["Chest","Triceps","Shoulders"],"categories":["Upper Body","Plyometric"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Horizontal Push","alternating":False},"equipment":["Medicine Ball"],"tags":["conditioning","explosive"]})
exercises.append({"name":"Medicine Ball Rotational Throw","description":"Rotational throw against a wall for core power.","body_parts":["Abdominals","Shoulders"],"categories":["Core","Plyometric"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Rotational","alternating":True},"equipment":["Medicine Ball"],"tags":["conditioning","sport-specific"]})
exercises.append({"name":"Medicine Ball Overhead Throw","description":"Overhead backward medicine ball throw for posterior chain power.","body_parts":["Back","Glutes","Shoulders"],"categories":["Full Body","Plyometric"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Medicine Ball"],"tags":["conditioning","explosive"]})
exercises.append({"name":"Wall Ball","description":"Squat and throw medicine ball at a wall target.","body_parts":["Quadriceps","Glutes","Shoulders"],"categories":["Full Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":False},"equipment":["Medicine Ball"],"tags":["conditioning","gym-staple"]})
exercises.append({"name":"Sandbag Clean","description":"Power clean with a sandbag for functional strength.","body_parts":["Back","Quadriceps","Glutes","Shoulders"],"categories":["Full Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Sandbag"],"tags":["functional","conditioning"]})
exercises.append({"name":"Sandbag Carry","description":"Loaded carry with a sandbag for grip and conditioning.","body_parts":["Trapezius","Forearms","Quadriceps","Abdominals"],"categories":["Full Body"],"tracking_type":"distance","options":{"posture":"Walking","grip":"Neutral","mechanics":"Compound","movementPattern":"Loaded Carry","alternating":False},"equipment":["Sandbag"],"tags":["functional","conditioning"]})
exercises.append({"name":"Sandbag Shoulder","description":"Ground to shoulder with a sandbag.","body_parts":["Back","Quadriceps","Glutes","Shoulders"],"categories":["Full Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":True},"equipment":["Sandbag"],"tags":["functional","conditioning"]})
exercises.append({"name":"Tire Flip","description":"Flipping a large tire for full-body power.","body_parts":["Quadriceps","Glutes","Back","Shoulders"],"categories":["Full Body"],"tracking_type":"reps_only","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Tire"],"tags":["strongman","conditioning"]})
exercises.append({"name":"Atlas Stone Load","description":"Lifting an atlas stone to a platform.","body_parts":["Back","Quadriceps","Glutes","Biceps"],"categories":["Full Body"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Other","mechanics":"Compound","movementPattern":"Hip Hinge","alternating":False},"equipment":["Atlas Stone"],"tags":["strongman"]})
exercises.append({"name":"Rope Climb","description":"Vertical rope climb using arms and legs.","body_parts":["Back","Biceps","Forearms","Abdominals"],"categories":["Full Body","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Hanging","grip":"Crush Grip","mechanics":"Compound","movementPattern":"Vertical Pull","alternating":True},"equipment":["Rope"],"tags":["functional","gym-staple"]})
exercises.append({"name":"Box Step Up with Dumbbells","description":"Dumbbell-loaded step-up onto a box.","body_parts":["Quadriceps","Glutes"],"categories":["Lower Body","Bodybuilding"],"tracking_type":"weight_reps","options":{"posture":"Standing","grip":"Neutral","mechanics":"Compound","movementPattern":"Knee Dominant","alternating":True},"equipment":["Dumbbell","Box"],"tags":["free-weight"]})
exercises.append({"name":"Decline Sit Up","description":"Sit-up on a decline bench for increased resistance.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Supine","grip":"No Grip","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Bench"],"tags":["gym-staple"]})
exercises.append({"name":"Hanging Knee Raise","description":"Hanging knee raise for lower abdominals.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Hanging","grip":"Pronated","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Pull Up Bar"],"tags":["bodyweight","alias"]})
exercises.append({"name":"Hanging Leg Raise","description":"Hanging straight-leg raise for abdominals.","body_parts":["Abdominals","Hip Flexors"],"categories":["Core","Calisthenics"],"tracking_type":"reps_only","options":{"posture":"Hanging","grip":"Pronated","mechanics":"Isolation","movementPattern":"Spinal Flexion","alternating":False},"equipment":["Pull Up Bar"],"tags":["bodyweight","alias"]})
exercises.append({"name":"Ab Wheel Rollout","description":"Ab wheel rollout for anti-extension core strength.","body_parts":["Abdominals","Shoulders"],"categories":["Core"],"tracking_type":"reps_only","options":{"posture":"Kneeling","grip":"Neutral","mechanics":"Compound","movementPattern":"Anti-Extension","alternating":False},"equipment":["Ab Wheel"],"tags":["core","alias"]})

# Write output
with open("c:/Users/stoke/.gemini/antigravity/scratch/Vault_traineros/sentinel-sportslab-v6/data/missing-common-exercises.json", "w") as f:
    json.dump(exercises, f, indent=2)

print(f"Total exercises written: {len(exercises)}")

# Count by category tag
from collections import Counter
tag_counts = Counter()
for e in exercises:
    for t in e.get("tags", []):
        tag_counts[t] += 1

equip_counts = Counter()
for e in exercises:
    for eq in e.get("equipment", []):
        equip_counts[eq] += 1

print("\nBy equipment:")
for k, v in equip_counts.most_common():
    print(f"  {k}: {v}")

print("\nBy tag:")
for k, v in tag_counts.most_common(15):
    print(f"  {k}: {v}")
