UPDATE exercises SET video_url = 'https://youtu.be/d7PGNbhmQVM' WHERE LOWER(TRIM(name)) = LOWER('Parallette Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/PgSZlX32WTo' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/XEFDMwmrLAM' WHERE LOWER(TRIM(name)) = LOWER('Barbell Close Grip Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/Pu5p6uZGTZM?si=MoB-YCpKDesQD9Nn' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/91nVZ7FLPyA?si=_khiKXF3khjyeuSP' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Shotgun Row');
UPDATE exercises SET video_url = 'https://youtu.be/_1ATOXmanEw?si=7DN0OJcZ8jGgOQxp' WHERE LOWER(TRIM(name)) = LOWER('Cable Half Kneeling Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/9Q9gwoXHn1o' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/Ln1j7lm6SrE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Gorilla Row');
UPDATE exercises SET video_url = 'https://youtu.be/wJcmanVh5EE' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Alternating Halo');
UPDATE exercises SET video_url = 'https://youtu.be/CwhbuoGqyug?si=Q9nkDUY4NvpGPqak' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/YzTfq9VaQKs' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/scf3uLuAATg' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/6GbGvGvedOc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/ekNrVv6G5v8' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/pJzThQgKKxw' WHERE LOWER(TRIM(name)) = LOWER('Barbell Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/XsV_KH5Xrng' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/pRfJwVHLp6c' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/2jFFCy8JBU8?si=BCYplSL2-ewJ8kiB' WHERE LOWER(TRIM(name)) = LOWER('Barbell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/2nJsZIScaVk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/x4PRrxvYtwk?si=arNJc-zXL0vatJmL' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Y Raise');
UPDATE exercises SET video_url = 'https://youtu.be/a33rvhoBWYM' WHERE LOWER(TRIM(name)) = LOWER('Suspension Face Pull to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/Cb5ZNB7Vf-0?si=_wFvEZ4u-wYsUhzm' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Reverse Grip Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/N7FcfA7UFZk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Seated Floor Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/p5MNNosenJc' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/XpcOM9Np9LQ?si=p-JIsZ-J0LYgrnEO' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/KoOmLu7ms1s' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/ZcUxxxNl1PA' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/KUsZAGWd0VQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/U2w1H0oXhhg?si=OkR2U3VpYiRe81Eo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/195-8CoZDgo' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Glute Bridge Isometric Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/55-ngw6hplo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/DmC9vPYvU0g?si=mIpOJCXLUo_un5rT' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/auBLPXO8Fww' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Burpee');
UPDATE exercises SET video_url = 'https://youtu.be/SCOxIkPDqxM?si=JHtcK8O5k4voNCP2' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Devil Press');
UPDATE exercises SET video_url = 'https://youtu.be/l6_aD2IWEEA' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Devil Press');
UPDATE exercises SET video_url = 'https://youtu.be/n54YmZS9uM4' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/IeGDlglTK9M' WHERE LOWER(TRIM(name)) = LOWER('Double Plate Lu Raise');
UPDATE exercises SET video_url = 'https://youtu.be/ToHy85wT3KE?si=z9VmwQGWt8A86_Mc' WHERE LOWER(TRIM(name)) = LOWER('Plate Steering Wheel');
UPDATE exercises SET video_url = 'https://youtu.be/ybVFLdr1_Vk?si=NGTNOkq-xBRDhbIF' WHERE LOWER(TRIM(name)) = LOWER('Suspension Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/6yGZ0KCaiWM' WHERE LOWER(TRIM(name)) = LOWER('Barbell Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/A2jT86tgnII' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Half Kneeling Alternating Halo');
UPDATE exercises SET video_url = 'https://youtu.be/9n3nSrJiuFE?si=oGT50V2Fg6jzr5X2' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Tall Kneeling Alternating Halo');
UPDATE exercises SET video_url = 'https://youtu.be/phmcox-C8iA' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Rolling Squat Burpee');
UPDATE exercises SET video_url = 'https://youtu.be/4frRMFUlaFs' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Tall Kneeling Alternating Hip to Halo');
UPDATE exercises SET video_url = 'https://youtu.be/Mdx1V3v7E5g' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/_othSKjqF30' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/HdsS7MO_KFs?si=6N85JwB13t24ha7T' WHERE LOWER(TRIM(name)) = LOWER('Barbell Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/j2slieruHx0?si=qsnkz69oUwDeE0hp' WHERE LOWER(TRIM(name)) = LOWER('Barbell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/bHO0A4ZF_Zg' WHERE LOWER(TRIM(name)) = LOWER('Barbell Inverted Row');
UPDATE exercises SET video_url = 'https://youtu.be/xhlReCpAE9k' WHERE LOWER(TRIM(name)) = LOWER('Ring Row');