UPDATE exercises SET video_url = 'https://youtu.be/Yk67o_LX2k8?si=zkvsiKBoliLmWwDT' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/FkOqXpYX2nE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/7xKPC6fiAnI?si=AjBy--nHV9jih9q4' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/ZrFBGqWoSzw?si=pCq_xiI6MtbnQOMx' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/-4eThA6jaBY?si=rvYxSeDEierXbTvB' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/BSiPJ84ik7o?si=oeCPF5tgAOTrYNIS' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/-L2RxqXxw3w?si=c5bWCZNShpG6g4Zw' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/RZsegx5MjMg?si=jrgTO3B_RBqc2Tow' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/D_XZAV9sh2I?si=9d58XpgxLS_aoYoQ' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/Z8wrpP7TT5E?si=tMWVlz_jrcW6ilLl' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/e-VjvaI7FEI?si=Uc1Aq16WW3xsbpcO' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/GMoIkfo2nP4?si=IB4Q_47E137Hsx_H' WHERE LOWER(TRIM(name)) = LOWER('Miniband Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/LyD7nH85x0c?si=Li3dCfeeWkoCcSX-' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/O1zrmDKSt9E?si=aLhoWHS87gUaM6iV' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/aWPqX1VXr-g?si=6F2i3SQxg7mvF5tb' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Dead Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/vFOeFxuWMa4?si=UW2lvkjDkxHqSPIf' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/QP8ZqZUuvmk?si=UOZV5omhXZ1F-93V' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Dead Clean');
UPDATE exercises SET video_url = 'https://youtu.be/587yc5WQcB0?si=il91YAGQf5s9QyXC' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Dead Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/Wq5CGNeQGUA?si=bULiT29sEH9tAv6z' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Dead Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/NUhpNbRmNMg?si=vqY017BanR5_s992' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Macebell Bull Whip to Mill');
UPDATE exercises SET video_url = 'https://youtu.be/XVlH1hEsqMY?si=60gTVsHXWLFVtref' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Kang Squat');
UPDATE exercises SET video_url = 'https://youtu.be/lLTBO5vqm8A?si=UXhSCQSR6oZS3B2T' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Feet Elevated Renegade Row');
UPDATE exercises SET video_url = 'https://youtu.be/9gglI77Kzq8?si=_dDcU05y48tssEAF' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/tEnO9W001b0?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Y9EGHil8cj0?si=2FSctgexRfTrAxb-' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/hUdSY_wXwWU?si=UfpUfMXiZqyUzBJ8' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/dgdMXVeApVM?si=C53j2jhBQ-HcBkp2' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/s-lZimLr_tg?si=Esmu-85tbaGWBDHx' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/gqAaDuZQjXY?si=XpGry05ejKZXpsz-' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/c-4dfhO8QTw?si=7jy_yBEvLZdLrTWC' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/nEFul0yIBzU?si=Dt-DKAqMcRsQMRWd' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/UbQwG3BPs54?si=OAD_X1vRpwmgJgHl' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/b5LGhv3B2us?si=6V7uUbW59eAmJ9Lx' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ZS0_Pnqs18o?si=iqfhdouw2kgEVNp1' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Q2ELBxwUp28?si=SahPctazGJoXnzHQ' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/mVJyt-hJqQ4?si=ZyQU-rcyvqeQG8GO' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Order Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1XKXGRQX-0w?si=hoLOL3F63ye-LGkD' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/GRFb4uKia9o?si=12NJKTAJm5VqsZCt' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/DoXtPhcQZ0A?si=-jOVMkwU4yMda8b5' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/GLx4dqyToMQ?si=SE9oL2hGuFmb1rI_' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/93jOACk6hCI?si=Wh87FQShHz6PdDPL' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/tCdyjT6r7IQ?si=rxUYwp8Jt_iRYs1A' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Contralateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/5zdsUZyVyZU?si=zOn7HfTe53mopVx9' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/B2jHsaojI4A?si=t3FbVaw_mjK5VgeG' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/bVOx0bS6BvI?si=E52DJq8hShYSUVbw' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/6qREgTKXbOM?si=gyM_F4WYjs2hqIS7' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Ipsilateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/hSqr6cDitEg?si=0Q3eJ7Civ09nXoAr' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/qfpKsxIGOu0?si=fKCRBwv_aknD3aFj' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Ipsilateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lBKvPGFLaKg?si=ysrtgn3hQImmLVaF' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Order Ipsilateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/TPCs1UFpADo?si=m8DKfTmxHGcavJDM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Ipsilateral Forward Lunge');