UPDATE exercises SET video_url = 'https://youtu.be/NEDrQPoITMc?si=ZeJ1LOUbzrjgk-_8' WHERE LOWER(TRIM(name)) = LOWER('Cable Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/G0Mo2LF8uLU' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/37tVohr7LcE' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/jqWAqPQvqAk' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Deficit Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/t7DBjlOTwAk' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Lsen4vH1nm8' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/yqH8u037IjM' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/anHX8Zp67C8?si=qbb7ETCqekLaflB_' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/pktIjwNiuYE?si=fWFt85clM0T2gopP' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Face the Wall Squat');
UPDATE exercises SET video_url = 'https://youtu.be/kFvF6ZHv-KI' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/8k08cvYq-n8?si=bbPqV1XKB99kPfpP' WHERE LOWER(TRIM(name)) = LOWER('Slider Kettlebell Goblet Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/po3I8qoRC2c?si=XeJ7Tq5PXt3WLJfl' WHERE LOWER(TRIM(name)) = LOWER('Miniband Thigh Monster Walk');
UPDATE exercises SET video_url = 'https://youtu.be/1UwyzWjFx5k' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Quadruped Hip Extension');
UPDATE exercises SET video_url = 'https://youtu.be/K7qfUjKf9rU' WHERE LOWER(TRIM(name)) = LOWER('Suspension Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/YyBeT4WWBk4' WHERE LOWER(TRIM(name)) = LOWER('Suspension Skater Squat');
UPDATE exercises SET video_url = 'https://youtu.be/vgB_eWuvGW8?si=anQ4gfG2ik-Y_uU9' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Tuck Jump');
UPDATE exercises SET video_url = 'https://youtu.be/eYGszeFcI7Y?si=jFOFuzza1JQMYuVE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Single Leg Wall Sit');
UPDATE exercises SET video_url = 'https://youtu.be/EmmP-jsvVJE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Romanian Deadlift Jump');
UPDATE exercises SET video_url = 'https://youtu.be/TBw3mPrKAIs' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/GbpDfXXKuk0?si=IsPMd_J3d72xrMcZ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Reverse Nordic');
UPDATE exercises SET video_url = 'https://youtu.be/pVoOtkGBN6s' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Lateral Bench Jump');
UPDATE exercises SET video_url = 'https://youtu.be/1VzKnqCcUJ4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/CaN4zfIPyXU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Skater Jump');
UPDATE exercises SET video_url = 'https://youtu.be/t8OkcdLjRFQ' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/IalP0lgYPnc' WHERE LOWER(TRIM(name)) = LOWER('Cable Prone Bench Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/CWTu90BUTIY?si=9JSuKmfFRaalZ6er' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bulgarian Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/tkh43Yc0tEs' WHERE LOWER(TRIM(name)) = LOWER('Cable Standing Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/kjv4WQXWl_A' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Nordic Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/szRINrcALyI' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/B86Zj72LwzA' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/KdE6b_r7wxA' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ZPoMxOrIeO4' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Ly71LeprFKQ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Box Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/pn8mqlG0nkE' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/oTRl7p13XtY' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Squat');
UPDATE exercises SET video_url = 'https://youtu.be/d-FBclT8W0g?si=wl1sJCzk2Z5PCnwx' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/UaecXxAgsKA' WHERE LOWER(TRIM(name)) = LOWER('Slider Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/GcV2LB0qqnY?si=PoIiYCAOL0uaDuPR' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hamstring Walkout');
UPDATE exercises SET video_url = 'https://youtu.be/tWmzgpoOUls?si=Fmrp6-y_e5qk2SNJ' WHERE LOWER(TRIM(name)) = LOWER('Slider Dumbbell Goblet Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/bQY7fLEkZqU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Dragon Squat');
UPDATE exercises SET video_url = 'https://youtu.be/cuM7OBHSVow' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/HLDhxSqMQyE' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/m6MczOv_Ayg' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/EKRiW9Yt3Ps' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/hwd_6Y9YKvI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Hack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/5yPvjJOqbg4?si=1OYvLb1R7Zq_hl94' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Shoulder Dislocates');
UPDATE exercises SET video_url = 'https://youtu.be/yewf3adybcc?si=-PZ9RsGl7FC8vp7J' WHERE LOWER(TRIM(name)) = LOWER('Suspension Reverse Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/RLlT3qbVS3Q?si=SYASKBhplBkTNYee' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Reverse Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/SIuDkLLlL6E?si=_Y_P-I5PU4GP5LRy' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Reverse Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/B1nRr__KiNk?si=5PGKtxdEbPpVW1Ds' WHERE LOWER(TRIM(name)) = LOWER('Bar Eccentric Chin Up');