UPDATE exercises SET video_url = 'https://youtu.be/7uS_6AgHk28?si=jXJ8ZwIqz_-aAInK' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/f8Mgse4j3uc?si=GV-Q36irrQm7tYhE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/aOIjzeK24fY?si=HuhPoFZBScLorUuf' WHERE LOWER(TRIM(name)) = LOWER('Macebell Offset Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/cc1TZmreJWE?si=aBzThLfX3rm5V3c1' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/IjmQgS0bDao?si=wKCRqF1MeVyvhSwR' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/JqoC2gQ1MRE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/_D87kNsSdv0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Ipsilateral Cossack Squat Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/fhkFo0BxF5k' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Foot Elevated Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/bYd08tHBi3c?si=jxsjM2VGsZK9-fBt' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/XJmnB32JJVw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/ozPUu1GnFTI?si=mWpQsYkoy7akxELn' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/2rYLwmQGZXg?si=FC91EHLdOWAxPSXL' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/23z9Mb4sMVk?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/fWhOG_9eHdE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Ipsilateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/8G0AKIfWSBs?si=A1jj7DSnbvZ7u7t-' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Ipsilateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/Eod-qE6O33E?si=6CUX35luY_zr0tT_' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Low Switch Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/svU3rff73Mo?si=wBPTEMnydOoIKHgd' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Low Hold Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZclBW2lK-lY?si=fR_4w2NKvW_BzggV' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Low Hold Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/AYgBothlkOA?si=hiSrcI8KbslXlQrq' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/iD8tG0qfztk?si=Z2QMS4VxJJkJ-kUk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/7JUe6YXSM3g?si=TrnVTv62WQxSpsZ1' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/sUaLKjZx4X0?si=tcwai7A-NJGrnfYn' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/UTV5o4Oi2KM?si=RDXt3oFCH3cgDQiw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/m7e4dzCqoGA?si=wc7zBINGvkkas6BV' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/AIMfooNNmvw?si=QCorVlRf7tHTepHu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Bent Press');
UPDATE exercises SET video_url = 'https://youtu.be/ixeU8JtnItE?si=yeqNnWyHu_lYZQay' WHERE LOWER(TRIM(name)) = LOWER('Bar Advanced Tuck Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/YLxytoB3RN4?si=bzXKJBCQCbLTNZhd' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/mZJieN2H4PM?si=gtPnQWWttdqNc67H' WHERE LOWER(TRIM(name)) = LOWER('Suspension Single Leg Standing Bent Knee Mid Row');
UPDATE exercises SET video_url = 'https://youtu.be/ZiUXNRmnC9o?si=H4E1QFrZ06yPO-Jz' WHERE LOWER(TRIM(name)) = LOWER('Bar Circle Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/PaYajo0NIjs?si=BnxQHt0l6HLbbkgL' WHERE LOWER(TRIM(name)) = LOWER('Suspension Single Leg Standing Bent Knee Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/EOjx-EK_91I?si=RWxX91ZewMkt9AFa' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Rotational Row');
UPDATE exercises SET video_url = 'https://youtu.be/3j-GT-SlBj4?si=UkgK_A3tck5Lm2rK' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Indian Club Outer Heart Shaped Swing');
UPDATE exercises SET video_url = 'https://youtu.be/nDugTXCHzFY?si=NQvVJIZJswsF1HNn' WHERE LOWER(TRIM(name)) = LOWER('Double Indian Club Parallel Swing');
UPDATE exercises SET video_url = 'https://youtu.be/rZ2F0Fo1Cts?si=ki-LUP1NvXaLVXL3' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Decline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/I5pStn4M6AU?si=xYguBx9qhd3Movl6' WHERE LOWER(TRIM(name)) = LOWER('Bar Full Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/1QCwhp_WlEA?si=wXgs8tAgUOVzgUhI' WHERE LOWER(TRIM(name)) = LOWER('Bar Full Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/XsU1dAVQ04M?si=xZbKraABgDpY1zUM' WHERE LOWER(TRIM(name)) = LOWER('Slider Atomic Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/7OwOfbA13Nw?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Slider Reach Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/mT2_DYAVu8c?si=shnn4gm9QMQ0x3Y5' WHERE LOWER(TRIM(name)) = LOWER('Bar Half Lay Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/z-zP32fnugI?si=38IL3ATf8aLehR74' WHERE LOWER(TRIM(name)) = LOWER('Bar Half Lay Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/KNzJ3GuIpB8?si=va7oq1yMev2p_dQ2' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging Knee Raise');
UPDATE exercises SET video_url = 'https://youtu.be/xX9Hzi7Onnw?si=DF7ySd87D6LcLvwN' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging Toes to Bar');
UPDATE exercises SET video_url = 'https://youtu.be/sqDdHFC1KYk?si=VwW9AhJxnFtKqLWf' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging Oblique Knee Raise');
UPDATE exercises SET video_url = 'https://youtu.be/MGBT77oSGiA?si=AGhUTOg_vYJNxD4y' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging L Sit Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/6p9PqTZuhcg?si=nxxkNsm2jrR22MT1' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Kneeling Ipsilateral Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/Rz_FBXCafls?si=wfY5MWfyEHQ-ZbZR' WHERE LOWER(TRIM(name)) = LOWER('Slider Alternating Reach Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/3M3VxKm08cs?si=dt2GQl57ObWtHdOH' WHERE LOWER(TRIM(name)) = LOWER('Bar Single Leg Out Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/HzcWRdP78Wo?si=l0PzesASSgyca9XI' WHERE LOWER(TRIM(name)) = LOWER('Bar Single Leg Out Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/-H0jvoX9D4U?si=JgYHw7fT5duJS_3Q' WHERE LOWER(TRIM(name)) = LOWER('Bar Straddle Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/xjbycsKgqjQ?si=LkTmhk8Js8iT50DU' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Bottoms Up Overhead Press');