UPDATE exercises SET video_url = 'https://youtu.be/OW3qG0eSgK4?si=ilF_TQTIcKH04qVz' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet March');
UPDATE exercises SET video_url = 'https://youtu.be/019lukD1BrU?si=Z3NYagSLu7vpxllW' WHERE LOWER(TRIM(name)) = LOWER('Landmine Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/l1Z6ltvHwcM?si=g47yzABqexq3NE7E' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Suitcase March');
UPDATE exercises SET video_url = 'https://youtu.be/i3j2R28TKH4?si=Vq9ICK3WiYcphvd9' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/0LSPT_gJcTk?si=oTv9Tc_18B1V8E3E' WHERE LOWER(TRIM(name)) = LOWER('Barbell Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/IlNtRJkIAfg?si=H3-HtM3eVSx3c8T-' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/QgzOgnBBivE?si=WqHP0U99yC8T0Pz_' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Incline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/MVC7c73K61I?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Incline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/y0IdUZhZ87s?si=g54AKBchD_Tow6sM' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Decline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/hLKejvgR5xY?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/-V2SqBSUh_A?si=eUQCnSpJ8s-ZcScI' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/si8q23nPVHk?si=aeyG4_3OSRLAIpiA' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/DvgvfUFjb4E?si=Yw6liGivI_UnZu76' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/XxVWmNbY6yo?si=7n1rTCkP0feHM1xA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Incline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/fRnRcmn7iWk?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Floor Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/kZ-ReOdn2qk?si=00jzpKZzHCr2EIm3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/2HBq-Tee-14?si=tTQPp2-MoSzG_hJL' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/cDkzaJaOYMo?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Tall Kneeling Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/hSVxpNktAZ4?si=X2QXPPV90G-NjXyx' WHERE LOWER(TRIM(name)) = LOWER('Miniband Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/fgP2oii-GiQ?si=mbhNYj3pW612wBRY' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/CB6AROCPwm4?si=cG6vqjgcH__bn9KN' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball Alternating Single Leg V Up Pass Through');
UPDATE exercises SET video_url = 'https://youtu.be/b-06cnxJ2YY?si=wCCcWK7wyR8RgwCV' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball Otis Up');
UPDATE exercises SET video_url = 'https://youtu.be/EqGVH1qHzwU?si=hyDFD2YkFH9OLT29' WHERE LOWER(TRIM(name)) = LOWER('Ring Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/pYy3IaD55OM?si=zoWOIZ-SmoJywASH' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Kneeling Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/GMbT_cHg0dU?si=cnXGlMZAT5YjS73B' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Kneeling Stir the Pot');
UPDATE exercises SET video_url = 'https://youtu.be/CWwVvvgiwxQ?si=16DmFUoBfHBpmKm_' WHERE LOWER(TRIM(name)) = LOWER('Medicine Ball Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/3-EuiQhr9fA?si=ZKO5oh7NHF8_OfxJ' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/18B_3fISG48?si=Tj8Ufhup9wvyOjvB' WHERE LOWER(TRIM(name)) = LOWER('Slam Ball Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/qyM7NdixJzI?si=NCooBu364vvvPnk3' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/FAZ-h5wEKr8?si=Vh1vqHW2hgIn69vC' WHERE LOWER(TRIM(name)) = LOWER('Plate Half Kneeling Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/Ke3i_CAVF6E?si=pJ9XGgJjXXGUnY95' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Body Saw');
UPDATE exercises SET video_url = 'https://youtu.be/ifMzUGTW5WA?si=EnT0Z-s6UM5TbSHH' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/F8A92P9zf-g?si=DNpM-zIiWn0alOvD' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Hanging Leg Raise');
UPDATE exercises SET video_url = 'https://youtu.be/aCmbZCGQ68U?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Climbing Rope Hanging Toes to Rope');
UPDATE exercises SET video_url = 'https://youtu.be/rmwijjkuXug?si=KrHxKYPbcDVtz1gH' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/ixn_1zDpCPc?si=5L7Yqa5uoLVVlY6W' WHERE LOWER(TRIM(name)) = LOWER('Double Cable High to Low Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/mlONJDFVtAY?si=T4BhC9LNsFQmK0y7' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Low to High Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/7t-rTOsyaxY?si=qYz3L4NU58UcOR3w' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band High to Low Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/MEVNntk8yEw?si=WwgxgS5XSi0p1o2k' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Low to High Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/WQnC460je7w?si=JmHZRydzDe7MFsRg' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Isometric Split Squat High to Low Chop');
UPDATE exercises SET video_url = 'https://youtu.be/2ANZ7BhSH4Y?si=3LCewsDbR_PJEwYi' WHERE LOWER(TRIM(name)) = LOWER('Landmine Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/wzeTk8XAGt4?si=5TCEG3ZxGjOGYntF' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/1ZFeqxlx-po?si=JUko8jYOJ3fI_TxM' WHERE LOWER(TRIM(name)) = LOWER('Slider Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/CR3CS7qhG_s?si=OjHoBQJlQQrmEXfw' WHERE LOWER(TRIM(name)) = LOWER('Slider Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/PEzA_n3woFs?si=4l_G-stlnHUfbhiB' WHERE LOWER(TRIM(name)) = LOWER('Suspension Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/MOS9lnGCnqM?si=4svtReY62yrKd7qk' WHERE LOWER(TRIM(name)) = LOWER('Landmine Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/If7pn5ZFY60?si=izUCZfaNWALhCSat' WHERE LOWER(TRIM(name)) = LOWER('Plate Hollow Body Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/jpxdm8SJ5wM?si=35jEMaJ1JRWnO1ET' WHERE LOWER(TRIM(name)) = LOWER('Plate Side Lying Bent Knee Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/m6dHgVYxAyc?si=NjK1qTP-dcOSCced' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Side Lying Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/s6API4Yeqxs?si=apjN7JBTfdY-DW16' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Extended Range Side Lying Hip Abduction');