UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Single Arm Clubbell Reverse Mill', 'https://youtu.be/sdICKS1Hsl8?si=TQcKHRoyYYB_DXgZ'),
  ('Single Arm Clubbell Mill', 'https://youtu.be/JL7-80LGmmU?si=wgcrQiv7L3ETryrv'),
  ('Double Kettlebell Suitcase Deadlift', 'https://youtu.be/aXwilZfmDyo'),
  ('Double Kettlebell Bottoms Up Clean', 'https://youtu.be/iPSx3HFBDJQ?si=yE7krt1ftsmuaend'),
  ('Double Clubbell Mill', 'https://youtu.be/vwRppLKenzw?si=lWbUFOXUJgHzwIVl'),
  ('Alternating Single Arm Clubbell Mill', 'https://youtu.be/p8aWK-U6uVQ?si=uIoHZ9IRigICcYkI'),
  ('Macebell Alternating 360 to Ballistic Curl', 'https://youtu.be/dAeNDa33dCg?si=DOdJKyHWeDTnUFjC'),
  ('Bar Chin Up', 'https://youtu.be/8mryJ3w2S78?si=feHRqrceUl_6Xatw'),
  ('Bar Pull Up', 'https://youtu.be/HRV5YKKaeVw?si=2FwPXMnKZC4QXyAO'),
  ('Single Arm Clubbell Inside Pendulum', 'https://youtu.be/9JrqgpJfxFs?si=ltubZdnwDPFzi-8r'),
  ('Double Clubbell Swipe', 'https://youtu.be/IABFtVxvqdo?si=Krk5vT1xDU9YcRb2'),
  ('Single Arm Clubbell Swipe', 'https://youtu.be/EZNev-kvl6A?si=GsKx6-ERsaOYXjDd'),
  ('Bar Scapular Pull Up', 'https://youtu.be/pE8PJsWEV7k?si=sXWG_h39gmTbgsNw'),
  ('Clubbell Barbarian Squat', 'https://youtu.be/SnRUNmL46So?si=LiGATOKJlrhb676E'),
  ('Bar Skin the Cat', 'https://youtu.be/mqZDdpFh1gA?si=5Sz7M4RZJh4kpYFa'),
  ('Single Arm Kettlebell Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/fyC2FBk2vho?si=9A4Unc4H-ndiHFMC'),
  ('Barbell Hang Squat Clean', 'https://youtu.be/DaKC_BEN5bk?si=-Q3RkXcSiRxscR4n'),
  ('Alternating Single Arm Kettlebell Feet Elevated Plank Pull Through', 'https://youtu.be/178a2eYjaow?si=5BIFyTIH_gQo8ef1'),
  ('Miniband Supine Alternating Hip Flexion', 'https://youtu.be/hcB3BdFBk9o?si=NCYoHHaTofHXzx2y'),
  ('Double Kettlebell Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/zlosFkTwleE?si=kPNf5P_AJZd7Sqrn'),
  ('Double Kettlebell Bottoms Up Half Kneeling Overhead Press', 'https://youtu.be/IoGfLT_8cPA?si=0w2tJHQG6XulCr7c'),
  ('Alternating Single Arm Macebell 10 to 2', 'https://youtu.be/7DW72Ft1LEo?si=kejdZkBMg1CFxl99'),
  ('Single Arm Kettlebell Bottoms Up Arm Bar Rotation', 'https://youtu.be/dlqDSzgxNwM?si=_l4eia6JX0ovy0ss'),
  ('Double Kettlebell Push Up', 'https://youtu.be/80WFnCM9Kbo?si=kxvBbrzAla92I6YM'),
  ('Bodyweight Pseudo Planche Lean', 'https://youtu.be/KMCZ6Pjg9_k?si=qLUPw94vxQVVs7nw'),
  ('Tire Feet Elevated Decline Push Up', 'https://youtu.be/-S5Zz3Hl6a4?si=8XSysf7jjGJx2X07'),
  ('Bodyweight Bench Feet Elevated Decline Push Up', 'https://youtu.be/1ZTYpiJJDZ8?feature=shared'),
  ('Bodyweight Box Feet Elevated Decline Push Up', 'https://youtu.be/5DTn4Euw6To?si=Qt5r8kEOx3ZW_AO9'),
  ('Bodyweight Feet Elevated Pike Push Up', 'https://youtu.be/s5VyQrNhEYY?si=9tSA6c3bjeje5MfX'),
  ('Single Arm Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/J5LEpIZSDS0?si=SukDsqWl5cS7XyF-'),
  ('Single Ring Rotational Row', 'https://youtu.be/1PiO_woAgDc?si=-nYhvQs3zKrAR7im'),
  ('Trap Bar Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/yQToM9xx5Y4?si=AAnvcezbT07hvy8I'),
  ('Trap Bar Z Press', 'https://youtu.be/nz99ncuEEt4?feature=shared'),
  ('Trap Bar Bottoms Up Bench Press', 'https://youtu.be/I8WCjE1hTPM?si=riNSekDaoROPTCoF'),
  ('Bulgarian Bag Alternating Spin to Side Swing Squat', 'https://youtu.be/2UpONYbzL7c?si=C2NbwmasH7LSljdz'),
  ('Bulgarian Bag Swipe', 'https://youtu.be/qFNcznHSBo8?si=5hfD700tGnPBWD3l'),
  ('Bulgarian Bag Snatch', 'https://youtu.be/9-gxBjR4OyE?si=Z1RZknDb7e1_9QmD'),
  ('Bulgarian Bag Alternating Side Swing Squat', 'https://youtu.be/KCyWRqPHOCQ?si=bsZ5UbqpPjccsnEp'),
  ('Bulgarian Bag Swing', 'https://youtu.be/Q7rAfqN-NH0?si=zEMPL2_L-ZEUhtLj'),
  ('Bulgarian Bag Front Rack Squat', 'https://youtu.be/jAo338cgsmU?si=1dPZPEL1g1HDUuIC'),
  ('Bulgarian Bag Back Rack Squat', 'https://youtu.be/ctrXJi1QgEQ?si=O95czG8N3RjyL-Y-'),
  ('Bulgarian Bag Swing Squat', 'https://youtu.be/gVYqz0SXsXE?si=WX6MR6-rxwXauydO'),
  ('Battle Rope Single Leg Standing Double Wave', 'https://youtu.be/6d6b8cx0pO0?si=NKi1a2se39GGFRx3'),
  ('Landmine V Grip Tall Kneeling Chest Press', 'https://youtu.be/FFWOG7Xk5RE?si=JwIHWZtHK6_oDHhQ'),
  ('Battle Rope Single Leg Standing Clap', 'https://youtu.be/bB3WGOVrqAg?si=Pby2lcyL_Cq98LT9'),
  ('Dumbbell Goblet Low Switch Cossack Squat', 'https://youtu.be/ggVuR079WHM?si=QWRGadB6a4zrJrLz'),
  ('Double Dumbbell Front Rack Cossack Squat', 'https://youtu.be/ZxjMX7k3Zp0?si=pZtrI1oUYV-FsjgX'),
  ('Double Dumbbell Low Hold Alternating Cossack Squat', 'https://youtu.be/k6L3kWztcNs?si=GiG4ZJIK5HCWo7Rm'),
  ('Suspension Cossack Squat', 'https://youtu.be/kZdZsw22lU4?si=Y2-3ATlU1R18Acir'),
  ('Barbell Back Rack Cossack Squat', 'https://youtu.be/pOSa7abtPaQ?si=RtB71Qujc9eZBx-J'),
  ('Landmine Goblet Cossack Squat', 'https://youtu.be/DYVAGWST-E8?si=NbgYbTD-kINhnv6a'),
  ('Dumbbell Goblet Cossack Squat', 'https://youtu.be/qxb36LOiBsc?si=9n0Wr7YfIHCom-_w'),
  ('Single Arm Dumbbell Front Rack Contralateral Cossack Squat', 'https://youtu.be/cmB4dq8MgVk?si=s0qFLxm2MDbbX3dw'),
  ('Double Dumbbell Front Rack Foot Elevated Cossack Squat', 'https://youtu.be/d0gACX9heHk?si=U0snvFOFoR0LH9Ne'),
  ('Dumbbell Low Hold Cossack Squat', 'https://youtu.be/k4p89WEkl58?si=S4JsgnfzWmFK3l4G'),
  ('Heavy Sandbag Bear Hug Carry', 'https://youtu.be/jb9Ge6SP8IA?si=FgQecwjAUfv-teLv'),
  ('Dumbbell Hip Thrust', 'https://youtu.be/LxdfGyNBuRU?si=x25Sk4tkkLiyY4t2'),
  ('Double Dumbbell Overhead Carry', 'https://youtu.be/dpVFicHv1PY?si=vQiTWZmKGTiqkHiH'),
  ('Single Arm Kettlebell Bottoms Up Clean', 'https://youtu.be/kMTZwJnCyjw?si=i72hlbqfO-UgCiPw'),
  ('Heavy Sandbag Shoulder Carry', 'https://youtu.be/35IarWLcV0s?si=4lqKX0sntuR1xdEa'),
  ('Double Dumbbell Front Rack Carry', 'https://youtu.be/dDq_T_H8h5E?si=g4wZK9kvKsPxqI3d'),
  ('Single Arm Dumbbell Front Rack Carry', 'https://youtu.be/5rsJK_z8nkY?si=CD5k3-b0r_JJpfHM'),
  ('Barbell Overhead Carry', 'https://youtu.be/ULpnqrFng5I?si=fKiyqdRwBpIeRaEx'),
  ('Barbell Front Rack Carry', 'https://youtu.be/ofwpNdE8yZU?si=T8V1vgUvY8g4tAZ9'),
  ('Double Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/FKrUoffD_W4?si=d07P0wkoguJqTTRV'),
  ('Alternating Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/BoihxFxtsyY?si=kZuvg9gJ179nJ1Xh'),
  ('Single Arm Kettlebell Suitcase March', 'https://youtu.be/Pjxd7M8bNU0?si=OeEny9WikOBA8B3P'),
  ('Double Kettlebell Half Snatch', 'https://youtu.be/5NV0b_RCWKk?si=LoNm1gGN8i-9QLGP'),
  ('Single Arm Kettlebell Half Snatch', 'https://youtu.be/iVaFwCBP1GM?si=9YPJCkbg5ckTydxm'),
  ('Heavy Sandbag Bear Hug Squat', 'https://youtu.be/ymSWvrARnCo?si=wSCDvQEQ8xPtVqbn'),
  ('Heavy Sandbag Shoulder Squat', 'https://youtu.be/VhCVdzYN820?si=07qvbVC4lpqJVZxR'),
  ('Heavy Sandbag Turkish Get Up', 'https://youtu.be/nUjB7PY_ch8?si=qTE38YBxSMytqVEV'),
  ('Heavy Sandbag Bear Hug Alternating Forward Lunge', 'https://youtu.be/68d5tiCgUy8?si=QZZ5qWDdvMU5WTQ_'),
  ('Heavy Sandbag Bear Hug Alternating Reverse Lunge', 'https://youtu.be/dd8M3MLhfjc?si=C40Jnp1OsYedBuT1'),
  ('Heavy Sandbag Shoulder Alternating Forward Lunge', 'https://youtu.be/2EkAq9e24EY?feature=shared'),
  ('Heavy Sandbag Shoulder Alternating Reverse Lunge', 'https://youtu.be/T4jp-7X-ai8?feature=shared'),
  ('Heavy Sandbag Shoulder Walking Lunge', 'https://youtu.be/YSd_xma0esE?si=1LEK7NMY3heh6sof'),
  ('Heavy Sandbag Shoulder Clean', 'https://youtu.be/cB7KJj-wqA4?si=_9jU8-LRtzGAT3e7'),
  ('Heavy Sandbag Over the Shoulder', 'https://youtu.be/fqzGFACRFWU?si=AdAu_hY9NYrlY8DS'),
  ('Heavy Sandbag Bear Hug Walking Lunge', 'https://youtu.be/X5s18gG7cJc?si=P3v8_2nsYkNdk5D7'),
  ('Bodyweight Hand Assisted Sissy Squat', 'https://youtu.be/nNAssQ-4HjA?si=wsCriUBiz-jLsGEk'),
  ('Bodyweight Sissy Squat', 'https://youtu.be/GHvRU4-Guuw?si=NJtNhZAAV3mKCcG-'),
  ('Bodyweight Hand Assisted Knee Over Toe Split Squat', 'https://youtu.be/gBSQOdjjKcc?si=oEXgjHk6m5c-o7MS'),
  ('Superband Sissy Squat', 'https://youtu.be/T2caG3uW8sA?si=AD_PdOw0tzZSfl3p'),
  ('Double Dumbbell Front Rack Walking Lunge', 'https://youtu.be/i3qlK1vA0z4?si=LCNdYUF9IbCDWnYm'),
  ('Single Arm Dumbbell Suitcase Walking Lunge', 'https://youtu.be/QR1CViFqmmc?si=4Lxq-QIIZ55jvMdx'),
  ('Single Arm Dumbbell Overhead Walking Lunge', 'https://youtu.be/lcCEvbAGHC8?si=Ri750XsY--4dDnB_'),
  ('Single Arm Dumbbell Front Rack Walking Lunge', 'https://youtu.be/GGjKBYEkZ-A?si=faI8XOKTHMInvAqG'),
  ('Barbell Front Rack Walking Lunge', 'https://youtu.be/ntGrVrVVNU0?si=3gtiQIlGPGnTePEX'),
  ('Kettlebell Goblet Horse Stance Squat', 'https://youtu.be/ZZ1piVHgy_8?si=I9HrW8xbkLx_UyJS'),
  ('Bodyweight Box Jump', 'https://youtu.be/-IzhFO7lOEU?si=Aftwsw6k2KY2-jf0'),
  ('Bodyweight Lateral Box Jump', 'https://youtu.be/GFdBbtdUfIU?si=GoMi96WWph2nlJpr'),
  ('Bodyweight Alternating Lateral Box Jump', 'https://youtu.be/kJqEVtWkYHo?si=aVVrhRraXLtyjPfg'),
  ('Bodyweight Straddle Planche', 'https://youtu.be/-huk0Idtr6M?si=mLwa_8pXggDXuFgO'),
  ('Macebell Single Leg Offset Bent Over Row', 'https://youtu.be/xpa6f9sJmiQ?si=gJH8lq53_OwgQY8F'),
  ('Single Arm Kettlebell Bird Dog Row', 'https://youtu.be/TBtjuZR8Dvo'),
  ('Single Arm Suspension Ipsilateral Pistol Squat', 'https://youtu.be/5G-vWzfeTy4?si=J9YetG0ZnmrQ6H76'),
  ('Kettlebell Single Leg Standing Hip Flexion', 'https://youtu.be/djxTlEIJdqc?si=IDadWzv3enNpiltr'),
  ('Kettlebell Goblet Alternating Cossack Squat', 'https://youtu.be/wrYqfSLWqdE'),
  ('Barbell Zercher Carry', 'https://youtu.be/yqtWcL9-1_k?si=q_p_4kAujNiWzCVq'),
  ('Double Kettlebell Bottoms Up Seated Overhead Press', 'https://youtu.be/7uS_6AgHk28?si=jXJ8ZwIqz_-aAInK'),
  ('Single Arm Kettlebell Bottoms Up Seated Overhead Press', 'https://youtu.be/f8Mgse4j3uc?si=GV-Q36irrQm7tYhE'),
  ('Macebell Offset Overhead Press', 'https://youtu.be/aOIjzeK24fY?si=HuhPoFZBScLorUuf'),
  ('Single Arm Dumbbell Sots Press', 'https://youtu.be/cc1TZmreJWE?si=aBzThLfX3rm5V3c1'),
  ('Double Dumbbell Sots Press', 'https://youtu.be/IjmQgS0bDao?si=wKCRqF1MeVyvhSwR'),
  ('Single Arm Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/JqoC2gQ1MRE'),
  ('Single Arm Kettlebell Ipsilateral Cossack Squat Thruster', 'https://youtu.be/_D87kNsSdv0'),
  ('Kettlebell Goblet Foot Elevated Cossack Squat', 'https://youtu.be/fhkFo0BxF5k'),
  ('Double Dumbbell Overhead Alternating Step Up', 'https://youtu.be/bYd08tHBi3c?si=jxsjM2VGsZK9-fBt'),
  ('Single Arm Dumbbell Overhead Contralateral Step Up', 'https://youtu.be/XJmnB32JJVw'),
  ('Barbell Overhead Alternating Step Up', 'https://youtu.be/ozPUu1GnFTI?si=mWpQsYkoy7akxELn'),
  ('Barbell Overhead Step Up', 'https://youtu.be/2rYLwmQGZXg?si=FC91EHLdOWAxPSXL'),
  ('Single Arm Dumbbell Suitcase Contralateral Step Up', 'https://youtu.be/23z9Mb4sMVk?feature=shared'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Step Up', 'https://youtu.be/fWhOG_9eHdE?feature=shared'),
  ('Single Arm Dumbbell Overhead Ipsilateral Step Up', 'https://youtu.be/8G0AKIfWSBs?si=A1jj7DSnbvZ7u7t-'),
  ('Kettlebell Goblet Low Switch Cossack Squat', 'https://youtu.be/Eod-qE6O33E?si=6CUX35luY_zr0tT_'),
  ('Kettlebell Low Hold Cossack Squat', 'https://youtu.be/svU3rff73Mo?si=wBPTEMnydOoIKHgd'),
  ('Kettlebell Low Hold Alternating Cossack Squat', 'https://youtu.be/ZclBW2lK-lY?si=fR_4w2NKvW_BzggV'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Cossack Squat', 'https://youtu.be/AYgBothlkOA?si=hiSrcI8KbslXlQrq'),
  ('Double Kettlebell Front Rack Carry', 'https://youtu.be/iD8tG0qfztk?si=Z2QMS4VxJJkJ-kUk'),
  ('Double Kettlebell Overhead Carry', 'https://youtu.be/7JUe6YXSM3g?si=TrnVTv62WQxSpsZ1'),
  ('Double Kettlebell Bottoms Up Overhead Carry', 'https://youtu.be/sUaLKjZx4X0?si=tcwai7A-NJGrnfYn'),
  ('Single Arm Kettlebell Overhead Carry', 'https://youtu.be/UTV5o4Oi2KM?si=RDXt3oFCH3cgDQiw'),
  ('Single Arm Kettlebell Bottoms Up Overhead Carry', 'https://youtu.be/m7e4dzCqoGA?si=wc7zBINGvkkas6BV'),
  ('Single Arm Kettlebell Half Kneeling Bent Press', 'https://youtu.be/AIMfooNNmvw?si=QCorVlRf7tHTepHu'),
  ('Bar Advanced Tuck Back Lever', 'https://youtu.be/ixeU8JtnItE?si=yeqNnWyHu_lYZQay'),
  ('Alternating Double Dumbbell Sots Press', 'https://youtu.be/YLxytoB3RN4?si=bzXKJBCQCbLTNZhd'),
  ('Suspension Single Leg Standing Bent Knee Mid Row', 'https://youtu.be/mZJieN2H4PM?si=gtPnQWWttdqNc67H'),
  ('Bar Circle Front Lever', 'https://youtu.be/ZiUXNRmnC9o?si=H4E1QFrZ06yPO-Jz'),
  ('Suspension Single Leg Standing Bent Knee Low Row', 'https://youtu.be/PaYajo0NIjs?si=BnxQHt0l6HLbbkgL'),
  ('Single Arm Suspension Rotational Row', 'https://youtu.be/EOjx-EK_91I?si=RWxX91ZewMkt9AFa'),
  ('Alternating Double Indian Club Outer Heart Shaped Swing', 'https://youtu.be/3j-GT-SlBj4?si=UkgK_A3tck5Lm2rK'),
  ('Double Indian Club Parallel Swing', 'https://youtu.be/nDugTXCHzFY?si=NQvVJIZJswsF1HNn'),
  ('Suspension Feet Elevated Decline Push Up', 'https://youtu.be/rZ2F0Fo1Cts?si=ki-LUP1NvXaLVXL3'),
  ('Bar Full Back Lever', 'https://youtu.be/I5pStn4M6AU?si=xYguBx9qhd3Movl6'),
  ('Bar Full Front Lever', 'https://youtu.be/1QCwhp_WlEA?si=wXgs8tAgUOVzgUhI'),
  ('Slider Atomic Push Up', 'https://youtu.be/XsU1dAVQ04M?si=xZbKraABgDpY1zUM'),
  ('Slider Reach Push Up', 'https://youtu.be/7OwOfbA13Nw?feature=shared'),
  ('Bar Half Lay Back Lever', 'https://youtu.be/mT2_DYAVu8c?si=shnn4gm9QMQ0x3Y5'),
  ('Bar Half Lay Front Lever', 'https://youtu.be/z-zP32fnugI?si=38IL3ATf8aLehR74'),
  ('Bar Hanging Knee Raise', 'https://youtu.be/KNzJ3GuIpB8?si=va7oq1yMev2p_dQ2'),
  ('Bar Hanging Toes to Bar', 'https://youtu.be/xX9Hzi7Onnw?si=DF7ySd87D6LcLvwN'),
  ('Bar Hanging Oblique Knee Raise', 'https://youtu.be/sqDdHFC1KYk?si=VwW9AhJxnFtKqLWf'),
  ('Bar Hanging L Sit Flutter Kicks', 'https://youtu.be/MGBT77oSGiA?si=AGhUTOg_vYJNxD4y'),
  ('Single Arm Kettlebell Half Kneeling Ipsilateral Overhead Press', 'https://youtu.be/6p9PqTZuhcg?si=nxxkNsm2jrR22MT1'),
  ('Slider Alternating Reach Push Up', 'https://youtu.be/Rz_FBXCafls?si=wfY5MWfyEHQ-ZbZR'),
  ('Bar Single Leg Out Back Lever', 'https://youtu.be/3M3VxKm08cs?si=dt2GQl57ObWtHdOH'),
  ('Bar Single Leg Out Front Lever', 'https://youtu.be/HzcWRdP78Wo?si=l0PzesASSgyca9XI'),
  ('Bar Straddle Back Lever', 'https://youtu.be/-H0jvoX9D4U?si=JgYHw7fT5duJS_3Q'),
  ('Alternating Double Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/xjbycsKgqjQ?si=LkTmhk8Js8iT50DU'),
  ('Bar Tuck Back Lever', 'https://youtu.be/LfyGMZh-Bz4?si=6Cp5HCRlHxaaAXAk'),
  ('Double Kettlebell Bottoms Up Seesaw Overhead Press', 'https://youtu.be/HDzbviKeH8A?si=B97qZHv-l5DP5Zwg'),
  ('Bar Tuck Front Lever', 'https://youtu.be/BDYs4d0-dbs?si=xhEemMS0ZwEdNi-P'),
  ('Bodyweight Fingertip Full Planche Push Up', 'https://youtu.be/kw0kXtvOpfU?si=l1qrLXesjuSAv8NK'),
  ('Ring Grip Push Up', 'https://youtu.be/d305HI37Rc0'),
  ('Single Arm Barbell Overhead Press', 'https://youtu.be/Oz--LasDphM?si=JVdkguhnIxf9Ho8X'),
  ('Ring Shoulder Stand', 'https://youtu.be/_Jf4hAHEwm8'),
  ('Ring Strap Handstand', 'https://youtu.be/3cLo1dWPqis'),
  ('Ring Strap Handstand Push Up', 'https://youtu.be/nUt-_d3zP2w'),
  ('Bodyweight Straddle Press Handstand', 'https://youtu.be/olR47A-UOYU?si=XvqzFclDvXSJPmsi'),
  ('Bodyweight Alternating Step Up', 'https://youtu.be/lUSmIRNqt9w?si=2Uzz5dQAroAGZKAK'),
  ('Bodyweight Step Up', 'https://youtu.be/V9ButqpLLcw?si=W7rot5ocLsfGP3zd'),
  ('Bodyweight Pike Press Handstand', 'https://youtu.be/5qjQF8Bwk9Y?si=hKn5hERkDvTWUSxe'),
  ('Parallette L Sit to Straddle Press Handstand', 'https://youtu.be/Hx31luas38Q'),
  ('Heavy Sandbag Clean to Push Press', 'https://youtu.be/AVH3_x1LZA4?si=xUfQv7BiQgAH0riW'),
  ('Ring Tuck Front Lever Pull Up', 'https://youtu.be/7gLyX3Q1KJA'),
  ('Double Kettlebell Suitcase Walking Lunge', 'https://youtu.be/OFSepehKEsg?si=cACSI6X-vniOrBik'),
  ('Single Arm Ring Push Up', 'https://youtu.be/9sjQEtGoScA'),
  ('Ring L Sit Muscle Up', 'https://youtu.be/CP4kwFLxRYg'),
  ('Ring Strict Muscle Up', 'https://youtu.be/vJTJFc2wmk4'),
  ('Single Arm Kettlebell Suitcase Walking Lunge', 'https://youtu.be/ojCvehn5SjY?si=tdD_tXPCt_VXy9h3'),
  ('Single Arm Kettlebell Front Rack Walking Lunge', 'https://youtu.be/9C-hKwyOaE4?si=SpYmw0aHIO29g-Cj'),
  ('Single Arm Kettlebell Overhead Walking Lunge', 'https://youtu.be/ApTlAc-7lGY?si=SjnB0ffZ9Ws6qo9D'),
  ('Single Arm Kettlebell Bottoms Up Overhead Walking Lunge', 'https://youtu.be/0D5CejWdGE4?feature=shared'),
  ('Clubbell Inside Pendulum', 'https://youtu.be/KPxWt4X3CYQ?si=LHuzEfvY58pZcQ4P'),
  ('Kettlebell Romanian Deadlift', 'https://youtu.be/keiZFdUgvKQ?si=dkMliNkbyV8fodl2'),
  ('Barbell Snatch Balance', 'https://youtu.be/XuFaD1sAVGI?si=TR-XC6iaJP514gda'),
  ('Parallette Straddle Press to Handstand', 'https://youtu.be/DRYQDMUVgYE'),
  ('Double Dumbbell Suitcase March', 'https://youtu.be/Yz0g3nK0UH8?si=uzYt2n3dgbhVRnnW'),
  ('Single Arm Dumbbell Suitcase March', 'https://youtu.be/l5n8bNkwXFo?si=N5Nmp5n6RrmLD2uu'),
  ('Double Dumbbell Front Rack March', 'https://youtu.be/46yupJpHPBM?feature=shared'),
  ('Single Arm Dumbbell Front Rack March', 'https://youtu.be/x_pMZHT1PJI?si=gXaoVxcFe0j1mtPQ'),
  ('Double Dumbbell Overhead March', 'https://youtu.be/Iqc40RmX2t8?si=6XNRQXHsREEsYjGr'),
  ('Single Arm Dumbbell Overhead March', 'https://youtu.be/6Yw94hTsI2s?si=oPrzNDtNw4g-Xhy-'),
  ('Barbell Front Rack March', 'https://youtu.be/dSSBwrzbtGI?feature=shared'),
  ('Barbell Back Rack Alternating Forward Lunge', 'https://youtu.be/H8YHDNCH5-o?si=niOwS0JaOXdOT4Ip'),
  ('Barbell Back Rack Alternating Reverse Lunge', 'https://youtu.be/fP3L8yqDaYo?si=xq03w4XotIlArOk3'),
  ('Kettlebell Single Leg Romanian Deadlift', 'https://youtu.be/wacHvU9ISqQ?si=6Hco-OabboEOEO3N'),
  ('Single Arm Ring Eccentric Chin Up', 'https://youtu.be/Vg0K1uuNQLI'),
  ('Parallette Freestanding Handstand', 'https://youtu.be/Qoyxwu0i5Og?si=v6_bUX0l76eWrYRZ'),
  ('Ring Gironda Sternum Chin Up', 'https://youtu.be/PUjiG2iQHzk?si=OVi5AVNaOFs0SP5b'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Pistol Squat', 'https://youtu.be/RHj4ErHsJAw?si=ZUMLXqjq5pmMSAf_'),
  ('Kettlebell Horn Grip Pistol Squat', 'https://youtu.be/L0S7ATOR1Rw?si=KpjiKwE_QaiTxnfw'),
  ('Double Kettlebell L Sit', 'https://youtu.be/AOjVLnxbmHU?si=LVrFAJ6HK8bfJmCb'),
  ('Double Kettlebell L Sit Lift Over', 'https://youtu.be/FNsKwVfAF2A?si=ZLDbQY35pGpv6Wk5'),
  ('Single Arm Kettlebell Bottoms Up Windmill', 'https://youtu.be/sGgI_gV85Zs?si=0_msxxqLJEv8yQl7'),
  ('Double Kettlebell Overhead March', 'https://youtu.be/R2nuXQJt-08?si=ZZwubaIV-9OycLD5'),
  ('Single Arm Kettlebell Overhead March', 'https://youtu.be/GL4yx2rQpIs?si=lvmUx2j0LaKZx4RZ'),
  ('Double Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/oeyAEgHBVYc?si=mHjzSFPeM2YyoC0H'),
  ('Double Kettlebell Suitcase Alternating Lateral Lunge', 'https://youtu.be/zO8xPAa4-cY?si=bSfD4Gd8EdQ631Hq')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);