UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Double Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/TzuHADj8h4M?si=tAyLqN0pCIXqxity'),
  ('Double Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/KIDRnwRAKAY?si=b00pYocO2xqWBGiJ'),
  ('Double Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/JKk87eVdbG8?si=Est-myfua9sI06NN'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/A4SnLhdMKu4?si=AWoi6qQOHivzUZeZ'),
  ('Double Dumbbell Suitcase Alternating Lateral Lunge', 'https://youtu.be/GkgTBlp417A?si=2RKL7GSC-wlwXQrE'),
  ('Double Dumbbell Front Rack Alternating Lateral Lunge', 'https://youtu.be/V-crv5-Tqbg?si=k00dfu1tLmH4-h3a'),
  ('Double Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/Ambx6K-_AfY?si=2pUqPVUnlmZLMMwH'),
  ('Double Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1iT74xBv0LA?si=vNMiZEtQ8W3QCkqc'),
  ('Double Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/8OZUh9sHk-8?si=euVM8-cldcw4zaJf'),
  ('Double Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/eK7AzF0-rt4?si=0L-vfrm5QmGhcV2l'),
  ('Single Arm Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/DbANzYj8EWQ?si=NULTCgfWBvm6vNpX'),
  ('Single Arm Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/kTfl5mhcwso?si=iDo9iOmHhKSZIQlN'),
  ('Single Arm Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/b3ewFBSqc9k?si=l6I7tV4HN4z6vcCS'),
  ('Single Arm Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1uuCmY9bVao?si=0iam54INq6LqKgrV'),
  ('Single Arm Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/RNdGRLDFZ_E?si=ViWm3Cym-_kPAyPr'),
  ('Single Arm Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/y6Z1csYJqI8?si=VJQkALrooI76ZWQ9'),
  ('Double Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/iPBOqxEBcto?si=yJqaSgMnybSQX6Oy'),
  ('Double Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/HFjBFM1Fswo?si=BiUd6crmcvrtRZx2'),
  ('Dumbbell Goblet Alternating Lateral Lunge', 'https://youtu.be/xFvob3P7I74?si=o6y90mzLlkb5kjLo'),
  ('Dumbbell Goblet Alternating Forward Lunge', 'https://youtu.be/MjHkEW-AMQI?si=EyW7vqzwyfCJv1bN'),
  ('Dumbbell Goblet Alternating Reverse Lunge', 'https://youtu.be/YidVOnuiDfc?si=ECuN-ZTMBkyH_maZ'),
  ('Landmine Goblet Alternating Lateral Lunge', 'https://youtu.be/-hWgE1P2aAA?si=7mOaE_-aBxpQNBSX'),
  ('Landmine Goblet Alternating Reverse Lunge', 'https://youtu.be/VI0GDe_doBk?si=U14f8Dk6Ly1aMzBr'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/aopAoW1cmUk?si=EyVEsJC9bLaQC6ND'),
  ('Double Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/QV4DL31Ch94?si=6O9QTMoEB9MtwsZY'),
  ('Single Arm Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/eGKpS3AxCVA?si=-uyv4kyU-FY0yBfB'),
  ('Single Arm Dumbbell Overhead Cyclist Squat', 'https://youtu.be/Fm-EgA1xP4g?si=TXFdciSwYJ3flVng'),
  ('Bodyweight Alternating Lateral Lunge', 'https://youtu.be/FvJS_MSN4Lo?si=Z7h-t5HEEQC6trw6'),
  ('Bodyweight Alternating Forward Lunge', 'https://youtu.be/0RqJM6GM5bg?si=eL5TvNrMzUaI1oOW'),
  ('Bodyweight Alternating Reverse Lunge', 'https://youtu.be/OX0fKkaY6_c?si=T0Ta2iyvXrGIGA7w'),
  ('Double Dumbbell Overhead Squat', 'https://youtu.be/iGLwbS5aHY4?si=f7TNizeYPw8xX1xR'),
  ('Single Arm Dumbbell Overhead Squat', 'https://youtu.be/SokWJEUYgfc?si=OWsmg8u6_2Xz09z9'),
  ('Double Dumbbell Front Rack Bulgarian Split Squat', 'https://youtu.be/6DO1p1pOAwM?si=zeLSk3SSoVkoP_B9'),
  ('Double Dumbbell Overhead Bulgarian Split Squat', 'https://youtu.be/7rGFnvK6KkE?si=SL3VLXM4o_8TDV_0'),
  ('Single Arm Dumbbell Suitcase Contralateral Bulgarian Split Squat', 'https://youtu.be/iylKd9ymBQE?si=D_mNdhDHgU7B8xbD'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Bulgarian Split Squat', 'https://youtu.be/7oQoOglG_cA?si=JLNoB9O2s2KyOAf1'),
  ('Single Arm Dumbbell Front Rack Contralateral Bulgarian Split Squat', 'https://youtu.be/-vKdvtdkRRc?si=CPo0dP5KaIc0TJu5'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Bulgarian Split Squat', 'https://youtu.be/pEZWYmpCzu8?si=i70Ip_o4npwew5bY'),
  ('Suspension Alternating Lateral Lunge', 'https://youtu.be/0bqrj4BimaI?si=03pxBE_5_ozxIivb'),
  ('Bulgarian Bag Back Rack Alternating Lateral Lunge', 'https://youtu.be/fJePN1sD5ok?si=g-YYXG1x8L53Vuv-'),
  ('Bulgarian Bag Back Rack Walking Lunge', 'https://youtu.be/FNr5JBGrJTU?si=bn24rl-sBOt5WTfx'),
  ('Bulgarian Bag Back Rack Alternating Forward Lunge', 'https://youtu.be/a8y1Qwir7YQ?si=izeBmxPLl4E0ekvy'),
  ('Sandbag Front Rack Alternating Lateral Lunge', 'https://youtu.be/0el8H9fy3g0?si=BdlZ75xoh6Xq1wpJ'),
  ('Sandbag Front Rack Walking Lunge', 'https://youtu.be/mGwXPP-QKko?si=pUfEZOZPOOYaTV3n'),
  ('Sandbag Front Rack Alternating Forward Lunge', 'https://youtu.be/1L2HnCKmsRs?si=fIVyc7oXYDkkRzgJ'),
  ('Sandbag Front Rack Alternating Reverse Lunge', 'https://youtu.be/SJe_O4NPU-E?si=OKoj1OGsurlSWTEA'),
  ('Plate Overhead Walking Lunge', 'https://youtu.be/hVIaVvyY-H8?si=HsyRlDh-j--gHbsk'),
  ('Plate Overhead Alternating Forward Lunge', 'https://youtu.be/k6pHuYm2nV8?si=ttotAgiXtgPihuX3'),
  ('Plate Overhead Alternating Reverse Lunge', 'https://youtu.be/X5UicuSpd-g?si=vkWg2RXcC-HFi6Pk'),
  ('Bodyweight Tuck Planche', 'https://youtu.be/VFYZh24e0RI?si=_Vjvy9tWBn4nc7l_'),
  ('Double Kettlebell Push Up to L Sit', 'https://youtu.be/V-157r2C-qU'),
  ('Bar Hanging L Sit', 'https://youtu.be/WHi1bvZLwlw?si=NKvlsqG8aI-wDQfJ'),
  ('Ring Hanging L Sit', 'https://youtu.be/8DMns2IRlg4?si=hbMMsP9DfSOthR7b'),
  ('Single Arm Bar Hanging L Sit', 'https://youtu.be/HvdS2ClV9KU?feature=shared'),
  ('Single Arm Ring Hanging L Sit', 'https://youtu.be/_o_4N2yJwAw?si=Hum3bBKngYoqfDUc'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/CQR7UUijw38?si=ncO4L8hVq2h4htQQ'),
  ('Parallette L Sit Flutter Kicks', 'https://youtu.be/zDRj6Sw6tw8?si=Fp368ZWQaw_YDQay'),
  ('Bodyweight Single Arm Contralateral Single Leg Push Up', 'https://youtu.be/I6f7uUmozDY'),
  ('Parallette Tuck Planche Push Up', 'https://youtu.be/hFHpQAqqMDA'),
  ('Ring Maltese Push Up', 'https://youtu.be/kpOpHoywVKU'),
  ('Bar Advanced Tuck Front Lever Pull Up', 'https://youtu.be/cVdb8oUGKAw?si=tC4dDZ3QsBtE_4_m'),
  ('Bar Gironda Sternum Chin Up', 'https://youtu.be/58QkcGVA12A?si=ddrndE8UqnvYVadB'),
  ('Bar Strict Muscle Up', 'https://youtu.be/t8_M2aHiNDk?si=s9zri6LcdUJrvwbV'),
  ('Bodyweight Tuck Planche Push Up', 'https://youtu.be/U-MgWVM_2-Y?si=-XnkVL5OAVXtyCPu'),
  ('Double Clubbell Asynchronous Mill', 'https://youtu.be/2t7u5sapU1Q?si=KigwClnysDsb8CGJ'),
  ('Bodyweight L Sit', 'https://youtu.be/pO4BH0dKCIY?si=qKwpWcDltQZ0K61z'),
  ('Bodyweight Single Arm L Sit', 'https://youtu.be/l-7PDo_nf-c?si=SV8BnhirXI2QflsN'),
  ('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/X8I4Uq4QgYE?si=0ZNJz2TPEC0nSZaa'),
  ('Single Arm Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/vVElqek25fI?si=4-FGE3vFSRTkYdG4'),
  ('Single Arm Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/oOB02xJgzrA?si=IO-ooFFstcNesTGD'),
  ('Single Arm Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/tildBryP8bI?si=mIky-m7uqR4kMvB3'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Forward Lunge', 'https://youtu.be/q7sQB0_p7XQ?feature=shared'),
  ('Parallette V Sit to Pike Press Handstand', 'https://youtu.be/i3tkgdhZuj0?si=lupWBeLYXNXi2bV0'),
  ('Ring Pseudo Planche Push Up', 'https://youtu.be/f09iB8jbioo?si=MFJiOigiohOtQybY'),
  ('Stability Ball Feet Elevated Glute Bridge', 'https://youtu.be/8Ta_A9vAEGs?si=pSj3gDFijzwcALE4'),
  ('Bodyweight Mountain Climber', 'https://youtu.be/kLh-uczlPLg?si=WfwS9PlCOc9d1t1N'),
  ('Suspension Feet Elevated Mountain Climber', 'https://youtu.be/XiB48dLaB9g?si=RkTU535X9lQ-XULA&amp;utm_source=MTQxZ'),
  ('Bodyweight Straddle L Sit', 'https://youtu.be/XS7Y1jQ-kxs?si=hFDuiao7cTRRHUCT'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/xhyigP6lpAM?feature=shared'),
  ('Bodyweight Cossack Squat', 'https://youtu.be/lyMHR7F8lPA?si=An72TBlVkZQu4GMO'),
  ('Bodyweight Wall Facing Handstand Push Up', 'https://youtu.be/ZDhNSacJLEE?si=aGw3Fw5a7Q34pWuk'),
  ('Ring Pelican Push Up', 'https://youtu.be/4zSzWYRiBGI?si=NqLN5I_ZFwPkfPXM'),
  ('Barbell Back Rack Alternating Step Up', 'https://youtu.be/_iZ9bGw84H8?si=4Ff3XGU-WRY1uN0k'),
  ('Barbell Front Rack Alternating Step Up', 'https://youtu.be/b8ldbeOnJEI?si=PBXslcF1v1YEXgGU'),
  ('Ring Feet Elevated Pelican Push Up', 'https://youtu.be/HdaAXHcN0-M?si=fT7_2ec7wdcSALfm'),
  ('Ring Tuck L Sit', 'https://youtu.be/Vuc-nodHS0Y?si=S81fiCUEtPrZUe6Z'),
  ('Ring Hanging Tuck L Sit', 'https://youtu.be/SLyOG8ujcu0?si=IAzc53JTuuKNMz90'),
  ('Bar Hanging Tuck L Sit', 'https://youtu.be/QA_dH6cjbw0?si=29xMuvVPe0ttRvvK'),
  ('Single Arm Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/LMStE_hD9E4?si=_iskUn08-BQH0mYu'),
  ('Ring Mountain Climber', 'https://youtu.be/5BaV4f58I3c?si=LhV-BmrDvHK1G_uI'),
  ('Ring Feet Elevated Mountain Climber', 'https://youtu.be/kbPOFMH-Ivk?si=ftd7bXesKjVBgNrW'),
  ('Single Arm Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/neuw_JknIms?si=QPBFpV8bvbtlFLfL'),
  ('Ring Dead Hang', 'https://youtu.be/uMcoQ-ijpsk'),
  ('Parallette Kneeling Push Up', 'https://youtu.be/iHR7BprMyEc'),
  ('Clubbell Outside Circle', 'https://youtu.be/9lVJZ8o8nzM?si=4NnTRdg9x60PkNsZ'),
  ('Single Arm Kettlebell Bottoms Up Overhead Alternating Reverse Lunge', 'https://youtu.be/N4GPqbj8Nds?feature=shared'),
  ('Stability Ball T''s Y''s I''s', 'https://youtu.be/1jP1PR9Gls0?si=esOirS5dWd5oUqG0'),
  ('Resistance Band Reverse Fly', 'https://youtu.be/C2wsrjVHvuA'),
  ('Resistance Band Lateral Raise', 'https://youtu.be/1feV0cW5U60?si=e6dhNFXt6CLSbkRE'),
  ('Double Dumbbell Lateral Raise', 'https://youtu.be/XPPfnSEATJA?si=yNFrwT2Aj4G98NVF'),
  ('Double Dumbbell Seated Lateral Raise', 'https://youtu.be/GBo4Cj8i9VI?si=_ZCYRalndjXZl58y'),
  ('Single Arm Dumbbell Side Lying Shoulder External Rotation', 'https://youtu.be/_qPQKid-LRs'),
  ('Miniband Standing Shoulder External Rotation', 'https://youtu.be/4cpQr1VbcEU'),
  ('Stability Ball Double Dumbbell Seated Arnold Press', 'https://youtu.be/4Hwcp9HP9D4'),
  ('Single Arm Cable Lateral Raise', 'https://youtu.be/9s0F9lgTG0E?si=hlzVQJ0I5qgbvM45'),
  ('Double Dumbbell Seated Overhead Press', 'https://youtu.be/3GFZpOYu0pQ'),
  ('Double Dumbbell Overhead Press', 'https://youtu.be/AqzDJHxynwo?si=FpgeOvlc1u-WxGMb'),
  ('Double Dumbbell Shrug', 'https://youtu.be/llSrlpd7TEE?si=7L7ARn0S6ByQmI59'),
  ('Double Dumbbell Standing Scaption', 'https://youtu.be/bhemEvr0qiM?si=WahKrQS3-uEP1hYU'),
  ('EZ Bar Kneeling Rollout', 'https://youtu.be/qGVLUwKTvTw?si=wziniMZUeqke6bE4'),
  ('EZ Bar Standing Rollout', 'https://youtu.be/zGZrhC_VWIQ?feature=shared'),
  ('Double Dumbbell Seated Scaption', 'https://youtu.be/Vn1cULRUhZI'),
  ('Stability Ball Double Dumbbell Seated Scaption', 'https://youtu.be/PKgkMmXAVUs'),
  ('Alternating Double Dumbbell Bicep Curl', 'https://youtu.be/WYezBGuUsdw'),
  ('Alternating Double Dumbbell Incline Bench Bicep Curl', 'https://youtu.be/bgYt7ZgFc9M'),
  ('Alternating Double Dumbbell Hammer Curl', 'https://youtu.be/h46ccQsXDEk'),
  ('Alternating Double Dumbbell Cross Body Hammer Curl', 'https://youtu.be/buP9fSqWcw4?si=-lKec0VHJ1XbZYRH'),
  ('Single Arm Dumbbell Incline Bench Preacher Curl', 'https://youtu.be/DPYrHeVKvQA'),
  ('Dumbbell Crush Grip Bicep Curl', 'https://youtu.be/at2g_OGyuDE'),
  ('Double Dumbbell Zottman Curl', 'https://youtu.be/wrjEdVZrkhk'),
  ('Dumbbell Waiter Curl', 'https://youtu.be/DjgrEWlgGaY'),
  ('Cable Straight Bar Drag Curl', 'https://youtu.be/s_5mJUQqQpY?si=4zKcXdHvIHVCrn6n'),
  ('Cable Rope Hammer Curl', 'https://youtu.be/BXcSLzXrab4?si=KZPHi7uurh7Nb31j'),
  ('Kettlebell Goblet Alternating Lateral Lunge', 'https://youtu.be/Z8dcGhS8giQ?si=iQZ35AJwvoHewxyk'),
  ('Suspension Bicep Curl', 'https://youtu.be/nipJ27JfpUI'),
  ('Double Dumbbell Tricep Kickback', 'https://youtu.be/m_UlDFNX4mk?si=FAleOyAOFc4IiSBT'),
  ('Tire Jump', 'https://youtu.be/yrNR2OK50Lw?si=o9UhhO3HdGYOlRvS'),
  ('Tire Jump Through', 'https://youtu.be/1DBz3vodUUc?feature=shared'),
  ('Tire Broad Jump', 'https://youtu.be/juTI6wnRiZ8?si=AItO7HER5TxfhHc9'),
  ('Tire Step Up', 'https://youtu.be/4RsPF6KynpE?feature=shared'),
  ('Tire Alternating Step Up', 'https://youtu.be/JdYIi6Vedy8?si=XLKOd1kgeuZgH3Wp'),
  ('Tire Alternating Toe Taps Around the World', 'https://youtu.be/diT5j5QRKhs?si=KBmQGQunZ8mtj5zz'),
  ('Dumbbell Seated Overhead Tricep Extension', 'https://youtu.be/-aBcUgsn8Dc'),
  ('Tire Lateral Jump Through', 'https://youtu.be/H80_t9poKQo?si=eTIuIU_bwT40hUvJ'),
  ('Tire Carry', 'https://youtu.be/QskOD3ROxGs?si=Vh3moyP5PVPO8sMy'),
  ('Dumbbell Overhead Tricep Extension', 'https://youtu.be/7h3lG2WnLXg'),
  ('Double Dumbbell Close Grip Floor Press', 'https://youtu.be/s6ydoB3ktlI'),
  ('Barbell Back Rack Carry', 'https://youtu.be/c2D4GkTgyo4?si=s6c03eCCz8TWg7br'),
  ('Single Arm Barbell Suitcase Carry', 'https://youtu.be/-FZcqOBDphU?si=FQJnUQP2TsxKmhRA'),
  ('Suspension Bulgarian Split Squat', 'https://youtu.be/BnLkbAGE4b4?si=mRL2wc8pDdJKZNbY'),
  ('Suspension Bulgarian Split Squat Jump', 'https://youtu.be/ABtwgwo4zyQ?si=eWDNpXtH8qJ31y72'),
  ('Bodyweight Lateral Bear Crawl', 'https://youtu.be/JLtXEZAwNxQ?feature=shared'),
  ('Bodyweight Step Up Jump', 'https://youtu.be/bZYAKXoBXGs?si=HbHeFnXtAvKsYndx'),
  ('Bodyweight Alternating Step Up Jump', 'https://youtu.be/vX2vagAc8Mw?si=UH9R_7g0TbIQyHja'),
  ('Barbell Power Clean to Push Press', 'https://youtu.be/4ws-kHR5NaU?si=3YQjL6sBFZ3aL-hW'),
  ('Double Dumbbell Close Grip Bench Press', 'https://youtu.be/bo6bVNho2v8?si=hNk_wo1PWsqhkRyo'),
  ('Single Arm Clubbell Outside Pendulum', 'https://youtu.be/nDGz-drTS1E?si=phIMAk1VibF9KzwH'),
  ('Clubbell Outside Pendulum', 'https://youtu.be/8v5XgK3oeeE?si=kU1NrAcgDEWvlUj6'),
  ('Double Dumbbell Close Grip Incline Bench Press', 'https://youtu.be/a2RWkUS7ja4?si=MlLBdANbCwT-w0d1'),
  ('Cable Rope Tricep Pushdown', 'https://youtu.be/e5aj8hhCPkA'),
  ('Barbell Incline Push Up', 'https://youtu.be/CKKfNBe687Q'),
  ('Bodyweight Kneeling Push Up', 'https://youtu.be/TBpk09QuVN8'),
  ('Suspension Push Up', 'https://youtu.be/cp_Hl7qd7CI?si=Tw8VVXnhtyW9vra4'),
  ('Suspension Chest Fly', 'https://youtu.be/ELmdfR9JvEA'),
  ('Stability Ball Double Dumbbell Chest Fly', 'https://youtu.be/pHsw9uHVXWA?si=0LlXNPKcyTKyfgU4'),
  ('Stability Ball Dumbbell Pullover', 'https://youtu.be/TI1gb3GFUVA'),
  ('Double Dumbbell Incline Bench Chest Fly', 'https://youtu.be/JSDpq14vCZ8?si=DX2UhxTVlOLFkyF3'),
  ('Suspension Low Row', 'https://youtu.be/hULU2N_9qjk?si=XmozOzBr-Uny0t4A'),
  ('Tire Flip', 'https://youtu.be/44E5KRVFWVQ?si=M9W-NS9JbwJV8hDU'),
  ('Tire In and Out Squat Jump', 'https://youtu.be/4h3cIxkFwlI?si=s_iXYmvt1ljfSFML'),
  ('Kettlebell Goblet Alternating Forward Lunge', 'https://youtu.be/wkMhmQ5wVWY?si=kFZCkvoaBfUNdjvU'),
  ('Double Dumbbell Suitcase Feet Elevated Calf Raise', 'https://youtu.be/UCfMPCfug60?si=hzjhqnpt1-9bHCWt'),
  ('Double Dumbbell Suitcase Calf Raise', 'https://youtu.be/wsOcmGYOn3M?si=2w1Cs0RdcdjnHLYG'),
  ('Suspension Mid Row', 'https://youtu.be/W-nnq0Ks1A0'),
  ('Double Dumbbell Seated Calf Raise', 'https://youtu.be/3ZRe_QpvRPg?si=X5ees0OsHDogPrA9'),
  ('Barbell Seated Calf Raise', 'https://youtu.be/hv00OCqm0HI?feature=shared'),
  ('Bodyweight Hand Assisted Feet Elevated Calf Raise', 'https://youtu.be/JUDbOvgH6AQ?si=p3CkDDLIlKjuufVF'),
  ('Bodyweight Hand Assisted Calf Raise', 'https://youtu.be/HwG4_WIMB7g?si=ly2SGRWM5lHuzOHF'),
  ('Bodyweight Calf Raise', 'https://youtu.be/tg3HcGWhGN8?si=i7ZBKBUTgTovDmeO'),
  ('Bodyweight Hand Assisted Foot Elevated Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=gPxN6_F1w9qQdHvy'),
  ('Bodyweight Hand Assisted Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=M_cdEJeEYZLJJD6j'),
  ('Bodyweight Single Leg Calf Raise', 'https://youtu.be/AWBGE0PlYkI?si=INJvlHfbZ6BpG0RT'),
  ('Kettlebell Goblet Alternating Reverse Lunge', 'https://youtu.be/Q8s5KVgRjsI?si=LU2DAUzkwtjOm87N'),
  ('Double Kettlebell L Sit Flutter Kicks', 'https://youtu.be/bNmYhWaTtDE?si=0pRJsSgsFQN8tX9D'),
  ('Double Dumbbell Front Rack Calf Raise', 'https://youtu.be/nDJ9cjw2J7Y?feature=shared'),
  ('Barbell Back Rack Feet Elevated Calf Raise', 'https://youtu.be/-zJsdaS13fk'),
  ('Tire Mountain Climber', 'https://youtu.be/-ouYHaP9g9g?si=qc9f_XLeK0tBdsDc'),
  ('Bodyweight Wall Supported Tibialis Raise', 'https://youtu.be/nQKgHwi8W9E?si=h2cdsN6y8_YWkxWd'),
  ('Cable Seated Tibialis Raise', 'https://youtu.be/XPrwraNV8zU?si=uYKDsDSy6F1lqx7L'),
  ('Cable Seated Single Leg Tibialis Raise', 'https://youtu.be/tSDRe05L18Q?si=tzWWp_aDlp6K7_QS'),
  ('Kettlebell Goblet Walking Lunge', 'https://youtu.be/oV97EckMQlo?si=-UB0G60JaIQ6f-4v'),
  ('Dumbbell Seated Tibialis Raise', 'https://youtu.be/2amvxbpU20c?si=ymK8PzcHyFCMv-oX'),
  ('Kettlebell Horn Grip Alternating Lateral Lunge', 'https://youtu.be/hP0wET7bCog?si=trU9Rde7VACKCuEn'),
  ('Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/w6vfiCgfbXA?si=RhaJhv_PYjW4LLj5'),
  ('Double Dumbbell Seated Feet Elevated Calf Raise', 'https://youtu.be/W5FNgQSaDfU?si=mrb4anmAuXMyWfuC'),
  ('Barbell Seated Feet Elevated Calf Raise', 'https://youtu.be/TyJOknODp8g?si=lIKKdyiWkncjpZtZ'),
  ('Kettlebell Horn Grip Alternating Forward Lunge', 'https://youtu.be/fZeR04SyMnM?si=PcC3GMitpRy-d_N5'),
  ('Tire Leg Press', 'https://youtu.be/YtKIXuPCj1M?si=ng5HKT4Y_EUFLk95'),
  ('Cable Isometric Split Squat Pallof Press', 'https://youtu.be/zMR-P_9GGKE?feature=shared'),
  ('Bodyweight Isometric Split Squat Calf Raise', 'https://youtu.be/pM_ycFCgDxU?si=YT2fo22-rIu4kKPM'),
  ('Bodyweight Isometric Split Squat Foot Elevated Calf Raise', 'https://youtu.be/mdl2K7zkcQ8?si=HIQ62ZGgxGxvMCfb'),
  ('Kettlebell Horn Grip Alternating Reverse Lunge', 'https://youtu.be/hn0H9wrT7I0?si=2puOZbS5dzRQTGh6'),
  ('Kettlebell Horn Grip Walking Lunge', 'https://youtu.be/d7cVOMtyjS8?si=-LwL939gyb_zs3lu'),
  ('Single Arm Dumbbell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise', 'https://youtu.be/xASrMCHjL4M?si=-Ue1QOKJH5pRPoTH'),
  ('Bodyweight Squat Jump', 'https://youtu.be/YGGq0AE5Uyc?si=or6Xddi0YaAkHuXV'),
  ('Double Dumbbell Suitcase Alternating Step Up', 'https://youtu.be/R61TjoYofDE?si=sA8kbakWIt24ow1A'),
  ('Double Dumbbell Front Rack Step Up', 'https://youtu.be/hKLIHPXmPA4?si=mk9hkktF_4qw0okV'),
  ('Cable V Grip Seated Low Row', 'https://youtu.be/EhAho9Szp-0'),
  ('Resistance Band Half Kneeling Face Pull', 'https://youtu.be/pxnaBaRRZiY'),
  ('Bodyweight Prone Cobra', 'https://youtu.be/NZSBjpVpvw8?si=lyk8zIAtzX2ETUc_')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);