UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Alternating Double Dumbbell Z Press', 'https://youtu.be/dsTU2qm4ef0?si=sT2aw7NxeFtfYYNV'),
  ('Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/HZM84steEyw?si=wN3l2SpjKBFPTIbD'),
  ('Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/y0t2PFFwSe4?si=VjtJz1Dg61jGQIZ9'),
  ('Alternating Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/UhOs_Wvckvs?si=FqNmpb8ECh_Y-9rl'),
  ('Alternating Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/12MxAGiIgK8?si=pO89QghXz2Ykj1lb'),
  ('Single Arm Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/QVFklRHtJxY?si=D_kiEaZg-5pSrfHL'),
  ('Double Plate Incline Bench Prone Y Raise', 'https://youtu.be/VHeZJHEj6ic?si=DTfOrwFveTP-memt'),
  ('Single Arm Kettlebell Pendlay Row', 'https://youtu.be/VOmnhGvccZ0?feature=shared'),
  ('Barbell Floor Press', 'https://youtu.be/YdiVxhxufG8?si=pMAxf531BcAPvatO'),
  ('Ring Plank', 'https://youtu.be/p3zS2AMqGlg'),
  ('Single Arm Ring Plank', 'https://youtu.be/_Iev7PLP6QY'),
  ('Battle Rope Alternating Outward Circle', 'https://youtu.be/O2HVcPD3wKQ?si=CFVI8GpHxTsirv6u'),
  ('Ring Support Hold', 'https://youtu.be/kONbxg4kzkE'),
  ('Ring Side Plank', 'https://youtu.be/PQ3Vz8fp73k'),
  ('Barbell Reverse Grip Bent Over Row', 'https://youtu.be/cZvQNvTUUu0?si=SqA3lYAZBc0jOnvn'),
  ('Macebell Offset Bent Over Row', 'https://youtu.be/OXl94TQd_vw?si=AMXpvOM-H382GJoz'),
  ('Macebell Reverse Grip Offset Bent Over Row', 'https://youtu.be/igNnqZZ69JM?si=xaqrnAFrW4r7NuVR'),
  ('Bodyweight Hollow Body Rock', 'https://youtu.be/p7j02V1fIzU'),
  ('Single Arm Dumbbell Power Snatch', 'https://youtu.be/3mlhF3dptAo'),
  ('Alternating Single Arm Dumbbell Power Snatch', 'https://youtu.be/OktkfRlGcns'),
  ('Single Arm Dumbbell Squat Snatch', 'https://youtu.be/etK3OPjM3S4'),
  ('Alternating Single Arm Dumbbell Squat Snatch', 'https://youtu.be/T0_a2xijJBE'),
  ('Single Arm Cable Single Leg Romanian Deadlift', 'https://youtu.be/OC_7QIo0uk4'),
  ('Double Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/6caQpfXMvyw?si=WY0XcdcIUuE20g-o'),
  ('Single Arm Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/AlxuA22ymwg?si=-tgz7djxN0QKxXfA'),
  ('Double Kettlebell Front Rack Step Up', 'https://youtu.be/wcnuhd6RHwE'),
  ('Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/jHpBzpxK16c?si=3sB9wGkke_B632ad'),
  ('Single Arm Dumbbell Incline Bench Prone Row', 'https://youtu.be/4Bv94e_ufjo?si=8V5SPIIuNai7zUm3'),
  ('Single Arm Dumbbell Spider Curl', 'https://youtu.be/Ew2ZzKqICfA?si=Irq2jLSDxKiagY3F'),
  ('Double Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/STeIzkHm6tE?si=BxEJOKh_KtwNSMK_'),
  ('Double Dumbbell Seated Good Morning', 'https://youtu.be/x5nnk8hUBo4'),
  ('Bodyweight Hip Thrust', 'https://youtu.be/OAhvIWLC0rc'),
  ('Single Arm Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/SoVCwno_9z8?si=BCvfBOVPW_aHbvZ_'),
  ('Alternating Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/rAoi4_AI7VA?si=b6KXmXEYoxIPmTt2'),
  ('Single Arm Kettlebell Incline Bench Prone Row', 'https://youtu.be/gPX8OmnYmQY?si=UgQnJkh9n3OobTcZ'),
  ('Single Arm Dumbbell Overhead Contralateral Bulgarian Split Squat', 'https://youtu.be/z7rygloAW30?si=p4kPPZcAKammq1Vv'),
  ('Double Kettlebell Suitcase Step Up', 'https://youtu.be/3HUEab31fks?si=B2OmGKfwSuXhts1z'),
  ('Single Arm Kettlebell Suitcase Contralateral Step Up', 'https://youtu.be/lMADALbx1eM?si=wJjWrYeLHPKqVgHh'),
  ('Double Kettlebell Overhead Step Up', 'https://youtu.be/eKUmMljLcKw?si=ocsvBon7ivrRziM6'),
  ('Kettlebell Half Kneeling Low to High Chop', 'https://youtu.be/wPXdGwc0NTs'),
  ('Single Arm Kettlebell Windmill', 'https://youtu.be/3rtUK_jUv4s'),
  ('Kettlebell Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Alternating Single Arm Kettlebell Plank Pull Through', 'https://youtu.be/fKbu_2L94x8'),
  ('Single Arm Kettlebell Swing', 'https://youtu.be/kneGICiz30g'),
  ('Double Kettlebell Bottoms Up Bench Press', 'https://youtu.be/bIzD1Z_C0cA'),
  ('Single Arm Kettlebell Suitcase Deadlift', 'https://youtu.be/1hcAoywwuRI'),
  ('Single Arm Kettlebell Clean', 'https://youtu.be/TQT7hBXVcOo'),
  ('Single Arm Kettlebell Clean to Overhead Press', 'https://youtu.be/JtlYyc5MaAc'),
  ('Alternating Single Arm Dumbbell Pendlay Row', 'https://youtu.be/7zKQ79awAvY?feature=shared'),
  ('Single Arm Kettlebell Snatch', 'https://youtu.be/VdNC_xicfyg'),
  ('Kettlebell Sumo Deadlift', 'https://youtu.be/odS65TnXgU0?si=l3QM9Nb4wHNt_JgK'),
  ('Single Arm Kettlebell Turkish Get Up', 'https://youtu.be/sgd8n917Zv0'),
  ('Kettlebell Goblet Squat', 'https://youtu.be/f-Vf2yRRqOg'),
  ('Single Arm Kettlebell Overhead Squat', 'https://youtu.be/nrfDq0DUhrE'),
  ('Double Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/vcMZNgn5G9c'),
  ('Single Arm Kettlebell Bottoms Up Bench Press', 'https://youtu.be/NIytPzrQ460?si=hBsVxzSTE6ddOTCD'),
  ('Single Arm Kettlebell Turkish Sit Up', 'https://youtu.be/KpufjJRtyPc'),
  ('Double Kettlebell Turkish Sit Up', 'https://youtu.be/RttCwCerCiM'),
  ('Double Kettlebell Turkish Sit Up to Z Press', 'https://youtu.be/UcLpNnWX8vE'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Cossack Squat', 'https://youtu.be/aJGPHYsiyTM'),
  ('Double Kettlebell Swing', 'https://youtu.be/fOPqk1FA4HU'),
  ('Double Kettlebell Front Rack Squat', 'https://youtu.be/JoT4bHnzTMw?si=i8z5wbuObKGVIl4_'),
  ('Single Arm Kettlebell Front Rack Squat', 'https://youtu.be/Wqg4NY5XAkU'),
  ('Single Arm Kettlebell Front Rack Contralateral Split Squat', 'https://youtu.be/-Z8NXAi59SE'),
  ('Single Arm Kettlebell Front Rack Carry', 'https://youtu.be/M39871Puz6c'),
  ('Single Arm Kettlebell Squat Clean', 'https://youtu.be/FZ8mMUwnCQs'),
  ('Double Kettlebell Prone Row', 'https://youtu.be/hUG_dolsaPE?si=_fw03cFT8VfLVtzo'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/0i2Aa8gV-VY?si=Z7AGqRY1Hod9Fwti'),
  ('Double Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/F19T2zGlPGA'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Walking Lunge', 'https://youtu.be/FvSL8slKKHY'),
  ('Alternating Double Kettlebell Prone Row', 'https://youtu.be/OD7URB1yHAo?si=UX_3VmEfO_WpeiuT'),
  ('Double Kettlebell Single Leg Romanian Deadlift', 'https://youtu.be/JkKxFADvLvk'),
  ('Double Kettlebell Romanian Deadlift', 'https://youtu.be/Xa8hHIwOHe4'),
  ('Single Arm Kettlebell Contralateral Single Leg Romanian Deadlift', 'https://youtu.be/9u_Fccgk9Ys'),
  ('Single Arm Kettlebell Bottoms Up Overhead Squat', 'https://youtu.be/j0aAMnMp0yU'),
  ('Single Arm Kettlebell Prone Row', 'https://youtu.be/QSbH7gNkBtc?si=ngxTS90XoTuvQDxs'),
  ('Parallette Tuck Planche', 'https://youtu.be/3WVToPNWjVk'),
  ('Macebell Offset Bicep Curl', 'https://youtu.be/xkyQtEH8fxM?si=Zh1mTKcYEFs382Sk'),
  ('Parallette L Sit to Tuck Planche', 'https://youtu.be/NUvTsZxo5nk'),
  ('Landmine Standing Oblique Twist', 'https://youtu.be/4dGj7rES9pY'),
  ('Cable Rope Tall Kneeling High to Low Chop', 'https://youtu.be/h-af-afj-Xg'),
  ('Single Arm Parallette Plank', 'https://youtu.be/NrkFLTzLuSM'),
  ('Single Arm Suspension Plank', 'https://youtu.be/hetklTC7y4M?si=gHU6ufU8oAcg21Jv'),
  ('Battle Rope Russian Twist', 'https://youtu.be/_-kclLM0Mak'),
  ('Bodyweight Bird Dog Knee to Elbow', 'https://youtu.be/1v4_Vsvk3gc'),
  ('Slam Ball Feet Elevated Russian Twist', 'https://youtu.be/W1FXse115qs'),
  ('Medicine Ball Feet Elevated Russian Twist', 'https://youtu.be/IdEocZzdUNY'),
  ('Alternating Double Dumbbell Prone Row', 'https://youtu.be/Ry9HwpfUbd8?si=oY89SBibCyKMJ7CT'),
  ('Bodyweight Forearm Plank Alternating Knee to Elbow', 'https://youtu.be/A_JgZzr6o-k'),
  ('Bodyweight Loaded Beast to Alternating Kick Through', 'https://youtu.be/lhh2tGD_47g'),
  ('Single Arm Dumbbell Prone Row', 'https://youtu.be/-fuxiCQvMxQ?si=lCRmzsfrTeNaP0Gk'),
  ('Double Kettlebell Clean', 'https://youtu.be/8tFmEJ9ElaM'),
  ('Double Kettlebell Snatch', 'https://youtu.be/5WNcWPHXRZ0'),
  ('Battle Rope Feet Elevated Russian Twist', 'https://youtu.be/XdKaa2lHuic'),
  ('Superband Dead Bug', 'https://youtu.be/wCwn7-Z-XjE'),
  ('Parallette V Sit', 'https://youtu.be/oBmFzeay6Z8?si=dliVO8cgoAWNKwT3'),
  ('Double Kettlebell Split Jerk', 'https://youtu.be/6sbNXcg-R0Y'),
  ('Double Kettlebell High Pull', 'https://youtu.be/zfWpy9oMOqc?si=8gZawgsKgTeeGHck&amp;utm_source=MTQxZ'),
  ('Superband Pallof Press', 'https://youtu.be/TvPRtxN8uoA'),
  ('Superband Half Kneeling Pallof Press', 'https://youtu.be/V-SoYj9uQV8'),
  ('Ring Archer Row', 'https://youtu.be/s1Cuq185q6Y?si=TNXwSjV_mkE_2ty0'),
  ('Single Arm Landmine Row to Rotational Shoulder Press', 'https://youtu.be/f-sh_ImlQUo'),
  ('Bodyweight Hand Assisted Skater Squat', 'https://youtu.be/DExb7UaAlbg'),
  ('Superband Pull Through', 'https://youtu.be/ZuKowDpVVXM'),
  ('Miniband Quadruped Hip Extension', 'https://youtu.be/k30hN0vhlsY?si=ycYwNbMrFEnA94pG'),
  ('Cable Hip Adduction', 'https://youtu.be/UyXncDziNGo?si=W4GuZaUvoWtiIOxj'),
  ('Superband Tall Kneeling Pallof Press', 'https://youtu.be/yUzjX1LdySo?si=2LpxjTl8N8OHsKqd'),
  ('Slider Eccentric Hamstring Curl', 'https://youtu.be/vcCVej7p_vc'),
  ('Landmine Low Hold Lateral Lunge', 'https://youtu.be/VTtLrBvHoJ8'),
  ('Double Kettlebell Sumo Deadlift', 'https://youtu.be/4m288BpgfcQ'),
  ('Slider Kneeling Reach Push Up', 'https://youtu.be/-RTSF7qbrhs?si=hznPEKw9aLONjGpz'),
  ('Slider Parallette Knee Tuck', 'https://youtu.be/Kj89v76f-l8?si=_B0Uc1Xs1x1S0G_M'),
  ('Superband Shoulder Dislocates', 'https://youtu.be/MPtMYQH9vvg?si=eEJrNr3oqGzcma8_'),
  ('Superband Alternating Shoulder Dislocates', 'https://youtu.be/AJmPEWu4FiM?si=0h2x72A-kGfK3a_0'),
  ('Superband Prone Shoulder Dislocates', 'https://youtu.be/3WOAWkEKZGA?si=lSddj94elx-N7ZKJ'),
  ('Ring L Sit', 'https://youtu.be/lwcHmXvw-T4'),
  ('Resistance Band Prone Shoulder Dislocates', 'https://youtu.be/YwELfevh5vs?si=tmPYSbe-vfbiD0vx'),
  ('Cable Straight Bar Spider Curl', 'https://youtu.be/zGyaLrwHJjs?si=sg4m9llWui7pmOT_'),
  ('Double Kettlebell Bottoms Up Front Rack Squat', 'https://youtu.be/IvN-CSDnvoc'),
  ('Barbell Back Rack Cyclist Squat', 'https://youtu.be/TT7Ra3TnlZY'),
  ('Gravity Boots Inverted Sit Up', 'https://youtu.be/AN4MBtCsJqo'),
  ('Double Kettlebell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/G7e7EenICzQ'),
  ('Barbell Back Rack Step Up', 'https://youtu.be/uQGRzdjxHes'),
  ('Barbell Front Rack Step Up', 'https://youtu.be/YR_7r6EzJdA'),
  ('Barbell Standing Rollout', 'https://youtu.be/_lI_GB0DI3o'),
  ('Stability Ball Cable Russian Twist', 'https://youtu.be/4ESBjh2BcdE'),
  ('Miniband Frog Pump', 'https://youtu.be/rzjQ8XpXt1Q'),
  ('Bodyweight Fire Hydrant', 'https://youtu.be/IFrN8GELc-k?feature=shared'),
  ('Bodyweight Knee Hover Quadruped Fire Hydrant', 'https://youtu.be/8nmBvZ1DkKQ?si=RUcdU_JPDGU_yIWv'),
  ('Alternating Double Dumbbell Spider Curl', 'https://youtu.be/KznrM_RhXDc?si=Qxgmd-eTnFuZ5rpo'),
  ('Bodyweight Bent Knee Copenhagen Plank Side Raise', 'https://youtu.be/xkcOhvzzta0'),
  ('Bodyweight Kneeling Side Plank', 'https://youtu.be/PAHxwhBVsYY?si=pym-tzPNwmH8zNeP'),
  ('Bodyweight Wall Assisted Hip Airplane', 'https://youtu.be/20R2FqNUBsA?si=3Nuvhsgux27gQFjW'),
  ('Superband Single Leg Tibialis Raise', 'https://youtu.be/fAf6Z7wu7fM?si=6K5_014ZCoGfknf8'),
  ('Barbell Zercher Squat', 'https://youtu.be/nwx6Ip7hd3I'),
  ('Barbell Squat Snatch', 'https://youtu.be/9xQp2sldyts'),
  ('Barbell Squat Clean to Split Jerk', 'https://youtu.be/PjY1rH4_MOA'),
  ('Slider Kneeling Alternating Reach Push Up', 'https://youtu.be/1UD0dTGE04w?si=q2odI18mbdJTtPDF'),
  ('Barbell Hang Squat Clean to Thruster', 'https://youtu.be/8DApihgXzGk'),
  ('Barbell Squat Clean to Thruster', 'https://youtu.be/4qZWqKDAhkQ'),
  ('Bodyweight Copenhagen Plank', 'https://youtu.be/tKb76R21AfM?si=zsuYyzMMfjZleCpc'),
  ('Bodyweight Bent Knee Copenhagen Plank', 'https://youtu.be/obtdLUWZi-Y'),
  ('Miniband Single Leg Hip Thrust', 'https://youtu.be/tPWyj85zsmg'),
  ('Barbell Deficit Snatch Grip Deadlift', 'https://youtu.be/s_Cx_ElOuQs'),
  ('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/hTBEkHf8GmA'),
  ('Bodyweight Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/Gu4qA5TevLU'),
  ('Double Kettlebell Thruster', 'https://youtu.be/5-mxMxigTfw'),
  ('Double Kettlebell Cossack Squat Thruster', 'https://youtu.be/DbKGRbkQ80E'),
  ('Single Arm Landmine Shrug', 'https://youtu.be/I_qhTOdNkHo?si=7wY3icLNd-TkFk5i'),
  ('Double Kettlebell Front Rack Walking Lunge', 'https://youtu.be/Xmfx1eZMKmY'),
  ('Double Kettlebell Overhead Walking Lunge', 'https://youtu.be/hcQJcKxc240'),
  ('Ring Straddle L Sit', 'https://youtu.be/pjk0vGe9YRU'),
  ('Double Kettlebell Seesaw Overhead Press', 'https://youtu.be/VWnVBfRkLXE?si=AeN6Q9aAnShqxuIb'),
  ('Double Kettlebell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/UiY-JIpmt24?si=ox4YNd9xIIVapyeB'),
  ('Double Dumbbell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Lk0xszw7Tf8?si=GHtFcn5OVifRVyDQ'),
  ('Double Dumbbell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/NP4p_SWAgnA?si=VoTKPhBbaaWrrYZH'),
  ('Double Dumbbell Seesaw Z Press', 'https://youtu.be/L_Y8osw78lA?si=3eK1QuOTlQjCzAxO'),
  ('Stability Ball Sit Up', 'https://youtu.be/7L90imlW0es?si=gY7k7XVC43IRrv-N'),
  ('EZ Bar Wide Grip Strict Bicep Curl', 'https://youtu.be/j83lzC2E4Ss?si=PcoF092JVJRpg8T4'),
  ('Double Kettlebell Squat Clean', 'https://youtu.be/6wyxpVY8PQ0'),
  ('Double Kettlebell Hollow Body Hold', 'https://youtu.be/do1yf3NMXdg'),
  ('Alternating Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/xkCR2CkkL1g?si=Qy0YPAcCasZF6kNk'),
  ('Bodyweight Side Lying Hip Adduction', 'https://youtu.be/UW52u8OaWhw?si=WdEOpAR_PSB9x9bR'),
  ('Superband Hollow Body Hold', 'https://youtu.be/8QRsSJ-Ny8M'),
  ('Parallette Freestanding Handstand Push Up', 'https://youtu.be/3FYYo6lP-dw'),
  ('Slider Single Leg Eccentric Hamstring Curl', 'https://youtu.be/yAOulKW0al4'),
  ('Bodyweight Freestanding Handstand Push Up', 'https://youtu.be/aAErmRDDJKY'),
  ('Single Arm Ring Grip Push Up', 'https://youtu.be/CXVqHGLmb3Q'),
  ('Superband Side Plank Hanging Hip Adduction', 'https://youtu.be/JG0Ay2QDVbI'),
  ('Ring Strap Bulgarian Handstand Push Up', 'https://youtu.be/ZNCupJIYP6M'),
  ('Stability Ball Feet Elevated Frog Pump', 'https://youtu.be/Rc5e-DsD--M'),
  ('Double Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/HOQeoz3zQeo'),
  ('Barbell Front Rack Cyclist Squat', 'https://youtu.be/IU_0IBe4G9w'),
  ('Double Kettlebell Dead Clean to Push Press', 'https://youtu.be/NAZ9uF9S_wk'),
  ('Bodyweight Bent Arm Press Handstand', 'https://youtu.be/Gzz3ku70W3I'),
  ('Single Arm Dumbbell Cyclist Thruster', 'https://youtu.be/2Tt0XZ2pZyE'),
  ('Double Kettlebell Front Rack Split Squat', 'https://youtu.be/ExJCssj4YV0'),
  ('Double Kettlebell Front Rack Bulgarian Split Squat', 'https://youtu.be/Q3yDIeMfdNg'),
  ('Double Kettlebell Overhead Squat', 'https://youtu.be/2Pk8jmse6vY'),
  ('Bodyweight Chest Roll to Straight Body Press Handstand', 'https://youtu.be/mYQAYnr2hlg?si=gqlNGvKWytXXQP1H'),
  ('Ring Bent Arm Bent Body Press Handstand', 'https://youtu.be/TxkC9nrvOho'),
  ('Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/1XyV5eNL1z0'),
  ('Kettlebell Swing', 'https://youtu.be/1cVT3ee9mgU'),
  ('Alternating Single Arm Kettlebell Swing', 'https://youtu.be/WK4ughYoUEI?si=2mvQ9x0jZEF2zzRA'),
  ('Alternating Single Arm Kettlebell Clean', 'https://youtu.be/dPN2mj5R2S8'),
  ('Alternating Single Arm Kettlebell Snatch', 'https://youtu.be/0aq5EW0euvA'),
  ('Single Arm Kettlebell Staggered Stance Swing', 'https://youtu.be/L2WY5gYUb1U'),
  ('Alternating Single Arm Kettlebell Alternating Staggered Stance Swing', 'https://youtu.be/Ss7KjOjCpVU'),
  ('Single Arm Kettlebell Half Kneeling Swing', 'https://youtu.be/QVvrdVbq9qs'),
  ('Double Kettlebell Outside Swing', 'https://youtu.be/zrvtXpwVTOI'),
  ('Double Kettlebell Outside Half Snatch', 'https://youtu.be/Fx-qV1dHGi4?feature=shared'),
  ('Double Kettlebell Outside Clean', 'https://youtu.be/QtlvLhVFR40'),
  ('Single Arm Kettlebell Side Swing', 'https://youtu.be/YBJnavxcbUA'),
  ('Kettlebell Feet Elevated Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Single Arm Kettlebell Half Kneeling Windmill', 'https://youtu.be/wjYNzITBDqg'),
  ('Kettlebell Horn Grip Skater Squat', 'https://youtu.be/q1TuasYdM2M'),
  ('Double Kettlebell Front Rack Pistol Squat', 'https://youtu.be/-A7yvmUv8Cw'),
  ('Single Arm Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/JGY8VuvaEHc?si=LVWYZO5Qt-3WONJf'),
  ('Ring Back Lever Pullout', 'https://youtu.be/FRBr2pomeOM?si=15TQvL3xIskTVzVA'),
  ('Double Kettlebell Clean to Overhead Press', 'https://youtu.be/5Fx69TRWARc')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);