UPDATE exercises SET video_url = 'https://youtu.be/KTcHetEk8Vw?si=xFuh3rDHIThNVEbK' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Clap');
UPDATE exercises SET video_url = 'https://youtu.be/WH4rwFZoce8?si=Yt1fEhmIXXEAa1s1' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Inward Circle');
UPDATE exercises SET video_url = 'https://youtu.be/ta0cdvQmADs?si=B6OcdshuVkMO34iV' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Outward Circle');
UPDATE exercises SET video_url = 'https://youtu.be/UKjQMYiQnS0?si=Lg6kuQMDGFaxi6X7' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/sj_bFtL9Oy4?si=osmoYlG_O5Fs6lPE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Low Switch Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/mPyE_hQolbs?si=0ulL0aaE23nJ0OiJ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Siwj8KDU5zI?si=qiHYnyo8qzTOwk1L' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zombie Squat');
UPDATE exercises SET video_url = 'https://youtu.be/G5gCl5b0E-4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/8xX1a7o6bKU?si=rLYvcvZkeDzk1KV5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Ipsilateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/wqXP71ooU44?si=oje6--5yoC_aZeha' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/XOCZvsIB-ys?si=icJ1C2ots-yLy5_7' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/DPNDaQoxjsQ?si=KOvphYYrIaszuK1F' WHERE LOWER(TRIM(name)) = LOWER('Plate Dead Bug');
UPDATE exercises SET video_url = 'https://youtu.be/41RTZolbtPk?si=HjTttPYPllgpQXeT' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/uuVkmAJd-y0?si=JvCPYFXj-MAzRMAF' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JYftrLVWUD8?si=WwaPZ7K8HUnsrnqN' WHERE LOWER(TRIM(name)) = LOWER('Plate Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/4p5jWyz-YRQ?si=A80S2QY5Wu5Lql2-' WHERE LOWER(TRIM(name)) = LOWER('Plate Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/WT9UCB_1Y8Q?si=dmkzRkM-dzlFe1ux' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/m-dlg3v8SkY?si=KI1hgOAtTqI0ty6r' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/OyKu-DvXxAc?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Landmine Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/_nfx1aDx87o?si=T4Vw1FKJpAnHEuV6' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Hawaiian Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6mefiFE8CVM?si=KyPC_eM0qqnT8F_x' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hawaiian Squat');
UPDATE exercises SET video_url = 'https://youtu.be/qnw_7_U_fJU?si=0CZNhyLC07DBXGKk' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Hawaiian Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Co5EWd-aiVk?si=NBvXIzNsQ1egWtQz' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/ifEMtPwfvV0?si=_xR4TF-oMs8-LVSH' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/R3_u3kg7Ioo?si=ekSihU-Mge0xIWxv' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/LcVh7l7WyJo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/JdXRG8B3N8E?si=uO1aFa0IBUO3nVqz' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Knee Supported Row');
UPDATE exercises SET video_url = 'https://youtu.be/yeaFdnu5pls?si=N1yYEQFwZfUlKLMg' WHERE LOWER(TRIM(name)) = LOWER('Macebell Offset Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/vSjthx8vHNs?si=HUKI9YcVXeNdFeVx' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/1ij5SfH4PMo?si=HuKVOjAkOpK16kCi' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/AlwLsoYSZo8?si=vd7o72xnaBnjH3gj' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/R2LOc0ZTcLI?si=0ry8ntEThAk2l6WI' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/MeBEmS3QRjE?si=lZ0o-kYlVdKtkDqe' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-E9IilV53AI?si=3376PVeqdmgVn2AJ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tall Kneeling Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/jme7uJ99oI4?si=zSBDr4Bv5l6vINmf' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/QPzYCYVpsFA?si=Kc9-HoWbiLTj997Y' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/nE9UnkFqPMg?si=uhDy9WDlpMa_ogud' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/uqIMqZmyyH8?si=J2AzvjdNfcenC6Jm' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/G-neztXXSCA?si=txR7W1HSVUCckbMc' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zombie Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/00Dc5QnwzGI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-TTZd1lASkw?si=T4OTaFzbqRaGAc3m' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/TTZlek-Jeec?si=nJsuOnJws7uylodj' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/V-CvLcQhsPk?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6Y7jLhsURck?si=ZI60iuhlYRh4x0Ul' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/LUESjt8b2vY?si=vYksLJ6mIw7_F_DZ' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Z9Bryd2XtwY?si=13MbA6khrvgobwKt' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Pull Apart');
UPDATE exercises SET video_url = 'https://youtu.be/QWniDREaQVY?si=nOmYsg0t5nXPcb0Q' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/hf7jnF45N_I?si=1OHNa_B7yazQ9w4L' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Bent Over Reverse Fly');
UPDATE exercises SET video_url = 'https://youtu.be/om2bTuwKGes?si=nJJaeiJglypyQD_G' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Knee Supported Tricep Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/kR9mqN6rxpQ?si=1GxxxZw4G3kFbAi0' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Tricep Kickback');