UPDATE exercises SET video_url = 'https://youtu.be/s1Cuq185q6Y?si=TNXwSjV_mkE_2ty0' WHERE LOWER(TRIM(name)) = LOWER('Ring Archer Row');
UPDATE exercises SET video_url = 'https://youtu.be/f-sh_ImlQUo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Row to Rotational Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/DExb7UaAlbg' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Skater Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZuKowDpVVXM' WHERE LOWER(TRIM(name)) = LOWER('Superband Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/k30hN0vhlsY?si=ycYwNbMrFEnA94pG' WHERE LOWER(TRIM(name)) = LOWER('Miniband Quadruped Hip Extension');
UPDATE exercises SET video_url = 'https://youtu.be/UyXncDziNGo?si=W4GuZaUvoWtiIOxj' WHERE LOWER(TRIM(name)) = LOWER('Cable Hip Adduction');
UPDATE exercises SET video_url = 'https://youtu.be/yUzjX1LdySo?si=2LpxjTl8N8OHsKqd' WHERE LOWER(TRIM(name)) = LOWER('Superband Tall Kneeling Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/vcCVej7p_vc' WHERE LOWER(TRIM(name)) = LOWER('Slider Eccentric Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/VTtLrBvHoJ8' WHERE LOWER(TRIM(name)) = LOWER('Landmine Low Hold Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/4m288BpgfcQ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Sumo Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/-RTSF7qbrhs?si=hznPEKw9aLONjGpz' WHERE LOWER(TRIM(name)) = LOWER('Slider Kneeling Reach Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Kj89v76f-l8?si=_B0Uc1Xs1x1S0G_M' WHERE LOWER(TRIM(name)) = LOWER('Slider Parallette Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/MPtMYQH9vvg?si=eEJrNr3oqGzcma8_' WHERE LOWER(TRIM(name)) = LOWER('Superband Shoulder Dislocates');
UPDATE exercises SET video_url = 'https://youtu.be/AJmPEWu4FiM?si=0h2x72A-kGfK3a_0' WHERE LOWER(TRIM(name)) = LOWER('Superband Alternating Shoulder Dislocates');
UPDATE exercises SET video_url = 'https://youtu.be/3WOAWkEKZGA?si=lSddj94elx-N7ZKJ' WHERE LOWER(TRIM(name)) = LOWER('Superband Prone Shoulder Dislocates');
UPDATE exercises SET video_url = 'https://youtu.be/lwcHmXvw-T4' WHERE LOWER(TRIM(name)) = LOWER('Ring L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/YwELfevh5vs?si=tmPYSbe-vfbiD0vx' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Prone Shoulder Dislocates');
UPDATE exercises SET video_url = 'https://youtu.be/zGyaLrwHJjs?si=sg4m9llWui7pmOT_' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/IvN-CSDnvoc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/TT7Ra3TnlZY' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/AN4MBtCsJqo' WHERE LOWER(TRIM(name)) = LOWER('Gravity Boots Inverted Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/G7e7EenICzQ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/uQGRzdjxHes' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/YR_7r6EzJdA' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/_lI_GB0DI3o' WHERE LOWER(TRIM(name)) = LOWER('Barbell Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/4ESBjh2BcdE' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Cable Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/rzjQ8XpXt1Q' WHERE LOWER(TRIM(name)) = LOWER('Miniband Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/IFrN8GELc-k?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Fire Hydrant');
UPDATE exercises SET video_url = 'https://youtu.be/8nmBvZ1DkKQ?si=RUcdU_JPDGU_yIWv' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Knee Hover Quadruped Fire Hydrant');
UPDATE exercises SET video_url = 'https://youtu.be/KznrM_RhXDc?si=Qxgmd-eTnFuZ5rpo' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/xkcOhvzzta0' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bent Knee Copenhagen Plank Side Raise');
UPDATE exercises SET video_url = 'https://youtu.be/PAHxwhBVsYY?si=pym-tzPNwmH8zNeP' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Kneeling Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/20R2FqNUBsA?si=3Nuvhsgux27gQFjW' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Assisted Hip Airplane');
UPDATE exercises SET video_url = 'https://youtu.be/fAf6Z7wu7fM?si=6K5_014ZCoGfknf8' WHERE LOWER(TRIM(name)) = LOWER('Superband Single Leg Tibialis Raise');
UPDATE exercises SET video_url = 'https://youtu.be/nwx6Ip7hd3I' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Squat');
UPDATE exercises SET video_url = 'https://youtu.be/9xQp2sldyts' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/PjY1rH4_MOA' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Clean to Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/1UD0dTGE04w?si=q2odI18mbdJTtPDF' WHERE LOWER(TRIM(name)) = LOWER('Slider Kneeling Alternating Reach Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/8DApihgXzGk' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Squat Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/4qZWqKDAhkQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/tKb76R21AfM?si=zsuYyzMMfjZleCpc' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/obtdLUWZi-Y' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bent Knee Copenhagen Plank');
UPDATE exercises SET video_url = 'https://youtu.be/tPWyj85zsmg' WHERE LOWER(TRIM(name)) = LOWER('Miniband Single Leg Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/s_Cx_ElOuQs' WHERE LOWER(TRIM(name)) = LOWER('Barbell Deficit Snatch Grip Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/hTBEkHf8GmA' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Gu4qA5TevLU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/5-mxMxigTfw' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/DbKGRbkQ80E' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Cossack Squat Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/I_qhTOdNkHo?si=7wY3icLNd-TkFk5i' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/Xmfx1eZMKmY' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Walking Lunge');