UPDATE exercises SET video_url = 'https://youtu.be/vnwL74DnWK8?si=qsKdUhrsdu46i1An' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Zko5x2SoQmo?si=PCTDak-unxScaIpM' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Plank Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/Q7FtGv0v7vg?si=DvtZ3VraSeIPHfHk' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Feet Elevated Plank Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/9JHFkrjW4_Y?si=m1HLdDm33Jymv5KP' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Swing');
UPDATE exercises SET video_url = 'https://youtu.be/UNgnGEswyR4?si=oWVFZerU0mt-Io9N' WHERE LOWER(TRIM(name)) = LOWER('Macebell Half Battle Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/0JAmWCoB7ec?si=aUSwxvV3VwO7Fqfi' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Plate Assisted Hip Airplane');
UPDATE exercises SET video_url = 'https://youtu.be/ZJ95ZoB0ZXY?si=pipbT6H4SgqjMWv0' WHERE LOWER(TRIM(name)) = LOWER('Macebell Battle Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/J9thOow3-iY?si=mZOrggfNx4BC4LdB' WHERE LOWER(TRIM(name)) = LOWER('Barbell Cuban Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/9ExnOQh3WDU?si=7rIFSmGhbv4rgcJ2' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Landmine Tall Kneeling Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/mVzkA_m7I8k?si=nz9dAss-NvLHBUln' WHERE LOWER(TRIM(name)) = LOWER('Barbell Feet Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/vexyZD8S1B8?si=qmrB8iZUTuht69xJ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/cqSuTycslLg?si=dnsKBV2QyBbtxyRD' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Contralateral Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/yoKxUD9pUj8?si=8BcXj2frpNXsJmfa' WHERE LOWER(TRIM(name)) = LOWER('Barbell Tall Kneeling Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/1SeR4V-EYK8?si=jeUtHpyY3S0-eqZF' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Tall Kneeling Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/l66EvN4X6Mk?si=i4fPkqXo_4_8fmO6' WHERE LOWER(TRIM(name)) = LOWER('Cable Prone Bench Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/a3wg2b8pd_w?si=UH9NFJeHHPoQpalx' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Vlgh0ImT5oU?si=WOAwroyeZ6jJWGto' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lssvh3-XTas?si=rmOXOmN8Rlb5bMEe' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/21r8Pdk6Vks?si=U-wSwCn696acnBp9' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/zZfh3tvp5CI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/PwtxLgNobQQ?si=DoSwEK_jWEv76qX3' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/JoV4UqO1tTc?si=3YJ_yF9NN8BUfwS9' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Zv8CDt76v-o?si=2EUkwtXgQzLAb65b' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/k9GGgck623Y?si=lU__htPe1riSTjAv' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ZsmsBmOMtnw?si=FMtq9k1eAmHq4gEX' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/d3oKvFQ2KOk?si=DHn68Kf7oX9vBrYU' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/U0PGg34Vx8A?si=JVT4ugA6ELAoJP3g' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/R3Kd1U5hPyc?si=BSEMsU-3AstW_2LI' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/pDA738FZsuk?si=bzG9vYvbc69IfMmO' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/rwlsbVNSqDQ?si=6ELRzgo6Ek1bVGBe' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/U7Nrwyu6Uqo?si=i10Myq56LE1Wlzzn' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/RqMG5v-jUyE?si=hxI8O10U-7CcGVRp' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/I9YUnFtd81o?si=yuqTt95kbjtVETJd' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/KC6oWhmOmPY?si=OWiPo66RrQ46WjHj' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/kcVqtqe03WI?si=KuFsD1PlWdph7WCt' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Zy3uowra52Q?si=TqlOPzqiZOcb_wkA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/bjxICX4wQMQ?si=s83QPA-v5pPzg1fM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/FJSjoyq9das?si=zs-BmTlnKVXLf4--' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/s5w0EOsU7e8?si=UCHj4c3UE1LScgnx' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/gWN9epxFqX8?si=h3iRgeFCZgBGHOMT' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/StvRmr-ZxmA?si=G51-gqCZ-oQMhQyp' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/uzn966rWQ4c?si=XF_kMH6vfBIw4hz4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/RxBzGBShf9w?si=yD5EyWT1k3UeODJI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/IiijJRQxMKM?si=rak-3KhujfWzeG6V' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Ae33oITfYwM?si=BTB-LZkHb2SHl8HM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/r1NS0BNUh3c?si=XwpKqEi6aUMJvPq5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/jDMv9KiKXco?si=j2SlwzpOX14P9zth' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/8AxBDKQTyR0?si=qTGmTVE5AbG0urg6' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Kx03EfVF0pU?si=ga2cI6XNh7JDM4dy' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Incline Bench Preacher Curl');
UPDATE exercises SET video_url = 'https://youtu.be/Ej-Imk_vGeQ?si=XXtAfuJDxAf0G8hk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Bent Over Row');