UPDATE exercises SET video_url = 'https://youtu.be/LfyGMZh-Bz4?si=6Cp5HCRlHxaaAXAk' WHERE LOWER(TRIM(name)) = LOWER('Bar Tuck Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/HDzbviKeH8A?si=B97qZHv-l5DP5Zwg' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/BDYs4d0-dbs?si=xhEemMS0ZwEdNi-P' WHERE LOWER(TRIM(name)) = LOWER('Bar Tuck Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/kw0kXtvOpfU?si=l1qrLXesjuSAv8NK' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Fingertip Full Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/d305HI37Rc0' WHERE LOWER(TRIM(name)) = LOWER('Ring Grip Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Oz--LasDphM?si=JVdkguhnIxf9Ho8X' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/_Jf4hAHEwm8' WHERE LOWER(TRIM(name)) = LOWER('Ring Shoulder Stand');
UPDATE exercises SET video_url = 'https://youtu.be/3cLo1dWPqis' WHERE LOWER(TRIM(name)) = LOWER('Ring Strap Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/nUt-_d3zP2w' WHERE LOWER(TRIM(name)) = LOWER('Ring Strap Handstand Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/olR47A-UOYU?si=XvqzFclDvXSJPmsi' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Straddle Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/lUSmIRNqt9w?si=2Uzz5dQAroAGZKAK' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/V9ButqpLLcw?si=W7rot5ocLsfGP3zd' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/5qjQF8Bwk9Y?si=hKn5hERkDvTWUSxe' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Pike Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/Hx31luas38Q' WHERE LOWER(TRIM(name)) = LOWER('Parallette L Sit to Straddle Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/AVH3_x1LZA4?si=xUfQv7BiQgAH0riW' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/7gLyX3Q1KJA' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Front Lever Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/OFSepehKEsg?si=cACSI6X-vniOrBik' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/9sjQEtGoScA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/CP4kwFLxRYg' WHERE LOWER(TRIM(name)) = LOWER('Ring L Sit Muscle Up');
UPDATE exercises SET video_url = 'https://youtu.be/vJTJFc2wmk4' WHERE LOWER(TRIM(name)) = LOWER('Ring Strict Muscle Up');
UPDATE exercises SET video_url = 'https://youtu.be/ojCvehn5SjY?si=tdD_tXPCt_VXy9h3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/9C-hKwyOaE4?si=SpYmw0aHIO29g-Cj' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ApTlAc-7lGY?si=SjnB0ffZ9Ws6qo9D' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/0D5CejWdGE4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/KPxWt4X3CYQ?si=LHuzEfvY58pZcQ4P' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Inside Pendulum');
UPDATE exercises SET video_url = 'https://youtu.be/keiZFdUgvKQ?si=dkMliNkbyV8fodl2' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/XuFaD1sAVGI?si=TR-XC6iaJP514gda' WHERE LOWER(TRIM(name)) = LOWER('Barbell Snatch Balance');
UPDATE exercises SET video_url = 'https://youtu.be/DRYQDMUVgYE' WHERE LOWER(TRIM(name)) = LOWER('Parallette Straddle Press to Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/Yz0g3nK0UH8?si=uzYt2n3dgbhVRnnW' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase March');
UPDATE exercises SET video_url = 'https://youtu.be/l5n8bNkwXFo?si=N5Nmp5n6RrmLD2uu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase March');
UPDATE exercises SET video_url = 'https://youtu.be/46yupJpHPBM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/x_pMZHT1PJI?si=gXaoVxcFe0j1mtPQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/Iqc40RmX2t8?si=6XNRQXHsREEsYjGr' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/6Yw94hTsI2s?si=oPrzNDtNw4g-Xhy-' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/dSSBwrzbtGI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/H8YHDNCH5-o?si=niOwS0JaOXdOT4Ip' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/fP3L8yqDaYo?si=xq03w4XotIlArOk3' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/wacHvU9ISqQ?si=6Hco-OabboEOEO3N' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/Vg0K1uuNQLI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Eccentric Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/Qoyxwu0i5Og?si=v6_bUX0l76eWrYRZ' WHERE LOWER(TRIM(name)) = LOWER('Parallette Freestanding Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/PUjiG2iQHzk?si=OVi5AVNaOFs0SP5b' WHERE LOWER(TRIM(name)) = LOWER('Ring Gironda Sternum Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/RHj4ErHsJAw?si=ZUMLXqjq5pmMSAf_' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/L0S7ATOR1Rw?si=KpjiKwE_QaiTxnfw' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/AOjVLnxbmHU?si=LVrFAJ6HK8bfJmCb' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/FNsKwVfAF2A?si=ZLDbQY35pGpv6Wk5' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell L Sit Lift Over');
UPDATE exercises SET video_url = 'https://youtu.be/sGgI_gV85Zs?si=0_msxxqLJEv8yQl7' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/R2nuXQJt-08?si=ZZwubaIV-9OycLD5' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/GL4yx2rQpIs?si=lvmUx2j0LaKZx4RZ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/oeyAEgHBVYc?si=mHjzSFPeM2YyoC0H' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/zO8xPAa4-cY?si=bSfD4Gd8EdQ631Hq' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Alternating Lateral Lunge');