UPDATE exercises SET video_url = 'https://youtu.be/-mLzQdVAwlw?si=sQHYkOPNIgOBbsrh' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Power Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/IucshEToDyM?si=ifH3zkJMJVCHypGV' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Squat Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/cL1HxbOBkTs' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Reverse Fly');
UPDATE exercises SET video_url = 'https://youtu.be/a2OQCwG9bd0?si=d_4n3IRKXeYoxBNs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Concentration Curl');
UPDATE exercises SET video_url = 'https://youtu.be/eZAvPxEB5Dw?si=ZrwbDJ6qgGac-wRn' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/c4EhnuYZQI8?si=O-MyHEA_d4DRkcEA' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/UWhyxvCCzhw' WHERE LOWER(TRIM(name)) = LOWER('Cable Wide Grip Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/zLKwAYUmGMc' WHERE LOWER(TRIM(name)) = LOWER('Cable Reverse Grip Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/8hzVLzu-RJk' WHERE LOWER(TRIM(name)) = LOWER('Cable V Grip Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/fHXcyedPCPo?si=haa5Z5z5wbVY6loh' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bicycle Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/0P8dbnUQrJI?si=IoU6OTqa34IekCVQ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Broad Jump');
UPDATE exercises SET video_url = 'https://youtu.be/YvUw_mKMGfQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/MP6yL_KKxYY?si=Q87bAjMVT-uTdGRq' WHERE LOWER(TRIM(name)) = LOWER('Parallette Plank');
UPDATE exercises SET video_url = 'https://youtu.be/88ySRsmla4U?si=HG4Mctbie8EQOKUi' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Swing to Alternating Shoulder Park Squat');
UPDATE exercises SET video_url = 'https://youtu.be/q3cXdiyY7-Q?si=8ulm789f1CXgoDiT' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/ZaDlbm8E8Tg?si=BvNUvyhh8eTuBDsz' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/GUDkOtraHHY?si=rRrpCqPIVW7T-7T5' WHERE LOWER(TRIM(name)) = LOWER('Barbell Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/Sk1vhXhHO_A?si=scaLm9b6g937lMhn' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean to Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/7QUcsq019Qs?si=rxXGikxFs6Y3YwPL' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/XtRq5jzUHqE?si=dBupO-9VrVoLknW-' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/vXTeZah_FjI?si=21zLDY_gy9epZ8bD' WHERE LOWER(TRIM(name)) = LOWER('Barbell Squat Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/t7dkLHdZ9uM?si=2TNd4Es589Vlu5uz' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/_VrAJlhDkIc?si=8vRLbrTcTLygHKZE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Seated Wall Angels');
UPDATE exercises SET video_url = 'https://youtu.be/dB5Wxd_zS80' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/yncmjpwl_9g?si=OTCbmCenqG5BN1WW' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/0Kr9lVl4JQ8?si=bGLAYv480sV-7xjg' WHERE LOWER(TRIM(name)) = LOWER('Suspension Y Raise');
UPDATE exercises SET video_url = 'https://youtu.be/pNuHObBC-rg?si=vkl3Eaw-boo60WvV' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Standing Wall Angels');
UPDATE exercises SET video_url = 'https://youtu.be/AHwcb1JLtp4?si=XfL4K_pZpBu8QsfO' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/RtY9kyhuh5I?si=ryQL7SpLXYab74U9' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/-swSVo8-i4I?si=sEL_AtnfPtYy7b1X' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Duck Walk');
UPDATE exercises SET video_url = 'https://youtu.be/VsgCBIQE8gU?si=1KNObbTrjXSha2sF' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/wQrvCnYb4yw?si=z3YIBbCc8EKvTdgG' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/KpE5v62Qnbk?si=0JFSRtn2gnAhSMeD' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/bYYJ4jQCUtg' WHERE LOWER(TRIM(name)) = LOWER('Suspension Reverse Fly');
UPDATE exercises SET video_url = 'https://youtu.be/2B6WxyLaIrE?si=YFskQesFUqPMQA7s' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/li8Cf-vxDvk?si=xn7C8oJeNgbhkv-d' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/FTRy8SXUJXs?si=9fREcoDrSO9GfdAR' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/0Cwk_wwL6uM?si=N_sqB6NG5HF2Hv7U' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Copenhagen Plank Side Raise');
UPDATE exercises SET video_url = 'https://youtu.be/Tt5O0gfZmr0?si=9wq43SCcrrNE16rB' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Copenhagen Plank with Leg Lift');
UPDATE exercises SET video_url = 'https://youtu.be/Nhvz9EzdJ4U?si=MdnuiWNh7Wkz1qK_' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/7NlIkLqcgnw?si=uIGPB18ukc3iERL2' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Decline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/gI-GqUg47UU?si=GQfpc8cxUMQ4kcui' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/ppmAYXaz0_k' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/3hFzUnWOQLU' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Bicep Curl to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/O2SYdrskhPU?si=RFInB5nFomiISnhm' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/2pN9ascZfGc?si=MWKxU4_8cj6Sv5bs' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/thF_jzznoVk?si=T8bHLGYmbaMBD8uL' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/1Dbd7wStRJg?si=Yx13oEQ5A4kl4YJ5' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/p2Z02O1M18w?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Leg Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/o4VnNZJ_ifM?si=mpuDr1i-66ZFR_7I' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise');