UPDATE exercises SET video_url = 'https://youtu.be/BD5mTDoy2UE?si=00skC1JcPnkjtd86' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/Gi_ccf9-y0k?si=cNFfPXedcyCb_lSv' WHERE LOWER(TRIM(name)) = LOWER('Barbell Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/wRgS5ObhBdQ?si=jFFxWIOs9ZRlGwqN' WHERE LOWER(TRIM(name)) = LOWER('Slider Kettlebell Horn Grip Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/6U-qtYBP-bc?si=-53gPzTz2qX4pX-W' WHERE LOWER(TRIM(name)) = LOWER('Superband Good Morning');
UPDATE exercises SET video_url = 'https://youtu.be/0spHTVOeZ-4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Superband Prone Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/eAklBxVmR6w?si=FCt-1WsfkCKhD2P_' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/03FS1YOetXA?si=owgtdy5Ia3OB0e7K' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Close Grip Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/OfmxKG10F5Q?si=8a3RFQgve9SfI8Mw' WHERE LOWER(TRIM(name)) = LOWER('Barbell Close Grip Incline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/murEjbBNhu4?si=wAJyraPSE67uNMnO' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet March');
UPDATE exercises SET video_url = 'https://youtu.be/WTpKwJlRLK4?si=0pMHaXA8XJ4fldaV' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet March');
UPDATE exercises SET video_url = 'https://youtu.be/LDkPoidjfsA?si=EVv239ngYX2tpMYR' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Overhead March');
UPDATE exercises SET video_url = 'https://youtu.be/tvzoG7Ua05Y?si=-i5BoLWWqI_tGovS' WHERE LOWER(TRIM(name)) = LOWER('Cable Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/zJTqReYQQGo?si=YEkchANMatD1FCxY' WHERE LOWER(TRIM(name)) = LOWER('Single Ring Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/wJvhlGDf1Hc?si=orGFEeLw20_33-Ur' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/ebyvvmmA00k?si=wJN4gwe0omjm34CV' WHERE LOWER(TRIM(name)) = LOWER('Barbell Standing Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/RrL3tkrRefw?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Miniband Thigh Kneeling Side Plank Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/Gala3hWxFTw?si=5Qrh2TKQB1NMQpCG' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/aIyadD7d7OA?si=I96m4yP0SA4lVKvH' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Reverse Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/vJhFJJu7ock?si=fw1wLN_DqI1nQovZ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Dips');
UPDATE exercises SET video_url = 'https://youtu.be/dQcKaPnET_U?si=BnxCG8Nw6jQvo43a' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Incline Bench Powell Raise');
UPDATE exercises SET video_url = 'https://youtu.be/su38T53sj_I?si=cqcEdslivlwvc0tG' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Half Kneeling Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/D4mJTEkNnLY?si=iLZLY-yBoFZVR8GZ' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Good Morning');
UPDATE exercises SET video_url = 'https://youtu.be/uVDzXg1lrLY?si=qhBp6Nh9qXBsFBEK' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/OjBghWkudHk?si=LxwZc1KnuyA20kv-' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/VFFS9y4czO8?si=iICpgUIx3HuQxAXK' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/m7SpIGBcysg?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Foot Elevated Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/rSaWYv37zzE?si=A1Q8ZZrV4BpY2YTj' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/1Yw4YA4cwAo?si=fX6SXG6cfeXhhNQ_' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Squat');
UPDATE exercises SET video_url = 'https://youtu.be/TyxhJBfOh58?si=ExY9V0DPBrWkWCel' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Contralateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/gOht2c4hMzg?si=yTn2j_m1x58wZj-l' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Ipsilateral Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/HLDhxSqMQyE?si=3iYb1Ys4Ld0KFpSn' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Low Hold Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/OEtwgF9fZcM?si=NiXeU6zewA9v0Fkx' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1vL0XkLlP-w?si=hzM0tCpVcWoTpqc7' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/TzuHADj8h4M?si=iwVlpYdKhmpx03MU' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/yX1XqdeaczU?si=-zoUhOUe3G-CUM4q' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/-5W0Wi2_vps?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/OWIhh8vYl-M?si=WNuup7a0fJkVHgbd' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Lfk8pR6zSpY?si=OohC0T89kZMsUcm0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Vfl-OUHFQQo?si=zECktY2dytdpOMdK' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/NlkYG2ZJ0OE?si=oa1-NGoydk-xKSsq' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/vwOrd9umMOc?si=dTiEBNYBRJajSW4a' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/U-z_jIM8Tew?si=SZspUD2oLZXeO5D2' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/iojT0TdeY-Q?si=ROEMSEe_KkOEdMc0' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Zsabw1IsO9I?si=b5LVn94BLkSHKB_5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/MmjIL_vngvw?si=aEO8f0KqC36Pr-Lx' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/kLdLvTsVbeU?si=ncvaPkFaqqmfK76j' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/rWKbV7s0bhc?si=DBfnajIIdfbAlzNg' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/xeeDCg5-Jxw?si=ji2BQOrjjkDkClD5' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/eKSHQsVMOK4?si=5Lej30jpx3r7UZJB' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/wmPn0Mvn1gU?si=J1dYeSMpkYaIcLj8' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Clean to Push Press');