UPDATE exercises SET video_url = 'https://youtu.be/DYsQWSbj7UM?si=XUOYSUKOaqGmOCQP' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Tricep Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/MQOnCts9N9c?si=0NLgrLb84fi_4vxZ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Tricep Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/bN9sXaI7tdg?si=W3RoLGE6wUeZ8kQg' WHERE LOWER(TRIM(name)) = LOWER('Slider Dumbbell Goblet Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/QJ_WNRYaM-s?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Dumbbell Low Hold Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/9IGbUVfZan8?si=FGf_5wCGLmr8DVD_' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/iiQueNJKmVQ?si=Ty5Dh9uswMacl2Jd' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Frog Reverse Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/NqNgdW_cvIg?si=KoSk_5f75bTzur4R' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/SFj46t9F1OQ?si=_kzqwXcEvJtP-gv1' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Bulgarian Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/GkANtw3THOg?si=LWzQCihOFKfrRvJz' WHERE LOWER(TRIM(name)) = LOWER('Slider Sandbag Back Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/PlktrKgFcT0?si=O4YEDtcE-rMg5fLn' WHERE LOWER(TRIM(name)) = LOWER('Miniband Ankle Monster Walk');
UPDATE exercises SET video_url = 'https://youtu.be/q56KJzFPbz4?si=QBb7bgZdSeYK7Q0i' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Front Rack Ipsilateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/W22ESpzYHdY?si=Vh4542ktziwY39x1' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Low Hold Contralateral Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/obc23NwC-3c?si=NHdYgvLBQoFpvdLm' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Incline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/neQw53mbivA?si=4di6VUfOBarrAAWQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/L15snvTU1qY?si=MYRw1-yq79vC87vm' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/iJmHIt3pq5U?si=O6Skib3fQIO2I526' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/cSmvSLAiJUM?si=h-chBAq-PsufLIrW' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Hang Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/VpZwBT07DR4?si=07HCrANRza3gU5O3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Hang Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/BNyymHJvcJc?si=Fwbl__UOgmJahIO5' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Hang Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/DD2ntrZLoEQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Miniband Kneeling Side Plank Clamshell');
UPDATE exercises SET video_url = 'https://youtu.be/TBYwwlojtvE?si=QWpnXUtKvTpFNuv_' WHERE LOWER(TRIM(name)) = LOWER('Miniband Thigh Side Plank Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/gyTX0ttszBs?si=mR6_J7SkVOuRHrQN' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/0EIDVDbzVNo?si=B73itVIXJWWYaH0C' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Single Leg V Up');
UPDATE exercises SET video_url = 'https://youtu.be/XVLaBw4NWe8?si=tFm4FlWxePeCRyh7' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Lateral Lunge Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/LaywjdRLK3c?si=nTMNGy0BPyxW6WR3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Seated Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/k_HORfTCsi0?si=-RDu4SzCjbkXl4P5' WHERE LOWER(TRIM(name)) = LOWER('Plate Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/Cm4HfYm9w3A?si=iRKP7u31KGlnfQZt' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/TiPDApTAJu0?si=dVw4o9DCHCZrIteK' WHERE LOWER(TRIM(name)) = LOWER('Suspension Single Leg Foot Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/YedqbteiWoU?si=rMl_RLv88kcBcMUR' WHERE LOWER(TRIM(name)) = LOWER('Suspension Sissy Squat');
UPDATE exercises SET video_url = 'https://youtu.be/fv3jtm7zP1I?si=Vx6jxC1bB20dsahE' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/xeUVzgEapmQ?si=ieR0dXu6Bem56sNy' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Dead Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/82ZJhsIOF8w?si=uigPvHNUp-5ce1jQ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/tiA23NSUm7A?si=_N2Va66rdUdrcMpD' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/XE7MrZADkr4?si=F2dW-lk_yYLoGHjE' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1VkEZirajQQ?si=4EJltD-xdvd_ifWT' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/SQHyEoZLd1o?si=_TJYUJVzm_zR7ZxZ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lJyMP5H-_pw?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/rzwJACyQNas?si=VKxH9lJuYtpzFxQo' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/0xnBB7_WBpQ?si=DNO9eiIOlnVvq62-' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/dj2zCtnlZEM?si=zXmmDlSwlhudznYC' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/SNtgnXpolPY?si=RQdshbRrgML5pKNu' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/L6KZyggcDjE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Back Rack Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/Qiu_qPGaGYM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Plate Hollow Body Hold');
UPDATE exercises SET video_url = 'https://youtu.be/xxUSV06CkFM?si=I4ywyVcTwGhyUwsk' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/CpQIh8MxCCQ?si=UvCgYzi5mZCUTXaX' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/4_7EUMcoYYY?si=s_ew72Z5lyKk18Er' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/-UVAa92y1r4?si=CIm_rryJMtDs0TPj' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hollow Body Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/h_L7Ntxcgtk?si=g04F5mBJSHow1QbI' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Seesaw Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/N4Y5hWOwDBY?si=TDvtFSl9MGsAg0L6' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/sbGP9VjnjEg?si=QtatKrbr2B5FgS6F' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Arnold Press');