UPDATE exercises SET video_url = 'https://youtu.be/T4Jv__fWjZ8?si=sbUarOu5VD7qBK4s' WHERE LOWER(TRIM(name)) = LOWER('Bar Eccentric Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/HGzu8tvh79U' WHERE LOWER(TRIM(name)) = LOWER('Landmine Half Kneeling Oblique Twist');
UPDATE exercises SET video_url = 'https://youtu.be/uyNR71ZCrho?si=blbw-wn6NHBGbR9y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Bar Dead Hang');
UPDATE exercises SET video_url = 'https://youtu.be/UF_oINIojVQ?si=nyrZ0y91pz4IIfOs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/2kWWWRpk6Co?si=gy0bI1KIAsGs2hhI' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/V3wxOSo53mQ?si=cM14QdTRQfd_FXUt' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/J3JZR2SFknM' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Arm Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/PAFvOAPjKwk' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Single Arm Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/avCA3xXb9hg' WHERE LOWER(TRIM(name)) = LOWER('Landmine Zercher Skater Squat');
UPDATE exercises SET video_url = 'https://youtu.be/h2bPSv9ka_o' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Front Rack Contralateral Reverse Lunge to Shoulder Press');
UPDATE exercises SET video_url = 'https://youtu.be/jLvQenjeus8' WHERE LOWER(TRIM(name)) = LOWER('Landmine Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/x5wWyQ-2k2E?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Landmine Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/rzJse5Ds98k' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Single Leg Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/OCMcVEdK5vw' WHERE LOWER(TRIM(name)) = LOWER('Landmine Tall Kneeling Oblique Twist');
UPDATE exercises SET video_url = 'https://youtu.be/Zb-l68-4KFM' WHERE LOWER(TRIM(name)) = LOWER('Landmine Feet Elevated Russian Twist');
UPDATE exercises SET video_url = 'https://youtu.be/EcUficjayCY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/Ke5Erzd3NjE?si=fOzgTGBaC6CMWfE6' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Tall Kneeling Seesaw Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/e7jkuKuWcZ0' WHERE LOWER(TRIM(name)) = LOWER('Landmine Zercher Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/YZQP6D9LP4E' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/_AEuTTkYzjg' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/glbP_VzHNkw?si=1k1fGSYRRORQv7W8' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/dhDjKmTX8tU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ufsoFnFCqA4' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/RBcrPYSWQb8' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/q7zJZAexRmc' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/vJuyPyyEdTs?si=_MMem5dVaaarfRRu' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Incline Bench Lying Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/eiCMrII3j9k?si=J2G1ZmeiFQDhnfxT' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/vx9j9l18pyE?si=U7boXKing8U74cQZ' WHERE LOWER(TRIM(name)) = LOWER('Slider Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/9VtEoirFmT8?si=B904_aTFyPDoEqMp' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Incline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/XFBsHDastRI?si=rP6H63ZVPOndCThK' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Decline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/N4HLFIr5H4A?si=l2WKwgNX9fExG7xF' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/MkmpHj0T3OQ' WHERE LOWER(TRIM(name)) = LOWER('Suspension Pike');
UPDATE exercises SET video_url = 'https://youtu.be/9PiqAsdkh6Q' WHERE LOWER(TRIM(name)) = LOWER('Suspension Side Plank Reach Through');
UPDATE exercises SET video_url = 'https://youtu.be/BZWoijzyF_4?si=2gKtoX0oa_Lef7o8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Cocoon Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/SFTn_VON9qw' WHERE LOWER(TRIM(name)) = LOWER('Ab Wheel Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/P4cP-juNM1Q' WHERE LOWER(TRIM(name)) = LOWER('Cable Fire Hydrant');
UPDATE exercises SET video_url = 'https://youtu.be/5mkpuBI-2Ls' WHERE LOWER(TRIM(name)) = LOWER('Cable Tall Kneeling Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/RbkVHCMU3xU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bent Knee Reverse Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/VhqEdeeAyvg' WHERE LOWER(TRIM(name)) = LOWER('Parallette Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/o1c9wFYt6FA?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Close Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/_5VJKCjn8YE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/V3hnphPbiAg' WHERE LOWER(TRIM(name)) = LOWER('Parallette Single Leg L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/tVfP2_HkXEc' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Windshield Wiper');
UPDATE exercises SET video_url = 'https://youtu.be/wIkwr6LV9E8?si=WttWmNStYjInstEN' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Tall Kneeling Balance');
UPDATE exercises SET video_url = 'https://youtu.be/4xODTD0UL-o?si=TSlUT4Fa309FslEb' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/bAaaXP2xb8E?si=AOaxE4RzaGKjiq0h' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Kettlebell Suitcase Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/OsP6_mqxBDI?si=Kdp1ECOmqjUFcNM9' WHERE LOWER(TRIM(name)) = LOWER('Slider Kettlebell Horn Grip Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/h9OYpweuJEc' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/EhYVfy1KUUA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/xkL1f4yewf0' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Cyclist Squat');