UPDATE exercises SET video_url = 'https://youtu.be/sdICKS1Hsl8?si=TQcKHRoyYYB_DXgZ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Reverse Mill');
UPDATE exercises SET video_url = 'https://youtu.be/JL7-80LGmmU?si=wgcrQiv7L3ETryrv' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Mill');
UPDATE exercises SET video_url = 'https://youtu.be/aXwilZfmDyo' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/iPSx3HFBDJQ?si=yE7krt1ftsmuaend' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Clean');
UPDATE exercises SET video_url = 'https://youtu.be/vwRppLKenzw?si=lWbUFOXUJgHzwIVl' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Mill');
UPDATE exercises SET video_url = 'https://youtu.be/p8aWK-U6uVQ?si=uIoHZ9IRigICcYkI' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Clubbell Mill');
UPDATE exercises SET video_url = 'https://youtu.be/dAeNDa33dCg?si=DOdJKyHWeDTnUFjC' WHERE LOWER(TRIM(name)) = LOWER('Macebell Alternating 360 to Ballistic Curl');
UPDATE exercises SET video_url = 'https://youtu.be/8mryJ3w2S78?si=feHRqrceUl_6Xatw' WHERE LOWER(TRIM(name)) = LOWER('Bar Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/HRV5YKKaeVw?si=2FwPXMnKZC4QXyAO' WHERE LOWER(TRIM(name)) = LOWER('Bar Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/9JrqgpJfxFs?si=ltubZdnwDPFzi-8r' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Inside Pendulum');
UPDATE exercises SET video_url = 'https://youtu.be/IABFtVxvqdo?si=Krk5vT1xDU9YcRb2' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Swipe');
UPDATE exercises SET video_url = 'https://youtu.be/EZNev-kvl6A?si=GsKx6-ERsaOYXjDd' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Swipe');
UPDATE exercises SET video_url = 'https://youtu.be/pE8PJsWEV7k?si=sXWG_h39gmTbgsNw' WHERE LOWER(TRIM(name)) = LOWER('Bar Scapular Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/SnRUNmL46So?si=LiGATOKJlrhb676E' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Barbarian Squat');
UPDATE exercises SET video_url = 'https://youtu.be/mqZDdpFh1gA?si=5Sz7M4RZJh4kpYFa' WHERE LOWER(TRIM(name)) = LOWER('Bar Skin the Cat');
UPDATE exercises SET video_url = 'https://youtu.be/fyC2FBk2vho?si=9A4Unc4H-ndiHFMC' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/DaKC_BEN5bk?si=-Q3RkXcSiRxscR4n' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/178a2eYjaow?si=5BIFyTIH_gQo8ef1' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Feet Elevated Plank Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/hcB3BdFBk9o?si=NCYoHHaTofHXzx2y' WHERE LOWER(TRIM(name)) = LOWER('Miniband Supine Alternating Hip Flexion');
UPDATE exercises SET video_url = 'https://youtu.be/zlosFkTwleE?si=kPNf5P_AJZd7Sqrn' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/IoGfLT_8cPA?si=0w2tJHQG6XulCr7c' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Half Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/7DW72Ft1LEo?si=kejdZkBMg1CFxl99' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Macebell 10 to 2');
UPDATE exercises SET video_url = 'https://youtu.be/dlqDSzgxNwM?si=_l4eia6JX0ovy0ss' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Arm Bar Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/80WFnCM9Kbo?si=kxvBbrzAla92I6YM' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/KMCZ6Pjg9_k?si=qLUPw94vxQVVs7nw' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Pseudo Planche Lean');
UPDATE exercises SET video_url = 'https://youtu.be/-S5Zz3Hl6a4?si=8XSysf7jjGJx2X07' WHERE LOWER(TRIM(name)) = LOWER('Tire Feet Elevated Decline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/1ZTYpiJJDZ8?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Bench Feet Elevated Decline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/5DTn4Euw6To?si=Qt5r8kEOx3ZW_AO9' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Box Feet Elevated Decline Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/s5VyQrNhEYY?si=9tSA6c3bjeje5MfX' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Feet Elevated Pike Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/J5LEpIZSDS0?si=SukDsqWl5cS7XyF-' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/1PiO_woAgDc?si=-nYhvQs3zKrAR7im' WHERE LOWER(TRIM(name)) = LOWER('Single Ring Rotational Row');
UPDATE exercises SET video_url = 'https://youtu.be/yQToM9xx5Y4?si=AAnvcezbT07hvy8I' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bottoms Up Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/nz99ncuEEt4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/I8WCjE1hTPM?si=riNSekDaoROPTCoF' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bottoms Up Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/2UpONYbzL7c?si=C2NbwmasH7LSljdz' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Alternating Spin to Side Swing Squat');
UPDATE exercises SET video_url = 'https://youtu.be/qFNcznHSBo8?si=5hfD700tGnPBWD3l' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Swipe');
UPDATE exercises SET video_url = 'https://youtu.be/9-gxBjR4OyE?si=Z1RZknDb7e1_9QmD' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/KCyWRqPHOCQ?si=bsZ5UbqpPjccsnEp' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Alternating Side Swing Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Q7rAfqN-NH0?si=zEMPL2_L-ZEUhtLj' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Swing');
UPDATE exercises SET video_url = 'https://youtu.be/jAo338cgsmU?si=1dPZPEL1g1HDUuIC' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ctrXJi1QgEQ?si=O95czG8N3RjyL-Y-' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Back Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/gVYqz0SXsXE?si=WX6MR6-rxwXauydO' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Swing Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6d6b8cx0pO0?si=NKi1a2se39GGFRx3' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Single Leg Standing Double Wave');
UPDATE exercises SET video_url = 'https://youtu.be/FFWOG7Xk5RE?si=JwIHWZtHK6_oDHhQ' WHERE LOWER(TRIM(name)) = LOWER('Landmine V Grip Tall Kneeling Chest Press');
UPDATE exercises SET video_url = 'https://youtu.be/bB3WGOVrqAg?si=Pby2lcyL_Cq98LT9' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Single Leg Standing Clap');
UPDATE exercises SET video_url = 'https://youtu.be/ggVuR079WHM?si=QWRGadB6a4zrJrLz' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Low Switch Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZxjMX7k3Zp0?si=pZtrI1oUYV-FsjgX' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/k6L3kWztcNs?si=GiG4ZJIK5HCWo7Rm' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Low Hold Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/kZdZsw22lU4?si=Y2-3ATlU1R18Acir' WHERE LOWER(TRIM(name)) = LOWER('Suspension Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/pOSa7abtPaQ?si=RtB71Qujc9eZBx-J' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Cossack Squat');