UPDATE exercises SET video_url = 'https://youtu.be/-0FIWmBbo9U' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Alternating Halo to Horn Grip Bottoms Up Squat');
UPDATE exercises SET video_url = 'https://youtu.be/J34xkKOc9GI' WHERE LOWER(TRIM(name)) = LOWER('Ring German Hang Pullout');
UPDATE exercises SET video_url = 'https://youtu.be/jpgvV6wdXVw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/vBkzGpZSEF4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/AeK6i-5gvJ0' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/EF4ep3h5Olk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Dead Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/lWVxdK_AT2s?si=lgWC5CSMGVpQHo9t' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tactical Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/oReUJtUlMGU' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Snatch to Overhead Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/VpURrAKPhcE?si=gSYbC8kpIa5xMxr8' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Snatch to Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/oqjLx5Injps' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean to Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/DeoexkyNuns?si=WrruI69jETw4SBe-' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/S22n8oqcDSY?si=GFs-J_IAwjttVe0y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/kSlZIksA8XQ' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Overhead Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZjNbjnGz1Cg' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/HZbee93OIdo' WHERE LOWER(TRIM(name)) = LOWER('Ring Iron Cross');
UPDATE exercises SET video_url = 'https://youtu.be/F_t7_XRdLbs?si=moBf8_s1adbBBwRY' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/qgNYrUdn1Oo?si=66l491gj5kmLLjA0' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Straddle Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/CGeBvG5XP7U?si=nGM9dXX2v8dyqJA_' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Two Finger Full Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/wcBXDGhqnBU' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Push Up to Alternating Kick Through');
UPDATE exercises SET video_url = 'https://youtu.be/zR7oQp1Ucq8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Standing Walkout Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/cLqkGqiva1M' WHERE LOWER(TRIM(name)) = LOWER('Ring Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/P-dqLz-r5po' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Plate Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/4_RrnWT847k' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Plate Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/QIZ6RXq72ZI' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Pike Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/EqXFl_YxF8k' WHERE LOWER(TRIM(name)) = LOWER('Parallette Feet Elevated Pike Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/eJ9MLnNV6FY' WHERE LOWER(TRIM(name)) = LOWER('Barbell Sots Press');
UPDATE exercises SET video_url = 'https://youtu.be/jcC9NyGLGyg' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/6AzrdFj3Qfc?si=52vAx7-XXfvkSz_l' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Around the World');
UPDATE exercises SET video_url = 'https://youtu.be/Ib-8BOyAgTQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/JtBPG6VeJ9Q' WHERE LOWER(TRIM(name)) = LOWER('Parallette Feet Elevated Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/-2fkjhJfcP8' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Diamond Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/O8WGl4_aYTQ?si=eq7Ylf5fkEliBcxD' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/ekR7MDSWwEQ' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Around the World');
UPDATE exercises SET video_url = 'https://youtu.be/9vZ0CU0dHcE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tall Kneeling Around the World');
UPDATE exercises SET video_url = 'https://youtu.be/fLXYRpxW4FI?si=AjNKRKLLVjzA8Uow' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Waiter Clean');
UPDATE exercises SET video_url = 'https://youtu.be/eH7w5psLPpk?si=XnO0PygbF5fzKCsm' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Waiter Clean');
UPDATE exercises SET video_url = 'https://youtu.be/K8atAt0LaTU?si=9XbtgY4Ntm5G8h7v' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Waiter Clean');
UPDATE exercises SET video_url = 'https://youtu.be/6yF_kl-76jw?si=rsxf0dRezcQc83ke' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Waiter Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/0WjMjA_4SoE?si=J46etYGhA2sshEat' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Waiter Clean to Alternating Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/k6F6ugHyTcA?si=XfnVnbcVgnDkbrFv' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Wrist Curl');
UPDATE exercises SET video_url = 'https://youtu.be/D82M_YDEGJ8' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Hollow Body Chest Press');
UPDATE exercises SET video_url = 'https://youtu.be/PX80lILLVhw?si=vmOhrWhU-xCpO4kr' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Waiter Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/cZSh_cYNXTw' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Start Stop Swing');
UPDATE exercises SET video_url = 'https://youtu.be/qdMDbLUg9_w?si=9t5V4loMJW5VI5mV' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Clean');
UPDATE exercises SET video_url = 'https://youtu.be/87I2gbRgtUI?si=4hUJ0N3X8wu8MMKC' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Windmill');
UPDATE exercises SET video_url = 'https://youtu.be/a4ctQ6GYixo?si=WP2e4CVK5KsFEluY' WHERE LOWER(TRIM(name)) = LOWER('Superband Isometric Split Squat Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/VAFM8kbz8uA?si=UAPSMjiSnRLN3jl3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/jmzZ2wQdXao' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Plate Plyometric Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/KsEBTYuqemI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Single Leg Contralateral Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/LrbAy459jkg?si=UDFXUQgUuwN4hkBz' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Single Leg Bent Over Row');