UPDATE exercises SET video_url = 'https://youtu.be/n2nbRRSMWu4?si=twYL2iJC0VYVj6WF' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Deficit Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/aciS41CW_Mc?si=7y6xxA-nZjKbqeNc' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/52-P8hlrKqg?si=cgixMNp8OmG6lTNQ' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/gm9bWFtRIrk?si=u3u3eYJ1rcURrYwf' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/WQ7QzKOCVLE?si=rWX43WDQ4l8VmtIy' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Power Slam to Burpee');
UPDATE exercises SET video_url = 'https://youtu.be/wRLkttcydwo?si=F9hMpgbV2W-oo3W5' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/cpytZ7Uv85s?si=tl6ya3gXriejNfxT' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Reverse Lunge Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/36kJjDfMHIc?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Isometric Split Squat Hold');
UPDATE exercises SET video_url = 'https://youtu.be/-aMgxO760L4?si=9gx0HVA_RdsNSgFi' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/coFi5XRmTAk?si=b564Njzd_-7c0U9x' WHERE LOWER(TRIM(name)) = LOWER('Barbell Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/_gDcrYTfTCU?si=HKjUJaexuiWSopvB' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/SpwcssWT0p4?si=XhO_l77nZbQDRttr' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/-Jb6VkZ4-tc?si=ZY9K1ZxEHtlV_gOz' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Calf Raise');
UPDATE exercises SET video_url = 'https://youtu.be/guw95GpKkY0?si=TrefJn9gELbrR9t3' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/5zBwce39LfU?si=N9TY90hZ5tEbb3oc' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Rack Pull');
UPDATE exercises SET video_url = 'https://youtu.be/mdf7cMhqRqs?si=P_AYp9PgEajEP_il' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Mid Row');
UPDATE exercises SET video_url = 'https://youtu.be/HHZ1_OZKLII?si=CyqPWtENsIMkdeyn' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/_VZ1cR730rs?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Face Pull to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/apYOwiF9moM?si=bOCR3Ldpx6nSTzj0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Resistance Band Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/8gcpEaHDgsY?si=5iKOYsOZ_3phaShu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Resistance Band Chest Press');
UPDATE exercises SET video_url = 'https://youtu.be/zgV5PpkReuI?si=SX9-dariFRe2W5q5' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Reverse Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/bcond2tqWg0?si=YEuafUqhelVkqYol' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/jnCBdIA1Mno?si=SHMrXoMGIywOdwJ4' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Jumping Jack');
UPDATE exercises SET video_url = 'https://youtu.be/3RbFYYr4RDQ?si=I_hq0oqYA6dy8acI' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Squat Jump Power Slam');
UPDATE exercises SET video_url = 'https://youtu.be/0ieiwGvtCT4?si=eBnoeYkD7iu_tawZ' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Side Slam');
UPDATE exercises SET video_url = 'https://youtu.be/HMK1KfYKJKw?si=8_j1X9PceX4ykwe_' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Squat Jump Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/HGV2NJ6EI3A?si=2zud6P-SPcw2soRh' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope In and Out Squat Jump Power Slam');
UPDATE exercises SET video_url = 'https://youtu.be/5KT8dr-J65U?si=YGtdHgvAy0DIgmt5' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight In and Out Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/cguZ74v0_bE?si=wU22GaKrEc-GA4sw' WHERE LOWER(TRIM(name)) = LOWER('Miniband Thigh In and Out Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/DUf4-qvOroU?si=LFkNn97WQn5oz1m6' WHERE LOWER(TRIM(name)) = LOWER('Miniband Ankle In and Out Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/7cBlrIqHv9o?si=34m2WPXJArSvm8ap' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Isometric Split Squat Power Slam');
UPDATE exercises SET video_url = 'https://youtu.be/0B_lk4-o850?si=g42on5mrqq1cAdUb' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Split Squat Jump Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/nkEeL2ULZGI?si=gDhAhABHiXhwi1Hv' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Alternating Split Squat Jump Power Slam');
UPDATE exercises SET video_url = 'https://youtu.be/4NCYLWTv5Mc?si=OT9LNGr9wS3RbezC' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/13Au7iJ02c8?si=2JaXbdRT8-eAxkx-' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/I4lYPJdwnDg?si=8AgvVHOfdxgX_-zE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Contralateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/MnDpmNYUjbc?si=PjX7rTfbGKTyeip0' WHERE LOWER(TRIM(name)) = LOWER('Superband Pull Apart');
UPDATE exercises SET video_url = 'https://youtu.be/6VDr-3Cmjzw?si=E5zp1jznZ4XPQQ5b' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Tall Kneeling Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/GeA6o0q5ccM?si=958ZadG3-_7ru6ZD' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/kVnIb_csFRw?si=bJHQnzuc7AHgbv9P' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Alternating Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/yQg0mHo-fjQ?si=1wCoEdQg1fR5hmAp' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/Q2eMD8iA-uE?si=aldL_x3sKGW4AXDO' WHERE LOWER(TRIM(name)) = LOWER('Suspension Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/EgG51yB1uZU?si=2CM1EcrBstAp5uOM' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Dumbbell Front Rack Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/90Smo-K6RbY?si=kkqWO4ejlGrcq6rR' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Dumbbell Suitcase Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/jO2Jl9eZpXk?si=u6mgvf-sooUW7DFo' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/G4Vdjr-byjE?si=-fBrLWIYYbgneaLx' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/UjS2nItQCf8?si=tgrOnpPIy1_W-KAt' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Decline Bench Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/ndVUBZ0Bch0?si=pSuQf6mCBer_ztTt' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/6gvmcqr226U?si=Ubc_zUNwRYINkZSI' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/mq_KoN3oCgo?si=zVWL6owtdpddPPFb' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Reverse Grip Bent Over Row');