UPDATE exercises SET video_url = 'https://youtu.be/DYVAGWST-E8?si=NbgYbTD-kINhnv6a' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/qxb36LOiBsc?si=9n0Wr7YfIHCom-_w' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/cmB4dq8MgVk?si=s0qFLxm2MDbbX3dw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/d0gACX9heHk?si=U0snvFOFoR0LH9Ne' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Foot Elevated Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/k4p89WEkl58?si=S4JsgnfzWmFK3l4G' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Low Hold Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/jb9Ge6SP8IA?si=FgQecwjAUfv-teLv' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Carry');
UPDATE exercises SET video_url = 'https://youtu.be/LxdfGyNBuRU?si=x25Sk4tkkLiyY4t2' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/dpVFicHv1PY?si=vQiTWZmKGTiqkHiH' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/kMTZwJnCyjw?si=i72hlbqfO-UgCiPw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Clean');
UPDATE exercises SET video_url = 'https://youtu.be/35IarWLcV0s?si=4lqKX0sntuR1xdEa' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Carry');
UPDATE exercises SET video_url = 'https://youtu.be/dDq_T_H8h5E?si=g4wZK9kvKsPxqI3d' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/5rsJK_z8nkY?si=CD5k3-b0r_JJpfHM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/ULpnqrFng5I?si=fKiyqdRwBpIeRaEx' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/ofwpNdE8yZU?si=T8V1vgUvY8g4tAZ9' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/FKrUoffD_W4?si=d07P0wkoguJqTTRV' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/BoihxFxtsyY?si=kZuvg9gJ179nJ1Xh' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Sumo Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/Pjxd7M8bNU0?si=OeEny9WikOBA8B3P' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase March');
UPDATE exercises SET video_url = 'https://youtu.be/5NV0b_RCWKk?si=LoNm1gGN8i-9QLGP' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Half Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/iVaFwCBP1GM?si=9YPJCkbg5ckTydxm' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Half Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/ymSWvrARnCo?si=wSCDvQEQ8xPtVqbn' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Squat');
UPDATE exercises SET video_url = 'https://youtu.be/VhCVdzYN820?si=07qvbVC4lpqJVZxR' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Squat');
UPDATE exercises SET video_url = 'https://youtu.be/nUjB7PY_ch8?si=qTE38YBxSMytqVEV' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Turkish Get Up');
UPDATE exercises SET video_url = 'https://youtu.be/68d5tiCgUy8?si=QZZ5qWDdvMU5WTQ_' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/dd8M3MLhfjc?si=C40Jnp1OsYedBuT1' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/2EkAq9e24EY?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/T4jp-7X-ai8?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/YSd_xma0esE?si=1LEK7NMY3heh6sof' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/cB7KJj-wqA4?si=_9jU8-LRtzGAT3e7' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Shoulder Clean');
UPDATE exercises SET video_url = 'https://youtu.be/fqzGFACRFWU?si=AdAu_hY9NYrlY8DS' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Over the Shoulder');
UPDATE exercises SET video_url = 'https://youtu.be/X5s18gG7cJc?si=P3v8_2nsYkNdk5D7' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/nNAssQ-4HjA?si=wsCriUBiz-jLsGEk' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Sissy Squat');
UPDATE exercises SET video_url = 'https://youtu.be/GHvRU4-Guuw?si=NJtNhZAAV3mKCcG-' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Sissy Squat');
UPDATE exercises SET video_url = 'https://youtu.be/gBSQOdjjKcc?si=oEXgjHk6m5c-o7MS' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/T2caG3uW8sA?si=AD_PdOw0tzZSfl3p' WHERE LOWER(TRIM(name)) = LOWER('Superband Sissy Squat');
UPDATE exercises SET video_url = 'https://youtu.be/i3qlK1vA0z4?si=LCNdYUF9IbCDWnYm' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/QR1CViFqmmc?si=4Lxq-QIIZ55jvMdx' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lcCEvbAGHC8?si=Ri750XsY--4dDnB_' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/GGjKBYEkZ-A?si=faI8XOKTHMInvAqG' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ntGrVrVVNU0?si=3gtiQIlGPGnTePEX' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ZZ1piVHgy_8?si=I9HrW8xbkLx_UyJS' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Horse Stance Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-IzhFO7lOEU?si=Aftwsw6k2KY2-jf0' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Box Jump');
UPDATE exercises SET video_url = 'https://youtu.be/GFdBbtdUfIU?si=GoMi96WWph2nlJpr' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Lateral Box Jump');
UPDATE exercises SET video_url = 'https://youtu.be/kJqEVtWkYHo?si=aVVrhRraXLtyjPfg' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Lateral Box Jump');
UPDATE exercises SET video_url = 'https://youtu.be/-huk0Idtr6M?si=mLwa_8pXggDXuFgO' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Straddle Planche');
UPDATE exercises SET video_url = 'https://youtu.be/xpa6f9sJmiQ?si=gJH8lq53_OwgQY8F' WHERE LOWER(TRIM(name)) = LOWER('Macebell Single Leg Offset Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/TBtjuZR8Dvo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bird Dog Row');
UPDATE exercises SET video_url = 'https://youtu.be/5G-vWzfeTy4?si=J9YetG0ZnmrQ6H76' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Ipsilateral Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/djxTlEIJdqc?si=IDadWzv3enNpiltr' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Single Leg Standing Hip Flexion');
UPDATE exercises SET video_url = 'https://youtu.be/wrYqfSLWqdE' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/yqtWcL9-1_k?si=q_p_4kAujNiWzCVq' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Carry');