UPDATE exercises SET video_url = 'https://youtu.be/kTJfy28oNFE?si=SfdE8XDz_tYT0vyI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Q_NVo7MW61E?si=3xxOUWjsx7Th2Acq' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/3HxbM0lO3a8?si=7zxP4xa8ZMIRdBAW' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/7TXfixD6LwA?si=ZgzyV23h1nt4RVQQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/lQH6gx3-q8E?si=ySQAsX-z8SQ9haRk' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JLyFg72CCrk?si=dyii9fe_jm4Th1O8' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZqPQvlALHlw?si=B7EklAroPtpJvXvc' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Ipsilateral Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/X13mW_a88Hw?si=bAwJPsrYMO6xCJWC' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/sd6bu56nO9A?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip March');
UPDATE exercises SET video_url = 'https://youtu.be/B6e5b8SY64g?si=OFbYwa08fPFsxurs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/_aiZoy57VFI?si=skTwggqvw_kxkno5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Cross Body Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/xh13VO9_qEA?si=lzogbMJOWGILmMX3' WHERE LOWER(TRIM(name)) = LOWER('Suspension Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/xHvXPam-ZBQ?si=8jfCw-5i-zrJ9hUd' WHERE LOWER(TRIM(name)) = LOWER('Suspension Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/LtTcXXgeRYo?si=80zdQRqZ21dGBf6n' WHERE LOWER(TRIM(name)) = LOWER('Superband Prone Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/qOu-89KQsIg?si=NzRrmfpYz9Rwpoy8' WHERE LOWER(TRIM(name)) = LOWER('Cable Prone Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/e5TRSsFNeug?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Superband Prone Bench Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/DE6BcaMCwJA?si=Q1Lbpg92nykSCfEE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/yCDJmfP1Tr8?si=UDCf5aMfQvMiW-69' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/EznLCDBAPIU' WHERE LOWER(TRIM(name)) = LOWER('Ring Dips');
UPDATE exercises SET video_url = 'https://youtu.be/CQ6VEzQAI7w?si=_nTW1Yq_iP18uBgt' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Arm Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/MeunnPVySSI?si=wuDGH7XuHo-e8M5X' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Aztec Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Bu50PXycHv8?si=SlReQTpVRUbKnVsC' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lyYXfpCV5ys?si=iACRC6Vlz_wbm5zc' WHERE LOWER(TRIM(name)) = LOWER('Slider Dumbbell Goblet Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/3psxN3YA0wg?si=BW-ePbc5Pg6OJ8z6' WHERE LOWER(TRIM(name)) = LOWER('Slider Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/JMGY7iOxEd8?si=VQLmn1jf71I47o_a' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/9b4Aatm0Wvo?si=35ADJVaHZbeshP13' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JGpJCYbDefo?si=NOFTsBroAKhZtrMl' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Foot Elevated Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/gA6gJS2ePGU?si=Ug9x4DfIITtyX9FE' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/CvVSQjBGdxY?si=NNbbzDLa-chZFz3I' WHERE LOWER(TRIM(name)) = LOWER('Ring Maltese');
UPDATE exercises SET video_url = 'https://youtu.be/oZCa8oh_YVI?si=rPzLwq3xpBKREAf7' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/b10GH56Feuc?si=DTF4gfUaKajgDIEP' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/tiuw2sbuhl0?si=TK4HTHPYjPWelq8-' WHERE LOWER(TRIM(name)) = LOWER('Suspension Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/u_cHR3_1IZw?si=oVJaTI9hNpMcfVFW' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Overhead Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/XVsdDBiLk2I?si=yYz392PvLdjJCOy5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/IlABYRygo3w?si=LYId2yiYvpqxybEC' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/ORgVFXTysI8?si=F2L2x6t0lsu7RXmy' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/tKQAKx25kyk?si=CVIu5jUCBGlS-CU4' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/6-K9hgU8YUI?si=eubdVXn2jNhff_kr' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/XSvx131FZ_s?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/sMUQOGVrmQM?si=shRczfTH98OihNfr' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/sb9anlSqH6w?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/863JuZlLiA4?si=Zj6W2E1ana1MwTBv' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/cXHnXTR79Kw?si=HidnQgZQ02ZN6GNc' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/fdt3gkMNv0Y?si=Wmdlb79kZmS0oZof' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/2DiU1YRLDQE?si=klXwkCZb6RsZjZl5' WHERE LOWER(TRIM(name)) = LOWER('Sandbag Front Rack Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/dwL1uWmadTI?si=6anEQDI0eEoOuB0Q' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Ipsilateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/yswpCMZ98OI?si=xOcXSLCrJIH3odmK' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Ipsilateral Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/aFrdGmSHqFI?si=RfqnoOy6-Ppa73et' WHERE LOWER(TRIM(name)) = LOWER('Ring Archer Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/E2s-D009x6E' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Freestanding Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/VVan0yoinV8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Eccentric Straddle Press Handstand');