UPDATE exercises SET video_url = 'https://youtu.be/4xRpGgttca8' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hollow Body Hold');
UPDATE exercises SET video_url = 'https://youtu.be/Wo-pGZst6l0' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Hollow Body Hold');
UPDATE exercises SET video_url = 'https://youtu.be/LXQTkeYPki8' WHERE LOWER(TRIM(name)) = LOWER('Bar Inverted Hanging Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/-p1l0vXTtAU?si=ebEJZJZkoWYTDFbC' WHERE LOWER(TRIM(name)) = LOWER('Slider Double Kettlebell Front Rack Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/IUCoqgdvDxU?si=8xtgp1M-mJqke2mR' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Supine Alternating Single Leg Raise');
UPDATE exercises SET video_url = 'https://youtu.be/q0JVBRHoLz4' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Supine Leg Raise');
UPDATE exercises SET video_url = 'https://youtu.be/q_c5MFYuza4' WHERE LOWER(TRIM(name)) = LOWER('Miniband Bicycle Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/7lfNb_zydvQ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Side Plank Reach Through');
UPDATE exercises SET video_url = 'https://youtu.be/bT8NVeDvuQg?si=paUR-bam-jwd-xPx' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/ZLyOWSPnVrM' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Butterfly Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/fjHQIVIPLHY' WHERE LOWER(TRIM(name)) = LOWER('Slider Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/vB803WCcQDk?si=hXUn4t23jP7Bn6R8' WHERE LOWER(TRIM(name)) = LOWER('Slider Pike');
UPDATE exercises SET video_url = 'https://youtu.be/-ciDJCuTu3A?si=zpBNDJ0Pbp7YfJOm' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Pike');
UPDATE exercises SET video_url = 'https://youtu.be/d64d_6PE9fY' WHERE LOWER(TRIM(name)) = LOWER('Slider Wide Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/O4d3kd1ZLyc?si=xAr_I7jNLwrDm7lL' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/fZZK29dMla0?si=BQpGveG4S8WqLjzv' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Oblique Crunch');
UPDATE exercises SET video_url = 'https://youtu.be/gi38qGKDzXY?si=XCqiGVtu482eeeTP' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/fv6mxdkTT60?si=1AhvmIbGHoW_9tm9' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Leg Knee Tuck');
UPDATE exercises SET video_url = 'https://youtu.be/7skasCMLRL8' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Leg Pike');
UPDATE exercises SET video_url = 'https://youtu.be/k_kXBEjURUA' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/Cf3CaHui43A?si=dFPcP6jQEQECmXmY' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/2WxwO9E93wI' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/z4J188sFD4g' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/JpDDoINkrog' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/cRCXEFhpBEI?si=6A2YpBsXM9WqT6rW' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Glute Bridge Isometric with Alternating Single Leg Extension');
UPDATE exercises SET video_url = 'https://youtu.be/vSpyJR3dA7s?si=voo83Swm5kMbYEwl' WHERE LOWER(TRIM(name)) = LOWER('Miniband Side Lying Clamshell');
UPDATE exercises SET video_url = 'https://youtu.be/bDvFd4EZt8M' WHERE LOWER(TRIM(name)) = LOWER('Miniband Ankle Side Lying Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/NeO0w4Jv4rs?si=zFKHnPvts0-arQgk' WHERE LOWER(TRIM(name)) = LOWER('Miniband Bench Seated Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/oS3cYfl6Bns' WHERE LOWER(TRIM(name)) = LOWER('Miniband Glute Bridge Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/4azLK_5vOqY?si=bceKCFzhvhSW5jXe' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/x4lc8HocO1c' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Dumbbell Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/7IVoH7E4rWo' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/N6t2Fv0SKGc' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Frog Pump');
UPDATE exercises SET video_url = 'https://youtu.be/qJxwJ1e1HxI?si=5y999i_uPybFFDol' WHERE LOWER(TRIM(name)) = LOWER('Cable Glute Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/I7Zwyzr8COk' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Leg Foot Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/bZUGEwxZVks?si=GXDy3dTxYcWMuQpw' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/34fVGXqWWs8' WHERE LOWER(TRIM(name)) = LOWER('Miniband Thigh Lateral Walk');
UPDATE exercises SET video_url = 'https://youtu.be/N4tkpDMlqCQ' WHERE LOWER(TRIM(name)) = LOWER('Miniband Ankle Lateral Walk');
UPDATE exercises SET video_url = 'https://youtu.be/GxqfnFHLH6c' WHERE LOWER(TRIM(name)) = LOWER('Miniband Feet Lateral Walk');
UPDATE exercises SET video_url = 'https://youtu.be/pdP0uJXvc44?si=lpmJ6krZopavsZrJ' WHERE LOWER(TRIM(name)) = LOWER('Miniband Standing Glute Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/5S8SApGU_Lk' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/BMIy2gtjsTI?si=JnJL8ZiliAOk_Ac1' WHERE LOWER(TRIM(name)) = LOWER('Barbell Single Leg Hip Thrust');
UPDATE exercises SET video_url = 'https://youtu.be/LSUPiOJOA6M' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Leg Foot Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/dZNkjqKNUUs' WHERE LOWER(TRIM(name)) = LOWER('Miniband Standing Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/3SOcMYQWbDU' WHERE LOWER(TRIM(name)) = LOWER('Miniband 3 Way Cha Cha');
UPDATE exercises SET video_url = 'https://youtu.be/5D-hSAvpFls?si=2EfexeMUADw51Wu2' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Suitcase Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/saVSMtIttZE?si=qgSuj5ww8uiz2Wkd' WHERE LOWER(TRIM(name)) = LOWER('Cable Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/w5nYnnT1E9s' WHERE LOWER(TRIM(name)) = LOWER('Miniband Wall Sit Hip Abduction');
UPDATE exercises SET video_url = 'https://youtu.be/4DUIY95jX6Y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Half Kneeling Contralateral Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/l3prcz-3FbI?si=qvb-6gLh-aavLGWK' WHERE LOWER(TRIM(name)) = LOWER('Cable Face Pull');