UPDATE exercises SET video_url = 'https://youtu.be/G3yQITNPIz8?si=V_AVSgSWE_RFAsSE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Side Lying Clamshell');
UPDATE exercises SET video_url = 'https://youtu.be/i6WHN9L5uYk?si=YLzKzoCoztvNvlQl&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Incline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/kMmV0thhwnA?si=JAh7-DW4Wpz2xBJd&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Seated Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/jIt8nG02Ss0?si=eVQ-M_zbzpxQN1mL&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Double Cable Decline Bench Chest Fly');
UPDATE exercises SET video_url = 'https://youtu.be/pzWVXEdABFg?si=rDT20cfa7nGutLCH&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/lM33VtF6SCg?si=JG_kyBmQ8H-MspnB&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Slider Plank Jack');
UPDATE exercises SET video_url = 'https://youtu.be/g93DurTL79E?si=BG_2IXTND6t0_DRn&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Plank');
UPDATE exercises SET video_url = 'https://youtu.be/hRWpFtDyofg?si=Xwts69VNdiYCB5-r&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Forearm Plank');
UPDATE exercises SET video_url = 'https://youtu.be/Wkeg0Gr1n7g?si=Xq62yMZ9kUc0lizD&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Side Plank');
UPDATE exercises SET video_url = 'https://youtu.be/MepSU7ua6Dw?si=wDktIQCYf3BtFlRS&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Plank');
UPDATE exercises SET video_url = 'https://youtu.be/7W7yCOrQMsA?si=fMaW2CwMSudtqBx5&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Reverse Grip Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/yTHdkQntOy0?si=MyTLO7RESotzfRsT&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Reverse Grip Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/LyN1Mt53HI4?si=D2E6-rpfLFoTHTc8&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Sled Sprint');