-- Plyometric Exercises Seed Data
-- 85 new plyometric exercises covering: depth/drop jumps, hurdle hops, bounding,
-- pogo hops, single leg hops, CMJ variations, rotational jumps, upper body plyos,
-- burpee variations, agility/reactive drills

INSERT INTO exercises (id, club_id, name, description, body_parts, categories, video_url, tags, options, tracking_type, equipment) VALUES

-- ============================================================
-- DEPTH DROPS / ALTITUDE LANDINGS
-- ============================================================
('ex_plyo_001', NULL, 'Bodyweight Depth Drop', 'Step off box and land softly in athletic position with knees tracking over toes, absorbing force through hips and ankles.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','landing','eccentric','force absorption'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_002', NULL, 'Bodyweight Single Leg Depth Drop', 'Step off box and land on one leg in quarter squat position, stabilising through ankle, knee and hip.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','landing','single leg','eccentric','force absorption'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_003', NULL, 'Bodyweight Altitude Landing', 'Step off elevated platform and land in deep athletic stance, holding the landing position for 2-3 seconds to reinforce deceleration mechanics.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','landing','deceleration','eccentric'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

-- ============================================================
-- DROP JUMPS (land and immediately rebound)
-- ============================================================
('ex_plyo_004', NULL, 'Bodyweight Drop Jump', 'Step off box, land briefly and immediately jump vertically as high as possible, minimising ground contact time.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','power','stretch shortening cycle'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_005', NULL, 'Bodyweight Drop Jump to Broad Jump', 'Step off box, land and immediately rebound forward into a maximal broad jump, combining vertical drop with horizontal power.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','power','horizontal'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_006', NULL, 'Bodyweight Drop Jump to Sprint', 'Step off box, land and immediately rebound into a 10-metre sprint, training the transition from reactive jump to acceleration.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','acceleration','sprint'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

-- ============================================================
-- HURDLE HOPS
-- ============================================================
('ex_plyo_007', NULL, 'Bodyweight Double Leg Hurdle Hop', 'Jump over consecutive hurdles with both feet together, driving knees up and minimising ground contact between hurdles.', ARRAY['Quadriceps','Glutes','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','consecutive','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

('ex_plyo_008', NULL, 'Bodyweight Single Leg Hurdle Hop', 'Hop over consecutive hurdles on one leg, driving the knee up on each rep while maintaining balance and alignment.', ARRAY['Quadriceps','Glutes','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','single leg','consecutive'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

('ex_plyo_009', NULL, 'Bodyweight Lateral Hurdle Hop', 'Stand beside hurdle and jump laterally over it, landing softly and immediately rebounding back. Repeat for prescribed reps.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','lateral','reactive','frontal plane'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

('ex_plyo_010', NULL, 'Bodyweight Single Leg Lateral Hurdle Hop', 'Hop laterally over hurdle on one leg, stabilising on landing before immediately rebounding back over.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','lateral','single leg','reactive'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

('ex_plyo_011', NULL, 'Bodyweight Forward Hurdle Hop', 'Jump forward over a single hurdle, landing in athletic stance. Reset and repeat, focusing on height and distance clearance.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','forward','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

('ex_plyo_012', NULL, 'Bodyweight Consecutive Forward Hurdle Hop', 'Jump forward over a series of hurdles without pausing, using a quick double-leg takeoff and landing between each.', ARRAY['Quadriceps','Glutes','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','forward','consecutive','reactive'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['hurdles']),

-- ============================================================
-- BOUNDING DRILLS
-- ============================================================
('ex_plyo_013', NULL, 'Bodyweight Alternating Bound', 'Drive off one leg and bound forward, landing on the opposite foot with exaggerated arm drive and knee lift, covering maximum distance per stride.', ARRAY['Quadriceps','Glutes','Hamstrings','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','power','horizontal','alternating'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lunge", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_014', NULL, 'Bodyweight Single Leg Bound', 'Perform consecutive single leg bounds on the same leg, driving forward and upward with each hop to maximise horizontal distance.', ARRAY['Quadriceps','Glutes','Hamstrings','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','single leg','horizontal'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lunge", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_015', NULL, 'Bodyweight Power Skip for Height', 'Perform an exaggerated skipping motion driving the knee as high as possible while pushing off the ground explosively for maximum vertical height.', ARRAY['Quadriceps','Glutes','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','power','vertical','skip'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_016', NULL, 'Bodyweight Power Skip for Distance', 'Perform exaggerated skipping motion driving forward for maximum horizontal distance per skip, emphasising powerful hip extension.', ARRAY['Quadriceps','Glutes','Hamstrings','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','power','horizontal','skip'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_017', NULL, 'Bodyweight Lateral Bound', 'Drive off one leg laterally, landing on the opposite leg in a single leg quarter squat. Hold briefly, then bound back.', ARRAY['Quadriceps','Glutes','Abductors','Adductors','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','lateral','frontal plane'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_018', NULL, 'Bodyweight Consecutive Lateral Bound', 'Perform continuous lateral bounds side to side without pausing, minimising ground contact time while covering maximum lateral distance.', ARRAY['Quadriceps','Glutes','Abductors','Adductors','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','lateral','reactive','consecutive'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

-- ============================================================
-- POGO HOPS / ANKLE BOUNCES
-- ============================================================
('ex_plyo_019', NULL, 'Bodyweight Bilateral Pogo Hop', 'With legs straight and stiff ankles, bounce rapidly off the ground using only ankle plantar flexion, keeping ground contact time minimal.', ARRAY['Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','ankle stiffness','pogo'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Calf Raise", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_020', NULL, 'Bodyweight Single Leg Pogo Hop', 'Hop rapidly on one foot using only ankle plantar flexion, maintaining a stiff ankle and straight leg with minimal ground contact.', ARRAY['Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','ankle stiffness','single leg','pogo'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Calf Raise", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_021', NULL, 'Bodyweight Ankle Hop Over Line', 'Hop forward and backward over a line on the ground with stiff ankles and minimal knee bend, focusing on rapid ground contacts.', ARRAY['Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','ankle stiffness','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Calf Raise", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_022', NULL, 'Bodyweight Lateral Ankle Hop Over Line', 'Hop side to side over a line using stiff ankles and minimal knee bend, training lateral reactive ankle stiffness.', ARRAY['Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','ankle stiffness','lateral'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

-- ============================================================
-- SINGLE LEG HOP VARIATIONS
-- ============================================================
('ex_plyo_023', NULL, 'Bodyweight Single Leg Forward Hop', 'Hop forward on one leg for distance, swinging arms to generate momentum and landing softly in a single leg stance.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','forward','horizontal'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_024', NULL, 'Bodyweight Single Leg Lateral Hop', 'Hop laterally on one leg, landing with control and immediately rebounding in the opposite direction.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','lateral','frontal plane'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_025', NULL, 'Bodyweight Single Leg Diagonal Hop', 'Hop diagonally forward on one leg at 45 degrees, alternating between forward-left and forward-right directions.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','diagonal','multi-directional'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_026', NULL, 'Bodyweight Single Leg Multi-Directional Hop', 'Hop in a clock pattern on one leg — forward, diagonal, lateral, backward — challenging stability and reactive strength in all planes.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','multi-directional','reactive'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_027', NULL, 'Bodyweight Single Leg Box Jump Down', 'Step off box and land on a single leg in controlled quarter squat, holding the landing to build eccentric single leg control.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','landing','eccentric'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

-- ============================================================
-- COUNTERMOVEMENT JUMP VARIATIONS
-- ============================================================
('ex_plyo_028', NULL, 'Bodyweight Countermovement Jump with Reach', 'Perform a standard CMJ reaching overhead to a target at peak height, maximising vertical displacement.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','vertical','CMJ'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_029', NULL, 'Bodyweight Countermovement Jump with Rotation', 'Perform CMJ and rotate 90 degrees in the air, landing in athletic stance facing perpendicular to start position.', ARRAY['Quadriceps','Glutes','Calves','Abdominals'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','rotational','CMJ'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Rotational", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_030', NULL, 'Bodyweight Single Leg Countermovement Jump', 'Perform a maximal vertical jump taking off and landing on one leg, using a quick countermovement dip before takeoff.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','vertical','single leg','CMJ'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

-- ============================================================
-- ROTATIONAL / SPECIAL JUMPS
-- ============================================================
('ex_plyo_031', NULL, 'Bodyweight Scissor Jump', 'From a split stance, jump and switch leg positions mid-air in a rapid scissoring motion, landing with opposite foot forward.', ARRAY['Quadriceps','Glutes','Hip Flexors','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','alternating','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lunge", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_032', NULL, 'Bodyweight Star Jump', 'From a quarter squat, explode upward spreading arms and legs into a star shape at peak height, then land back in squat.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Shoulders'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','vertical','explosive'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_033', NULL, 'Bodyweight 180 Degree Jump', 'Perform a vertical jump rotating 180 degrees in the air, landing softly facing the opposite direction.', ARRAY['Quadriceps','Glutes','Calves','Abdominals'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','rotational','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Rotational", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_034', NULL, 'Bodyweight 360 Degree Jump', 'Perform a vertical jump rotating a full 360 degrees, landing in the same position facing the same direction.', ARRAY['Quadriceps','Glutes','Calves','Abdominals'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','rotational','power','advanced'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Rotational", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_035', NULL, 'Bodyweight Lunge Jump', 'From a deep lunge position, jump vertically and switch legs mid-air, landing in a lunge with the opposite leg forward.', ARRAY['Quadriceps','Glutes','Hamstrings','Hip Flexors','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','alternating','lunge'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lunge", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_036', NULL, 'Bodyweight Lateral Jump', 'Jump laterally to one side, landing on both feet in athletic stance. Immediately jump back to the starting position.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','lateral','power','frontal plane'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_037', NULL, 'Bodyweight Depth Jump to Box', 'Step off one box, land and immediately rebound onto a second box of equal or greater height, minimising ground contact time.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','depth','advanced'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_038', NULL, 'Bodyweight Consecutive Box Jump', 'Perform repeated box jumps stepping or jumping down and immediately rebounding onto the box without pausing.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','consecutive','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_039', NULL, 'Bodyweight Seated Box Jump', 'Sit on a box, pause to eliminate stretch reflex, then explode upward to standing or onto a second box using pure concentric power.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','concentric','power','starting strength'], '{"posture": "Seated", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

-- ============================================================
-- UPPER BODY PLYOMETRICS
-- ============================================================
('ex_plyo_040', NULL, 'Bodyweight Clap Push Up', 'Perform an explosive push up, clapping hands together at peak height before landing back in push up position.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','explosive'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_041', NULL, 'Bodyweight Behind the Back Clap Push Up', 'Perform an explosive push up, clapping hands behind the back at peak height before returning to push up position.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','advanced'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_042', NULL, 'Bodyweight Explosive Push Up', 'Perform a push up with maximum force so hands leave the ground at the top, landing softly back in push up position.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','explosive'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_043', NULL, 'Bodyweight Plyometric Push Up to Box', 'Start in push up position on the floor, explode upward and land with hands on an elevated box, then drop back to floor and repeat.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','box'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_044', NULL, 'Bodyweight Depth Push Up', 'Start with hands on two low boxes, drop into push up between them and immediately push explosively back up to the boxes.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','reactive','upper body','depth'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_045', NULL, 'Bodyweight Alternating Single Arm Explosive Push Up', 'Perform explosive push ups alternating between left and right hand elevated on a medicine ball or small box.', ARRAY['Chest','Triceps','Shoulders','Abdominals'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','alternating'], '{"posture": "Prone", "grip": "Flat Palm", "alternating": true, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_046', NULL, 'Medicine Ball Chest Pass', 'Stand facing a wall or partner and explosively throw a medicine ball from chest level using both hands, catching the rebound.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','throw'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_047', NULL, 'Medicine Ball Kneeling Chest Pass', 'From a tall kneeling position, explosively throw a medicine ball from chest level, eliminating lower body contribution to isolate upper body power.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','kneeling','throw'], '{"posture": "Tall Kneeling", "grip": "Neutral", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_048', NULL, 'Medicine Ball Seated Chest Pass', 'Sitting on the floor with legs extended, throw a medicine ball explosively from the chest to a wall or partner.', ARRAY['Chest','Triceps','Shoulders','Abdominals'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','seated','throw'], '{"posture": "Seated Floor", "grip": "Neutral", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_049', NULL, 'Medicine Ball Overhead Throw', 'Hold medicine ball overhead and throw it forward and downward with maximum force, extending through the hips and shoulders.', ARRAY['Shoulders','Back','Abdominals'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','throw','overhead'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Vertical Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_050', NULL, 'Medicine Ball Overhead Backward Throw', 'Stand facing away from target, squat down and explosively throw the medicine ball overhead and backward for maximum distance.', ARRAY['Glutes','Shoulders','Back','Hamstrings'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','throw','overhead','posterior chain'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Hip Extension", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_051', NULL, 'Medicine Ball Rotational Throw', 'Stand perpendicular to wall, rotate through hips and torso and explosively throw the medicine ball into the wall, catching the rebound.', ARRAY['Abdominals','Shoulders','Hip Flexors'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','rotational','throw'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Rotational", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_052', NULL, 'Medicine Ball Scoop Throw', 'Hold medicine ball between legs, squat down and explosively throw it forward and upward using a scooping motion from the hips.', ARRAY['Quadriceps','Glutes','Shoulders','Hamstrings'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','throw','hip extension'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Hip Extension", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_053', NULL, 'Medicine Ball Slam', 'Lift medicine ball overhead and slam it into the ground as hard as possible, using full hip flexion and lat engagement.', ARRAY['Shoulders','Abdominals','Back'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','slam','full body'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Vertical Pull", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_054', NULL, 'Medicine Ball Side Slam', 'Lift medicine ball overhead and slam it diagonally to one side, rotating through the trunk to generate rotational power.', ARRAY['Abdominals','Shoulders','Back'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','slam','rotational'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Rotational", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_055', NULL, 'Medicine Ball Drop and Catch', 'Lie supine with arms extended, have a partner drop a medicine ball which you catch and immediately throw back up as fast as possible.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','reactive','upper body','catch'], '{"posture": "Supine", "grip": "Neutral", "alternating": false, "movementPattern": "Horizontal Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

('ex_plyo_056', NULL, 'Medicine Ball Explosive Floor Press', 'Lie supine holding a medicine ball at chest, explosively press and release the ball upward, catch it and immediately repeat.', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Upper Body','Plyometric'], NULL, ARRAY['plyometric','power','upper body','press'], '{"posture": "Supine", "grip": "Neutral", "alternating": false, "movementPattern": "Vertical Push", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['medicine ball']),

-- ============================================================
-- FULL BODY / BURPEE VARIATIONS
-- ============================================================
('ex_plyo_057', NULL, 'Bodyweight Box Jump Burpee', 'Perform a burpee and immediately jump onto a box at the top of the movement, step down and repeat.', ARRAY['Quadriceps','Glutes','Chest','Shoulders','Calves'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','full body','burpee'], '{"posture": "Standing", "grip": "Flat Palm", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_058', NULL, 'Bodyweight Broad Jump Burpee', 'Perform a burpee and at the top explode forward into a broad jump instead of a vertical jump.', ARRAY['Quadriceps','Glutes','Chest','Shoulders','Hamstrings'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','full body','burpee','horizontal'], '{"posture": "Standing", "grip": "Flat Palm", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_059', NULL, 'Bodyweight Lateral Burpee', 'Perform a burpee and at the top jump laterally over an obstacle before dropping into the next rep.', ARRAY['Quadriceps','Glutes','Chest','Shoulders','Abductors'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','full body','burpee','lateral'], '{"posture": "Standing", "grip": "Flat Palm", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_060', NULL, 'Bodyweight Burpee to Pull Up', 'Perform a burpee under a pull up bar, then jump and perform a pull up at the top of the movement.', ARRAY['Quadriceps','Glutes','Chest','Back','Shoulders'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','full body','burpee','pull'], '{"posture": "Standing", "grip": "Pronated", "alternating": false, "movementPattern": "Vertical Pull", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['pull up bar']),

('ex_plyo_061', NULL, 'Bodyweight Tuck Jump Burpee', 'Perform a burpee and at the top execute a tuck jump, pulling knees to chest at peak height.', ARRAY['Quadriceps','Glutes','Chest','Shoulders','Hip Flexors'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','power','full body','burpee'], '{"posture": "Standing", "grip": "Flat Palm", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_062', NULL, 'Bodyweight Bear Crawl Sprint', 'From quadruped position with knees hovering, sprint forward on hands and feet as fast as possible for a set distance.', ARRAY['Shoulders','Quadriceps','Abdominals','Hip Flexors'], ARRAY['Full Body','Plyometric'], NULL, ARRAY['plyometric','speed','full body','locomotion'], '{"posture": "Knee Hover Quadruped", "grip": "Flat Palm", "alternating": true, "movementPattern": "Anti-Extension", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['bodyweight']),

-- ============================================================
-- AGILITY LADDER DRILLS
-- ============================================================
('ex_plyo_063', NULL, 'Agility Ladder Lateral Shuffle', 'Move laterally through the ladder stepping in and out of each square with quick feet, maintaining low athletic stance.', ARRAY['Calves','Quadriceps','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','lateral','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_064', NULL, 'Agility Ladder Crossover Step', 'Move laterally through the ladder using crossover steps, alternating feet crossing in front and behind.', ARRAY['Calves','Quadriceps','Abductors','Adductors','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','crossover','lateral'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_065', NULL, 'Agility Ladder Ali Shuffle', 'Straddle the ladder and perform a rapid forward shuffle, alternating which foot lands inside each rung.', ARRAY['Calves','Quadriceps','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','speed','coordination'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_066', NULL, 'Agility Ladder Hopscotch', 'Alternate between landing with both feet outside the ladder rung and one foot inside, progressing forward through each square.', ARRAY['Calves','Quadriceps','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','coordination','plyometric'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_067', NULL, 'Agility Ladder Carioca', 'Move laterally through the ladder using carioca footwork — alternating crossover steps in front and behind while moving sideways.', ARRAY['Calves','Quadriceps','Abductors','Adductors','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','carioca','lateral','coordination'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_068', NULL, 'Agility Ladder Single Leg Hop Through', 'Hop through each rung of the ladder on one leg, maintaining balance and speed throughout.', ARRAY['Calves','Quadriceps','Glutes'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','single leg','plyometric'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_069', NULL, 'Agility Ladder Two Feet In Each', 'Run through the ladder placing both feet in each square as quickly as possible, maintaining a forward lean and arm drive.', ARRAY['Calves','Quadriceps','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','speed','coordination'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

('ex_plyo_070', NULL, 'Agility Ladder Lateral In-Out', 'Move laterally, stepping both feet into each rung then both feet out, progressing sideways through the ladder.', ARRAY['Calves','Quadriceps','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','lateral','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['agility ladder']),

-- ============================================================
-- CONE DRILLS
-- ============================================================
('ex_plyo_071', NULL, 'Cone T-Drill', 'Sprint forward to centre cone, shuffle left to cone, shuffle right past centre to far cone, shuffle back to centre, backpedal to start.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_072', NULL, 'Cone 5-10-5 Pro Agility Shuttle', 'Straddle centre line, sprint 5 yards to one side, touch line, sprint 10 yards to the other side, touch line, sprint 5 yards back through centre.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','speed','shuttle'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_073', NULL, 'Cone L-Drill', 'Sprint forward 5 yards, touch cone, sprint back, immediately sprint to far cone and round it in a figure-of-eight pattern.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','acceleration'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_074', NULL, 'Cone W-Drill', 'Sprint diagonally between five cones arranged in a W pattern, planting and changing direction at each cone.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','multi-directional'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_075', NULL, 'Cone Illinois Agility Test', 'Sprint, weave through four central cones, and change direction around end cones in the standard Illinois agility course layout.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings','Abdominals'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','test'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_076', NULL, 'Cone Box Drill', 'Sprint between four cones arranged in a square — forward, lateral shuffle, backpedal, lateral shuffle back to start.', ARRAY['Quadriceps','Glutes','Calves','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','cone drill','change of direction','multi-directional'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

-- ============================================================
-- SHUTTLE RUNS
-- ============================================================
('ex_plyo_077', NULL, 'Suicide Line Drill', 'Sprint to progressively distant lines (foul line, half court, far foul line, end line), touching each line and sprinting back to start.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','conditioning','change of direction','deceleration'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

('ex_plyo_078', NULL, 'Shuttle Run 20m', 'Sprint 20 metres, touch the line, turn and sprint back. Repeat for prescribed reps or duration.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','conditioning','shuttle','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['cones']),

-- ============================================================
-- DOT DRILLS / HEX DRILL
-- ============================================================
('ex_plyo_079', NULL, 'Dot Drill', 'Jump between five dots arranged in a dice-five pattern, performing prescribed footwork sequences as quickly as possible.', ARRAY['Calves','Quadriceps','Glutes'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','reactive','coordination','plyometric'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['bodyweight']),

('ex_plyo_080', NULL, 'Hexagonal Agility Drill', 'Stand in the centre of a hexagon taped on the floor. Jump in and out over each side of the hexagon as fast as possible, completing the full rotation.', ARRAY['Calves','Quadriceps','Glutes','Abductors','Adductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['agility','footwork','reactive','multi-directional','plyometric'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['bodyweight']),

-- ============================================================
-- ADDITIONAL LOWER BODY PLYOS
-- ============================================================
('ex_plyo_081', NULL, 'Bodyweight Repeat Tuck Jump', 'Perform consecutive tuck jumps without pausing between reps, pulling knees to chest each rep and rebounding immediately on landing.', ARRAY['Quadriceps','Glutes','Calves','Hip Flexors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','consecutive','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_082', NULL, 'Bodyweight Triple Broad Jump', 'Perform three consecutive broad jumps without pausing, immediately rebounding forward on each landing for maximum total distance.', ARRAY['Quadriceps','Glutes','Hamstrings','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','horizontal','consecutive','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_083', NULL, 'Bodyweight Single Leg Triple Hop', 'Perform three consecutive forward hops on one leg, maintaining balance and covering maximum distance with each hop.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','single leg','consecutive','horizontal'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_084', NULL, 'Bodyweight Lateral Box Shuffle', 'Stand beside a low box, step up and over it laterally then immediately step back, shuffling back and forth as quickly as possible.', ARRAY['Quadriceps','Glutes','Calves','Abductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','lateral','reactive','speed'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'timed', ARRAY['box']),

('ex_plyo_085', NULL, 'Bodyweight Squat Jump to Box', 'From standing on the floor, perform a squat jump and land on top of the box in a soft squat position.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','power','vertical','box'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_086', NULL, 'Trap Bar Depth Jump', 'Hold trap bar, step off a low platform and upon landing immediately jump as high as possible, using the added load for overload.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','loaded','power'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'weight_reps', ARRAY['trap bar','box']),

('ex_plyo_087', NULL, 'Dumbbell Squat Jump', 'Hold dumbbells at sides and perform a maximal squat jump, landing softly and resetting before the next rep.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','loaded','power','vertical'], '{"posture": "Standing", "grip": "Neutral", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'weight_reps', ARRAY['dumbbells']),

('ex_plyo_088', NULL, 'Bodyweight Stiff Leg Bound', 'Bound forward with minimal knee bend, driving primarily from the hips and ankles to train posterior chain power and ankle stiffness.', ARRAY['Hamstrings','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','posterior chain','ankle stiffness'], '{"posture": "Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Hip Extension", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_089', NULL, 'Bodyweight Depth Jump Lateral', 'Step off box and upon landing immediately jump laterally as far as possible, training reactive lateral power.', ARRAY['Quadriceps','Glutes','Calves','Abductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','reactive','lateral','depth'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['box']),

('ex_plyo_090', NULL, 'Miniband Lateral Bound', 'With miniband around ankles, perform lateral bounds against band resistance, emphasising hip abductor activation on takeoff.', ARRAY['Glutes','Abductors','Quadriceps','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','lateral','banded','resistance'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['miniband']),

('ex_plyo_091', NULL, 'Superband Resisted Broad Jump', 'Attach superband to anchor behind you and perform broad jumps against band resistance, overloading horizontal power production.', ARRAY['Quadriceps','Glutes','Hamstrings','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','resisted','horizontal','power'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['superband']),

('ex_plyo_092', NULL, 'Bodyweight Lateral Bound to Vertical Jump', 'Perform a lateral bound, stabilise on one leg, then immediately explode into a maximal vertical jump, combining frontal and sagittal plane power.', ARRAY['Quadriceps','Glutes','Calves','Abductors'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','combination','lateral','vertical','reactive'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_093', NULL, 'Bodyweight Zigzag Bound', 'Bound forward at alternating 45-degree angles, landing on the outside leg each time and driving diagonally on the next bound.', ARRAY['Quadriceps','Glutes','Abductors','Adductors','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','bounding','multi-directional','diagonal'], '{"posture": "Single Leg Standing", "grip": "No Grip", "alternating": true, "movementPattern": "Lateral", "mechanics": "Plyometric"}'::jsonb, 'reps_only', ARRAY['bodyweight']),

('ex_plyo_094', NULL, 'Weighted Vest Box Jump', 'Wearing a weighted vest, perform box jumps to increase external load while maintaining reactive jump mechanics.', ARRAY['Quadriceps','Glutes','Calves'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','loaded','power','vertical'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'weight_reps', ARRAY['weighted vest','box']),

('ex_plyo_095', NULL, 'Weighted Vest Depth Jump', 'Wearing a weighted vest, step off box and immediately rebound as high as possible, overloading reactive strength.', ARRAY['Quadriceps','Glutes','Calves','Hamstrings'], ARRAY['Lower Body','Plyometric'], NULL, ARRAY['plyometric','loaded','reactive','depth'], '{"posture": "Standing", "grip": "No Grip", "alternating": false, "movementPattern": "Squat", "mechanics": "Plyometric"}'::jsonb, 'weight_reps', ARRAY['weighted vest','box']);
