UPDATE exercises SET video_url = 'https://youtu.be/GBo4Cj8i9VI?si=_ZCYRalndjXZl58y' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Lateral Raise');
UPDATE exercises SET video_url = 'https://youtu.be/_qPQKid-LRs' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Side Lying Shoulder External Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/4cpQr1VbcEU' WHERE LOWER(TRIM(name)) = LOWER('Miniband Standing Shoulder External Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/4Hwcp9HP9D4' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Double Dumbbell Seated Arnold Press');
UPDATE exercises SET video_url = 'https://youtu.be/9s0F9lgTG0E?si=hlzVQJ0I5qgbvM45' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Lateral Raise');
UPDATE exercises SET video_url = 'https://youtu.be/3GFZpOYu0pQ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/AqzDJHxynwo?si=FpgeOvlc1u-WxGMb' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/llSrlpd7TEE?si=7L7ARn0S6ByQmI59' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/bhemEvr0qiM?si=WahKrQS3-uEP1hYU' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Standing Scaption');
UPDATE exercises SET video_url = 'https://youtu.be/qGVLUwKTvTw?si=wziniMZUeqke6bE4' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/zGZrhC_VWIQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Standing Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/Vn1cULRUhZI' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Seated Scaption');
UPDATE exercises SET video_url = 'https://youtu.be/PKgkMmXAVUs' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Double Dumbbell Seated Scaption');
UPDATE exercises SET video_url = 'https://youtu.be/WYezBGuUsdw' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/bgYt7ZgFc9M' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Incline Bench Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/h46ccQsXDEk' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/buP9fSqWcw4?si=-lKec0VHJ1XbZYRH' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Cross Body Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/DPYrHeVKvQA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Incline Bench Preacher Curl');
UPDATE exercises SET video_url = 'https://youtu.be/at2g_OGyuDE' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Crush Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/wrjEdVZrkhk' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Zottman Curl');
UPDATE exercises SET video_url = 'https://youtu.be/DjgrEWlgGaY' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Waiter Curl');
UPDATE exercises SET video_url = 'https://youtu.be/s_5mJUQqQpY?si=4zKcXdHvIHVCrn6n' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Drag Curl');
UPDATE exercises SET video_url = 'https://youtu.be/BXcSLzXrab4?si=KZPHi7uurh7Nb31j' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Hammer Curl');
UPDATE exercises SET video_url = 'https://youtu.be/Z8dcGhS8giQ?si=iQZ35AJwvoHewxyk' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/nipJ27JfpUI' WHERE LOWER(TRIM(name)) = LOWER('Suspension Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/m_UlDFNX4mk?si=FAleOyAOFc4IiSBT' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Tricep Kickback');
UPDATE exercises SET video_url = 'https://youtu.be/yrNR2OK50Lw?si=o9UhhO3HdGYOlRvS' WHERE LOWER(TRIM(name)) = LOWER('Tire Jump');
UPDATE exercises SET video_url = 'https://youtu.be/1DBz3vodUUc?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Tire Jump Through');
UPDATE exercises SET video_url = 'https://youtu.be/juTI6wnRiZ8?si=AItO7HER5TxfhHc9' WHERE LOWER(TRIM(name)) = LOWER('Tire Broad Jump');
UPDATE exercises SET video_url = 'https://youtu.be/4RsPF6KynpE?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Tire Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/JdYIi6Vedy8?si=XLKOd1kgeuZgH3Wp' WHERE LOWER(TRIM(name)) = LOWER('Tire Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/diT5j5QRKhs?si=KBmQGQunZ8mtj5zz' WHERE LOWER(TRIM(name)) = LOWER('Tire Alternating Toe Taps Around the World');
UPDATE exercises SET video_url = 'https://youtu.be/-aBcUgsn8Dc' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/H80_t9poKQo?si=eTIuIU_bwT40hUvJ' WHERE LOWER(TRIM(name)) = LOWER('Tire Lateral Jump Through');
UPDATE exercises SET video_url = 'https://youtu.be/QskOD3ROxGs?si=Vh3moyP5PVPO8sMy' WHERE LOWER(TRIM(name)) = LOWER('Tire Carry');
UPDATE exercises SET video_url = 'https://youtu.be/7h3lG2WnLXg' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/s6ydoB3ktlI' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Close Grip Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/c2D4GkTgyo4?si=s6c03eCCz8TWg7br' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Carry');
UPDATE exercises SET video_url = 'https://youtu.be/-FZcqOBDphU?si=FQJnUQP2TsxKmhRA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/BnLkbAGE4b4?si=mRL2wc8pDdJKZNbY' WHERE LOWER(TRIM(name)) = LOWER('Suspension Bulgarian Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ABtwgwo4zyQ?si=eWDNpXtH8qJ31y72' WHERE LOWER(TRIM(name)) = LOWER('Suspension Bulgarian Split Squat Jump');
UPDATE exercises SET video_url = 'https://youtu.be/JLtXEZAwNxQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Lateral Bear Crawl');
UPDATE exercises SET video_url = 'https://youtu.be/bZYAKXoBXGs?si=HbHeFnXtAvKsYndx' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Step Up Jump');
UPDATE exercises SET video_url = 'https://youtu.be/vX2vagAc8Mw?si=UH9R_7g0TbIQyHja' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Step Up Jump');
UPDATE exercises SET video_url = 'https://youtu.be/4ws-kHR5NaU?si=3YQjL6sBFZ3aL-hW' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/bo6bVNho2v8?si=hNk_wo1PWsqhkRyo' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Close Grip Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/nDGz-drTS1E?si=phIMAk1VibF9KzwH' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Outside Pendulum');
UPDATE exercises SET video_url = 'https://youtu.be/8v5XgK3oeeE?si=kU1NrAcgDEWvlUj6' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Outside Pendulum');
UPDATE exercises SET video_url = 'https://youtu.be/a2RWkUS7ja4?si=MlLBdANbCwT-w0d1' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Close Grip Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/e5aj8hhCPkA' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Tricep Pushdown');