UPDATE exercises SET video_url = 'https://youtu.be/ziQjz1-DmX8?si=8Y9dWdjG-9LfdUJv' WHERE LOWER(TRIM(name)) = LOWER('Bar Archer Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/7Wd45lzZhQk?si=WbC5VTiJ33pRjzDJ' WHERE LOWER(TRIM(name)) = LOWER('Bar L Sit Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/QH0dDfyF7QM?si=W4RMoCz0b-U3zq7d' WHERE LOWER(TRIM(name)) = LOWER('Bar L Sit Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/IJbop150-bY?si=9X5umbrrhrvCZkT0' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean to Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/47WVg_XVE8I?si=4PkmY9S8bnXLI6A5' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Power Clean to Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/8IYt7AtP8BI?si=Mc82QusXSQLbFS6b' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Power Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/50VRLZancXI?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Power Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/ljPUr6K-it4?si=ivG82c-7_tzg3KRy' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Squat Clean to Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/KBpys4KTG5Q?si=HQyyuqWBfXWcY7wV' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Squat Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/t7vqdHxMVGY?si=BMd0xRrTYjoV5zrL' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/Xs5q4IDjTRA?si=v-B326quPWXgDphc' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/tG3t_B6t-88?si=JcYBrgVmlHOaRvf5' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/AvrSSwSSPFI?si=2q2v3SuLMeByGkJK' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Glute Bridge Isometric Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/Pca41QxE7l4?si=HXkK4AvIOETo2UkI' WHERE LOWER(TRIM(name)) = LOWER('Slider Archer Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/bIdsEOkgWTM?si=5aKZj2ofWld4V-Fb' WHERE LOWER(TRIM(name)) = LOWER('Suspension Archer Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Df4Jsk1ayk8?si=IICqh6B9ycW-xmJf' WHERE LOWER(TRIM(name)) = LOWER('Superband Chaos Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/2AwE60IueM0?si=6m0bhquaUgiVawPE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean to Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/s16IX5IJDt0?si=mkoHNGyJw3Pa8PoM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean to Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/Shvnso0RADI?si=bnQTaetZPmjwCpd3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/zBGaxRD-_UQ?si=vN7hcMF7S4eYQB1u' WHERE LOWER(TRIM(name)) = LOWER('Landmine Pivot Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/DJJ03oEDJGU?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Half Kneeling Swing');
UPDATE exercises SET video_url = 'https://youtu.be/3Nb6pMK8__Y?si=5ew2YOh7JxivCONp' WHERE LOWER(TRIM(name)) = LOWER('Heavy Sandbag Bear Hug March');
UPDATE exercises SET video_url = 'https://youtu.be/JyElZdIB29g?si=v2iiDrMxGAq4A9rl' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Dead Clean');
UPDATE exercises SET video_url = 'https://youtu.be/NVWQauhMnRQ?si=UgmuOye7VOzX-UjA' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Dead Clean to Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/KGBRsXKjWOc?si=RnQ_ABDo5MNzq0-i' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Front Rack Contralateral Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/LAjAtHI8zwQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/FVmLcTGmJZ0?si=EDG5LdzfEeiqin-z' WHERE LOWER(TRIM(name)) = LOWER('Plate Overhead Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/efg-AS2o3lM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/LQOGjjbAF6w?si=YO-bbJpBtYiLPA1T' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/ci0s9-U1S50?si=yYac1epKRR8CESOn' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/uT2473eo8Rw?si=1pxHtkIQiIW_apsw' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Goblet Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/PLk0TE6nYag?si=vbbSLrl8kCSWEbLQ' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/gcP-jawjJ0s?si=kFE3ztEzT7nJwF3I' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/vKxoihlGR4A?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bottoms Up Z Press');
UPDATE exercises SET video_url = 'https://youtu.be/ciJ8vZIyapM?si=F5Cq1A6IBA0ElWWo' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/moDnqcjmUnw?si=2L_tGgiIN_WKjnSh' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/GHI2nT9CchQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Reverse Nordic');
UPDATE exercises SET video_url = 'https://youtu.be/jIV6huBUy40?si=LI0qU1gmKWUNaN4X' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Hang Power Clean');
UPDATE exercises SET video_url = 'https://youtu.be/-hApznQV1wg?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Dumbbell Hang Power Clean');
UPDATE exercises SET video_url = 'https://youtu.be/OpEgnt3M98k?si=98bk34oOvELlwHao' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/KuNBOsyKvNs?si=xGQdh89b83Z6zfD1' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/N3HnkJ4Sp2s?si=L6L1BDMG1XO5MO94' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/nijhpzgUUi0?si=OYbqhyHxgBZEG3ZY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Contralateral Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/SEh-o4ousa0?si=f_LvuDf-cSL8gy43' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/KHHTwaBgTqg?si=0-6AOui90rWJD7EE' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/-UtFmeC_gz8?si=Cbn-i607GWj4GbJt' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/cB20h7IpdJQ?si=KBJR-jjHokOwHkYv' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Contralateral Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/h7uCFbFFEpg?si=rYfRpyQwdrzMUPgo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Ipsilateral Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/uWQaD_zDNP8?si=e7uAr4KO-Uxs3C4h' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Alternating Russian Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/T0aGAd4z8_g?si=LLndgNIkangYyqvf' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Russian Step Up');