UPDATE exercises SET video_url = 'https://youtu.be/DS-pvuh8VEo?si=KEDC31EUxCubFjGj' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/iRHrBseKm0k?si=X-TqbB38SGkCSqnE' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/5CxPrNkhm2k' WHERE LOWER(TRIM(name)) = LOWER('Ring Bulgarian Row');
UPDATE exercises SET video_url = 'https://youtu.be/VQKcF1HfsYk' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Rotational Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/kUgzuCAvO3A' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/e8aZdfRK4FE?si=VtO52sSIMj0T-KCF' WHERE LOWER(TRIM(name)) = LOWER('Macebell Ballistic Curl');
UPDATE exercises SET video_url = 'https://youtu.be/JJgOmmqZneM?si=v93qv5Poy03NJqj_' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/2ZYphWzJedw?si=f5GGOhThihsKqIds' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/0sRFLvzcqxw?si=cqK8W0uEQdEUfDAy' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/3_F4oUpYY7Q?si=qgoqjkcK33CSqmX4' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Front Flag Press');
UPDATE exercises SET video_url = 'https://youtu.be/7J_x9uMtr-o?si=2tga8qG4urWcSCMT' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Dead Hang');
UPDATE exercises SET video_url = 'https://youtu.be/yMRbcOd51pA?si=7Hc1xBgOqKKuKw3C' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Suitcase Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/7wCLqLLyHh0?si=hFc7L_yPlG-KnZVg' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/REUDhFnYMYc?si=13Shwx4VKvuvNLZh' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Torch Press');
UPDATE exercises SET video_url = 'https://youtu.be/UU4WhE25JfI?si=6sinMuju_2nUhgZK' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Torch Press');
UPDATE exercises SET video_url = 'https://youtu.be/op9kVnSso6Q' WHERE LOWER(TRIM(name)) = LOWER('Barbell Conventional Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/wQHSYDSgDn8' WHERE LOWER(TRIM(name)) = LOWER('Barbell Sumo Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/zdaEWO0S5HU' WHERE LOWER(TRIM(name)) = LOWER('Barbell Rack Pull');
UPDATE exercises SET video_url = 'https://youtu.be/0Ah-ol5EGlo' WHERE LOWER(TRIM(name)) = LOWER('Barbell Snatch Grip Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/bmRTtzOOiVM' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Hyperextension');
UPDATE exercises SET video_url = 'https://youtu.be/ZPeJ0s8X6Gs' WHERE LOWER(TRIM(name)) = LOWER('Barbell Seated Good Morning');
UPDATE exercises SET video_url = 'https://youtu.be/F8dCjzbed-4' WHERE LOWER(TRIM(name)) = LOWER('Barbell Good Morning');
UPDATE exercises SET video_url = 'https://youtu.be/SszDMOZvFuw' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Sit');
UPDATE exercises SET video_url = 'https://youtu.be/3J99J5NxNSQ?si=Xv_W-o9GzT-nvtVQ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Slide Squat');
UPDATE exercises SET video_url = 'https://youtu.be/lWJ6BujsDYY?si=Hl4kTZutf9b6tDUi' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Wall Slide Squat');
UPDATE exercises SET video_url = 'https://youtu.be/MafftY-3lC0?si=bGTlr29qg0ZvBtT_' WHERE LOWER(TRIM(name)) = LOWER('Suspension Squat');
UPDATE exercises SET video_url = 'https://youtu.be/oRO4ailwZb4' WHERE LOWER(TRIM(name)) = LOWER('Suspension Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/93l0NGCosAE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Squat to Bench');
UPDATE exercises SET video_url = 'https://youtu.be/C_VtOYc6j5c' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Squat');
UPDATE exercises SET video_url = 'https://youtu.be/WRCsxtCfrEE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Hand Assisted Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/tlbTz6IamaE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Walking Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/a-dqF4NL2K4' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Squat');
UPDATE exercises SET video_url = 'https://youtu.be/N5lBa2zMAPI?si=Eth4HWtKMOXBXNx6' WHERE LOWER(TRIM(name)) = LOWER('Miniband Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/VHBOyCCupJ4?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Superband Resisted Skater Jump');
UPDATE exercises SET video_url = 'https://youtu.be/k6Vo8hBLypQ' WHERE LOWER(TRIM(name)) = LOWER('Cable Prone Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/BpwGQP8k7aY' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Candlestick Roll Up Tuck Jump');
UPDATE exercises SET video_url = 'https://youtu.be/iVpVk8x-VDQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Block Pull Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/dLG78_Z9rjM' WHERE LOWER(TRIM(name)) = LOWER('Barbell Box Back Squat');
UPDATE exercises SET video_url = 'https://youtu.be/PzoxegwRlOw' WHERE LOWER(TRIM(name)) = LOWER('Barbell Deficit Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/uYumuL_G_V0' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/6EhYj5eSngY' WHERE LOWER(TRIM(name)) = LOWER('Barbell Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/ultWZbUMPL8' WHERE LOWER(TRIM(name)) = LOWER('Barbell High Bar Back Squat');
UPDATE exercises SET video_url = 'https://youtu.be/KwYJTpQ_x5A' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Clean');
UPDATE exercises SET video_url = 'https://youtu.be/TL8SMp7RdXQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Power Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/LURGDIX3adY?si=fHh3AAX-mZB09HXi' WHERE LOWER(TRIM(name)) = LOWER('Barbell Romanian Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/KXUJxb8hO8U' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/5_t0SsovgW8?si=5Zg1x855TTmrp1cL' WHERE LOWER(TRIM(name)) = LOWER('Barbell Stiff Legged Deadlift');
UPDATE exercises SET video_url = 'https://youtu.be/qiQAsB0x-7k?si=OlWu0ou6Vr0NnuvE' WHERE LOWER(TRIM(name)) = LOWER('Barbell Sumo Back Squat');
UPDATE exercises SET video_url = 'https://youtu.be/qDcniqddTeE?si=G4KPahZUmlQQChZ_' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Pistol Squat');
UPDATE exercises SET video_url = 'https://youtu.be/kRnLZadW5Q0' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Skater Squat');