UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Double Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/TzuHADj8h4M?si=tAyLqN0pCIXqxity'),
  ('Double Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/KIDRnwRAKAY?si=b00pYocO2xqWBGiJ'),
  ('Double Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/JKk87eVdbG8?si=Est-myfua9sI06NN'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/A4SnLhdMKu4?si=AWoi6qQOHivzUZeZ'),
  ('Double Dumbbell Suitcase Alternating Lateral Lunge', 'https://youtu.be/GkgTBlp417A?si=2RKL7GSC-wlwXQrE'),
  ('Double Dumbbell Front Rack Alternating Lateral Lunge', 'https://youtu.be/V-crv5-Tqbg?si=k00dfu1tLmH4-h3a'),
  ('Double Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/Ambx6K-_AfY?si=2pUqPVUnlmZLMMwH'),
  ('Double Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1iT74xBv0LA?si=vNMiZEtQ8W3QCkqc'),
  ('Double Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/8OZUh9sHk-8?si=euVM8-cldcw4zaJf'),
  ('Double Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/eK7AzF0-rt4?si=0L-vfrm5QmGhcV2l'),
  ('Single Arm Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/DbANzYj8EWQ?si=NULTCgfWBvm6vNpX'),
  ('Single Arm Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/kTfl5mhcwso?si=iDo9iOmHhKSZIQlN'),
  ('Single Arm Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/b3ewFBSqc9k?si=l6I7tV4HN4z6vcCS'),
  ('Single Arm Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1uuCmY9bVao?si=0iam54INq6LqKgrV'),
  ('Single Arm Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/RNdGRLDFZ_E?si=ViWm3Cym-_kPAyPr'),
  ('Single Arm Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/y6Z1csYJqI8?si=VJQkALrooI76ZWQ9'),
  ('Double Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/iPBOqxEBcto?si=yJqaSgMnybSQX6Oy'),
  ('Double Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/HFjBFM1Fswo?si=BiUd6crmcvrtRZx2'),
  ('Dumbbell Goblet Alternating Lateral Lunge', 'https://youtu.be/xFvob3P7I74?si=o6y90mzLlkb5kjLo'),
  ('Dumbbell Goblet Alternating Forward Lunge', 'https://youtu.be/MjHkEW-AMQI?si=EyW7vqzwyfCJv1bN'),
  ('Dumbbell Goblet Alternating Reverse Lunge', 'https://youtu.be/YidVOnuiDfc?si=ECuN-ZTMBkyH_maZ'),
  ('Landmine Goblet Alternating Lateral Lunge', 'https://youtu.be/-hWgE1P2aAA?si=7mOaE_-aBxpQNBSX'),
  ('Landmine Goblet Alternating Reverse Lunge', 'https://youtu.be/VI0GDe_doBk?si=U14f8Dk6Ly1aMzBr'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/aopAoW1cmUk?si=EyVEsJC9bLaQC6ND'),
  ('Double Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/QV4DL31Ch94?si=6O9QTMoEB9MtwsZY'),
  ('Single Arm Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/eGKpS3AxCVA?si=-uyv4kyU-FY0yBfB'),
  ('Single Arm Dumbbell Overhead Cyclist Squat', 'https://youtu.be/Fm-EgA1xP4g?si=TXFdciSwYJ3flVng'),
  ('Bodyweight Alternating Lateral Lunge', 'https://youtu.be/FvJS_MSN4Lo?si=Z7h-t5HEEQC6trw6'),
  ('Bodyweight Alternating Forward Lunge', 'https://youtu.be/0RqJM6GM5bg?si=eL5TvNrMzUaI1oOW'),
  ('Bodyweight Alternating Reverse Lunge', 'https://youtu.be/OX0fKkaY6_c?si=T0Ta2iyvXrGIGA7w'),
  ('Double Dumbbell Overhead Squat', 'https://youtu.be/iGLwbS5aHY4?si=f7TNizeYPw8xX1xR'),
  ('Single Arm Dumbbell Overhead Squat', 'https://youtu.be/SokWJEUYgfc?si=OWsmg8u6_2Xz09z9'),
  ('Double Dumbbell Front Rack Bulgarian Split Squat', 'https://youtu.be/6DO1p1pOAwM?si=zeLSk3SSoVkoP_B9'),
  ('Double Dumbbell Overhead Bulgarian Split Squat', 'https://youtu.be/7rGFnvK6KkE?si=SL3VLXM4o_8TDV_0'),
  ('Single Arm Dumbbell Suitcase Contralateral Bulgarian Split Squat', 'https://youtu.be/iylKd9ymBQE?si=D_mNdhDHgU7B8xbD'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Bulgarian Split Squat', 'https://youtu.be/7oQoOglG_cA?si=JLNoB9O2s2KyOAf1'),
  ('Single Arm Dumbbell Front Rack Contralateral Bulgarian Split Squat', 'https://youtu.be/-vKdvtdkRRc?si=CPo0dP5KaIc0TJu5'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Bulgarian Split Squat', 'https://youtu.be/pEZWYmpCzu8?si=i70Ip_o4npwew5bY'),
  ('Suspension Alternating Lateral Lunge', 'https://youtu.be/0bqrj4BimaI?si=03pxBE_5_ozxIivb'),
  ('Bulgarian Bag Back Rack Alternating Lateral Lunge', 'https://youtu.be/fJePN1sD5ok?si=g-YYXG1x8L53Vuv-'),
  ('Bulgarian Bag Back Rack Walking Lunge', 'https://youtu.be/FNr5JBGrJTU?si=bn24rl-sBOt5WTfx'),
  ('Bulgarian Bag Back Rack Alternating Forward Lunge', 'https://youtu.be/a8y1Qwir7YQ?si=izeBmxPLl4E0ekvy'),
  ('Sandbag Front Rack Alternating Lateral Lunge', 'https://youtu.be/0el8H9fy3g0?si=BdlZ75xoh6Xq1wpJ'),
  ('Sandbag Front Rack Walking Lunge', 'https://youtu.be/mGwXPP-QKko?si=pUfEZOZPOOYaTV3n'),
  ('Sandbag Front Rack Alternating Forward Lunge', 'https://youtu.be/1L2HnCKmsRs?si=fIVyc7oXYDkkRzgJ'),
  ('Sandbag Front Rack Alternating Reverse Lunge', 'https://youtu.be/SJe_O4NPU-E?si=OKoj1OGsurlSWTEA'),
  ('Plate Overhead Walking Lunge', 'https://youtu.be/hVIaVvyY-H8?si=HsyRlDh-j--gHbsk'),
  ('Plate Overhead Alternating Forward Lunge', 'https://youtu.be/k6pHuYm2nV8?si=ttotAgiXtgPihuX3'),
  ('Plate Overhead Alternating Reverse Lunge', 'https://youtu.be/X5UicuSpd-g?si=vkWg2RXcC-HFi6Pk'),
  ('Bodyweight Tuck Planche', 'https://youtu.be/VFYZh24e0RI?si=_Vjvy9tWBn4nc7l_'),
  ('Double Kettlebell Push Up to L Sit', 'https://youtu.be/V-157r2C-qU'),
  ('Bar Hanging L Sit', 'https://youtu.be/WHi1bvZLwlw?si=NKvlsqG8aI-wDQfJ'),
  ('Ring Hanging L Sit', 'https://youtu.be/8DMns2IRlg4?si=hbMMsP9DfSOthR7b'),
  ('Single Arm Bar Hanging L Sit', 'https://youtu.be/HvdS2ClV9KU?feature=shared'),
  ('Single Arm Ring Hanging L Sit', 'https://youtu.be/_o_4N2yJwAw?si=Hum3bBKngYoqfDUc'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/CQR7UUijw38?si=ncO4L8hVq2h4htQQ'),
  ('Parallette L Sit Flutter Kicks', 'https://youtu.be/zDRj6Sw6tw8?si=Fp368ZWQaw_YDQay'),
  ('Bodyweight Single Arm Contralateral Single Leg Push Up', 'https://youtu.be/I6f7uUmozDY'),
  ('Parallette Tuck Planche Push Up', 'https://youtu.be/hFHpQAqqMDA'),
  ('Ring Maltese Push Up', 'https://youtu.be/kpOpHoywVKU'),
  ('Bar Advanced Tuck Front Lever Pull Up', 'https://youtu.be/cVdb8oUGKAw?si=tC4dDZ3QsBtE_4_m'),
  ('Bar Gironda Sternum Chin Up', 'https://youtu.be/58QkcGVA12A?si=ddrndE8UqnvYVadB'),
  ('Bar Strict Muscle Up', 'https://youtu.be/t8_M2aHiNDk?si=s9zri6LcdUJrvwbV'),
  ('Bodyweight Tuck Planche Push Up', 'https://youtu.be/U-MgWVM_2-Y?si=-XnkVL5OAVXtyCPu'),
  ('Double Clubbell Asynchronous Mill', 'https://youtu.be/2t7u5sapU1Q?si=KigwClnysDsb8CGJ'),
  ('Bodyweight L Sit', 'https://youtu.be/pO4BH0dKCIY?si=qKwpWcDltQZ0K61z'),
  ('Bodyweight Single Arm L Sit', 'https://youtu.be/l-7PDo_nf-c?si=SV8BnhirXI2QflsN'),
  ('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/X8I4Uq4QgYE?si=0ZNJz2TPEC0nSZaa'),
  ('Single Arm Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/vVElqek25fI?si=4-FGE3vFSRTkYdG4'),
  ('Single Arm Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/oOB02xJgzrA?si=IO-ooFFstcNesTGD'),
  ('Single Arm Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/tildBryP8bI?si=mIky-m7uqR4kMvB3'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Forward Lunge', 'https://youtu.be/q7sQB0_p7XQ?feature=shared'),
  ('Parallette V Sit to Pike Press Handstand', 'https://youtu.be/i3tkgdhZuj0?si=lupWBeLYXNXi2bV0'),
  ('Ring Pseudo Planche Push Up', 'https://youtu.be/f09iB8jbioo?si=MFJiOigiohOtQybY'),
  ('Stability Ball Feet Elevated Glute Bridge', 'https://youtu.be/8Ta_A9vAEGs?si=pSj3gDFijzwcALE4'),
  ('Bodyweight Mountain Climber', 'https://youtu.be/kLh-uczlPLg?si=WfwS9PlCOc9d1t1N'),
  ('Suspension Feet Elevated Mountain Climber', 'https://youtu.be/XiB48dLaB9g?si=RkTU535X9lQ-XULA&amp;utm_source=MTQxZ'),
  ('Bodyweight Straddle L Sit', 'https://youtu.be/XS7Y1jQ-kxs?si=hFDuiao7cTRRHUCT'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/xhyigP6lpAM?feature=shared'),
  ('Bodyweight Cossack Squat', 'https://youtu.be/lyMHR7F8lPA?si=An72TBlVkZQu4GMO'),
  ('Bodyweight Wall Facing Handstand Push Up', 'https://youtu.be/ZDhNSacJLEE?si=aGw3Fw5a7Q34pWuk'),
  ('Ring Pelican Push Up', 'https://youtu.be/4zSzWYRiBGI?si=NqLN5I_ZFwPkfPXM'),
  ('Barbell Back Rack Alternating Step Up', 'https://youtu.be/_iZ9bGw84H8?si=4Ff3XGU-WRY1uN0k'),
  ('Barbell Front Rack Alternating Step Up', 'https://youtu.be/b8ldbeOnJEI?si=PBXslcF1v1YEXgGU'),
  ('Ring Feet Elevated Pelican Push Up', 'https://youtu.be/HdaAXHcN0-M?si=fT7_2ec7wdcSALfm'),
  ('Ring Tuck L Sit', 'https://youtu.be/Vuc-nodHS0Y?si=S81fiCUEtPrZUe6Z'),
  ('Ring Hanging Tuck L Sit', 'https://youtu.be/SLyOG8ujcu0?si=IAzc53JTuuKNMz90'),
  ('Bar Hanging Tuck L Sit', 'https://youtu.be/QA_dH6cjbw0?si=29xMuvVPe0ttRvvK'),
  ('Single Arm Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/LMStE_hD9E4?si=_iskUn08-BQH0mYu'),
  ('Ring Mountain Climber', 'https://youtu.be/5BaV4f58I3c?si=LhV-BmrDvHK1G_uI'),
  ('Ring Feet Elevated Mountain Climber', 'https://youtu.be/kbPOFMH-Ivk?si=ftd7bXesKjVBgNrW'),
  ('Single Arm Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/neuw_JknIms?si=QPBFpV8bvbtlFLfL'),
  ('Ring Dead Hang', 'https://youtu.be/uMcoQ-ijpsk'),
  ('Parallette Kneeling Push Up', 'https://youtu.be/iHR7BprMyEc'),
  ('Clubbell Outside Circle', 'https://youtu.be/9lVJZ8o8nzM?si=4NnTRdg9x60PkNsZ'),
  ('Single Arm Kettlebell Bottoms Up Overhead Alternating Reverse Lunge', 'https://youtu.be/N4GPqbj8Nds?feature=shared'),
  ('Stability Ball T''s Y''s I''s', 'https://youtu.be/1jP1PR9Gls0?si=esOirS5dWd5oUqG0'),
  ('Resistance Band Reverse Fly', 'https://youtu.be/C2wsrjVHvuA'),
  ('Resistance Band Lateral Raise', 'https://youtu.be/1feV0cW5U60?si=e6dhNFXt6CLSbkRE'),
  ('Double Dumbbell Lateral Raise', 'https://youtu.be/XPPfnSEATJA?si=yNFrwT2Aj4G98NVF'),
  ('Double Dumbbell Seated Lateral Raise', 'https://youtu.be/GBo4Cj8i9VI?si=_ZCYRalndjXZl58y'),
  ('Single Arm Dumbbell Side Lying Shoulder External Rotation', 'https://youtu.be/_qPQKid-LRs'),
  ('Miniband Standing Shoulder External Rotation', 'https://youtu.be/4cpQr1VbcEU'),
  ('Stability Ball Double Dumbbell Seated Arnold Press', 'https://youtu.be/4Hwcp9HP9D4'),
  ('Single Arm Cable Lateral Raise', 'https://youtu.be/9s0F9lgTG0E?si=hlzVQJ0I5qgbvM45'),
  ('Double Dumbbell Seated Overhead Press', 'https://youtu.be/3GFZpOYu0pQ'),
  ('Double Dumbbell Overhead Press', 'https://youtu.be/AqzDJHxynwo?si=FpgeOvlc1u-WxGMb'),
  ('Double Dumbbell Shrug', 'https://youtu.be/llSrlpd7TEE?si=7L7ARn0S6ByQmI59'),
  ('Double Dumbbell Standing Scaption', 'https://youtu.be/bhemEvr0qiM?si=WahKrQS3-uEP1hYU'),
  ('EZ Bar Kneeling Rollout', 'https://youtu.be/qGVLUwKTvTw?si=wziniMZUeqke6bE4'),
  ('EZ Bar Standing Rollout', 'https://youtu.be/zGZrhC_VWIQ?feature=shared'),
  ('Double Dumbbell Seated Scaption', 'https://youtu.be/Vn1cULRUhZI'),
  ('Stability Ball Double Dumbbell Seated Scaption', 'https://youtu.be/PKgkMmXAVUs'),
  ('Alternating Double Dumbbell Bicep Curl', 'https://youtu.be/WYezBGuUsdw'),
  ('Alternating Double Dumbbell Incline Bench Bicep Curl', 'https://youtu.be/bgYt7ZgFc9M'),
  ('Alternating Double Dumbbell Hammer Curl', 'https://youtu.be/h46ccQsXDEk'),
  ('Alternating Double Dumbbell Cross Body Hammer Curl', 'https://youtu.be/buP9fSqWcw4?si=-lKec0VHJ1XbZYRH'),
  ('Single Arm Dumbbell Incline Bench Preacher Curl', 'https://youtu.be/DPYrHeVKvQA'),
  ('Dumbbell Crush Grip Bicep Curl', 'https://youtu.be/at2g_OGyuDE'),
  ('Double Dumbbell Zottman Curl', 'https://youtu.be/wrjEdVZrkhk'),
  ('Dumbbell Waiter Curl', 'https://youtu.be/DjgrEWlgGaY'),
  ('Cable Straight Bar Drag Curl', 'https://youtu.be/s_5mJUQqQpY?si=4zKcXdHvIHVCrn6n'),
  ('Cable Rope Hammer Curl', 'https://youtu.be/BXcSLzXrab4?si=KZPHi7uurh7Nb31j'),
  ('Kettlebell Goblet Alternating Lateral Lunge', 'https://youtu.be/Z8dcGhS8giQ?si=iQZ35AJwvoHewxyk'),
  ('Suspension Bicep Curl', 'https://youtu.be/nipJ27JfpUI'),
  ('Double Dumbbell Tricep Kickback', 'https://youtu.be/m_UlDFNX4mk?si=FAleOyAOFc4IiSBT'),
  ('Tire Jump', 'https://youtu.be/yrNR2OK50Lw?si=o9UhhO3HdGYOlRvS'),
  ('Tire Jump Through', 'https://youtu.be/1DBz3vodUUc?feature=shared'),
  ('Tire Broad Jump', 'https://youtu.be/juTI6wnRiZ8?si=AItO7HER5TxfhHc9'),
  ('Tire Step Up', 'https://youtu.be/4RsPF6KynpE?feature=shared'),
  ('Tire Alternating Step Up', 'https://youtu.be/JdYIi6Vedy8?si=XLKOd1kgeuZgH3Wp'),
  ('Tire Alternating Toe Taps Around the World', 'https://youtu.be/diT5j5QRKhs?si=KBmQGQunZ8mtj5zz'),
  ('Dumbbell Seated Overhead Tricep Extension', 'https://youtu.be/-aBcUgsn8Dc'),
  ('Tire Lateral Jump Through', 'https://youtu.be/H80_t9poKQo?si=eTIuIU_bwT40hUvJ'),
  ('Tire Carry', 'https://youtu.be/QskOD3ROxGs?si=Vh3moyP5PVPO8sMy'),
  ('Dumbbell Overhead Tricep Extension', 'https://youtu.be/7h3lG2WnLXg'),
  ('Double Dumbbell Close Grip Floor Press', 'https://youtu.be/s6ydoB3ktlI'),
  ('Barbell Back Rack Carry', 'https://youtu.be/c2D4GkTgyo4?si=s6c03eCCz8TWg7br'),
  ('Single Arm Barbell Suitcase Carry', 'https://youtu.be/-FZcqOBDphU?si=FQJnUQP2TsxKmhRA'),
  ('Suspension Bulgarian Split Squat', 'https://youtu.be/BnLkbAGE4b4?si=mRL2wc8pDdJKZNbY'),
  ('Suspension Bulgarian Split Squat Jump', 'https://youtu.be/ABtwgwo4zyQ?si=eWDNpXtH8qJ31y72'),
  ('Bodyweight Lateral Bear Crawl', 'https://youtu.be/JLtXEZAwNxQ?feature=shared'),
  ('Bodyweight Step Up Jump', 'https://youtu.be/bZYAKXoBXGs?si=HbHeFnXtAvKsYndx'),
  ('Bodyweight Alternating Step Up Jump', 'https://youtu.be/vX2vagAc8Mw?si=UH9R_7g0TbIQyHja'),
  ('Barbell Power Clean to Push Press', 'https://youtu.be/4ws-kHR5NaU?si=3YQjL6sBFZ3aL-hW'),
  ('Double Dumbbell Close Grip Bench Press', 'https://youtu.be/bo6bVNho2v8?si=hNk_wo1PWsqhkRyo'),
  ('Single Arm Clubbell Outside Pendulum', 'https://youtu.be/nDGz-drTS1E?si=phIMAk1VibF9KzwH'),
  ('Clubbell Outside Pendulum', 'https://youtu.be/8v5XgK3oeeE?si=kU1NrAcgDEWvlUj6'),
  ('Double Dumbbell Close Grip Incline Bench Press', 'https://youtu.be/a2RWkUS7ja4?si=MlLBdANbCwT-w0d1'),
  ('Cable Rope Tricep Pushdown', 'https://youtu.be/e5aj8hhCPkA'),
  ('Barbell Incline Push Up', 'https://youtu.be/CKKfNBe687Q'),
  ('Bodyweight Kneeling Push Up', 'https://youtu.be/TBpk09QuVN8'),
  ('Suspension Push Up', 'https://youtu.be/cp_Hl7qd7CI?si=Tw8VVXnhtyW9vra4'),
  ('Suspension Chest Fly', 'https://youtu.be/ELmdfR9JvEA'),
  ('Stability Ball Double Dumbbell Chest Fly', 'https://youtu.be/pHsw9uHVXWA?si=0LlXNPKcyTKyfgU4'),
  ('Stability Ball Dumbbell Pullover', 'https://youtu.be/TI1gb3GFUVA'),
  ('Double Dumbbell Incline Bench Chest Fly', 'https://youtu.be/JSDpq14vCZ8?si=DX2UhxTVlOLFkyF3'),
  ('Suspension Low Row', 'https://youtu.be/hULU2N_9qjk?si=XmozOzBr-Uny0t4A'),
  ('Tire Flip', 'https://youtu.be/44E5KRVFWVQ?si=M9W-NS9JbwJV8hDU'),
  ('Tire In and Out Squat Jump', 'https://youtu.be/4h3cIxkFwlI?si=s_iXYmvt1ljfSFML'),
  ('Kettlebell Goblet Alternating Forward Lunge', 'https://youtu.be/wkMhmQ5wVWY?si=kFZCkvoaBfUNdjvU'),
  ('Double Dumbbell Suitcase Feet Elevated Calf Raise', 'https://youtu.be/UCfMPCfug60?si=hzjhqnpt1-9bHCWt'),
  ('Double Dumbbell Suitcase Calf Raise', 'https://youtu.be/wsOcmGYOn3M?si=2w1Cs0RdcdjnHLYG'),
  ('Suspension Mid Row', 'https://youtu.be/W-nnq0Ks1A0'),
  ('Double Dumbbell Seated Calf Raise', 'https://youtu.be/3ZRe_QpvRPg?si=X5ees0OsHDogPrA9'),
  ('Barbell Seated Calf Raise', 'https://youtu.be/hv00OCqm0HI?feature=shared'),
  ('Bodyweight Hand Assisted Feet Elevated Calf Raise', 'https://youtu.be/JUDbOvgH6AQ?si=p3CkDDLIlKjuufVF'),
  ('Bodyweight Hand Assisted Calf Raise', 'https://youtu.be/HwG4_WIMB7g?si=ly2SGRWM5lHuzOHF'),
  ('Bodyweight Calf Raise', 'https://youtu.be/tg3HcGWhGN8?si=i7ZBKBUTgTovDmeO'),
  ('Bodyweight Hand Assisted Foot Elevated Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=gPxN6_F1w9qQdHvy'),
  ('Bodyweight Hand Assisted Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=M_cdEJeEYZLJJD6j'),
  ('Bodyweight Single Leg Calf Raise', 'https://youtu.be/AWBGE0PlYkI?si=INJvlHfbZ6BpG0RT'),
  ('Kettlebell Goblet Alternating Reverse Lunge', 'https://youtu.be/Q8s5KVgRjsI?si=LU2DAUzkwtjOm87N'),
  ('Double Kettlebell L Sit Flutter Kicks', 'https://youtu.be/bNmYhWaTtDE?si=0pRJsSgsFQN8tX9D'),
  ('Double Dumbbell Front Rack Calf Raise', 'https://youtu.be/nDJ9cjw2J7Y?feature=shared'),
  ('Barbell Back Rack Feet Elevated Calf Raise', 'https://youtu.be/-zJsdaS13fk'),
  ('Tire Mountain Climber', 'https://youtu.be/-ouYHaP9g9g?si=qc9f_XLeK0tBdsDc'),
  ('Bodyweight Wall Supported Tibialis Raise', 'https://youtu.be/nQKgHwi8W9E?si=h2cdsN6y8_YWkxWd'),
  ('Cable Seated Tibialis Raise', 'https://youtu.be/XPrwraNV8zU?si=uYKDsDSy6F1lqx7L'),
  ('Cable Seated Single Leg Tibialis Raise', 'https://youtu.be/tSDRe05L18Q?si=tzWWp_aDlp6K7_QS'),
  ('Kettlebell Goblet Walking Lunge', 'https://youtu.be/oV97EckMQlo?si=-UB0G60JaIQ6f-4v'),
  ('Dumbbell Seated Tibialis Raise', 'https://youtu.be/2amvxbpU20c?si=ymK8PzcHyFCMv-oX'),
  ('Kettlebell Horn Grip Alternating Lateral Lunge', 'https://youtu.be/hP0wET7bCog?si=trU9Rde7VACKCuEn'),
  ('Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/w6vfiCgfbXA?si=RhaJhv_PYjW4LLj5'),
  ('Double Dumbbell Seated Feet Elevated Calf Raise', 'https://youtu.be/W5FNgQSaDfU?si=mrb4anmAuXMyWfuC'),
  ('Barbell Seated Feet Elevated Calf Raise', 'https://youtu.be/TyJOknODp8g?si=lIKKdyiWkncjpZtZ'),
  ('Kettlebell Horn Grip Alternating Forward Lunge', 'https://youtu.be/fZeR04SyMnM?si=PcC3GMitpRy-d_N5'),
  ('Tire Leg Press', 'https://youtu.be/YtKIXuPCj1M?si=ng5HKT4Y_EUFLk95'),
  ('Cable Isometric Split Squat Pallof Press', 'https://youtu.be/zMR-P_9GGKE?feature=shared'),
  ('Bodyweight Isometric Split Squat Calf Raise', 'https://youtu.be/pM_ycFCgDxU?si=YT2fo22-rIu4kKPM'),
  ('Bodyweight Isometric Split Squat Foot Elevated Calf Raise', 'https://youtu.be/mdl2K7zkcQ8?si=HIQ62ZGgxGxvMCfb'),
  ('Kettlebell Horn Grip Alternating Reverse Lunge', 'https://youtu.be/hn0H9wrT7I0?si=2puOZbS5dzRQTGh6'),
  ('Kettlebell Horn Grip Walking Lunge', 'https://youtu.be/d7cVOMtyjS8?si=-LwL939gyb_zs3lu'),
  ('Single Arm Dumbbell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise', 'https://youtu.be/xASrMCHjL4M?si=-Ue1QOKJH5pRPoTH'),
  ('Bodyweight Squat Jump', 'https://youtu.be/YGGq0AE5Uyc?si=or6Xddi0YaAkHuXV'),
  ('Double Dumbbell Suitcase Alternating Step Up', 'https://youtu.be/R61TjoYofDE?si=sA8kbakWIt24ow1A'),
  ('Double Dumbbell Front Rack Step Up', 'https://youtu.be/hKLIHPXmPA4?si=mk9hkktF_4qw0okV'),
  ('Cable V Grip Seated Low Row', 'https://youtu.be/EhAho9Szp-0'),
  ('Resistance Band Half Kneeling Face Pull', 'https://youtu.be/pxnaBaRRZiY'),
  ('Bodyweight Prone Cobra', 'https://youtu.be/NZSBjpVpvw8?si=lyk8zIAtzX2ETUc_'),
  ('Barbell Hang Power Snatch', 'https://youtu.be/-mLzQdVAwlw?si=sQHYkOPNIgOBbsrh'),
  ('Barbell Hang Squat Snatch', 'https://youtu.be/IucshEToDyM?si=ifH3zkJMJVCHypGV'),
  ('Double Dumbbell Seated Reverse Fly', 'https://youtu.be/cL1HxbOBkTs'),
  ('Single Arm Dumbbell Seated Concentration Curl', 'https://youtu.be/a2OQCwG9bd0?si=d_4n3IRKXeYoxBNs'),
  ('Alternating Double Dumbbell Seated Bicep Curl', 'https://youtu.be/eZAvPxEB5Dw?si=ZrwbDJ6qgGac-wRn'),
  ('Alternating Double Dumbbell Front Raise', 'https://youtu.be/c4EhnuYZQI8?si=O-MyHEA_d4DRkcEA'),
  ('Cable Wide Grip Lat Pulldown', 'https://youtu.be/UWhyxvCCzhw'),
  ('Cable Reverse Grip Lat Pulldown', 'https://youtu.be/zLKwAYUmGMc'),
  ('Cable V Grip Lat Pulldown', 'https://youtu.be/8hzVLzu-RJk'),
  ('Bodyweight Bicycle Crunch', 'https://youtu.be/fHXcyedPCPo?si=haa5Z5z5wbVY6loh'),
  ('Bodyweight Broad Jump', 'https://youtu.be/0P8dbnUQrJI?si=IoU6OTqa34IekCVQ'),
  ('Bodyweight Forearm Plank', 'https://youtu.be/YvUw_mKMGfQ?feature=shared'),
  ('Parallette Plank', 'https://youtu.be/MP6yL_KKxYY?si=Q87bAjMVT-uTdGRq'),
  ('Clubbell Swing to Alternating Shoulder Park Squat', 'https://youtu.be/88ySRsmla4U?si=HG4Mctbie8EQOKUi'),
  ('Single Arm Dumbbell Bench Press', 'https://youtu.be/q3cXdiyY7-Q?si=8ulm789f1CXgoDiT'),
  ('Double Dumbbell Bench Press', 'https://youtu.be/ZaDlbm8E8Tg?si=BvNUvyhh8eTuBDsz'),
  ('Barbell Split Jerk', 'https://youtu.be/GUDkOtraHHY?si=rRrpCqPIVW7T-7T5'),
  ('Barbell Power Clean to Split Jerk', 'https://youtu.be/Sk1vhXhHO_A?si=scaLm9b6g937lMhn'),
  ('Double Dumbbell Incline Bench Press', 'https://youtu.be/7QUcsq019Qs?si=rxXGikxFs6Y3YwPL'),
  ('Barbell Power Jerk', 'https://youtu.be/XtRq5jzUHqE?si=dBupO-9VrVoLknW-'),
  ('Barbell Squat Jerk', 'https://youtu.be/vXTeZah_FjI?si=21zLDY_gy9epZ8bD'),
  ('Double Kettlebell Bent Over Row', 'https://youtu.be/t7dkLHdZ9uM?si=2TNd4Es589Vlu5uz'),
  ('Bodyweight Seated Wall Angels', 'https://youtu.be/_VrAJlhDkIc?si=8vRLbrTcTLygHKZE'),
  ('Double Kettlebell Shrug', 'https://youtu.be/dB5Wxd_zS80'),
  ('Bodyweight Alternating Split Squat Jump', 'https://youtu.be/yncmjpwl_9g?si=OTCbmCenqG5BN1WW'),
  ('Suspension Y Raise', 'https://youtu.be/0Kr9lVl4JQ8?si=bGLAYv480sV-7xjg'),
  ('Bodyweight Standing Wall Angels', 'https://youtu.be/pNuHObBC-rg?si=vkl3Eaw-boo60WvV'),
  ('Double Kettlebell Mountain Climber', 'https://youtu.be/AHwcb1JLtp4?si=XfL4K_pZpBu8QsfO'),
  ('Bodyweight Split Squat Jump', 'https://youtu.be/RtY9kyhuh5I?si=ryQL7SpLXYab74U9'),
  ('Bodyweight Duck Walk', 'https://youtu.be/-swSVo8-i4I?si=sEL_AtnfPtYy7b1X'),
  ('Barbell Front Rack Split Squat', 'https://youtu.be/VsgCBIQE8gU?si=1KNObbTrjXSha2sF'),
  ('Barbell Overhead Split Squat', 'https://youtu.be/wQrvCnYb4yw?si=z3YIBbCc8EKvTdgG'),
  ('Double Dumbbell Split Jerk', 'https://youtu.be/KpE5v62Qnbk?si=0JFSRtn2gnAhSMeD'),
  ('Suspension Reverse Fly', 'https://youtu.be/bYYJ4jQCUtg'),
  ('Double Dumbbell Decline Bench Press', 'https://youtu.be/2B6WxyLaIrE?si=YFskQesFUqPMQA7s'),
  ('Single Arm Dumbbell Split Jerk', 'https://youtu.be/li8Cf-vxDvk?si=xn7C8oJeNgbhkv-d'),
  ('Single Arm Kettlebell Bottoms Up Snatch', 'https://youtu.be/FTRy8SXUJXs?si=9fREcoDrSO9GfdAR'),
  ('Bodyweight Copenhagen Plank Side Raise', 'https://youtu.be/0Cwk_wwL6uM?si=N_sqB6NG5HF2Hv7U'),
  ('Bodyweight Copenhagen Plank with Leg Lift', 'https://youtu.be/Tt5O0gfZmr0?si=9wq43SCcrrNE16rB'),
  ('Double Dumbbell Chest Fly', 'https://youtu.be/Nhvz9EzdJ4U?si=MdnuiWNh7Wkz1qK_'),
  ('Double Dumbbell Decline Bench Chest Fly', 'https://youtu.be/7NlIkLqcgnw?si=uIGPB18ukc3iERL2'),
  ('Double Kettlebell Suitcase Calf Raise', 'https://youtu.be/gI-GqUg47UU?si=GQfpc8cxUMQ4kcui'),
  ('Dumbbell Crush Grip Bent Over Row', 'https://youtu.be/ppmAYXaz0_k'),
  ('Dumbbell Crush Grip Bicep Curl to Overhead Press', 'https://youtu.be/3hFzUnWOQLU'),
  ('Dumbbell Crush Grip Overhead Press', 'https://youtu.be/O2SYdrskhPU?si=RFInB5nFomiISnhm'),
  ('Dumbbell Crush Grip Floor Press', 'https://youtu.be/2pN9ascZfGc?si=MWKxU4_8cj6Sv5bs'),
  ('Dumbbell Crush Grip Overhead Tricep Extension', 'https://youtu.be/thF_jzznoVk?si=T8bHLGYmbaMBD8uL'),
  ('Bodyweight Single Leg Hip Thrust', 'https://youtu.be/1Dbd7wStRJg?si=Yx13oEQ5A4kl4YJ5'),
  ('Stability Ball Single Leg Hip Thrust', 'https://youtu.be/p2Z02O1M18w?feature=shared'),
  ('Single Arm Kettlebell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise', 'https://youtu.be/o4VnNZJ_ifM?si=mpuDr1i-66ZFR_7I'),
  ('Cable V Grip Seated Floor Lat Pulldown', 'https://youtu.be/wo-YhhSpEJI'),
  ('Battle Rope Alternating Wave', 'https://youtu.be/ZujykKeVZpM'),
  ('Cable Rope Tall Kneeling Tricep Pushdown', 'https://youtu.be/fjYbHu5oXn0?si=h7OFn1fToKpfmC3B'),
  ('Bodyweight Feet Elevated Calf Raise', 'https://youtu.be/VuvZCiSMw_A?si=wJFjWj_7127inskf'),
  ('Stability Ball Reverse Hyperextension', 'https://youtu.be/ujcZZ0kLEmY?si=Vb7GDY3_NgNICWqW'),
  ('Bodyweight Frog Reverse Hyperextension', 'https://youtu.be/zH8QN413Vuo?si=htM_QtEmupefpV2z'),
  ('Bodyweight Reverse Hyperextension', 'https://youtu.be/UP44YFNMF4A?si=ymXfKPXP3jXmkT4j'),
  ('Cable Rope Tall Kneeling Low to High Chop', 'https://youtu.be/dz0OxCiLkjI?si=-FrxaHRLjT-KzMPb'),
  ('Bodyweight V Up', 'https://youtu.be/7UVgs18Y1P4?si=o0GvxxE-1wAYvgfE'),
  ('Slider Barbell Back Rack Reverse Lunge', 'https://youtu.be/svmnL4VOmdQ?si=LsXy5ZYYQ72FtD7F'),
  ('Slider Reverse Lunge', 'https://youtu.be/X9swqObTGJw?si=Qpxrkq0cR0xf5eiU'),
  ('Barbell Push Jerk', 'https://youtu.be/VrHNJXoSyXw'),
  ('Barbell Power Clean to Push Jerk', 'https://youtu.be/LtoksZKesMA?si=rSvsSk9ilVqlS937'),
  ('Barbell Squat Clean to Push Jerk', 'https://youtu.be/GqAEuwXQXRU?si=a2lQdD8ZT7OeBRNX'),
  ('Single Arm Kettlebell Outside Swing', 'https://youtu.be/sEerteQ9q8Y?si=eO7tUCscpuCkcIez'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge Pass Through', 'https://youtu.be/61BWrwBMUlk?si=zXjflLRvn7EaFnuR'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge Pass Through', 'https://youtu.be/6flBwO_bKB8?si=_cijIvoTOn2fDR7y'),
  ('Single Arm Kettlebell Contralateral Forward Lunge Snatch', 'https://youtu.be/T6QWzXtiHVk?si=6Qx4S0Y9YS8kR-E8'),
  ('Single Arm Kettlebell Alternating Forward Lunge Snatch', 'https://youtu.be/yVbXFUpxZDo?si=fGc1RAIfM6JUdZ4B'),
  ('Double Kettlebell Overhead Press', 'https://youtu.be/IfGxPcgiTmY'),
  ('Cable Straight Bar Bicep Curl', 'https://youtu.be/F3Y03RnVY8Y?si=8uzaga9fPI14rc9M'),
  ('Double Kettlebell Glute Bridge Isometric Floor Press', 'https://youtu.be/hEEUpEwRE7g?si=x48upd1YMj1w_xrR'),
  ('Slider Single Arm Dumbbell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/MAiTY-4x82Q?si=zKIXO7qWRH9Fp9yh'),
  ('Slider Double Dumbbell Front Rack Reverse Lunge', 'https://youtu.be/RoS53TjR2QY?si=6bemyT1DeK6D_ziA'),
  ('Slider Double Dumbbell Suitcase Reverse Lunge', 'https://youtu.be/jo1G9aygVIY?si=rDCyU7nAR0DQrhQr'),
  ('Slider Double Dumbbell Overhead Reverse Lunge', 'https://youtu.be/t27p0HCStHg?si=P5VidxzYpMaxRdyY'),
  ('Double Dumbbell Hammer Curl', 'https://youtu.be/fM0TQLoesLs?si=Jdgh0xyXpZA-KwyM'),
  ('Alternating Double Dumbbell Bench Press', 'https://youtu.be/-umNkuKth1U?si=17upb868pBHT1MIg'),
  ('Slider Landmine Shoulder Contralateral Reverse Lunge', 'https://youtu.be/EKtY3UJFmTg?si=_1L9MCgCQ4f1c_fB'),
  ('Slider Single Arm Landmine Suitcase Contralateral Reverse Lunge', 'https://youtu.be/XUrqwdRtU54?si=i9PTTagf_EVKwx0j'),
  ('Suspension Squat Jump', 'https://youtu.be/NcyZj45wcnY?si=cwEgFB3aBkfIjMQy'),
  ('Alternating Double Dumbbell Incline Bench Press', 'https://youtu.be/xt1UdzhkMfY?si=OIM1LWctboVJi66d'),
  ('Alternating Double Dumbbell Decline Bench Press', 'https://youtu.be/XuYszvlq1Zk?si=cRt_Xb7fwOGFU40U'),
  ('Miniband Glute Bridge', 'https://youtu.be/Zr2RLjIjCN0?si=CFxCFwgSlgd_2sCv'),
  ('Alternating Double Dumbbell Top Down Bench Press', 'https://youtu.be/LD5vanDs9G4?si=beAWPFWY1Y8shTBO'),
  ('Alternating Double Dumbbell Top Down Incline Bench Press', 'https://youtu.be/oPk0SGlvX98?si=AjZmhQyk03HHYgPO'),
  ('Alternating Double Dumbbell Top Down Decline Bench Press', 'https://youtu.be/Ztg7B04oVXU?si=KGYDSnNrZiBMfVab'),
  ('Bar Dead Hang', 'https://youtu.be/4RqNGRVaTUQ?si=geYUBIdFOo8AzeHT'),
  ('Trap Bar Deadlift', 'https://youtu.be/FYx76NSijfU?si=SQ4p_SUWbJGUlk0N'),
  ('Trap Bar Staggered Stance Deadlift', 'https://youtu.be/UfCzhPWBmhU?si=PEQal1FTSXhdUQED'),
  ('Resistance Band Alternating Bicep Curl', 'https://youtu.be/E-6iFVLC66I?si=HTrleCkD1HyCvWuq'),
  ('Landmine Goblet Alternating Curtsy Lunge', 'https://youtu.be/XLnOFLtWCaU?feature=shared'),
  ('Barbell Overhead Alternating Curtsy Lunge', 'https://youtu.be/VrOZZjPvj84?si=nwwNU54x-itcb4Ha'),
  ('Barbell Back Rack Alternating Curtsy Lunge', 'https://youtu.be/zUV4jRr6DPk?si=WdsGqclPVPcWvX9C'),
  ('Barbell Zercher Alternating Curtsy Lunge', 'https://youtu.be/-CSU1ZIDcRs?si=r1puJp7Mv2H5UpDs'),
  ('Trap Bar Suitcase Carry', 'https://youtu.be/df-MeZsxCAM?si=DWozx3zEr924L2oN'),
  ('Trap Bar Romanian Deadlift', 'https://youtu.be/2L_LpH_IIbc?si=bI9uPdiltgD6G9Mf'),
  ('Resistance Band Bicep Curl', 'https://youtu.be/xE20IwkSELc?si=FM0m4qOgocoDEdDz'),
  ('Resistance Band Chest Press', 'https://youtu.be/Rn-hf5iauTc?si=9JMXffEInfAmWfNH'),
  ('Resistance Band Alternating Chest Press', 'https://youtu.be/m3wEZExvGCY?si=qPi52D7LtCC72Ccj'),
  ('Trap Bar Deficit Deadlift', 'https://youtu.be/n2nbRRSMWu4?si=twYL2iJC0VYVj6WF'),
  ('Trap Bar Bulgarian Split Squat', 'https://youtu.be/aciS41CW_Mc?si=7y6xxA-nZjKbqeNc'),
  ('Trap Bar Squat Jump', 'https://youtu.be/52-P8hlrKqg?si=cgixMNp8OmG6lTNQ'),
  ('Resistance Band Chest Fly', 'https://youtu.be/gm9bWFtRIrk?si=u3u3eYJ1rcURrYwf'),
  ('Battle Rope Power Slam to Burpee', 'https://youtu.be/WQ7QzKOCVLE?si=rWX43WDQ4l8VmtIy'),
  ('Resistance Band Low Row', 'https://youtu.be/wRLkttcydwo?si=F9hMpgbV2W-oo3W5'),
  ('Battle Rope Alternating Reverse Lunge Alternating Wave', 'https://youtu.be/cpytZ7Uv85s?si=tl6ya3gXriejNfxT'),
  ('Bodyweight Isometric Split Squat Hold', 'https://youtu.be/36kJjDfMHIc?feature=shared'),
  ('Bodyweight Split Squat', 'https://youtu.be/-aMgxO760L4?si=9gx0HVA_RdsNSgFi'),
  ('Barbell Frog Pump', 'https://youtu.be/coFi5XRmTAk?si=b564Njzd_-7c0U9x'),
  ('Barbell Front Rack Calf Raise', 'https://youtu.be/_gDcrYTfTCU?si=HKjUJaexuiWSopvB'),
  ('Barbell Back Rack Calf Raise', 'https://youtu.be/SpwcssWT0p4?si=XhO_l77nZbQDRttr'),
  ('Trap Bar Calf Raise', 'https://youtu.be/-Jb6VkZ4-tc?si=ZY9K1ZxEHtlV_gOz'),
  ('Barbell Zercher Cyclist Squat', 'https://youtu.be/guw95GpKkY0?si=TrefJn9gELbrR9t3'),
  ('Trap Bar Rack Pull', 'https://youtu.be/5zBwce39LfU?si=N9TY90hZ5tEbb3oc'),
  ('Resistance Band Mid Row', 'https://youtu.be/mdf7cMhqRqs?si=P_AYp9PgEajEP_il'),
  ('Resistance Band Face Pull', 'https://youtu.be/HHZ1_OZKLII?si=CyqPWtENsIMkdeyn'),
  ('Resistance Band Face Pull to Overhead Press', 'https://youtu.be/_VZ1cR730rs?feature=shared'),
  ('Single Arm Resistance Band Low Row', 'https://youtu.be/apYOwiF9moM?si=bOCR3Ldpx6nSTzj0'),
  ('Single Arm Resistance Band Chest Press', 'https://youtu.be/8gcpEaHDgsY?si=5iKOYsOZ_3phaShu'),
  ('Resistance Band Reverse Grip Bicep Curl', 'https://youtu.be/zgV5PpkReuI?si=SX9-dariFRe2W5q5'),
  ('Resistance Band Hammer Curl', 'https://youtu.be/bcond2tqWg0?si=YEuafUqhelVkqYol'),
  ('Battle Rope Jumping Jack', 'https://youtu.be/jnCBdIA1Mno?si=SHMrXoMGIywOdwJ4'),
  ('Battle Rope Squat Jump Power Slam', 'https://youtu.be/3RbFYYr4RDQ?si=I_hq0oqYA6dy8acI'),
  ('Battle Rope Alternating Side Slam', 'https://youtu.be/0ieiwGvtCT4?si=eBnoeYkD7iu_tawZ'),
  ('Battle Rope Squat Jump Alternating Wave', 'https://youtu.be/HMK1KfYKJKw?si=8_j1X9PceX4ykwe_'),
  ('Battle Rope In and Out Squat Jump Power Slam', 'https://youtu.be/HGV2NJ6EI3A?si=2zud6P-SPcw2soRh'),
  ('Bodyweight In and Out Squat Jump', 'https://youtu.be/5KT8dr-J65U?si=YGtdHgvAy0DIgmt5'),
  ('Miniband Thigh In and Out Squat Jump', 'https://youtu.be/cguZ74v0_bE?si=wU22GaKrEc-GA4sw'),
  ('Miniband Ankle In and Out Squat Jump', 'https://youtu.be/DUf4-qvOroU?si=LFkNn97WQn5oz1m6'),
  ('Battle Rope Isometric Split Squat Power Slam', 'https://youtu.be/7cBlrIqHv9o?si=34m2WPXJArSvm8ap'),
  ('Battle Rope Alternating Split Squat Jump Alternating Wave', 'https://youtu.be/0B_lk4-o850?si=g42on5mrqq1cAdUb'),
  ('Battle Rope Alternating Split Squat Jump Power Slam', 'https://youtu.be/nkEeL2ULZGI?si=gDhAhABHiXhwi1Hv'),
  ('Single Arm Kettlebell Front Rack Contralateral Cossack Squat', 'https://youtu.be/4NCYLWTv5Mc?si=OT9LNGr9wS3RbezC'),
  ('Resistance Band Cuban Press', 'https://youtu.be/13Au7iJ02c8?si=2JaXbdRT8-eAxkx-'),
  ('Single Arm Kettlebell Overhead Contralateral Cossack Squat', 'https://youtu.be/I4lYPJdwnDg?si=8AgvVHOfdxgX_-zE'),
  ('Superband Pull Apart', 'https://youtu.be/MnDpmNYUjbc?si=PjX7rTfbGKTyeip0'),
  ('Resistance Band Tall Kneeling Face Pull', 'https://youtu.be/6VDr-3Cmjzw?si=E5zp1jznZ4XPQQ5b'),
  ('Resistance Band Overhead Press', 'https://youtu.be/GeA6o0q5ccM?si=958ZadG3-_7ru6ZD'),
  ('Resistance Band Alternating Overhead Press', 'https://youtu.be/kVnIb_csFRw?si=bJHQnzuc7AHgbv9P'),
  ('Alternating Double Dumbbell Overhead Press', 'https://youtu.be/yQg0mHo-fjQ?si=1wCoEdQg1fR5hmAp'),
  ('Suspension Skull Crusher', 'https://youtu.be/Q2eMD8iA-uE?si=aldL_x3sKGW4AXDO'),
  ('Slider Double Dumbbell Front Rack Lateral Lunge', 'https://youtu.be/EgG51yB1uZU?si=2CM1EcrBstAp5uOM'),
  ('Slider Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/90Smo-K6RbY?si=kkqWO4ejlGrcq6rR'),
  ('Double Dumbbell Skull Crusher', 'https://youtu.be/jO2Jl9eZpXk?si=u6mgvf-sooUW7DFo'),
  ('Double Dumbbell Incline Bench Skull Crusher', 'https://youtu.be/G4Vdjr-byjE?si=-fBrLWIYYbgneaLx'),
  ('Double Dumbbell Decline Bench Skull Crusher', 'https://youtu.be/UjS2nItQCf8?si=tgrOnpPIy1_W-KAt'),
  ('Dumbbell Crush Grip Skull Crusher', 'https://youtu.be/ndVUBZ0Bch0?si=pSuQf6mCBer_ztTt'),
  ('Double Dumbbell Bent Over Row', 'https://youtu.be/6gvmcqr226U?si=Ubc_zUNwRYINkZSI'),
  ('EZ Bar Reverse Grip Bent Over Row', 'https://youtu.be/mq_KoN3oCgo?si=zVWL6owtdpddPPFb'),
  ('Single Arm Dumbbell Bent Over Row', 'https://youtu.be/ma__uqUlYmE?si=Yw6Iw4KOA3T7mJeL'),
  ('Single Arm Dumbbell Knee Supported Row', 'https://youtu.be/ZRSGpBUVcNw?si=x3MRv2xRNjCc6s42'),
  ('Dumbbell Pullover', 'https://youtu.be/owr5y-s6-Qk?si=gd2Nfg1PVMbahXjx'),
  ('Dumbbell Incline Bench Pullover', 'https://youtu.be/LQEag7MKXSs?si=vVcujNN4QVFLQ71H'),
  ('Tire Incline Push Up', 'https://youtu.be/sYpuz37bK2k?si=UpMtMbHU8GOboER_'),
  ('Bodyweight Eccentric Push Up', 'https://youtu.be/4JJB2m4AuO8?si=NqYITu6_1fcaAbn7'),
  ('Double Dumbbell Bicep Curl', 'https://youtu.be/HnHuhf4hEWY?si=WSqsCA9Khdbz3ag0'),
  ('Double Dumbbell Incline Bench Bicep Curl', 'https://youtu.be/aG7CXiKxepw?si=FH8eUTIYzp_z04m0'),
  ('Double Dumbbell Seated Hammer Curl', 'https://youtu.be/4hKyhFBeclI?si=OrpNWuwGzVfolESP'),
  ('Alternating Double Dumbbell Seated Hammer Curl', 'https://youtu.be/YW9citXbrQc?si=5VFsuGIAvF6WHm17'),
  ('Double Dumbbell Incline Bench Hammer Curl', 'https://youtu.be/1Z6XiaBxwHQ?si=Da0lptFOFg_s0tyV'),
  ('Single Arm Dumbbell Half Kneeling Windmill', 'https://youtu.be/c0LP3YIO4vY?si=w_DOEV2ERQmctiSb'),
  ('Alternating Double Dumbbell Incline Bench Hammer Curl', 'https://youtu.be/Z_oWLq9uQZI?feature=shared'),
  ('Double Dumbbell Cyclist Thruster', 'https://youtu.be/qoswYkyJG-I?si=Jigh3MmNt7IIj-BA'),
  ('Kettlebell Goblet Pistol Squat', 'https://youtu.be/JS5HxlkWZzU?si=gKhPydrLwgHeGTcO'),
  ('Kettlebell Horn Grip Alternating Pistol Squat', 'https://youtu.be/WGCrIXBHteQ?si=lcLSwZ_90St3r6W4'),
  ('Single Arm Dumbbell Bent Press', 'https://youtu.be/4cCItXCsEDo?si=xrvm1LxY3e8jhStd'),
  ('Double Dumbbell Seated Zottman Curl', 'https://youtu.be/FG6Y_r6-DJM?si=2qExXvynTbOnna2u'),
  ('Cable Straight Bar Tricep Pushdown', 'https://youtu.be/LXkCrxn3caQ?si=24dygODdgdRhEqJK'),
  ('Cable Straight Bar Reverse Grip Tricep Pushdown', 'https://youtu.be/GqK6WrZEyEk?si=JPCXXCLg2YG3rQa7'),
  ('Alternating Double Dumbbell Zottman Curl', 'https://youtu.be/2IBxr91kSI8?si=NutPVlDJSpcDczLP'),
  ('Alternating Double Dumbbell Seated Zottman Curl', 'https://youtu.be/GIGFFYAKG6M?si=5QEN9x3BJwkxTal7'),
  ('Dumbbell Crush Grip Tall Kneeling Overhead Tricep Extension', 'https://youtu.be/9kib4kUJJ1A?si=KTQ4D8iMokjT6LqW'),
  ('Single Arm Dumbbell Overhead Press', 'https://youtu.be/156_Z9969FQ?si=bmP-isrzfk-iAjdj'),
  ('Single Arm Dumbbell Seated Overhead Press', 'https://youtu.be/9DB2kibw0os?si=-BYlQ8gHAlszJaDo'),
  ('Double Dumbbell Seated Bicep Curl', 'https://youtu.be/40w4sx4FAVU?si=i0K5ruXclQupBuxc'),
  ('Double Dumbbell Incline Bench Zottman Curl', 'https://youtu.be/o9w3-CMPRxQ?si=nSVQxRbx2GvgZi-u'),
  ('Alternating Double Dumbbell Incline Bench Zottman Curl', 'https://youtu.be/Xakexn9Y5Oo?si=YY664vMjXBLBT2Ha'),
  ('Alternating Double Dumbbell Seated Overhead Press', 'https://youtu.be/Z4fmeY-GQ8o?si=jZD1QoPzdXBx4Hd8'),
  ('Double Kettlebell Floor Press', 'https://youtu.be/GC0TS5XuuAA?si=1gRhkWItRmgaTYmb'),
  ('Single Arm Kettlebell Floor Press', 'https://youtu.be/P_ijh09h23s?si=U9pK9AQYG1xx2yxE'),
  ('Alternating Double Kettlebell Floor Press', 'https://youtu.be/Uf1jY-575lo?si=pKedIxKhmO0-sY6O'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Cossack Squat', 'https://youtu.be/S1-SPv3YXG8?si=QCE1ikc3-Mg60u3x'),
  ('Dumbbell Crush Grip Seated Overhead Tricep Extension', 'https://youtu.be/o_3RHmSwIgE?si=jrBjCATOeTuvtWzq'),
  ('Alternating Double Kettlebell Bent Over Row', 'https://youtu.be/jdx2kl5K0Ps?si=ABHltAh0E_8BUz7i'),
  ('Battle Rope Double Wave', 'https://youtu.be/mTZENozi5x4?si=Us7_yx5MJoQLZHhO'),
  ('Double Dumbbell Front Raise', 'https://youtu.be/67-J94MVJUg?si=TUVKne9uaJdYMy3x'),
  ('Double Dumbbell Incline Bench Prone Lateral Raise', 'https://youtu.be/e8K9KPGcwr8?si=HpsrB1akXMIU8ANX'),
  ('Dumbbell Crush Grip Seated Bicep Curl', 'https://youtu.be/xZKMteV7T6I?si=r_V-HvZTiORRBmxM'),
  ('Double Dumbbell Incline Bench Prone Hammer Curl', 'https://youtu.be/P-QvV7zOHjw?si=suRdks_sCJLNPIKX'),
  ('Alternating Double Dumbbell Incline Bench Prone Hammer Curl', 'https://youtu.be/N_eGFKGR7ZQ?si=J-4OOQpNwgwM0LrL'),
  ('Single Arm Dumbbell Incline Bench Press', 'https://youtu.be/1RdiI_ta3CY?si=ELtb0jc2iPVUiqNN'),
  ('Single Arm Dumbbell Decline Bench Press', 'https://youtu.be/SisxAKThq70?si=tJqclsa9iiqndA6R'),
  ('Single Arm Kettlebell Bottoms Up Copenhagen Plank', 'https://youtu.be/l2Hu2D3z84w?si=H3JslwI5uQK49RTu'),
  ('Double Dumbbell Floor Press', 'https://youtu.be/3u2DR9HL0tY?si=3Bcig3xQ4BI89qLa'),
  ('Alternating Double Dumbbell Floor Press', 'https://youtu.be/hyb1jJ98ORU?si=UKrLCDD8rhcoKu0p'),
  ('Kettlebell Seated Single Leg Tibialis Raise', 'https://youtu.be/kIRvGGD21Zw?si=nBLhNjFMITgsl7fd'),
  ('Double Kettlebell Seated Feet Elevated Calf Raise', 'https://youtu.be/trgsU9LSHcM?si=LkOOKLtsyEAMWIWJ'),
  ('Alternating Double Dumbbell Thruster', 'https://youtu.be/NDA72gV21vM?si=nr1ibCzWJfLIYTXz'),
  ('Single Arm Dumbbell Floor Press', 'https://youtu.be/0S0pPgQXWNk?si=sd5taBTsE1Qux9Er')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);