UPDATE exercises SET video_url = 'https://youtu.be/LcF_derN9KA?si=U_Cqiq6zxtQlpRhf' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Carry');
UPDATE exercises SET video_url = 'https://youtu.be/qa-CYBhvSDA?si=qbgdCK6xq_Ftfez0' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Carry');
UPDATE exercises SET video_url = 'https://youtu.be/7KN_RrCS_EU?si=seR_4LNmjEtTdXfj' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Dead Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/GwxzBGhm6ac?si=vrTFU3w6T1NGn8DM' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Start Stop Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/BpwgvVjQXiw?si=SPwizx5lirRdfFmX' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Start Stop Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/djCYBs70KLE?si=JiYJei8Eqv-UiCG7' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Start Stop Swing');
UPDATE exercises SET video_url = 'https://youtu.be/3Xhy3dz61to?si=8lmx3c2FvDHq6Zy5' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Start Stop Swing');
UPDATE exercises SET video_url = 'https://youtu.be/sS-bxWAoPWk?si=zgyeJNYUfOuTOFyj' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Start Stop Swing');
UPDATE exercises SET video_url = 'https://youtu.be/Aa9U0XNNBfU' WHERE LOWER(TRIM(name)) = LOWER('Ring L Sit Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/Y8Wn_vTZFFg?si=AtpqJfd4OVnOo7ZO' WHERE LOWER(TRIM(name)) = LOWER('Suspension Skater Jump');
UPDATE exercises SET video_url = 'https://youtu.be/SaBcgeWdynY?si=VUGBebh0ht8z7ISy' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Start Stop Clean');
UPDATE exercises SET video_url = 'https://youtu.be/SLm1ou6-SLM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Start Stop Clean');
UPDATE exercises SET video_url = 'https://youtu.be/_OtZfks5rfU?si=iwf-Hc6P6vZ3ke6I' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Start Stop Clean');
UPDATE exercises SET video_url = 'https://youtu.be/Xk0GovwG8Go' WHERE LOWER(TRIM(name)) = LOWER('Ring Bulgarian Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/3U86aaJuyRs' WHERE LOWER(TRIM(name)) = LOWER('Ring Bulgarian L Sit Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/RzeAb6wnMsk?si=aedjaQmoWjF7IB75' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Split Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/_1Tp01g9ciU?si=NTgkT4x59EZyPH9T' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Hang Power Clean');
UPDATE exercises SET video_url = 'https://youtu.be/NQ53MadCtW0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/7zn_K1omwQs' WHERE LOWER(TRIM(name)) = LOWER('Ring False Grip Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/T7F6-FEmvrs' WHERE LOWER(TRIM(name)) = LOWER('Ring Feet Elevated Pike Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/tDKju5qmxOM?si=j82cBg7j8A8GUsiV' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Split Clean');
UPDATE exercises SET video_url = 'https://youtu.be/SYxObzJ3gn0?si=MxNFujZbMP9ff4gw' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/lYo3ofjjUKI?si=6bwkgshNWDvWIlQc' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Hang Squat Clean');
UPDATE exercises SET video_url = 'https://youtu.be/J4MJUcilrmo?si=4cbvgzB0vHx2Gb3e' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Split Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/8gLU9bNm4TE?si=4FnpId_WJCijmDqW' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Hammer Swing');
UPDATE exercises SET video_url = 'https://youtu.be/DB63aMHSfX8' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Back Lever with Alternating Single Leg Extensions');
UPDATE exercises SET video_url = 'https://youtu.be/iK78Q6NwH-Q' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Front Lever with Alternating Single Leg Extensions');
UPDATE exercises SET video_url = 'https://youtu.be/a5CR3Bi2Gc8?si=fy5lJhtOGwem51y_' WHERE LOWER(TRIM(name)) = LOWER('Barbell Split Clean');
UPDATE exercises SET video_url = 'https://youtu.be/ILaWpcO0NdQ?si=wZ59jqUF1LZLoldu' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Hang Split Clean');
UPDATE exercises SET video_url = 'https://youtu.be/Go96FtKDQIA' WHERE LOWER(TRIM(name)) = LOWER('Ring Archer Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/OE8VmAtG3iw?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Half Kneeling Lateral Toss');
UPDATE exercises SET video_url = 'https://youtu.be/vEI0fyG4150?si=H1RJwNd1aUDk0Xh7' WHERE LOWER(TRIM(name)) = LOWER('Wall Ball Isometric Split Squat Lateral Toss');
UPDATE exercises SET video_url = 'https://youtu.be/tkhmiyJiZ2E' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Bar Muscle Up');
UPDATE exercises SET video_url = 'https://youtu.be/VmLIr9_YfAs?si=auhUGS9WeZfuzEj-' WHERE LOWER(TRIM(name)) = LOWER('Parallette Push Up to L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/zMJpC7y-6SE' WHERE LOWER(TRIM(name)) = LOWER('Ring L Sit Dips');
UPDATE exercises SET video_url = 'https://youtu.be/8sJtCQgvc4Y?si=DkWjEgV5brDYcPXM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Single Leg Standing Bent Knee Contralateral Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/cBuy7xDJZN0' WHERE LOWER(TRIM(name)) = LOWER('Single Ring Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/SnBGaBxK3T0' WHERE LOWER(TRIM(name)) = LOWER('Ring L Sit Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/Ha9sM7H6Prk' WHERE LOWER(TRIM(name)) = LOWER('Single Ring L Sit Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/GCU9MgR78go?si=9_MfbrIFqCoJ9wnJ' WHERE LOWER(TRIM(name)) = LOWER('Ring Pelican Curl');
UPDATE exercises SET video_url = 'https://youtu.be/lpZUsYQVwuE' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Pseudo Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/YDO8UmA9lr8' WHERE LOWER(TRIM(name)) = LOWER('Parallette Pseudo Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/zbJBaxCypSQ?si=93h4TqDxZreFns6w' WHERE LOWER(TRIM(name)) = LOWER('Macebell Alternating 360 to Pivot Split Squat Uppercut');
UPDATE exercises SET video_url = 'https://youtu.be/PbysPTU69fc?si=8cDk2dXzGqWm8BiX' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Spin');
UPDATE exercises SET video_url = 'https://youtu.be/m3pCByzR5Is?si=d4rUJA6uUKzAub51' WHERE LOWER(TRIM(name)) = LOWER('Bulgarian Bag Alternating Spin');
UPDATE exercises SET video_url = 'https://youtu.be/_eVC54UW6eE?si=6tC__RV3slyYwUuP' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Feet Elevated Renegade Row');
UPDATE exercises SET video_url = 'https://youtu.be/9hZ1mWk3-gA?si=Tko55A45WxNaGz27' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Feet Elevated Renegade Row to Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/eLcNzP40LXQ?si=NCe5LCfcGAS-20f4' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/BGrdZtL5kqA?si=OVCBqhib32tJ12QT' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/E9f1yZXR3Vk?si=dWF4gSXuKpukJ-1Q' WHERE LOWER(TRIM(name)) = LOWER('Barbell Zercher Walking Lunge');