UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/DS-pvuh8VEo?si=KEDC31EUxCubFjGj'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/iRHrBseKm0k?si=X-TqbB38SGkCSqnE'),
  ('Ring Bulgarian Row', 'https://youtu.be/5CxPrNkhm2k'),
  ('Alternating Double Kettlebell Rotational Overhead Press', 'https://youtu.be/VQKcF1HfsYk'),
  ('Alternating Double Kettlebell Push Press', 'https://youtu.be/kUgzuCAvO3A'),
  ('Macebell Ballistic Curl', 'https://youtu.be/e8aZdfRK4FE?si=VtO52sSIMj0T-KCF'),
  ('Single Arm Clubbell Pullover', 'https://youtu.be/JJgOmmqZneM?si=v93qv5Poy03NJqj_'),
  ('Double Clubbell Pullover', 'https://youtu.be/2ZYphWzJedw?si=f5GGOhThihsKqIds'),
  ('Clubbell Pullover', 'https://youtu.be/0sRFLvzcqxw?si=cqK8W0uEQdEUfDAy'),
  ('Clubbell Front Flag Press', 'https://youtu.be/3_F4oUpYY7Q?si=qgoqjkcK33CSqmX4'),
  ('Single Arm Ring Dead Hang', 'https://youtu.be/7J_x9uMtr-o?si=2tga8qG4urWcSCMT'),
  ('Single Arm Dumbbell Suitcase Deadlift', 'https://youtu.be/yMRbcOd51pA?si=7Hc1xBgOqKKuKw3C'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/7wCLqLLyHh0?si=hFc7L_yPlG-KnZVg'),
  ('Clubbell Torch Press', 'https://youtu.be/REUDhFnYMYc?si=13Shwx4VKvuvNLZh'),
  ('Single Arm Clubbell Torch Press', 'https://youtu.be/UU4WhE25JfI?si=6sinMuju_2nUhgZK'),
  ('Barbell Conventional Deadlift', 'https://youtu.be/op9kVnSso6Q'),
  ('Barbell Sumo Deadlift', 'https://youtu.be/wQHSYDSgDn8'),
  ('Barbell Rack Pull', 'https://youtu.be/zdaEWO0S5HU'),
  ('Barbell Snatch Grip Deadlift', 'https://youtu.be/0Ah-ol5EGlo'),
  ('Stability Ball Hyperextension', 'https://youtu.be/bmRTtzOOiVM'),
  ('Barbell Seated Good Morning', 'https://youtu.be/ZPeJ0s8X6Gs'),
  ('Barbell Good Morning', 'https://youtu.be/F8dCjzbed-4'),
  ('Bodyweight Wall Sit', 'https://youtu.be/SszDMOZvFuw'),
  ('Bodyweight Wall Slide Squat', 'https://youtu.be/3J99J5NxNSQ?si=Xv_W-o9GzT-nvtVQ'),
  ('Stability Ball Wall Slide Squat', 'https://youtu.be/lWJ6BujsDYY?si=Hl4kTZutf9b6tDUi'),
  ('Suspension Squat', 'https://youtu.be/MafftY-3lC0?si=bGTlr29qg0ZvBtT_'),
  ('Suspension Alternating Reverse Lunge', 'https://youtu.be/oRO4ailwZb4'),
  ('Bodyweight Squat to Bench', 'https://youtu.be/93l0NGCosAE'),
  ('Bodyweight Squat', 'https://youtu.be/C_VtOYc6j5c'),
  ('Bodyweight Hand Assisted Split Squat', 'https://youtu.be/WRCsxtCfrEE'),
  ('Bodyweight Walking Lunge', 'https://youtu.be/tlbTz6IamaE'),
  ('Dumbbell Goblet Squat', 'https://youtu.be/a-dqF4NL2K4'),
  ('Miniband Romanian Deadlift', 'https://youtu.be/N5lBa2zMAPI?si=Eth4HWtKMOXBXNx6'),
  ('Superband Resisted Skater Jump', 'https://youtu.be/VHBOyCCupJ4?feature=shared'),
  ('Cable Prone Single Leg Hamstring Curl', 'https://youtu.be/k6Vo8hBLypQ'),
  ('Bodyweight Candlestick Roll Up Tuck Jump', 'https://youtu.be/BpwGQP8k7aY'),
  ('Barbell Block Pull Deadlift', 'https://youtu.be/iVpVk8x-VDQ'),
  ('Barbell Box Back Squat', 'https://youtu.be/dLG78_Z9rjM'),
  ('Barbell Deficit Deadlift', 'https://youtu.be/PzoxegwRlOw'),
  ('Barbell Front Rack Squat', 'https://youtu.be/uYumuL_G_V0'),
  ('Barbell Glute Bridge', 'https://youtu.be/6EhYj5eSngY'),
  ('Barbell High Bar Back Squat', 'https://youtu.be/ultWZbUMPL8'),
  ('Barbell Power Clean', 'https://youtu.be/KwYJTpQ_x5A'),
  ('Barbell Power Snatch', 'https://youtu.be/TL8SMp7RdXQ'),
  ('Barbell Romanian Deadlift', 'https://youtu.be/LURGDIX3adY?si=fHh3AAX-mZB09HXi'),
  ('Barbell Back Rack Split Squat', 'https://youtu.be/KXUJxb8hO8U'),
  ('Barbell Stiff Legged Deadlift', 'https://youtu.be/5_t0SsovgW8?si=5Zg1x855TTmrp1cL'),
  ('Barbell Sumo Back Squat', 'https://youtu.be/qiQAsB0x-7k?si=OlWu0ou6Vr0NnuvE'),
  ('Bodyweight Pistol Squat', 'https://youtu.be/qDcniqddTeE?si=G4KPahZUmlQQChZ_'),
  ('Bodyweight Skater Squat', 'https://youtu.be/kRnLZadW5Q0'),
  ('Cable Pull Through', 'https://youtu.be/NEDrQPoITMc?si=ZeJ1LOUbzrjgk-_8'),
  ('Double Dumbbell Suitcase Bulgarian Split Squat', 'https://youtu.be/G0Mo2LF8uLU'),
  ('Double Dumbbell Suitcase Step Up', 'https://youtu.be/37tVohr7LcE'),
  ('Double Dumbbell Suitcase Deficit Split Squat', 'https://youtu.be/jqWAqPQvqAk'),
  ('Double Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/t7DBjlOTwAk'),
  ('Double Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/Lsen4vH1nm8'),
  ('Double Dumbbell Suitcase Split Squat', 'https://youtu.be/yqH8u037IjM'),
  ('Double Dumbbell Front Rack Alternating Step Up', 'https://youtu.be/anHX8Zp67C8?si=qbb7ETCqekLaflB_'),
  ('Bodyweight Face the Wall Squat', 'https://youtu.be/pktIjwNiuYE?si=fWFt85clM0T2gopP'),
  ('Bodyweight Feet Elevated Glute Bridge', 'https://youtu.be/kFvF6ZHv-KI'),
  ('Slider Kettlebell Goblet Reverse Lunge', 'https://youtu.be/8k08cvYq-n8?si=bbPqV1XKB99kPfpP'),
  ('Miniband Thigh Monster Walk', 'https://youtu.be/po3I8qoRC2c?si=XeJ7Tq5PXt3WLJfl'),
  ('Bodyweight Quadruped Hip Extension', 'https://youtu.be/1UwyzWjFx5k'),
  ('Suspension Pistol Squat', 'https://youtu.be/K7qfUjKf9rU'),
  ('Suspension Skater Squat', 'https://youtu.be/YyBeT4WWBk4'),
  ('Bodyweight Tuck Jump', 'https://youtu.be/vgB_eWuvGW8?si=anQ4gfG2ik-Y_uU9'),
  ('Bodyweight Alternating Single Leg Wall Sit', 'https://youtu.be/eYGszeFcI7Y?si=jFOFuzza1JQMYuVE'),
  ('Bodyweight Single Leg Romanian Deadlift Jump', 'https://youtu.be/EmmP-jsvVJE'),
  ('Double Dumbbell Overhead Walking Lunge', 'https://youtu.be/TBw3mPrKAIs'),
  ('Bodyweight Reverse Nordic', 'https://youtu.be/GbpDfXXKuk0?si=IsPMd_J3d72xrMcZ'),
  ('Bodyweight Alternating Lateral Bench Jump', 'https://youtu.be/pVoOtkGBN6s'),
  ('Single Arm Dumbbell Front Rack Squat', 'https://youtu.be/1VzKnqCcUJ4'),
  ('Bodyweight Skater Jump', 'https://youtu.be/CaN4zfIPyXU'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/t8OkcdLjRFQ'),
  ('Cable Prone Bench Hamstring Curl', 'https://youtu.be/IalP0lgYPnc'),
  ('Bodyweight Bulgarian Split Squat Jump', 'https://youtu.be/CWTu90BUTIY?si=9JSuKmfFRaalZ6er'),
  ('Cable Standing Single Leg Hamstring Curl', 'https://youtu.be/tkh43Yc0tEs'),
  ('Bodyweight Nordic Hamstring Curl', 'https://youtu.be/kjv4WQXWl_A'),
  ('Superband Assisted Pistol Squat', 'https://youtu.be/szRINrcALyI'),
  ('Double Dumbbell Front Rack Squat', 'https://youtu.be/B86Zj72LwzA'),
  ('Double Dumbbell Suitcase Walking Lunge', 'https://youtu.be/KdE6b_r7wxA'),
  ('Barbell Back Rack Walking Lunge', 'https://youtu.be/ZPoMxOrIeO4'),
  ('Bodyweight Box Pistol Squat', 'https://youtu.be/Ly71LeprFKQ'),
  ('Barbell Overhead Squat', 'https://youtu.be/pn8mqlG0nkE'),
  ('Landmine Goblet Squat', 'https://youtu.be/oTRl7p13XtY'),
  ('Stability Ball Hamstring Curl', 'https://youtu.be/d-FBclT8W0g?si=wl1sJCzk2Z5PCnwx'),
  ('Slider Hamstring Curl', 'https://youtu.be/UaecXxAgsKA'),
  ('Bodyweight Hamstring Walkout', 'https://youtu.be/GcV2LB0qqnY?si=PoIiYCAOL0uaDuPR'),
  ('Slider Dumbbell Goblet Reverse Lunge', 'https://youtu.be/tWmzgpoOUls?si=Fmrp6-y_e5qk2SNJ'),
  ('Bodyweight Dragon Squat', 'https://youtu.be/bQY7fLEkZqU'),
  ('Stability Ball Single Leg Hamstring Curl', 'https://youtu.be/cuM7OBHSVow'),
  ('Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/HLDhxSqMQyE'),
  ('Barbell Overhead Walking Lunge', 'https://youtu.be/m6MczOv_Ayg'),
  ('Barbell Squat Clean', 'https://youtu.be/EKRiW9Yt3Ps'),
  ('Single Arm Landmine Hack Squat', 'https://youtu.be/hwd_6Y9YKvI'),
  ('Resistance Band Shoulder Dislocates', 'https://youtu.be/5yPvjJOqbg4?si=1OYvLb1R7Zq_hl94'),
  ('Suspension Reverse Grip Bicep Curl', 'https://youtu.be/yewf3adybcc?si=-PZ9RsGl7FC8vp7J'),
  ('Cable Straight Bar Reverse Grip Bicep Curl', 'https://youtu.be/RLlT3qbVS3Q?si=SYASKBhplBkTNYee'),
  ('Single Arm Cable Reverse Grip Bicep Curl', 'https://youtu.be/SIuDkLLlL6E?si=_Y_P-I5PU4GP5LRy'),
  ('Bar Eccentric Chin Up', 'https://youtu.be/B1nRr__KiNk?si=5PGKtxdEbPpVW1Ds'),
  ('Bar Eccentric Pull Up', 'https://youtu.be/T4Jv__fWjZ8?si=sbUarOu5VD7qBK4s'),
  ('Landmine Half Kneeling Oblique Twist', 'https://youtu.be/HGzu8tvh79U'),
  ('Single Arm Bar Dead Hang', 'https://youtu.be/uyNR71ZCrho?si=blbw-wn6NHBGbR9y'),
  ('Single Arm Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/UF_oINIojVQ?si=nyrZ0y91pz4IIfOs'),
  ('Alternating Double Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/2kWWWRpk6Co?si=gy0bI1KIAsGs2hhI'),
  ('Alternating Double Kettlebell Half Kneeling Overhead Press', 'https://youtu.be/V3wxOSo53mQ?si=cM14QdTRQfd_FXUt'),
  ('Stability Ball Single Arm Forearm Plank', 'https://youtu.be/J3JZR2SFknM'),
  ('Stability Ball Feet Elevated Single Arm Forearm Plank', 'https://youtu.be/PAFvOAPjKwk'),
  ('Landmine Zercher Skater Squat', 'https://youtu.be/avCA3xXb9hg'),
  ('Single Arm Landmine Front Rack Contralateral Reverse Lunge to Shoulder Press', 'https://youtu.be/h2bPSv9ka_o'),
  ('Landmine Thruster', 'https://youtu.be/jLvQenjeus8'),
  ('Landmine Romanian Deadlift', 'https://youtu.be/x5wWyQ-2k2E?feature=shared'),
  ('Single Arm Landmine Single Leg Romanian Deadlift', 'https://youtu.be/rzJse5Ds98k'),
  ('Landmine Tall Kneeling Oblique Twist', 'https://youtu.be/OCMcVEdK5vw'),
  ('Landmine Feet Elevated Russian Twist', 'https://youtu.be/Zb-l68-4KFM'),
  ('Single Arm Landmine Thruster', 'https://youtu.be/EcUficjayCY'),
  ('Double Kettlebell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Ke5Erzd3NjE?si=fOzgTGBaC6CMWfE6'),
  ('Landmine Zercher Curtsy Lunge', 'https://youtu.be/e7jkuKuWcZ0'),
  ('Barbell Back Rack Alternating Cossack Squat', 'https://youtu.be/YZQP6D9LP4E'),
  ('Barbell Front Rack Alternating Cossack Squat', 'https://youtu.be/_AEuTTkYzjg'),
  ('Dumbbell Goblet Alternating Cossack Squat', 'https://youtu.be/glbP_VzHNkw?si=1k1fGSYRRORQv7W8'),
  ('Bodyweight Alternating Cossack Squat', 'https://youtu.be/dhDjKmTX8tU'),
  ('Bodyweight Knee Over Toe Split Squat', 'https://youtu.be/ufsoFnFCqA4'),
  ('Barbell Back Rack Knee Over Toe Split Squat', 'https://youtu.be/RBcrPYSWQb8'),
  ('Barbell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/q7zJZAexRmc'),
  ('EZ Bar Incline Bench Lying Tricep Extension', 'https://youtu.be/vJuyPyyEdTs?si=_MMem5dVaaarfRRu'),
  ('EZ Bar Skull Crusher', 'https://youtu.be/eiCMrII3j9k?si=J2G1ZmeiFQDhnfxT'),
  ('Slider Knee Tuck', 'https://youtu.be/vx9j9l18pyE?si=U7boXKing8U74cQZ'),
  ('EZ Bar Incline Bench Skull Crusher', 'https://youtu.be/9VtEoirFmT8?si=B904_aTFyPDoEqMp'),
  ('EZ Bar Decline Bench Skull Crusher', 'https://youtu.be/XFBsHDastRI?si=rP6H63ZVPOndCThK'),
  ('EZ Bar Front Raise', 'https://youtu.be/N4HLFIr5H4A?si=l2WKwgNX9fExG7xF'),
  ('Suspension Pike', 'https://youtu.be/MkmpHj0T3OQ'),
  ('Suspension Side Plank Reach Through', 'https://youtu.be/9PiqAsdkh6Q'),
  ('Bodyweight Cocoon Crunch', 'https://youtu.be/BZWoijzyF_4?si=2gKtoX0oa_Lef7o8'),
  ('Ab Wheel Standing Rollout', 'https://youtu.be/SFTn_VON9qw'),
  ('Cable Fire Hydrant', 'https://youtu.be/P4cP-juNM1Q'),
  ('Cable Tall Kneeling Pull Through', 'https://youtu.be/5mkpuBI-2Ls'),
  ('Bodyweight Bent Knee Reverse Hyperextension', 'https://youtu.be/RbkVHCMU3xU'),
  ('Parallette Tuck L Sit', 'https://youtu.be/VhqEdeeAyvg'),
  ('EZ Bar Close Grip Bicep Curl', 'https://youtu.be/o1c9wFYt6FA?feature=shared'),
  ('EZ Bar Overhead Press', 'https://youtu.be/_5VJKCjn8YE?feature=shared'),
  ('Parallette Single Leg L Sit', 'https://youtu.be/V3hnphPbiAg'),
  ('Stability Ball Windshield Wiper', 'https://youtu.be/tVfP2_HkXEc'),
  ('Stability Ball Tall Kneeling Balance', 'https://youtu.be/wIkwr6LV9E8?si=WttWmNStYjInstEN'),
  ('Stability Ball Forearm Plank', 'https://youtu.be/4xODTD0UL-o?si=TSlUT4Fa309FslEb'),
  ('Slider Double Kettlebell Suitcase Lateral Lunge', 'https://youtu.be/bAaaXP2xb8E?si=AOaxE4RzaGKjiq0h'),
  ('Slider Kettlebell Horn Grip Lateral Lunge', 'https://youtu.be/OsP6_mqxBDI?si=Kdp1ECOmqjUFcNM9'),
  ('Single Arm Dumbbell Turkish Sit Up', 'https://youtu.be/h9OYpweuJEc'),
  ('Single Arm Landmine Turkish Sit Up', 'https://youtu.be/EhYVfy1KUUA'),
  ('Double Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/xkL1f4yewf0'),
  ('Double Dumbbell Turkish Sit Up', 'https://youtu.be/SreLOxzaIX4'),
  ('Single Arm Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/_FjMUe0AhTY'),
  ('Single Arm Kettlebell Overhead Cyclist Squat', 'https://youtu.be/PSRoSLw3GME'),
  ('Double Dumbbell Front Rack Alternating Cossack Squat', 'https://youtu.be/JFeG8YiLYmk'),
  ('Kettlebell Horn Grip Cyclist Squat', 'https://youtu.be/TysYZ7rKhpM'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Cyclist Squat', 'https://youtu.be/x8bLCSXTChA'),
  ('EZ Bar Seated Overhead Press', 'https://youtu.be/-MwL_9KOv7U?si=z-KgUayvNC37N78i'),
  ('Double Dumbbell Suitcase Knee Over Toe Split Squat', 'https://youtu.be/2U58iHm7oSM'),
  ('EZ Bar Close Grip Bench Press', 'https://youtu.be/yoS-cVxq28Q?si=hPjefaZ8jY6Ugoh_'),
  ('EZ Bar Close Grip Incline Bench Press', 'https://youtu.be/PEH5Ncie81g?si=F2eXxzjoehGGc9Bb'),
  ('EZ Bar Close Grip Decline Bench Press', 'https://youtu.be/K40CGYdAysc?si=AY-3wTXsp03-uRQ_'),
  ('Cable Half Kneeling Pallof Press', 'https://youtu.be/7JBR6JGE1hY'),
  ('Barbell Kneeling Rollout', 'https://youtu.be/AEfj6Lnn0Ao'),
  ('Barbell Reverse Grip Overhead Press', 'https://youtu.be/ZO_ALQcMaq4?si=Sv5NmxfQj3aIKU84'),
  ('Cable Tall Kneeling Pallof Press', 'https://youtu.be/EtEPKajf0PE'),
  ('Tire Sledge Hammer Staggered Stance Slam', 'https://youtu.be/ykhGpORlJ4Y?si=6hFSwmMbG1lGLXki'),
  ('Barbell Hang Power Clean', 'https://youtu.be/0aP3tgKZcHQ'),
  ('Landmine Goblet Alternating Cossack Squat', 'https://youtu.be/N549md2Wu2A'),
  ('Landmine Low Hold Alternating Cossack Squat', 'https://youtu.be/PnBI0wLBZIg'),
  ('Bodyweight Push Up', 'https://youtu.be/_l3ySVKYVJ8?si=PZh3DAAcRNF9txaZ'),
  ('Barbell Close Grip Incline Bench Press', 'https://youtu.be/wbI4qof1454?si=WRjRCDTcll5n5uKu'),
  ('Double Dumbbell Push Press', 'https://youtu.be/JqztIwOb4Hs?si=89lHhxGXew7SEPqj'),
  ('Single Arm Dumbbell Push Press', 'https://youtu.be/-TVuoR8URxg?si=RsWhCdjyNahveL9y'),
  ('Alternating Double Dumbbell Push Press', 'https://youtu.be/Kn3oZ9MNAhg?si=j1DYyyohu1ImlWt4'),
  ('Cable Rope Tall Kneeling Overhead Tricep Extension', 'https://youtu.be/cDMXXH7Y9AM?si=pObK3p_2FqS0HqbC'),
  ('Alternating Double Kettlebell Push Jerk', 'https://youtu.be/4wXnxXq4hX4?si=21E2nrYJROeQgBUm'),
  ('Double Dumbbell Push Jerk', 'https://youtu.be/oWfLP7JFwTg?si=UbP4KHHXrg5hVRnc'),
  ('Alternating Double Kettlebell Overhead Press', 'https://youtu.be/KMKqAY-T3wE?si=DccwyejeKVDgXRV-'),
  ('Single Arm Dumbbell Push Jerk', 'https://youtu.be/r-yDtVg8Yf0?si=XQ5L1OU_VTCHZWRf'),
  ('Alternating Double Dumbbell Push Jerk', 'https://youtu.be/ZQ653_FImKw?si=O2ttj0r4a_Nbkwq1'),
  ('Double Kettlebell Bottoms Up Floor Press', 'https://youtu.be/BDCAkIEOPvE?si=ouPFKCSuMS-REkBT'),
  ('Single Arm Kettlebell Bottoms Up Floor Press', 'https://youtu.be/uk39UR9K25Y?si=s6ejJf9GtQ4llbjw'),
  ('Trap Bar Bent Over Row', 'https://youtu.be/aNllFax4shk?si=J0w79P4ud8wpm67U'),
  ('Trap Bar Pendlay Row', 'https://youtu.be/d5rLWfIN9fo?si=iiKqMHW4Xr9OMyaR'),
  ('Trap Bar Shrug', 'https://youtu.be/DjFdFkeXSDM?si=RIA3ok7NhzuAj8LK'),
  ('Bodyweight Tuck L Sit', 'https://youtu.be/U9Z7WWNm1d4?si=pWSS4MOr8iZXWiNj'),
  ('Parallette Straddle L Sit', 'https://youtu.be/F6o417SxU1g'),
  ('Battle Rope Power Slam', 'https://youtu.be/7wDx6mZDxA8?si=rDE21yzc81AXz5sw'),
  ('Bodyweight Manna', 'https://youtu.be/L7reIo5f6uo'),
  ('Ring Tuck Back Lever', 'https://youtu.be/SZV1-ts76CM'),
  ('Ring Full Back Lever', 'https://youtu.be/ZFEy1s_N820'),
  ('Trap Bar Floor Press', 'https://youtu.be/4C4LDf-eZ5A?si=Uh-L_Lu-0xta0H-S'),
  ('Trap Bar Overhead Press', 'https://youtu.be/Vorw1hVd_Dc?si=CRIVCwpCzzeBwN26'),
  ('Ring Tuck Front Lever', 'https://youtu.be/JxlKAuD9gkA'),
  ('Ring Straddle Front Lever', 'https://youtu.be/eI-15uPc0yE'),
  ('Ring Full Front Lever', 'https://youtu.be/rB9EcLohiVs'),
  ('Ring Inverted Hang', 'https://youtu.be/txtXtF2-4S0'),
  ('Single Arm Barbell Kneeling Rollout', 'https://youtu.be/i-JO6pBsKWk'),
  ('Trap Bar Tall Kneeling Overhead Press', 'https://youtu.be/ILFSDv6TaiY?si=0iUQUtwUMsGFbVuI'),
  ('Trap Bar Bench Press', 'https://youtu.be/8TIFsF_HU_8?feature=shared'),
  ('Alternating Double Dumbbell Z Press', 'https://youtu.be/dsTU2qm4ef0?si=sT2aw7NxeFtfYYNV'),
  ('Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/HZM84steEyw?si=wN3l2SpjKBFPTIbD'),
  ('Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/y0t2PFFwSe4?si=VjtJz1Dg61jGQIZ9'),
  ('Alternating Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/UhOs_Wvckvs?si=FqNmpb8ECh_Y-9rl'),
  ('Alternating Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/12MxAGiIgK8?si=pO89QghXz2Ykj1lb'),
  ('Single Arm Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/QVFklRHtJxY?si=D_kiEaZg-5pSrfHL'),
  ('Double Plate Incline Bench Prone Y Raise', 'https://youtu.be/VHeZJHEj6ic?si=DTfOrwFveTP-memt'),
  ('Single Arm Kettlebell Pendlay Row', 'https://youtu.be/VOmnhGvccZ0?feature=shared'),
  ('Barbell Floor Press', 'https://youtu.be/YdiVxhxufG8?si=pMAxf531BcAPvatO'),
  ('Ring Plank', 'https://youtu.be/p3zS2AMqGlg'),
  ('Single Arm Ring Plank', 'https://youtu.be/_Iev7PLP6QY'),
  ('Battle Rope Alternating Outward Circle', 'https://youtu.be/O2HVcPD3wKQ?si=CFVI8GpHxTsirv6u'),
  ('Ring Support Hold', 'https://youtu.be/kONbxg4kzkE'),
  ('Ring Side Plank', 'https://youtu.be/PQ3Vz8fp73k'),
  ('Barbell Reverse Grip Bent Over Row', 'https://youtu.be/cZvQNvTUUu0?si=SqA3lYAZBc0jOnvn'),
  ('Macebell Offset Bent Over Row', 'https://youtu.be/OXl94TQd_vw?si=AMXpvOM-H382GJoz'),
  ('Macebell Reverse Grip Offset Bent Over Row', 'https://youtu.be/igNnqZZ69JM?si=xaqrnAFrW4r7NuVR'),
  ('Bodyweight Hollow Body Rock', 'https://youtu.be/p7j02V1fIzU'),
  ('Single Arm Dumbbell Power Snatch', 'https://youtu.be/3mlhF3dptAo'),
  ('Alternating Single Arm Dumbbell Power Snatch', 'https://youtu.be/OktkfRlGcns'),
  ('Single Arm Dumbbell Squat Snatch', 'https://youtu.be/etK3OPjM3S4'),
  ('Alternating Single Arm Dumbbell Squat Snatch', 'https://youtu.be/T0_a2xijJBE'),
  ('Single Arm Cable Single Leg Romanian Deadlift', 'https://youtu.be/OC_7QIo0uk4'),
  ('Double Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/6caQpfXMvyw?si=WY0XcdcIUuE20g-o'),
  ('Single Arm Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/AlxuA22ymwg?si=-tgz7djxN0QKxXfA'),
  ('Double Kettlebell Front Rack Step Up', 'https://youtu.be/wcnuhd6RHwE'),
  ('Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/jHpBzpxK16c?si=3sB9wGkke_B632ad'),
  ('Single Arm Dumbbell Incline Bench Prone Row', 'https://youtu.be/4Bv94e_ufjo?si=8V5SPIIuNai7zUm3'),
  ('Single Arm Dumbbell Spider Curl', 'https://youtu.be/Ew2ZzKqICfA?si=Irq2jLSDxKiagY3F'),
  ('Double Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/STeIzkHm6tE?si=BxEJOKh_KtwNSMK_'),
  ('Double Dumbbell Seated Good Morning', 'https://youtu.be/x5nnk8hUBo4'),
  ('Bodyweight Hip Thrust', 'https://youtu.be/OAhvIWLC0rc'),
  ('Single Arm Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/SoVCwno_9z8?si=BCvfBOVPW_aHbvZ_'),
  ('Alternating Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/rAoi4_AI7VA?si=b6KXmXEYoxIPmTt2'),
  ('Single Arm Kettlebell Incline Bench Prone Row', 'https://youtu.be/gPX8OmnYmQY?si=UgQnJkh9n3OobTcZ'),
  ('Single Arm Dumbbell Overhead Contralateral Bulgarian Split Squat', 'https://youtu.be/z7rygloAW30?si=p4kPPZcAKammq1Vv'),
  ('Double Kettlebell Suitcase Step Up', 'https://youtu.be/3HUEab31fks?si=B2OmGKfwSuXhts1z'),
  ('Single Arm Kettlebell Suitcase Contralateral Step Up', 'https://youtu.be/lMADALbx1eM?si=wJjWrYeLHPKqVgHh'),
  ('Double Kettlebell Overhead Step Up', 'https://youtu.be/eKUmMljLcKw?si=ocsvBon7ivrRziM6'),
  ('Kettlebell Half Kneeling Low to High Chop', 'https://youtu.be/wPXdGwc0NTs'),
  ('Single Arm Kettlebell Windmill', 'https://youtu.be/3rtUK_jUv4s'),
  ('Kettlebell Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Alternating Single Arm Kettlebell Plank Pull Through', 'https://youtu.be/fKbu_2L94x8'),
  ('Single Arm Kettlebell Swing', 'https://youtu.be/kneGICiz30g'),
  ('Double Kettlebell Bottoms Up Bench Press', 'https://youtu.be/bIzD1Z_C0cA'),
  ('Single Arm Kettlebell Suitcase Deadlift', 'https://youtu.be/1hcAoywwuRI'),
  ('Single Arm Kettlebell Clean', 'https://youtu.be/TQT7hBXVcOo'),
  ('Single Arm Kettlebell Clean to Overhead Press', 'https://youtu.be/JtlYyc5MaAc'),
  ('Alternating Single Arm Dumbbell Pendlay Row', 'https://youtu.be/7zKQ79awAvY?feature=shared'),
  ('Single Arm Kettlebell Snatch', 'https://youtu.be/VdNC_xicfyg'),
  ('Kettlebell Sumo Deadlift', 'https://youtu.be/odS65TnXgU0?si=l3QM9Nb4wHNt_JgK'),
  ('Single Arm Kettlebell Turkish Get Up', 'https://youtu.be/sgd8n917Zv0'),
  ('Kettlebell Goblet Squat', 'https://youtu.be/f-Vf2yRRqOg'),
  ('Single Arm Kettlebell Overhead Squat', 'https://youtu.be/nrfDq0DUhrE'),
  ('Double Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/vcMZNgn5G9c'),
  ('Single Arm Kettlebell Bottoms Up Bench Press', 'https://youtu.be/NIytPzrQ460?si=hBsVxzSTE6ddOTCD'),
  ('Single Arm Kettlebell Turkish Sit Up', 'https://youtu.be/KpufjJRtyPc'),
  ('Double Kettlebell Turkish Sit Up', 'https://youtu.be/RttCwCerCiM'),
  ('Double Kettlebell Turkish Sit Up to Z Press', 'https://youtu.be/UcLpNnWX8vE'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Cossack Squat', 'https://youtu.be/aJGPHYsiyTM'),
  ('Double Kettlebell Swing', 'https://youtu.be/fOPqk1FA4HU'),
  ('Double Kettlebell Front Rack Squat', 'https://youtu.be/JoT4bHnzTMw?si=i8z5wbuObKGVIl4_'),
  ('Single Arm Kettlebell Front Rack Squat', 'https://youtu.be/Wqg4NY5XAkU'),
  ('Single Arm Kettlebell Front Rack Contralateral Split Squat', 'https://youtu.be/-Z8NXAi59SE'),
  ('Single Arm Kettlebell Front Rack Carry', 'https://youtu.be/M39871Puz6c'),
  ('Single Arm Kettlebell Squat Clean', 'https://youtu.be/FZ8mMUwnCQs'),
  ('Double Kettlebell Prone Row', 'https://youtu.be/hUG_dolsaPE?si=_fw03cFT8VfLVtzo'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/0i2Aa8gV-VY?si=Z7AGqRY1Hod9Fwti'),
  ('Double Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/F19T2zGlPGA'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Walking Lunge', 'https://youtu.be/FvSL8slKKHY'),
  ('Alternating Double Kettlebell Prone Row', 'https://youtu.be/OD7URB1yHAo?si=UX_3VmEfO_WpeiuT'),
  ('Double Kettlebell Single Leg Romanian Deadlift', 'https://youtu.be/JkKxFADvLvk'),
  ('Double Kettlebell Romanian Deadlift', 'https://youtu.be/Xa8hHIwOHe4'),
  ('Single Arm Kettlebell Contralateral Single Leg Romanian Deadlift', 'https://youtu.be/9u_Fccgk9Ys'),
  ('Single Arm Kettlebell Bottoms Up Overhead Squat', 'https://youtu.be/j0aAMnMp0yU'),
  ('Single Arm Kettlebell Prone Row', 'https://youtu.be/QSbH7gNkBtc?si=ngxTS90XoTuvQDxs'),
  ('Parallette Tuck Planche', 'https://youtu.be/3WVToPNWjVk'),
  ('Macebell Offset Bicep Curl', 'https://youtu.be/xkyQtEH8fxM?si=Zh1mTKcYEFs382Sk'),
  ('Parallette L Sit to Tuck Planche', 'https://youtu.be/NUvTsZxo5nk'),
  ('Landmine Standing Oblique Twist', 'https://youtu.be/4dGj7rES9pY'),
  ('Cable Rope Tall Kneeling High to Low Chop', 'https://youtu.be/h-af-afj-Xg'),
  ('Single Arm Parallette Plank', 'https://youtu.be/NrkFLTzLuSM'),
  ('Single Arm Suspension Plank', 'https://youtu.be/hetklTC7y4M?si=gHU6ufU8oAcg21Jv'),
  ('Battle Rope Russian Twist', 'https://youtu.be/_-kclLM0Mak'),
  ('Bodyweight Bird Dog Knee to Elbow', 'https://youtu.be/1v4_Vsvk3gc'),
  ('Slam Ball Feet Elevated Russian Twist', 'https://youtu.be/W1FXse115qs'),
  ('Medicine Ball Feet Elevated Russian Twist', 'https://youtu.be/IdEocZzdUNY'),
  ('Alternating Double Dumbbell Prone Row', 'https://youtu.be/Ry9HwpfUbd8?si=oY89SBibCyKMJ7CT'),
  ('Bodyweight Forearm Plank Alternating Knee to Elbow', 'https://youtu.be/A_JgZzr6o-k'),
  ('Bodyweight Loaded Beast to Alternating Kick Through', 'https://youtu.be/lhh2tGD_47g'),
  ('Single Arm Dumbbell Prone Row', 'https://youtu.be/-fuxiCQvMxQ?si=lCRmzsfrTeNaP0Gk'),
  ('Double Kettlebell Clean', 'https://youtu.be/8tFmEJ9ElaM'),
  ('Double Kettlebell Snatch', 'https://youtu.be/5WNcWPHXRZ0'),
  ('Battle Rope Feet Elevated Russian Twist', 'https://youtu.be/XdKaa2lHuic'),
  ('Superband Dead Bug', 'https://youtu.be/wCwn7-Z-XjE'),
  ('Parallette V Sit', 'https://youtu.be/oBmFzeay6Z8?si=dliVO8cgoAWNKwT3'),
  ('Double Kettlebell Split Jerk', 'https://youtu.be/6sbNXcg-R0Y'),
  ('Double Kettlebell High Pull', 'https://youtu.be/zfWpy9oMOqc?si=8gZawgsKgTeeGHck&amp;utm_source=MTQxZ'),
  ('Superband Pallof Press', 'https://youtu.be/TvPRtxN8uoA'),
  ('Superband Half Kneeling Pallof Press', 'https://youtu.be/V-SoYj9uQV8'),
  ('Ring Archer Row', 'https://youtu.be/s1Cuq185q6Y?si=TNXwSjV_mkE_2ty0'),
  ('Single Arm Landmine Row to Rotational Shoulder Press', 'https://youtu.be/f-sh_ImlQUo'),
  ('Bodyweight Hand Assisted Skater Squat', 'https://youtu.be/DExb7UaAlbg'),
  ('Superband Pull Through', 'https://youtu.be/ZuKowDpVVXM'),
  ('Miniband Quadruped Hip Extension', 'https://youtu.be/k30hN0vhlsY?si=ycYwNbMrFEnA94pG'),
  ('Cable Hip Adduction', 'https://youtu.be/UyXncDziNGo?si=W4GuZaUvoWtiIOxj'),
  ('Superband Tall Kneeling Pallof Press', 'https://youtu.be/yUzjX1LdySo?si=2LpxjTl8N8OHsKqd'),
  ('Slider Eccentric Hamstring Curl', 'https://youtu.be/vcCVej7p_vc'),
  ('Landmine Low Hold Lateral Lunge', 'https://youtu.be/VTtLrBvHoJ8'),
  ('Double Kettlebell Sumo Deadlift', 'https://youtu.be/4m288BpgfcQ'),
  ('Slider Kneeling Reach Push Up', 'https://youtu.be/-RTSF7qbrhs?si=hznPEKw9aLONjGpz'),
  ('Slider Parallette Knee Tuck', 'https://youtu.be/Kj89v76f-l8?si=_B0Uc1Xs1x1S0G_M'),
  ('Superband Shoulder Dislocates', 'https://youtu.be/MPtMYQH9vvg?si=eEJrNr3oqGzcma8_'),
  ('Superband Alternating Shoulder Dislocates', 'https://youtu.be/AJmPEWu4FiM?si=0h2x72A-kGfK3a_0'),
  ('Superband Prone Shoulder Dislocates', 'https://youtu.be/3WOAWkEKZGA?si=lSddj94elx-N7ZKJ'),
  ('Ring L Sit', 'https://youtu.be/lwcHmXvw-T4'),
  ('Resistance Band Prone Shoulder Dislocates', 'https://youtu.be/YwELfevh5vs?si=tmPYSbe-vfbiD0vx'),
  ('Cable Straight Bar Spider Curl', 'https://youtu.be/zGyaLrwHJjs?si=sg4m9llWui7pmOT_'),
  ('Double Kettlebell Bottoms Up Front Rack Squat', 'https://youtu.be/IvN-CSDnvoc'),
  ('Barbell Back Rack Cyclist Squat', 'https://youtu.be/TT7Ra3TnlZY'),
  ('Gravity Boots Inverted Sit Up', 'https://youtu.be/AN4MBtCsJqo'),
  ('Double Kettlebell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/G7e7EenICzQ'),
  ('Barbell Back Rack Step Up', 'https://youtu.be/uQGRzdjxHes'),
  ('Barbell Front Rack Step Up', 'https://youtu.be/YR_7r6EzJdA'),
  ('Barbell Standing Rollout', 'https://youtu.be/_lI_GB0DI3o'),
  ('Stability Ball Cable Russian Twist', 'https://youtu.be/4ESBjh2BcdE'),
  ('Miniband Frog Pump', 'https://youtu.be/rzjQ8XpXt1Q'),
  ('Bodyweight Fire Hydrant', 'https://youtu.be/IFrN8GELc-k?feature=shared'),
  ('Bodyweight Knee Hover Quadruped Fire Hydrant', 'https://youtu.be/8nmBvZ1DkKQ?si=RUcdU_JPDGU_yIWv'),
  ('Alternating Double Dumbbell Spider Curl', 'https://youtu.be/KznrM_RhXDc?si=Qxgmd-eTnFuZ5rpo'),
  ('Bodyweight Bent Knee Copenhagen Plank Side Raise', 'https://youtu.be/xkcOhvzzta0'),
  ('Bodyweight Kneeling Side Plank', 'https://youtu.be/PAHxwhBVsYY?si=pym-tzPNwmH8zNeP'),
  ('Bodyweight Wall Assisted Hip Airplane', 'https://youtu.be/20R2FqNUBsA?si=3Nuvhsgux27gQFjW'),
  ('Superband Single Leg Tibialis Raise', 'https://youtu.be/fAf6Z7wu7fM?si=6K5_014ZCoGfknf8'),
  ('Barbell Zercher Squat', 'https://youtu.be/nwx6Ip7hd3I'),
  ('Barbell Squat Snatch', 'https://youtu.be/9xQp2sldyts'),
  ('Barbell Squat Clean to Split Jerk', 'https://youtu.be/PjY1rH4_MOA'),
  ('Slider Kneeling Alternating Reach Push Up', 'https://youtu.be/1UD0dTGE04w?si=q2odI18mbdJTtPDF'),
  ('Barbell Hang Squat Clean to Thruster', 'https://youtu.be/8DApihgXzGk'),
  ('Barbell Squat Clean to Thruster', 'https://youtu.be/4qZWqKDAhkQ'),
  ('Bodyweight Copenhagen Plank', 'https://youtu.be/tKb76R21AfM?si=zsuYyzMMfjZleCpc'),
  ('Bodyweight Bent Knee Copenhagen Plank', 'https://youtu.be/obtdLUWZi-Y'),
  ('Miniband Single Leg Hip Thrust', 'https://youtu.be/tPWyj85zsmg'),
  ('Barbell Deficit Snatch Grip Deadlift', 'https://youtu.be/s_Cx_ElOuQs'),
  ('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/hTBEkHf8GmA'),
  ('Bodyweight Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/Gu4qA5TevLU'),
  ('Double Kettlebell Thruster', 'https://youtu.be/5-mxMxigTfw'),
  ('Double Kettlebell Cossack Squat Thruster', 'https://youtu.be/DbKGRbkQ80E'),
  ('Single Arm Landmine Shrug', 'https://youtu.be/I_qhTOdNkHo?si=7wY3icLNd-TkFk5i'),
  ('Double Kettlebell Front Rack Walking Lunge', 'https://youtu.be/Xmfx1eZMKmY'),
  ('Double Kettlebell Overhead Walking Lunge', 'https://youtu.be/hcQJcKxc240'),
  ('Ring Straddle L Sit', 'https://youtu.be/pjk0vGe9YRU'),
  ('Double Kettlebell Seesaw Overhead Press', 'https://youtu.be/VWnVBfRkLXE?si=AeN6Q9aAnShqxuIb'),
  ('Double Kettlebell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/UiY-JIpmt24?si=ox4YNd9xIIVapyeB'),
  ('Double Dumbbell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Lk0xszw7Tf8?si=GHtFcn5OVifRVyDQ'),
  ('Double Dumbbell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/NP4p_SWAgnA?si=VoTKPhBbaaWrrYZH'),
  ('Double Dumbbell Seesaw Z Press', 'https://youtu.be/L_Y8osw78lA?si=3eK1QuOTlQjCzAxO'),
  ('Stability Ball Sit Up', 'https://youtu.be/7L90imlW0es?si=gY7k7XVC43IRrv-N'),
  ('EZ Bar Wide Grip Strict Bicep Curl', 'https://youtu.be/j83lzC2E4Ss?si=PcoF092JVJRpg8T4'),
  ('Double Kettlebell Squat Clean', 'https://youtu.be/6wyxpVY8PQ0'),
  ('Double Kettlebell Hollow Body Hold', 'https://youtu.be/do1yf3NMXdg'),
  ('Alternating Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/xkCR2CkkL1g?si=Qy0YPAcCasZF6kNk'),
  ('Bodyweight Side Lying Hip Adduction', 'https://youtu.be/UW52u8OaWhw?si=WdEOpAR_PSB9x9bR'),
  ('Superband Hollow Body Hold', 'https://youtu.be/8QRsSJ-Ny8M'),
  ('Parallette Freestanding Handstand Push Up', 'https://youtu.be/3FYYo6lP-dw'),
  ('Slider Single Leg Eccentric Hamstring Curl', 'https://youtu.be/yAOulKW0al4'),
  ('Bodyweight Freestanding Handstand Push Up', 'https://youtu.be/aAErmRDDJKY'),
  ('Single Arm Ring Grip Push Up', 'https://youtu.be/CXVqHGLmb3Q'),
  ('Superband Side Plank Hanging Hip Adduction', 'https://youtu.be/JG0Ay2QDVbI'),
  ('Ring Strap Bulgarian Handstand Push Up', 'https://youtu.be/ZNCupJIYP6M'),
  ('Stability Ball Feet Elevated Frog Pump', 'https://youtu.be/Rc5e-DsD--M'),
  ('Double Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/HOQeoz3zQeo'),
  ('Barbell Front Rack Cyclist Squat', 'https://youtu.be/IU_0IBe4G9w'),
  ('Double Kettlebell Dead Clean to Push Press', 'https://youtu.be/NAZ9uF9S_wk'),
  ('Bodyweight Bent Arm Press Handstand', 'https://youtu.be/Gzz3ku70W3I'),
  ('Single Arm Dumbbell Cyclist Thruster', 'https://youtu.be/2Tt0XZ2pZyE'),
  ('Double Kettlebell Front Rack Split Squat', 'https://youtu.be/ExJCssj4YV0'),
  ('Double Kettlebell Front Rack Bulgarian Split Squat', 'https://youtu.be/Q3yDIeMfdNg'),
  ('Double Kettlebell Overhead Squat', 'https://youtu.be/2Pk8jmse6vY'),
  ('Bodyweight Chest Roll to Straight Body Press Handstand', 'https://youtu.be/mYQAYnr2hlg?si=gqlNGvKWytXXQP1H'),
  ('Ring Bent Arm Bent Body Press Handstand', 'https://youtu.be/TxkC9nrvOho'),
  ('Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/1XyV5eNL1z0'),
  ('Kettlebell Swing', 'https://youtu.be/1cVT3ee9mgU'),
  ('Alternating Single Arm Kettlebell Swing', 'https://youtu.be/WK4ughYoUEI?si=2mvQ9x0jZEF2zzRA'),
  ('Alternating Single Arm Kettlebell Clean', 'https://youtu.be/dPN2mj5R2S8'),
  ('Alternating Single Arm Kettlebell Snatch', 'https://youtu.be/0aq5EW0euvA'),
  ('Single Arm Kettlebell Staggered Stance Swing', 'https://youtu.be/L2WY5gYUb1U'),
  ('Alternating Single Arm Kettlebell Alternating Staggered Stance Swing', 'https://youtu.be/Ss7KjOjCpVU'),
  ('Single Arm Kettlebell Half Kneeling Swing', 'https://youtu.be/QVvrdVbq9qs'),
  ('Double Kettlebell Outside Swing', 'https://youtu.be/zrvtXpwVTOI'),
  ('Double Kettlebell Outside Half Snatch', 'https://youtu.be/Fx-qV1dHGi4?feature=shared'),
  ('Double Kettlebell Outside Clean', 'https://youtu.be/QtlvLhVFR40'),
  ('Single Arm Kettlebell Side Swing', 'https://youtu.be/YBJnavxcbUA'),
  ('Kettlebell Feet Elevated Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Single Arm Kettlebell Half Kneeling Windmill', 'https://youtu.be/wjYNzITBDqg'),
  ('Kettlebell Horn Grip Skater Squat', 'https://youtu.be/q1TuasYdM2M'),
  ('Double Kettlebell Front Rack Pistol Squat', 'https://youtu.be/-A7yvmUv8Cw'),
  ('Single Arm Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/JGY8VuvaEHc?si=LVWYZO5Qt-3WONJf'),
  ('Ring Back Lever Pullout', 'https://youtu.be/FRBr2pomeOM?si=15TQvL3xIskTVzVA'),
  ('Double Kettlebell Clean to Overhead Press', 'https://youtu.be/5Fx69TRWARc')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);