UPDATE exercises SET video_url = 'https://youtu.be/4UhV4cCkugM' WHERE LOWER(TRIM(name)) = LOWER('Cable Seated Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/KLM1hUecXbY' WHERE LOWER(TRIM(name)) = LOWER('Cable Guillotine Curl');
UPDATE exercises SET video_url = 'https://youtu.be/hBC7lPyEkVM' WHERE LOWER(TRIM(name)) = LOWER('Cable Supine Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/xaMJYDzqTZg' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar High Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/9Dd8iiEUs_Q?si=juy6zuf-MVn-W8j8' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/wtbHEt6Qi8g?si=wca7IhWcGWNDg2QX' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Spider Curl');
UPDATE exercises SET video_url = 'https://youtu.be/uEjtuyC6-bc' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Cable Preacher Curl');
UPDATE exercises SET video_url = 'https://youtu.be/fOV-z1wARvs?si=pxr3u-XyVhL6BlD3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Standing Concentration Curl');
UPDATE exercises SET video_url = 'https://youtu.be/xUdw3EtnTLM?si=6zj86RhHEsTUIlf4' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Wide Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/shIYFhPQVSo' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Standing High Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/QGK3RQ_Eexc?si=2Go8XA5nbKIfwUBr' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Seated Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/99qXUnFuQdM' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/aea5BGj9a8Y' WHERE LOWER(TRIM(name)) = LOWER('Barbell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/XtU2VQVuLYs' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Diamond Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/fUW3C1lVWkk?si=uxeyIMMcnTpM46fm' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Lying Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/KvrP8c6eVBc?si=1EP-aMrXRtcbPO6b' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/pXd8vm-ZSOA?si=8_iZ3618RVjOmu3S' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Reverse Grip Tricep Pushdown');
UPDATE exercises SET video_url = 'https://youtu.be/aIrvcBlNHBA' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Reverse Grip Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/EQlfrWvaU6w' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Single Arm Dumbbell Chest Press');
UPDATE exercises SET video_url = 'https://youtu.be/3FVZDVJnvIA' WHERE LOWER(TRIM(name)) = LOWER('Suspension Face Pull');
UPDATE exercises SET video_url = 'https://youtu.be/gnikveF7dgI' WHERE LOWER(TRIM(name)) = LOWER('Landmine V Grip Row');
UPDATE exercises SET video_url = 'https://youtu.be/u3wKkZjE8QM' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/03aX4h5-EkA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Thruster');
UPDATE exercises SET video_url = 'https://youtu.be/tiETx7VNDf0' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Row');
UPDATE exercises SET video_url = 'https://youtu.be/__TzXC-Hc_4?si=Z59SDF6EfXOY4pa_' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Bar Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/qt1WWg8QDg8?si=Go7eAWcyWu13yBIi' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Prone Cobra');
UPDATE exercises SET video_url = 'https://youtu.be/Pvs-dT7KPh4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Overhead Carry');
UPDATE exercises SET video_url = 'https://youtu.be/4-Jz3c_u1dw' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/SgzJGLlAtok?si=p2bo--kETp2ajVVX' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Pullover');
UPDATE exercises SET video_url = 'https://youtu.be/4QDCC2gU5_E' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Half Kneeling Lat Pulldown');
UPDATE exercises SET video_url = 'https://youtu.be/redrpTwkplw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Half Kneeling Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/wH4TXGV8UyA?si=N8Y8Uk0A9glEeeuQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Low Row');
UPDATE exercises SET video_url = 'https://youtu.be/93ZAdx24QVQ' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Incline Bench Prone Row');
UPDATE exercises SET video_url = 'https://youtu.be/ezrZnmjZTR4' WHERE LOWER(TRIM(name)) = LOWER('Barbell Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/SCVCLChPQFY' WHERE LOWER(TRIM(name)) = LOWER('Barbell Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/1OnBBhiaQjY' WHERE LOWER(TRIM(name)) = LOWER('Cable Single Leg Standing Bent Knee Hip External Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/ApvO0XTFjRc' WHERE LOWER(TRIM(name)) = LOWER('Cable Hip Rotation');
UPDATE exercises SET video_url = 'https://youtu.be/BVrlItPBX8M?si=4NJpARumV7sAFCki' WHERE LOWER(TRIM(name)) = LOWER('Barbell Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/43GSKivZnw4?si=OIfasYK8gG4sUDBW' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/iaBVSJm78ko' WHERE LOWER(TRIM(name)) = LOWER('Barbell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/9Gf-Ourup_k?si=qt-DlqHLDICtOmju' WHERE LOWER(TRIM(name)) = LOWER('Barbell Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/e-c4gMcqdyw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Landmine Meadows Row');
UPDATE exercises SET video_url = 'https://youtu.be/iWyvxI5A1cA?si=aBSi-dGZ6CxySnnU' WHERE LOWER(TRIM(name)) = LOWER('Cable Straight Bar Seated Bicep Curl');
UPDATE exercises SET video_url = 'https://youtu.be/NfOLyLpoGII' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Skull Crusher');
UPDATE exercises SET video_url = 'https://youtu.be/KxPNCVXkvAg?si=pDMoju9bpHN_T9_7' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Seated Cuban Press');
UPDATE exercises SET video_url = 'https://youtu.be/yHuLx1J9orw' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Facing Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/hDH5pliNKoM?si=NTV941Sjf3NsUGDj' WHERE LOWER(TRIM(name)) = LOWER('Parallette Close Grip Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/UEZy-OmXdZs' WHERE LOWER(TRIM(name)) = LOWER('Parallette Wide Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/DL-HN35sxdg' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Raise');
UPDATE exercises SET video_url = 'https://youtu.be/acozHQv1JLk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Cable Front Raise');