UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Stability Ball Dead Bug', 'https://youtu.be/5jDEulwWs04'),
  ('Bodyweight Glute Bridge', 'https://youtu.be/ncpMkhXAykg?si=a_b3ot2rsThtz4DE'),
  ('Bodyweight Bird Dog', 'https://youtu.be/tU-WZsouVjo?si=Ti1JUU03OqgnmtX6'),
  ('Stability Ball Russian Twist', 'https://youtu.be/2rbbUJR-Nx4?si=aAPlfM1RYBeErvZk'),
  ('Stability Ball Feet Elevated Crunch', 'https://youtu.be/ByXVlY2L3nw'),
  ('Ring Hanging Knee Raise', 'https://youtu.be/RPBH_Dw5hUo?si=SqKs_FnqsPMuLdq0'),
  ('Parallette Mountain Climber', 'https://youtu.be/W0RoAqlFzrA'),
  ('Parallette Push Up', 'https://youtu.be/Kbhl_O1N4aw'),
  ('Bodyweight Knee Hover Bird Dog', 'https://youtu.be/fGaqVUHB1aA'),
  ('Stability Ball V Up Pass', 'https://youtu.be/n4UPDi5BuL0'),
  ('Bodyweight Dead Bug', 'https://youtu.be/jbWmbhElf3Q'),
  ('Bodyweight Alternating Heel Taps', 'https://youtu.be/URWXz0DmE7s'),
  ('Bodyweight Flutter Kicks', 'https://youtu.be/e_s7uBNPnow'),
  ('Bodyweight Kneeling Forearm Plank', 'https://youtu.be/Ns1NS9ThNhI'),
  ('Bodyweight Seated Ab Circles', 'https://youtu.be/GflQ_ymx9Nw'),
  ('Stability Ball Stir the Pot', 'https://youtu.be/IfOtFv6zz8I'),
  ('Bodyweight Alternating Lateral Kick Through', 'https://youtu.be/1jCudOtlLsc'),
  ('Ring Hanging L Sit Flutter Kicks', 'https://youtu.be/Y7Ua1YRsqd0'),
  ('Slam Ball Russian Twist', 'https://youtu.be/qyZ0pAtgo_Y'),
  ('Single Arm Dumbbell Side Plank Reach Through', 'https://youtu.be/Ec9Ymqhe5i4'),
  ('Ab Wheel Kneeling Rollout', 'https://youtu.be/QB2Gj1QGfjQ'),
  ('Cable Seated Crunch', 'https://youtu.be/gQT76pz_X9Y'),
  ('Cable Kneeling Crunch', 'https://youtu.be/ToJeyhydUxU'),
  ('Medicine Ball V Up', 'https://youtu.be/E0WFCTnN728?si=YvTVZvOCRm_hjh2B'),
  ('Suspension Knee Tuck', 'https://youtu.be/z2tctrNfTrY'),
  ('Suspension Lateral Knee Tuck', 'https://youtu.be/nedEXGnhHak'),
  ('Suspension Archer Row', 'https://youtu.be/O0wf46CgVZg'),
  ('Single Arm Dumbbell Turkish Get Up', 'https://youtu.be/saYKvqSscuY'),
  ('Bodyweight Bear Crawl', 'https://youtu.be/8y-C1wUb-3c'),
  ('Stability Ball Knee Tuck', 'https://youtu.be/Q8MnsYG5sbk?si=8Aln2doES1PVTKQP'),
  ('Ring Hanging Leg Raise', 'https://youtu.be/IMWzJ7zkklA'),
  ('Parallette L Sit', 'https://youtu.be/lLu9U0G7Ogw'),
  ('Bodyweight Standing Walkout Plank', 'https://youtu.be/R6SMJ-TzgZo'),
  ('Ring Eccentric Pull Up', 'https://youtu.be/4vEoBieXyKk'),
  ('Bodyweight Ipsilateral Bird Dog', 'https://youtu.be/8e1m4FNO7t8'),
  ('Ring Eccentric Chin Up', 'https://youtu.be/QvgPN5XfDX8?si=0U64Q99rkmh8yNmO'),
  ('Single Arm Dumbbell Seated Shoulder External Rotation', 'https://youtu.be/HeY0G79zbGA?si=qV6g26pqatUMpDew'),
  ('Double Dumbbell Seated Cuban Rotation', 'https://youtu.be/oYGHjG0jZuA'),
  ('Double Dumbbell Cuban Rotation', 'https://youtu.be/_Cfrbn8dxH4'),
  ('Single Arm Cable Half Kneeling Contralateral Shoulder External Rotation 90 Degrees', 'https://youtu.be/Ff4Dg3T4pNQ?si=xU9cm-kpyPdrIwA0'),
  ('Miniband Fire Hydrant', 'https://youtu.be/gnzypKUFU6Y'),
  ('Medicine Ball Russian Twist', 'https://youtu.be/vT8p57mXVDo?feature=shared'),
  ('Bodyweight Side Plank', 'https://youtu.be/_R389Jk0tIo'),
  ('Cable Reverse Crunch', 'https://youtu.be/3Mn_4KTDTi0?si=3zBBQ33AQDN7XPp4'),
  ('Cable Rope Half Kneeling High to Low Chop', 'https://youtu.be/hUbRkz4AxkE'),
  ('Cable Rope Half Kneeling Low to High Chop', 'https://youtu.be/48LIxDpby_E?feature=shared'),
  ('Cable Rope Staggered Stance High to Low Chop', 'https://youtu.be/FFaeQW7hwYs?feature=shared'),
  ('Single Arm Dumbbell Windmill', 'https://youtu.be/EVLXzqAzAHI'),
  ('Bodyweight Feet On Wall Mountain Climber', 'https://youtu.be/jGwHfj957eU?si=i-ZtryUkm2Geud9J'),
  ('Slider Double Kettlebell Suitcase Reverse Lunge', 'https://youtu.be/1SlpUMsiiiw?si=WnEVv0WTROHdU4eR'),
  ('Bodyweight Hollow Body Hold', 'https://youtu.be/4xRpGgttca8'),
  ('Dumbbell Crush Grip Hollow Body Hold', 'https://youtu.be/Wo-pGZst6l0'),
  ('Bar Inverted Hanging Crunch', 'https://youtu.be/LXQTkeYPki8'),
  ('Slider Double Kettlebell Front Rack Reverse Lunge', 'https://youtu.be/-p1l0vXTtAU?si=ebEJZJZkoWYTDFbC'),
  ('Bodyweight Supine Alternating Single Leg Raise', 'https://youtu.be/IUCoqgdvDxU?si=8xtgp1M-mJqke2mR'),
  ('Bodyweight Supine Leg Raise', 'https://youtu.be/q0JVBRHoLz4'),
  ('Miniband Bicycle Crunch', 'https://youtu.be/q_c5MFYuza4'),
  ('Bodyweight Side Plank Reach Through', 'https://youtu.be/7lfNb_zydvQ'),
  ('Bodyweight Sit Up', 'https://youtu.be/bT8NVeDvuQg?si=paUR-bam-jwd-xPx'),
  ('Bodyweight Butterfly Sit Up', 'https://youtu.be/ZLyOWSPnVrM'),
  ('Slider Mountain Climber', 'https://youtu.be/fjHQIVIPLHY'),
  ('Slider Pike', 'https://youtu.be/vB803WCcQDk?si=hXUn4t23jP7Bn6R8'),
  ('Stability Ball Pike', 'https://youtu.be/-ciDJCuTu3A?si=zpBNDJ0Pbp7YfJOm'),
  ('Slider Wide Mountain Climber', 'https://youtu.be/d64d_6PE9fY'),
  ('Stability Ball Crunch', 'https://youtu.be/O4d3kd1ZLyc?si=xAr_I7jNLwrDm7lL'),
  ('Stability Ball Feet Elevated Oblique Crunch', 'https://youtu.be/fZZK29dMla0?si=BQpGveG4S8WqLjzv'),
  ('Stability Ball Kneeling Rollout', 'https://youtu.be/gi38qGKDzXY?si=XCqiGVtu482eeeTP'),
  ('Stability Ball Single Leg Knee Tuck', 'https://youtu.be/fv6mxdkTT60?si=1AhvmIbGHoW_9tm9'),
  ('Stability Ball Single Leg Pike', 'https://youtu.be/7skasCMLRL8'),
  ('Double Dumbbell Z Press', 'https://youtu.be/k_kXBEjURUA'),
  ('Double Dumbbell Romanian Deadlift', 'https://youtu.be/Cf3CaHui43A?si=dFPcP6jQEQECmXmY'),
  ('Single Arm Dumbbell Side Plank', 'https://youtu.be/2WxwO9E93wI'),
  ('Bodyweight Single Leg Glute Bridge', 'https://youtu.be/z4J188sFD4g'),
  ('Dumbbell Glute Bridge', 'https://youtu.be/JpDDoINkrog'),
  ('Bodyweight Glute Bridge Isometric with Alternating Single Leg Extension', 'https://youtu.be/cRCXEFhpBEI?si=6A2YpBsXM9WqT6rW'),
  ('Miniband Side Lying Clamshell', 'https://youtu.be/vSpyJR3dA7s?si=voo83Swm5kMbYEwl'),
  ('Miniband Ankle Side Lying Hip Abduction', 'https://youtu.be/bDvFd4EZt8M'),
  ('Miniband Bench Seated Hip Abduction', 'https://youtu.be/NeO0w4Jv4rs?si=zFKHnPvts0-arQgk'),
  ('Miniband Glute Bridge Hip Abduction', 'https://youtu.be/oS3cYfl6Bns'),
  ('Stability Ball Hip Thrust', 'https://youtu.be/4azLK_5vOqY?si=bceKCFzhvhSW5jXe'),
  ('Stability Ball Dumbbell Hip Thrust', 'https://youtu.be/x4lc8HocO1c'),
  ('Bodyweight Frog Pump', 'https://youtu.be/7IVoH7E4rWo'),
  ('Dumbbell Frog Pump', 'https://youtu.be/N6t2Fv0SKGc'),
  ('Cable Glute Kickback', 'https://youtu.be/qJxwJ1e1HxI?si=5y999i_uPybFFDol'),
  ('Bodyweight Single Leg Foot Elevated Glute Bridge', 'https://youtu.be/I7Zwyzr8COk'),
  ('Suspension Feet Elevated Glute Bridge', 'https://youtu.be/bZUGEwxZVks?si=GXDy3dTxYcWMuQpw'),
  ('Miniband Thigh Lateral Walk', 'https://youtu.be/34fVGXqWWs8'),
  ('Miniband Ankle Lateral Walk', 'https://youtu.be/N4tkpDMlqCQ'),
  ('Miniband Feet Lateral Walk', 'https://youtu.be/GxqfnFHLH6c'),
  ('Miniband Standing Glute Kickback', 'https://youtu.be/pdP0uJXvc44?si=lpmJ6krZopavsZrJ'),
  ('Barbell Hip Thrust', 'https://youtu.be/5S8SApGU_Lk'),
  ('Barbell Single Leg Hip Thrust', 'https://youtu.be/BMIy2gtjsTI?si=JnJL8ZiliAOk_Ac1'),
  ('Stability Ball Single Leg Foot Elevated Glute Bridge', 'https://youtu.be/LSUPiOJOA6M'),
  ('Miniband Standing Hip Abduction', 'https://youtu.be/dZNkjqKNUUs'),
  ('Miniband 3 Way Cha Cha', 'https://youtu.be/3SOcMYQWbDU'),
  ('Slider Single Arm Kettlebell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/5D-hSAvpFls?si=2EfexeMUADw51Wu2'),
  ('Cable Hip Abduction', 'https://youtu.be/saVSMtIttZE?si=qgSuj5ww8uiz2Wkd'),
  ('Miniband Wall Sit Hip Abduction', 'https://youtu.be/w5nYnnT1E9s'),
  ('Single Arm Dumbbell Half Kneeling Contralateral Overhead Press', 'https://youtu.be/4DUIY95jX6Y'),
  ('Cable Face Pull', 'https://youtu.be/l3prcz-3FbI?si=qvb-6gLh-aavLGWK'),
  ('Cable Seated Face Pull', 'https://youtu.be/4UhV4cCkugM'),
  ('Cable Guillotine Curl', 'https://youtu.be/KLM1hUecXbY'),
  ('Cable Supine Bicep Curl', 'https://youtu.be/hBC7lPyEkVM'),
  ('Cable Straight Bar High Bicep Curl', 'https://youtu.be/xaMJYDzqTZg'),
  ('Double Dumbbell Spider Curl', 'https://youtu.be/9Dd8iiEUs_Q?si=juy6zuf-MVn-W8j8'),
  ('EZ Bar Spider Curl', 'https://youtu.be/wtbHEt6Qi8g?si=wca7IhWcGWNDg2QX'),
  ('Stability Ball Cable Preacher Curl', 'https://youtu.be/uEjtuyC6-bc'),
  ('Single Arm Dumbbell Standing Concentration Curl', 'https://youtu.be/fOV-z1wARvs?si=pxr3u-XyVhL6BlD3'),
  ('EZ Bar Wide Grip Bicep Curl', 'https://youtu.be/xUdw3EtnTLM?si=6zj86RhHEsTUIlf4'),
  ('Single Arm Cable Standing High Bicep Curl', 'https://youtu.be/shIYFhPQVSo'),
  ('EZ Bar Seated Overhead Tricep Extension', 'https://youtu.be/QGK3RQ_Eexc?si=2Go8XA5nbKIfwUBr'),
  ('EZ Bar Overhead Tricep Extension', 'https://youtu.be/99qXUnFuQdM'),
  ('Barbell Thruster', 'https://youtu.be/aea5BGj9a8Y'),
  ('Bodyweight Diamond Push Up', 'https://youtu.be/XtU2VQVuLYs'),
  ('EZ Bar Lying Tricep Extension', 'https://youtu.be/fUW3C1lVWkk?si=uxeyIMMcnTpM46fm'),
  ('Cable Rope Overhead Tricep Extension', 'https://youtu.be/KvrP8c6eVBc?si=1EP-aMrXRtcbPO6b'),
  ('Single Arm Cable Reverse Grip Tricep Pushdown', 'https://youtu.be/pXd8vm-ZSOA?si=8_iZ3618RVjOmu3S'),
  ('EZ Bar Reverse Grip Bicep Curl', 'https://youtu.be/aIrvcBlNHBA'),
  ('Stability Ball Single Arm Dumbbell Chest Press', 'https://youtu.be/EQlfrWvaU6w'),
  ('Suspension Face Pull', 'https://youtu.be/3FVZDVJnvIA'),
  ('Landmine V Grip Row', 'https://youtu.be/gnikveF7dgI'),
  ('Double Dumbbell Thruster', 'https://youtu.be/u3wKkZjE8QM'),
  ('Single Arm Dumbbell Thruster', 'https://youtu.be/03aX4h5-EkA'),
  ('Single Arm Landmine Row', 'https://youtu.be/tiETx7VNDf0'),
  ('Superband Assisted Bar Pull Up', 'https://youtu.be/__TzXC-Hc_4?si=Z59SDF6EfXOY4pa_'),
  ('Stability Ball Prone Cobra', 'https://youtu.be/qt1WWg8QDg8?si=Go7eAWcyWu13yBIi'),
  ('Single Arm Dumbbell Overhead Carry', 'https://youtu.be/Pvs-dT7KPh4'),
  ('Double Dumbbell Pendlay Row', 'https://youtu.be/4-Jz3c_u1dw'),
  ('Cable Straight Bar Pullover', 'https://youtu.be/SgzJGLlAtok?si=p2bo--kETp2ajVVX'),
  ('Single Arm Cable Half Kneeling Lat Pulldown', 'https://youtu.be/4QDCC2gU5_E'),
  ('Single Arm Cable Half Kneeling Low Row', 'https://youtu.be/redrpTwkplw'),
  ('Single Arm Suspension Low Row', 'https://youtu.be/wH4TXGV8UyA?si=N8Y8Uk0A9glEeeuQ'),
  ('Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/93ZAdx24QVQ'),
  ('Barbell Pendlay Row', 'https://youtu.be/ezrZnmjZTR4'),
  ('Barbell Bench Press', 'https://youtu.be/SCVCLChPQFY'),
  ('Cable Single Leg Standing Bent Knee Hip External Rotation', 'https://youtu.be/1OnBBhiaQjY'),
  ('Cable Hip Rotation', 'https://youtu.be/ApvO0XTFjRc'),
  ('Barbell Bicep Curl', 'https://youtu.be/BVrlItPBX8M?si=4NJpARumV7sAFCki'),
  ('Barbell Overhead Press', 'https://youtu.be/43GSKivZnw4?si=OIfasYK8gG4sUDBW'),
  ('Barbell Push Press', 'https://youtu.be/iaBVSJm78ko'),
  ('Barbell Bent Over Row', 'https://youtu.be/9Gf-Ourup_k?si=qt-DlqHLDICtOmju'),
  ('Single Arm Landmine Meadows Row', 'https://youtu.be/e-c4gMcqdyw'),
  ('Cable Straight Bar Seated Bicep Curl', 'https://youtu.be/iWyvxI5A1cA?si=aBSi-dGZ6CxySnnU'),
  ('Cable Rope Skull Crusher', 'https://youtu.be/NfOLyLpoGII'),
  ('Single Arm Dumbbell Seated Cuban Press', 'https://youtu.be/KxPNCVXkvAg?si=pDMoju9bpHN_T9_7'),
  ('Bodyweight Wall Facing Handstand', 'https://youtu.be/yHuLx1J9orw'),
  ('Parallette Close Grip Push Up', 'https://youtu.be/hDH5pliNKoM?si=NTV941Sjf3NsUGDj'),
  ('Parallette Wide Push Up', 'https://youtu.be/UEZy-OmXdZs'),
  ('Barbell Front Raise', 'https://youtu.be/DL-HN35sxdg'),
  ('Single Arm Cable Front Raise', 'https://youtu.be/acozHQv1JLk'),
  ('Parallette Side Plank', 'https://youtu.be/d7PGNbhmQVM'),
  ('Cable Straight Bar Front Raise', 'https://youtu.be/PgSZlX32WTo'),
  ('Barbell Close Grip Bench Press', 'https://youtu.be/XEFDMwmrLAM'),
  ('Single Arm Cable Bicep Curl', 'https://youtu.be/Pu5p6uZGTZM?si=MoB-YCpKDesQD9Nn'),
  ('Single Arm Cable Shotgun Row', 'https://youtu.be/91nVZ7FLPyA?si=_khiKXF3khjyeuSP'),
  ('Cable Half Kneeling Face Pull', 'https://youtu.be/_1ATOXmanEw?si=7DN0OJcZ8jGgOQxp'),
  ('Single Arm Kettlebell Bent Over Row', 'https://youtu.be/9Q9gwoXHn1o'),
  ('Double Kettlebell Gorilla Row', 'https://youtu.be/Ln1j7lm6SrE'),
  ('Kettlebell Alternating Halo', 'https://youtu.be/wJcmanVh5EE'),
  ('Single Arm Kettlebell Overhead Press', 'https://youtu.be/CwhbuoGqyug?si=Q9nkDUY4NvpGPqak'),
  ('Kettlebell Horn Grip Bicep Curl', 'https://youtu.be/YzTfq9VaQKs'),
  ('Double Dumbbell Prone Row', 'https://youtu.be/scf3uLuAATg'),
  ('Double Kettlebell Z Press', 'https://youtu.be/6GbGvGvedOc'),
  ('Double Kettlebell Push Press', 'https://youtu.be/ekNrVv6G5v8'),
  ('Barbell Prone Row', 'https://youtu.be/pJzThQgKKxw'),
  ('Single Arm Dumbbell Cuban Press', 'https://youtu.be/XsV_KH5Xrng'),
  ('Single Arm Kettlebell Push Jerk', 'https://youtu.be/pRfJwVHLp6c'),
  ('Barbell Incline Bench Press', 'https://youtu.be/2jFFCy8JBU8?si=BCYplSL2-ewJ8kiB'),
  ('Double Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/2nJsZIScaVk'),
  ('Double Dumbbell Incline Bench Prone Y Raise', 'https://youtu.be/x4PRrxvYtwk?si=arNJc-zXL0vatJmL'),
  ('Suspension Face Pull to Overhead Press', 'https://youtu.be/a33rvhoBWYM'),
  ('Double Dumbbell Reverse Grip Bench Press', 'https://youtu.be/Cb5ZNB7Vf-0?si=_wFvEZ4u-wYsUhzm'),
  ('Single Arm Cable Seated Floor Lat Pulldown', 'https://youtu.be/N7FcfA7UFZk'),
  ('Double Dumbbell Suitcase Carry', 'https://youtu.be/p5MNNosenJc'),
  ('Double Dumbbell Cuban Press', 'https://youtu.be/XpcOM9Np9LQ?si=p-JIsZ-J0LYgrnEO'),
  ('Double Kettlebell Pendlay Row', 'https://youtu.be/KoOmLu7ms1s'),
  ('Double Kettlebell Half Kneeling Overhead Press', 'https://youtu.be/ZcUxxxNl1PA'),
  ('Single Arm Kettlebell Push Press', 'https://youtu.be/KUsZAGWd0VQ'),
  ('Double Kettlebell Push Jerk', 'https://youtu.be/U2w1H0oXhhg?si=OkR2U3VpYiRe81Eo'),
  ('Double Dumbbell Glute Bridge Isometric Floor Press', 'https://youtu.be/195-8CoZDgo'),
  ('Double Kettlebell Seesaw Overhead Press', 'https://youtu.be/55-ngw6hplo'),
  ('Alternating Double Kettlebell Z Press', 'https://youtu.be/DmC9vPYvU0g?si=mIpOJCXLUo_un5rT'),
  ('Bodyweight Burpee', 'https://youtu.be/auBLPXO8Fww'),
  ('Double Dumbbell Devil Press', 'https://youtu.be/SCOxIkPDqxM?si=JHtcK8O5k4voNCP2'),
  ('Alternating Single Arm Dumbbell Devil Press', 'https://youtu.be/l6_aD2IWEEA'),
  ('Double Kettlebell Seesaw Z Press', 'https://youtu.be/n54YmZS9uM4'),
  ('Double Plate Lu Raise', 'https://youtu.be/IeGDlglTK9M'),
  ('Plate Steering Wheel', 'https://youtu.be/ToHy85wT3KE?si=z9VmwQGWt8A86_Mc'),
  ('Suspension Cuban Press', 'https://youtu.be/ybVFLdr1_Vk?si=NGTNOkq-xBRDhbIF'),
  ('Barbell Decline Bench Press', 'https://youtu.be/6yGZ0KCaiWM'),
  ('Kettlebell Half Kneeling Alternating Halo', 'https://youtu.be/A2jT86tgnII'),
  ('Kettlebell Tall Kneeling Alternating Halo', 'https://youtu.be/9n3nSrJiuFE?si=oGT50V2Fg6jzr5X2'),
  ('Bodyweight Rolling Squat Burpee', 'https://youtu.be/phmcox-C8iA'),
  ('Kettlebell Tall Kneeling Alternating Hip to Halo', 'https://youtu.be/4frRMFUlaFs'),
  ('Barbell Seated Overhead Press', 'https://youtu.be/Mdx1V3v7E5g'),
  ('Dumbbell Crush Grip Z Press', 'https://youtu.be/_othSKjqF30'),
  ('Barbell Half Kneeling Overhead Press', 'https://youtu.be/HdsS7MO_KFs?si=6N85JwB13t24ha7T'),
  ('Barbell Tall Kneeling Overhead Press', 'https://youtu.be/j2slieruHx0?si=qsnkz69oUwDeE0hp'),
  ('Barbell Inverted Row', 'https://youtu.be/bHO0A4ZF_Zg'),
  ('Ring Row', 'https://youtu.be/xhlReCpAE9k')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);