UPDATE exercises AS e
SET video_url = v.url
FROM (VALUES
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/DS-pvuh8VEo?si=KEDC31EUxCubFjGj'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/iRHrBseKm0k?si=X-TqbB38SGkCSqnE'),
  ('Ring Bulgarian Row', 'https://youtu.be/5CxPrNkhm2k'),
  ('Alternating Double Kettlebell Rotational Overhead Press', 'https://youtu.be/VQKcF1HfsYk'),
  ('Alternating Double Kettlebell Push Press', 'https://youtu.be/kUgzuCAvO3A'),
  ('Macebell Ballistic Curl', 'https://youtu.be/e8aZdfRK4FE?si=VtO52sSIMj0T-KCF'),
  ('Single Arm Clubbell Pullover', 'https://youtu.be/JJgOmmqZneM?si=v93qv5Poy03NJqj_'),
  ('Double Clubbell Pullover', 'https://youtu.be/2ZYphWzJedw?si=f5GGOhThihsKqIds'),
  ('Clubbell Pullover', 'https://youtu.be/0sRFLvzcqxw?si=cqK8W0uEQdEUfDAy'),
  ('Clubbell Front Flag Press', 'https://youtu.be/3_F4oUpYY7Q?si=qgoqjkcK33CSqmX4'),
  ('Single Arm Ring Dead Hang', 'https://youtu.be/7J_x9uMtr-o?si=2tga8qG4urWcSCMT'),
  ('Single Arm Dumbbell Suitcase Deadlift', 'https://youtu.be/yMRbcOd51pA?si=7Hc1xBgOqKKuKw3C'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/7wCLqLLyHh0?si=hFc7L_yPlG-KnZVg'),
  ('Clubbell Torch Press', 'https://youtu.be/REUDhFnYMYc?si=13Shwx4VKvuvNLZh'),
  ('Single Arm Clubbell Torch Press', 'https://youtu.be/UU4WhE25JfI?si=6sinMuju_2nUhgZK'),
  ('Barbell Conventional Deadlift', 'https://youtu.be/op9kVnSso6Q'),
  ('Barbell Sumo Deadlift', 'https://youtu.be/wQHSYDSgDn8'),
  ('Barbell Rack Pull', 'https://youtu.be/zdaEWO0S5HU'),
  ('Barbell Snatch Grip Deadlift', 'https://youtu.be/0Ah-ol5EGlo'),
  ('Stability Ball Hyperextension', 'https://youtu.be/bmRTtzOOiVM'),
  ('Barbell Seated Good Morning', 'https://youtu.be/ZPeJ0s8X6Gs'),
  ('Barbell Good Morning', 'https://youtu.be/F8dCjzbed-4'),
  ('Bodyweight Wall Sit', 'https://youtu.be/SszDMOZvFuw'),
  ('Bodyweight Wall Slide Squat', 'https://youtu.be/3J99J5NxNSQ?si=Xv_W-o9GzT-nvtVQ'),
  ('Stability Ball Wall Slide Squat', 'https://youtu.be/lWJ6BujsDYY?si=Hl4kTZutf9b6tDUi'),
  ('Suspension Squat', 'https://youtu.be/MafftY-3lC0?si=bGTlr29qg0ZvBtT_'),
  ('Suspension Alternating Reverse Lunge', 'https://youtu.be/oRO4ailwZb4'),
  ('Bodyweight Squat to Bench', 'https://youtu.be/93l0NGCosAE'),
  ('Bodyweight Squat', 'https://youtu.be/C_VtOYc6j5c'),
  ('Bodyweight Hand Assisted Split Squat', 'https://youtu.be/WRCsxtCfrEE'),
  ('Bodyweight Walking Lunge', 'https://youtu.be/tlbTz6IamaE'),
  ('Dumbbell Goblet Squat', 'https://youtu.be/a-dqF4NL2K4'),
  ('Miniband Romanian Deadlift', 'https://youtu.be/N5lBa2zMAPI?si=Eth4HWtKMOXBXNx6'),
  ('Superband Resisted Skater Jump', 'https://youtu.be/VHBOyCCupJ4?feature=shared'),
  ('Cable Prone Single Leg Hamstring Curl', 'https://youtu.be/k6Vo8hBLypQ'),
  ('Bodyweight Candlestick Roll Up Tuck Jump', 'https://youtu.be/BpwGQP8k7aY'),
  ('Barbell Block Pull Deadlift', 'https://youtu.be/iVpVk8x-VDQ'),
  ('Barbell Box Back Squat', 'https://youtu.be/dLG78_Z9rjM'),
  ('Barbell Deficit Deadlift', 'https://youtu.be/PzoxegwRlOw'),
  ('Barbell Front Rack Squat', 'https://youtu.be/uYumuL_G_V0'),
  ('Barbell Glute Bridge', 'https://youtu.be/6EhYj5eSngY'),
  ('Barbell High Bar Back Squat', 'https://youtu.be/ultWZbUMPL8'),
  ('Barbell Power Clean', 'https://youtu.be/KwYJTpQ_x5A'),
  ('Barbell Power Snatch', 'https://youtu.be/TL8SMp7RdXQ'),
  ('Barbell Romanian Deadlift', 'https://youtu.be/LURGDIX3adY?si=fHh3AAX-mZB09HXi'),
  ('Barbell Back Rack Split Squat', 'https://youtu.be/KXUJxb8hO8U'),
  ('Barbell Stiff Legged Deadlift', 'https://youtu.be/5_t0SsovgW8?si=5Zg1x855TTmrp1cL'),
  ('Barbell Sumo Back Squat', 'https://youtu.be/qiQAsB0x-7k?si=OlWu0ou6Vr0NnuvE'),
  ('Bodyweight Pistol Squat', 'https://youtu.be/qDcniqddTeE?si=G4KPahZUmlQQChZ_'),
  ('Bodyweight Skater Squat', 'https://youtu.be/kRnLZadW5Q0'),
  ('Cable Pull Through', 'https://youtu.be/NEDrQPoITMc?si=ZeJ1LOUbzrjgk-_8'),
  ('Double Dumbbell Suitcase Bulgarian Split Squat', 'https://youtu.be/G0Mo2LF8uLU'),
  ('Double Dumbbell Suitcase Step Up', 'https://youtu.be/37tVohr7LcE'),
  ('Double Dumbbell Suitcase Deficit Split Squat', 'https://youtu.be/jqWAqPQvqAk'),
  ('Double Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/t7DBjlOTwAk'),
  ('Double Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/Lsen4vH1nm8'),
  ('Double Dumbbell Suitcase Split Squat', 'https://youtu.be/yqH8u037IjM'),
  ('Double Dumbbell Front Rack Alternating Step Up', 'https://youtu.be/anHX8Zp67C8?si=qbb7ETCqekLaflB_'),
  ('Bodyweight Face the Wall Squat', 'https://youtu.be/pktIjwNiuYE?si=fWFt85clM0T2gopP'),
  ('Bodyweight Feet Elevated Glute Bridge', 'https://youtu.be/kFvF6ZHv-KI'),
  ('Slider Kettlebell Goblet Reverse Lunge', 'https://youtu.be/8k08cvYq-n8?si=bbPqV1XKB99kPfpP'),
  ('Miniband Thigh Monster Walk', 'https://youtu.be/po3I8qoRC2c?si=XeJ7Tq5PXt3WLJfl'),
  ('Bodyweight Quadruped Hip Extension', 'https://youtu.be/1UwyzWjFx5k'),
  ('Suspension Pistol Squat', 'https://youtu.be/K7qfUjKf9rU'),
  ('Suspension Skater Squat', 'https://youtu.be/YyBeT4WWBk4'),
  ('Bodyweight Tuck Jump', 'https://youtu.be/vgB_eWuvGW8?si=anQ4gfG2ik-Y_uU9'),
  ('Bodyweight Alternating Single Leg Wall Sit', 'https://youtu.be/eYGszeFcI7Y?si=jFOFuzza1JQMYuVE'),
  ('Bodyweight Single Leg Romanian Deadlift Jump', 'https://youtu.be/EmmP-jsvVJE'),
  ('Double Dumbbell Overhead Walking Lunge', 'https://youtu.be/TBw3mPrKAIs'),
  ('Bodyweight Reverse Nordic', 'https://youtu.be/GbpDfXXKuk0?si=IsPMd_J3d72xrMcZ'),
  ('Bodyweight Alternating Lateral Bench Jump', 'https://youtu.be/pVoOtkGBN6s'),
  ('Single Arm Dumbbell Front Rack Squat', 'https://youtu.be/1VzKnqCcUJ4'),
  ('Bodyweight Skater Jump', 'https://youtu.be/CaN4zfIPyXU'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/t8OkcdLjRFQ'),
  ('Cable Prone Bench Hamstring Curl', 'https://youtu.be/IalP0lgYPnc'),
  ('Bodyweight Bulgarian Split Squat Jump', 'https://youtu.be/CWTu90BUTIY?si=9JSuKmfFRaalZ6er'),
  ('Cable Standing Single Leg Hamstring Curl', 'https://youtu.be/tkh43Yc0tEs'),
  ('Bodyweight Nordic Hamstring Curl', 'https://youtu.be/kjv4WQXWl_A'),
  ('Superband Assisted Pistol Squat', 'https://youtu.be/szRINrcALyI'),
  ('Double Dumbbell Front Rack Squat', 'https://youtu.be/B86Zj72LwzA'),
  ('Double Dumbbell Suitcase Walking Lunge', 'https://youtu.be/KdE6b_r7wxA'),
  ('Barbell Back Rack Walking Lunge', 'https://youtu.be/ZPoMxOrIeO4'),
  ('Bodyweight Box Pistol Squat', 'https://youtu.be/Ly71LeprFKQ'),
  ('Barbell Overhead Squat', 'https://youtu.be/pn8mqlG0nkE'),
  ('Landmine Goblet Squat', 'https://youtu.be/oTRl7p13XtY'),
  ('Stability Ball Hamstring Curl', 'https://youtu.be/d-FBclT8W0g?si=wl1sJCzk2Z5PCnwx'),
  ('Slider Hamstring Curl', 'https://youtu.be/UaecXxAgsKA'),
  ('Bodyweight Hamstring Walkout', 'https://youtu.be/GcV2LB0qqnY?si=PoIiYCAOL0uaDuPR'),
  ('Slider Dumbbell Goblet Reverse Lunge', 'https://youtu.be/tWmzgpoOUls?si=Fmrp6-y_e5qk2SNJ'),
  ('Bodyweight Dragon Squat', 'https://youtu.be/bQY7fLEkZqU'),
  ('Stability Ball Single Leg Hamstring Curl', 'https://youtu.be/cuM7OBHSVow'),
  ('Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/HLDhxSqMQyE'),
  ('Barbell Overhead Walking Lunge', 'https://youtu.be/m6MczOv_Ayg'),
  ('Barbell Squat Clean', 'https://youtu.be/EKRiW9Yt3Ps'),
  ('Single Arm Landmine Hack Squat', 'https://youtu.be/hwd_6Y9YKvI'),
  ('Resistance Band Shoulder Dislocates', 'https://youtu.be/5yPvjJOqbg4?si=1OYvLb1R7Zq_hl94'),
  ('Suspension Reverse Grip Bicep Curl', 'https://youtu.be/yewf3adybcc?si=-PZ9RsGl7FC8vp7J'),
  ('Cable Straight Bar Reverse Grip Bicep Curl', 'https://youtu.be/RLlT3qbVS3Q?si=SYASKBhplBkTNYee'),
  ('Single Arm Cable Reverse Grip Bicep Curl', 'https://youtu.be/SIuDkLLlL6E?si=_Y_P-I5PU4GP5LRy'),
  ('Bar Eccentric Chin Up', 'https://youtu.be/B1nRr__KiNk?si=5PGKtxdEbPpVW1Ds'),
  ('Bar Eccentric Pull Up', 'https://youtu.be/T4Jv__fWjZ8?si=sbUarOu5VD7qBK4s'),
  ('Landmine Half Kneeling Oblique Twist', 'https://youtu.be/HGzu8tvh79U'),
  ('Single Arm Bar Dead Hang', 'https://youtu.be/uyNR71ZCrho?si=blbw-wn6NHBGbR9y'),
  ('Single Arm Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/UF_oINIojVQ?si=nyrZ0y91pz4IIfOs'),
  ('Alternating Double Kettlebell Tall Kneeling Overhead Press', 'https://youtu.be/2kWWWRpk6Co?si=gy0bI1KIAsGs2hhI'),
  ('Alternating Double Kettlebell Half Kneeling Overhead Press', 'https://youtu.be/V3wxOSo53mQ?si=cM14QdTRQfd_FXUt'),
  ('Stability Ball Single Arm Forearm Plank', 'https://youtu.be/J3JZR2SFknM'),
  ('Stability Ball Feet Elevated Single Arm Forearm Plank', 'https://youtu.be/PAFvOAPjKwk'),
  ('Landmine Zercher Skater Squat', 'https://youtu.be/avCA3xXb9hg'),
  ('Single Arm Landmine Front Rack Contralateral Reverse Lunge to Shoulder Press', 'https://youtu.be/h2bPSv9ka_o'),
  ('Landmine Thruster', 'https://youtu.be/jLvQenjeus8'),
  ('Landmine Romanian Deadlift', 'https://youtu.be/x5wWyQ-2k2E?feature=shared'),
  ('Single Arm Landmine Single Leg Romanian Deadlift', 'https://youtu.be/rzJse5Ds98k'),
  ('Landmine Tall Kneeling Oblique Twist', 'https://youtu.be/OCMcVEdK5vw'),
  ('Landmine Feet Elevated Russian Twist', 'https://youtu.be/Zb-l68-4KFM'),
  ('Single Arm Landmine Thruster', 'https://youtu.be/EcUficjayCY'),
  ('Double Kettlebell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Ke5Erzd3NjE?si=fOzgTGBaC6CMWfE6'),
  ('Landmine Zercher Curtsy Lunge', 'https://youtu.be/e7jkuKuWcZ0'),
  ('Barbell Back Rack Alternating Cossack Squat', 'https://youtu.be/YZQP6D9LP4E'),
  ('Barbell Front Rack Alternating Cossack Squat', 'https://youtu.be/_AEuTTkYzjg'),
  ('Dumbbell Goblet Alternating Cossack Squat', 'https://youtu.be/glbP_VzHNkw?si=1k1fGSYRRORQv7W8'),
  ('Bodyweight Alternating Cossack Squat', 'https://youtu.be/dhDjKmTX8tU'),
  ('Bodyweight Knee Over Toe Split Squat', 'https://youtu.be/ufsoFnFCqA4'),
  ('Barbell Back Rack Knee Over Toe Split Squat', 'https://youtu.be/RBcrPYSWQb8'),
  ('Barbell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/q7zJZAexRmc'),
  ('EZ Bar Incline Bench Lying Tricep Extension', 'https://youtu.be/vJuyPyyEdTs?si=_MMem5dVaaarfRRu'),
  ('EZ Bar Skull Crusher', 'https://youtu.be/eiCMrII3j9k?si=J2G1ZmeiFQDhnfxT'),
  ('Slider Knee Tuck', 'https://youtu.be/vx9j9l18pyE?si=U7boXKing8U74cQZ'),
  ('EZ Bar Incline Bench Skull Crusher', 'https://youtu.be/9VtEoirFmT8?si=B904_aTFyPDoEqMp'),
  ('EZ Bar Decline Bench Skull Crusher', 'https://youtu.be/XFBsHDastRI?si=rP6H63ZVPOndCThK'),
  ('EZ Bar Front Raise', 'https://youtu.be/N4HLFIr5H4A?si=l2WKwgNX9fExG7xF'),
  ('Suspension Pike', 'https://youtu.be/MkmpHj0T3OQ'),
  ('Suspension Side Plank Reach Through', 'https://youtu.be/9PiqAsdkh6Q'),
  ('Bodyweight Cocoon Crunch', 'https://youtu.be/BZWoijzyF_4?si=2gKtoX0oa_Lef7o8'),
  ('Ab Wheel Standing Rollout', 'https://youtu.be/SFTn_VON9qw'),
  ('Cable Fire Hydrant', 'https://youtu.be/P4cP-juNM1Q'),
  ('Cable Tall Kneeling Pull Through', 'https://youtu.be/5mkpuBI-2Ls'),
  ('Bodyweight Bent Knee Reverse Hyperextension', 'https://youtu.be/RbkVHCMU3xU'),
  ('Parallette Tuck L Sit', 'https://youtu.be/VhqEdeeAyvg'),
  ('EZ Bar Close Grip Bicep Curl', 'https://youtu.be/o1c9wFYt6FA?feature=shared'),
  ('EZ Bar Overhead Press', 'https://youtu.be/_5VJKCjn8YE?feature=shared'),
  ('Parallette Single Leg L Sit', 'https://youtu.be/V3hnphPbiAg'),
  ('Stability Ball Windshield Wiper', 'https://youtu.be/tVfP2_HkXEc'),
  ('Stability Ball Tall Kneeling Balance', 'https://youtu.be/wIkwr6LV9E8?si=WttWmNStYjInstEN'),
  ('Stability Ball Forearm Plank', 'https://youtu.be/4xODTD0UL-o?si=TSlUT4Fa309FslEb'),
  ('Slider Double Kettlebell Suitcase Lateral Lunge', 'https://youtu.be/bAaaXP2xb8E?si=AOaxE4RzaGKjiq0h'),
  ('Slider Kettlebell Horn Grip Lateral Lunge', 'https://youtu.be/OsP6_mqxBDI?si=Kdp1ECOmqjUFcNM9'),
  ('Single Arm Dumbbell Turkish Sit Up', 'https://youtu.be/h9OYpweuJEc'),
  ('Single Arm Landmine Turkish Sit Up', 'https://youtu.be/EhYVfy1KUUA'),
  ('Double Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/xkL1f4yewf0'),
  ('Double Dumbbell Turkish Sit Up', 'https://youtu.be/SreLOxzaIX4'),
  ('Single Arm Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/_FjMUe0AhTY'),
  ('Single Arm Kettlebell Overhead Cyclist Squat', 'https://youtu.be/PSRoSLw3GME'),
  ('Double Dumbbell Front Rack Alternating Cossack Squat', 'https://youtu.be/JFeG8YiLYmk'),
  ('Kettlebell Horn Grip Cyclist Squat', 'https://youtu.be/TysYZ7rKhpM'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Cyclist Squat', 'https://youtu.be/x8bLCSXTChA'),
  ('EZ Bar Seated Overhead Press', 'https://youtu.be/-MwL_9KOv7U?si=z-KgUayvNC37N78i'),
  ('Double Dumbbell Suitcase Knee Over Toe Split Squat', 'https://youtu.be/2U58iHm7oSM'),
  ('EZ Bar Close Grip Bench Press', 'https://youtu.be/yoS-cVxq28Q?si=hPjefaZ8jY6Ugoh_'),
  ('EZ Bar Close Grip Incline Bench Press', 'https://youtu.be/PEH5Ncie81g?si=F2eXxzjoehGGc9Bb'),
  ('EZ Bar Close Grip Decline Bench Press', 'https://youtu.be/K40CGYdAysc?si=AY-3wTXsp03-uRQ_'),
  ('Cable Half Kneeling Pallof Press', 'https://youtu.be/7JBR6JGE1hY'),
  ('Barbell Kneeling Rollout', 'https://youtu.be/AEfj6Lnn0Ao'),
  ('Barbell Reverse Grip Overhead Press', 'https://youtu.be/ZO_ALQcMaq4?si=Sv5NmxfQj3aIKU84'),
  ('Cable Tall Kneeling Pallof Press', 'https://youtu.be/EtEPKajf0PE'),
  ('Tire Sledge Hammer Staggered Stance Slam', 'https://youtu.be/ykhGpORlJ4Y?si=6hFSwmMbG1lGLXki'),
  ('Barbell Hang Power Clean', 'https://youtu.be/0aP3tgKZcHQ'),
  ('Landmine Goblet Alternating Cossack Squat', 'https://youtu.be/N549md2Wu2A'),
  ('Landmine Low Hold Alternating Cossack Squat', 'https://youtu.be/PnBI0wLBZIg'),
  ('Bodyweight Push Up', 'https://youtu.be/_l3ySVKYVJ8?si=PZh3DAAcRNF9txaZ'),
  ('Barbell Close Grip Incline Bench Press', 'https://youtu.be/wbI4qof1454?si=WRjRCDTcll5n5uKu'),
  ('Double Dumbbell Push Press', 'https://youtu.be/JqztIwOb4Hs?si=89lHhxGXew7SEPqj'),
  ('Single Arm Dumbbell Push Press', 'https://youtu.be/-TVuoR8URxg?si=RsWhCdjyNahveL9y'),
  ('Alternating Double Dumbbell Push Press', 'https://youtu.be/Kn3oZ9MNAhg?si=j1DYyyohu1ImlWt4'),
  ('Cable Rope Tall Kneeling Overhead Tricep Extension', 'https://youtu.be/cDMXXH7Y9AM?si=pObK3p_2FqS0HqbC'),
  ('Alternating Double Kettlebell Push Jerk', 'https://youtu.be/4wXnxXq4hX4?si=21E2nrYJROeQgBUm'),
  ('Double Dumbbell Push Jerk', 'https://youtu.be/oWfLP7JFwTg?si=UbP4KHHXrg5hVRnc'),
  ('Alternating Double Kettlebell Overhead Press', 'https://youtu.be/KMKqAY-T3wE?si=DccwyejeKVDgXRV-'),
  ('Single Arm Dumbbell Push Jerk', 'https://youtu.be/r-yDtVg8Yf0?si=XQ5L1OU_VTCHZWRf'),
  ('Alternating Double Dumbbell Push Jerk', 'https://youtu.be/ZQ653_FImKw?si=O2ttj0r4a_Nbkwq1'),
  ('Double Kettlebell Bottoms Up Floor Press', 'https://youtu.be/BDCAkIEOPvE?si=ouPFKCSuMS-REkBT'),
  ('Single Arm Kettlebell Bottoms Up Floor Press', 'https://youtu.be/uk39UR9K25Y?si=s6ejJf9GtQ4llbjw'),
  ('Trap Bar Bent Over Row', 'https://youtu.be/aNllFax4shk?si=J0w79P4ud8wpm67U'),
  ('Trap Bar Pendlay Row', 'https://youtu.be/d5rLWfIN9fo?si=iiKqMHW4Xr9OMyaR'),
  ('Trap Bar Shrug', 'https://youtu.be/DjFdFkeXSDM?si=RIA3ok7NhzuAj8LK'),
  ('Bodyweight Tuck L Sit', 'https://youtu.be/U9Z7WWNm1d4?si=pWSS4MOr8iZXWiNj'),
  ('Parallette Straddle L Sit', 'https://youtu.be/F6o417SxU1g'),
  ('Battle Rope Power Slam', 'https://youtu.be/7wDx6mZDxA8?si=rDE21yzc81AXz5sw'),
  ('Bodyweight Manna', 'https://youtu.be/L7reIo5f6uo'),
  ('Ring Tuck Back Lever', 'https://youtu.be/SZV1-ts76CM'),
  ('Ring Full Back Lever', 'https://youtu.be/ZFEy1s_N820'),
  ('Trap Bar Floor Press', 'https://youtu.be/4C4LDf-eZ5A?si=Uh-L_Lu-0xta0H-S'),
  ('Trap Bar Overhead Press', 'https://youtu.be/Vorw1hVd_Dc?si=CRIVCwpCzzeBwN26'),
  ('Ring Tuck Front Lever', 'https://youtu.be/JxlKAuD9gkA'),
  ('Ring Straddle Front Lever', 'https://youtu.be/eI-15uPc0yE'),
  ('Ring Full Front Lever', 'https://youtu.be/rB9EcLohiVs'),
  ('Ring Inverted Hang', 'https://youtu.be/txtXtF2-4S0'),
  ('Single Arm Barbell Kneeling Rollout', 'https://youtu.be/i-JO6pBsKWk'),
  ('Trap Bar Tall Kneeling Overhead Press', 'https://youtu.be/ILFSDv6TaiY?si=0iUQUtwUMsGFbVuI'),
  ('Trap Bar Bench Press', 'https://youtu.be/8TIFsF_HU_8?feature=shared'),
  ('Alternating Double Dumbbell Z Press', 'https://youtu.be/dsTU2qm4ef0?si=sT2aw7NxeFtfYYNV'),
  ('Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/HZM84steEyw?si=wN3l2SpjKBFPTIbD'),
  ('Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/y0t2PFFwSe4?si=VjtJz1Dg61jGQIZ9'),
  ('Alternating Double Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/UhOs_Wvckvs?si=FqNmpb8ECh_Y-9rl'),
  ('Alternating Double Dumbbell Half Kneeling Overhead Press', 'https://youtu.be/12MxAGiIgK8?si=pO89QghXz2Ykj1lb'),
  ('Single Arm Dumbbell Tall Kneeling Overhead Press', 'https://youtu.be/QVFklRHtJxY?si=D_kiEaZg-5pSrfHL'),
  ('Double Plate Incline Bench Prone Y Raise', 'https://youtu.be/VHeZJHEj6ic?si=DTfOrwFveTP-memt'),
  ('Single Arm Kettlebell Pendlay Row', 'https://youtu.be/VOmnhGvccZ0?feature=shared'),
  ('Barbell Floor Press', 'https://youtu.be/YdiVxhxufG8?si=pMAxf531BcAPvatO'),
  ('Ring Plank', 'https://youtu.be/p3zS2AMqGlg'),
  ('Single Arm Ring Plank', 'https://youtu.be/_Iev7PLP6QY'),
  ('Battle Rope Alternating Outward Circle', 'https://youtu.be/O2HVcPD3wKQ?si=CFVI8GpHxTsirv6u'),
  ('Ring Support Hold', 'https://youtu.be/kONbxg4kzkE'),
  ('Ring Side Plank', 'https://youtu.be/PQ3Vz8fp73k'),
  ('Barbell Reverse Grip Bent Over Row', 'https://youtu.be/cZvQNvTUUu0?si=SqA3lYAZBc0jOnvn'),
  ('Macebell Offset Bent Over Row', 'https://youtu.be/OXl94TQd_vw?si=AMXpvOM-H382GJoz'),
  ('Macebell Reverse Grip Offset Bent Over Row', 'https://youtu.be/igNnqZZ69JM?si=xaqrnAFrW4r7NuVR'),
  ('Bodyweight Hollow Body Rock', 'https://youtu.be/p7j02V1fIzU'),
  ('Single Arm Dumbbell Power Snatch', 'https://youtu.be/3mlhF3dptAo'),
  ('Alternating Single Arm Dumbbell Power Snatch', 'https://youtu.be/OktkfRlGcns'),
  ('Single Arm Dumbbell Squat Snatch', 'https://youtu.be/etK3OPjM3S4'),
  ('Alternating Single Arm Dumbbell Squat Snatch', 'https://youtu.be/T0_a2xijJBE'),
  ('Single Arm Cable Single Leg Romanian Deadlift', 'https://youtu.be/OC_7QIo0uk4'),
  ('Double Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/6caQpfXMvyw?si=WY0XcdcIUuE20g-o'),
  ('Single Arm Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/AlxuA22ymwg?si=-tgz7djxN0QKxXfA'),
  ('Double Kettlebell Front Rack Step Up', 'https://youtu.be/wcnuhd6RHwE'),
  ('Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/jHpBzpxK16c?si=3sB9wGkke_B632ad'),
  ('Single Arm Dumbbell Incline Bench Prone Row', 'https://youtu.be/4Bv94e_ufjo?si=8V5SPIIuNai7zUm3'),
  ('Single Arm Dumbbell Spider Curl', 'https://youtu.be/Ew2ZzKqICfA?si=Irq2jLSDxKiagY3F'),
  ('Double Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/STeIzkHm6tE?si=BxEJOKh_KtwNSMK_'),
  ('Double Dumbbell Seated Good Morning', 'https://youtu.be/x5nnk8hUBo4'),
  ('Bodyweight Hip Thrust', 'https://youtu.be/OAhvIWLC0rc'),
  ('Single Arm Kettlebell Bottoms Up Incline Bench Press', 'https://youtu.be/SoVCwno_9z8?si=BCvfBOVPW_aHbvZ_'),
  ('Alternating Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/rAoi4_AI7VA?si=b6KXmXEYoxIPmTt2'),
  ('Single Arm Kettlebell Incline Bench Prone Row', 'https://youtu.be/gPX8OmnYmQY?si=UgQnJkh9n3OobTcZ'),
  ('Single Arm Dumbbell Overhead Contralateral Bulgarian Split Squat', 'https://youtu.be/z7rygloAW30?si=p4kPPZcAKammq1Vv'),
  ('Double Kettlebell Suitcase Step Up', 'https://youtu.be/3HUEab31fks?si=B2OmGKfwSuXhts1z'),
  ('Single Arm Kettlebell Suitcase Contralateral Step Up', 'https://youtu.be/lMADALbx1eM?si=wJjWrYeLHPKqVgHh'),
  ('Double Kettlebell Overhead Step Up', 'https://youtu.be/eKUmMljLcKw?si=ocsvBon7ivrRziM6'),
  ('Kettlebell Half Kneeling Low to High Chop', 'https://youtu.be/wPXdGwc0NTs'),
  ('Single Arm Kettlebell Windmill', 'https://youtu.be/3rtUK_jUv4s'),
  ('Kettlebell Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Alternating Single Arm Kettlebell Plank Pull Through', 'https://youtu.be/fKbu_2L94x8'),
  ('Single Arm Kettlebell Swing', 'https://youtu.be/kneGICiz30g'),
  ('Double Kettlebell Bottoms Up Bench Press', 'https://youtu.be/bIzD1Z_C0cA'),
  ('Single Arm Kettlebell Suitcase Deadlift', 'https://youtu.be/1hcAoywwuRI'),
  ('Single Arm Kettlebell Clean', 'https://youtu.be/TQT7hBXVcOo'),
  ('Single Arm Kettlebell Clean to Overhead Press', 'https://youtu.be/JtlYyc5MaAc'),
  ('Alternating Single Arm Dumbbell Pendlay Row', 'https://youtu.be/7zKQ79awAvY?feature=shared'),
  ('Single Arm Kettlebell Snatch', 'https://youtu.be/VdNC_xicfyg'),
  ('Kettlebell Sumo Deadlift', 'https://youtu.be/odS65TnXgU0?si=l3QM9Nb4wHNt_JgK'),
  ('Single Arm Kettlebell Turkish Get Up', 'https://youtu.be/sgd8n917Zv0'),
  ('Kettlebell Goblet Squat', 'https://youtu.be/f-Vf2yRRqOg'),
  ('Single Arm Kettlebell Overhead Squat', 'https://youtu.be/nrfDq0DUhrE'),
  ('Double Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/vcMZNgn5G9c'),
  ('Single Arm Kettlebell Bottoms Up Bench Press', 'https://youtu.be/NIytPzrQ460?si=hBsVxzSTE6ddOTCD'),
  ('Single Arm Kettlebell Turkish Sit Up', 'https://youtu.be/KpufjJRtyPc'),
  ('Double Kettlebell Turkish Sit Up', 'https://youtu.be/RttCwCerCiM'),
  ('Double Kettlebell Turkish Sit Up to Z Press', 'https://youtu.be/UcLpNnWX8vE'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Cossack Squat', 'https://youtu.be/aJGPHYsiyTM'),
  ('Double Kettlebell Swing', 'https://youtu.be/fOPqk1FA4HU'),
  ('Double Kettlebell Front Rack Squat', 'https://youtu.be/JoT4bHnzTMw?si=i8z5wbuObKGVIl4_'),
  ('Single Arm Kettlebell Front Rack Squat', 'https://youtu.be/Wqg4NY5XAkU'),
  ('Single Arm Kettlebell Front Rack Contralateral Split Squat', 'https://youtu.be/-Z8NXAi59SE'),
  ('Single Arm Kettlebell Front Rack Carry', 'https://youtu.be/M39871Puz6c'),
  ('Single Arm Kettlebell Squat Clean', 'https://youtu.be/FZ8mMUwnCQs'),
  ('Double Kettlebell Prone Row', 'https://youtu.be/hUG_dolsaPE?si=_fw03cFT8VfLVtzo'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/0i2Aa8gV-VY?si=Z7AGqRY1Hod9Fwti'),
  ('Double Kettlebell Bottoms Up Front Rack Carry', 'https://youtu.be/F19T2zGlPGA'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Walking Lunge', 'https://youtu.be/FvSL8slKKHY'),
  ('Alternating Double Kettlebell Prone Row', 'https://youtu.be/OD7URB1yHAo?si=UX_3VmEfO_WpeiuT'),
  ('Double Kettlebell Single Leg Romanian Deadlift', 'https://youtu.be/JkKxFADvLvk'),
  ('Double Kettlebell Romanian Deadlift', 'https://youtu.be/Xa8hHIwOHe4'),
  ('Single Arm Kettlebell Contralateral Single Leg Romanian Deadlift', 'https://youtu.be/9u_Fccgk9Ys'),
  ('Single Arm Kettlebell Bottoms Up Overhead Squat', 'https://youtu.be/j0aAMnMp0yU'),
  ('Single Arm Kettlebell Prone Row', 'https://youtu.be/QSbH7gNkBtc?si=ngxTS90XoTuvQDxs'),
  ('Parallette Tuck Planche', 'https://youtu.be/3WVToPNWjVk'),
  ('Macebell Offset Bicep Curl', 'https://youtu.be/xkyQtEH8fxM?si=Zh1mTKcYEFs382Sk'),
  ('Parallette L Sit to Tuck Planche', 'https://youtu.be/NUvTsZxo5nk'),
  ('Landmine Standing Oblique Twist', 'https://youtu.be/4dGj7rES9pY'),
  ('Cable Rope Tall Kneeling High to Low Chop', 'https://youtu.be/h-af-afj-Xg'),
  ('Single Arm Parallette Plank', 'https://youtu.be/NrkFLTzLuSM'),
  ('Single Arm Suspension Plank', 'https://youtu.be/hetklTC7y4M?si=gHU6ufU8oAcg21Jv'),
  ('Battle Rope Russian Twist', 'https://youtu.be/_-kclLM0Mak'),
  ('Bodyweight Bird Dog Knee to Elbow', 'https://youtu.be/1v4_Vsvk3gc'),
  ('Slam Ball Feet Elevated Russian Twist', 'https://youtu.be/W1FXse115qs'),
  ('Medicine Ball Feet Elevated Russian Twist', 'https://youtu.be/IdEocZzdUNY'),
  ('Alternating Double Dumbbell Prone Row', 'https://youtu.be/Ry9HwpfUbd8?si=oY89SBibCyKMJ7CT'),
  ('Bodyweight Forearm Plank Alternating Knee to Elbow', 'https://youtu.be/A_JgZzr6o-k'),
  ('Bodyweight Loaded Beast to Alternating Kick Through', 'https://youtu.be/lhh2tGD_47g'),
  ('Single Arm Dumbbell Prone Row', 'https://youtu.be/-fuxiCQvMxQ?si=lCRmzsfrTeNaP0Gk'),
  ('Double Kettlebell Clean', 'https://youtu.be/8tFmEJ9ElaM'),
  ('Double Kettlebell Snatch', 'https://youtu.be/5WNcWPHXRZ0'),
  ('Battle Rope Feet Elevated Russian Twist', 'https://youtu.be/XdKaa2lHuic'),
  ('Superband Dead Bug', 'https://youtu.be/wCwn7-Z-XjE'),
  ('Parallette V Sit', 'https://youtu.be/oBmFzeay6Z8?si=dliVO8cgoAWNKwT3'),
  ('Double Kettlebell Split Jerk', 'https://youtu.be/6sbNXcg-R0Y'),
  ('Double Kettlebell High Pull', 'https://youtu.be/zfWpy9oMOqc?si=8gZawgsKgTeeGHck&amp;utm_source=MTQxZ'),
  ('Superband Pallof Press', 'https://youtu.be/TvPRtxN8uoA'),
  ('Superband Half Kneeling Pallof Press', 'https://youtu.be/V-SoYj9uQV8'),
  ('Ring Archer Row', 'https://youtu.be/s1Cuq185q6Y?si=TNXwSjV_mkE_2ty0'),
  ('Single Arm Landmine Row to Rotational Shoulder Press', 'https://youtu.be/f-sh_ImlQUo'),
  ('Bodyweight Hand Assisted Skater Squat', 'https://youtu.be/DExb7UaAlbg'),
  ('Superband Pull Through', 'https://youtu.be/ZuKowDpVVXM'),
  ('Miniband Quadruped Hip Extension', 'https://youtu.be/k30hN0vhlsY?si=ycYwNbMrFEnA94pG'),
  ('Cable Hip Adduction', 'https://youtu.be/UyXncDziNGo?si=W4GuZaUvoWtiIOxj'),
  ('Superband Tall Kneeling Pallof Press', 'https://youtu.be/yUzjX1LdySo?si=2LpxjTl8N8OHsKqd'),
  ('Slider Eccentric Hamstring Curl', 'https://youtu.be/vcCVej7p_vc'),
  ('Landmine Low Hold Lateral Lunge', 'https://youtu.be/VTtLrBvHoJ8'),
  ('Double Kettlebell Sumo Deadlift', 'https://youtu.be/4m288BpgfcQ'),
  ('Slider Kneeling Reach Push Up', 'https://youtu.be/-RTSF7qbrhs?si=hznPEKw9aLONjGpz'),
  ('Slider Parallette Knee Tuck', 'https://youtu.be/Kj89v76f-l8?si=_B0Uc1Xs1x1S0G_M'),
  ('Superband Shoulder Dislocates', 'https://youtu.be/MPtMYQH9vvg?si=eEJrNr3oqGzcma8_'),
  ('Superband Alternating Shoulder Dislocates', 'https://youtu.be/AJmPEWu4FiM?si=0h2x72A-kGfK3a_0'),
  ('Superband Prone Shoulder Dislocates', 'https://youtu.be/3WOAWkEKZGA?si=lSddj94elx-N7ZKJ'),
  ('Ring L Sit', 'https://youtu.be/lwcHmXvw-T4'),
  ('Resistance Band Prone Shoulder Dislocates', 'https://youtu.be/YwELfevh5vs?si=tmPYSbe-vfbiD0vx'),
  ('Cable Straight Bar Spider Curl', 'https://youtu.be/zGyaLrwHJjs?si=sg4m9llWui7pmOT_'),
  ('Double Kettlebell Bottoms Up Front Rack Squat', 'https://youtu.be/IvN-CSDnvoc'),
  ('Barbell Back Rack Cyclist Squat', 'https://youtu.be/TT7Ra3TnlZY'),
  ('Gravity Boots Inverted Sit Up', 'https://youtu.be/AN4MBtCsJqo'),
  ('Double Kettlebell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/G7e7EenICzQ'),
  ('Barbell Back Rack Step Up', 'https://youtu.be/uQGRzdjxHes'),
  ('Barbell Front Rack Step Up', 'https://youtu.be/YR_7r6EzJdA'),
  ('Barbell Standing Rollout', 'https://youtu.be/_lI_GB0DI3o'),
  ('Stability Ball Cable Russian Twist', 'https://youtu.be/4ESBjh2BcdE'),
  ('Miniband Frog Pump', 'https://youtu.be/rzjQ8XpXt1Q'),
  ('Bodyweight Fire Hydrant', 'https://youtu.be/IFrN8GELc-k?feature=shared'),
  ('Bodyweight Knee Hover Quadruped Fire Hydrant', 'https://youtu.be/8nmBvZ1DkKQ?si=RUcdU_JPDGU_yIWv'),
  ('Alternating Double Dumbbell Spider Curl', 'https://youtu.be/KznrM_RhXDc?si=Qxgmd-eTnFuZ5rpo'),
  ('Bodyweight Bent Knee Copenhagen Plank Side Raise', 'https://youtu.be/xkcOhvzzta0'),
  ('Bodyweight Kneeling Side Plank', 'https://youtu.be/PAHxwhBVsYY?si=pym-tzPNwmH8zNeP'),
  ('Bodyweight Wall Assisted Hip Airplane', 'https://youtu.be/20R2FqNUBsA?si=3Nuvhsgux27gQFjW'),
  ('Superband Single Leg Tibialis Raise', 'https://youtu.be/fAf6Z7wu7fM?si=6K5_014ZCoGfknf8'),
  ('Barbell Zercher Squat', 'https://youtu.be/nwx6Ip7hd3I'),
  ('Barbell Squat Snatch', 'https://youtu.be/9xQp2sldyts'),
  ('Barbell Squat Clean to Split Jerk', 'https://youtu.be/PjY1rH4_MOA'),
  ('Slider Kneeling Alternating Reach Push Up', 'https://youtu.be/1UD0dTGE04w?si=q2odI18mbdJTtPDF'),
  ('Barbell Hang Squat Clean to Thruster', 'https://youtu.be/8DApihgXzGk'),
  ('Barbell Squat Clean to Thruster', 'https://youtu.be/4qZWqKDAhkQ'),
  ('Bodyweight Copenhagen Plank', 'https://youtu.be/tKb76R21AfM?si=zsuYyzMMfjZleCpc'),
  ('Bodyweight Bent Knee Copenhagen Plank', 'https://youtu.be/obtdLUWZi-Y'),
  ('Miniband Single Leg Hip Thrust', 'https://youtu.be/tPWyj85zsmg'),
  ('Barbell Deficit Snatch Grip Deadlift', 'https://youtu.be/s_Cx_ElOuQs'),
  ('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/hTBEkHf8GmA'),
  ('Bodyweight Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/Gu4qA5TevLU'),
  ('Double Kettlebell Thruster', 'https://youtu.be/5-mxMxigTfw'),
  ('Double Kettlebell Cossack Squat Thruster', 'https://youtu.be/DbKGRbkQ80E'),
  ('Single Arm Landmine Shrug', 'https://youtu.be/I_qhTOdNkHo?si=7wY3icLNd-TkFk5i'),
  ('Double Kettlebell Front Rack Walking Lunge', 'https://youtu.be/Xmfx1eZMKmY'),
  ('Double Kettlebell Overhead Walking Lunge', 'https://youtu.be/hcQJcKxc240'),
  ('Ring Straddle L Sit', 'https://youtu.be/pjk0vGe9YRU'),
  ('Double Kettlebell Seesaw Overhead Press', 'https://youtu.be/VWnVBfRkLXE?si=AeN6Q9aAnShqxuIb'),
  ('Double Kettlebell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/UiY-JIpmt24?si=ox4YNd9xIIVapyeB'),
  ('Double Dumbbell Tall Kneeling Seesaw Overhead Press', 'https://youtu.be/Lk0xszw7Tf8?si=GHtFcn5OVifRVyDQ'),
  ('Double Dumbbell Half Kneeling Seesaw Overhead Press', 'https://youtu.be/NP4p_SWAgnA?si=VoTKPhBbaaWrrYZH'),
  ('Double Dumbbell Seesaw Z Press', 'https://youtu.be/L_Y8osw78lA?si=3eK1QuOTlQjCzAxO'),
  ('Stability Ball Sit Up', 'https://youtu.be/7L90imlW0es?si=gY7k7XVC43IRrv-N'),
  ('EZ Bar Wide Grip Strict Bicep Curl', 'https://youtu.be/j83lzC2E4Ss?si=PcoF092JVJRpg8T4'),
  ('Double Kettlebell Squat Clean', 'https://youtu.be/6wyxpVY8PQ0'),
  ('Double Kettlebell Hollow Body Hold', 'https://youtu.be/do1yf3NMXdg'),
  ('Alternating Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/xkCR2CkkL1g?si=Qy0YPAcCasZF6kNk'),
  ('Bodyweight Side Lying Hip Adduction', 'https://youtu.be/UW52u8OaWhw?si=WdEOpAR_PSB9x9bR'),
  ('Superband Hollow Body Hold', 'https://youtu.be/8QRsSJ-Ny8M'),
  ('Parallette Freestanding Handstand Push Up', 'https://youtu.be/3FYYo6lP-dw'),
  ('Slider Single Leg Eccentric Hamstring Curl', 'https://youtu.be/yAOulKW0al4'),
  ('Bodyweight Freestanding Handstand Push Up', 'https://youtu.be/aAErmRDDJKY'),
  ('Single Arm Ring Grip Push Up', 'https://youtu.be/CXVqHGLmb3Q'),
  ('Superband Side Plank Hanging Hip Adduction', 'https://youtu.be/JG0Ay2QDVbI'),
  ('Ring Strap Bulgarian Handstand Push Up', 'https://youtu.be/ZNCupJIYP6M'),
  ('Stability Ball Feet Elevated Frog Pump', 'https://youtu.be/Rc5e-DsD--M'),
  ('Double Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/HOQeoz3zQeo'),
  ('Barbell Front Rack Cyclist Squat', 'https://youtu.be/IU_0IBe4G9w'),
  ('Double Kettlebell Dead Clean to Push Press', 'https://youtu.be/NAZ9uF9S_wk'),
  ('Bodyweight Bent Arm Press Handstand', 'https://youtu.be/Gzz3ku70W3I'),
  ('Single Arm Dumbbell Cyclist Thruster', 'https://youtu.be/2Tt0XZ2pZyE'),
  ('Double Kettlebell Front Rack Split Squat', 'https://youtu.be/ExJCssj4YV0'),
  ('Double Kettlebell Front Rack Bulgarian Split Squat', 'https://youtu.be/Q3yDIeMfdNg'),
  ('Double Kettlebell Overhead Squat', 'https://youtu.be/2Pk8jmse6vY'),
  ('Bodyweight Chest Roll to Straight Body Press Handstand', 'https://youtu.be/mYQAYnr2hlg?si=gqlNGvKWytXXQP1H'),
  ('Ring Bent Arm Bent Body Press Handstand', 'https://youtu.be/TxkC9nrvOho'),
  ('Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/1XyV5eNL1z0'),
  ('Kettlebell Swing', 'https://youtu.be/1cVT3ee9mgU'),
  ('Alternating Single Arm Kettlebell Swing', 'https://youtu.be/WK4ughYoUEI?si=2mvQ9x0jZEF2zzRA'),
  ('Alternating Single Arm Kettlebell Clean', 'https://youtu.be/dPN2mj5R2S8'),
  ('Alternating Single Arm Kettlebell Snatch', 'https://youtu.be/0aq5EW0euvA'),
  ('Single Arm Kettlebell Staggered Stance Swing', 'https://youtu.be/L2WY5gYUb1U'),
  ('Alternating Single Arm Kettlebell Alternating Staggered Stance Swing', 'https://youtu.be/Ss7KjOjCpVU'),
  ('Single Arm Kettlebell Half Kneeling Swing', 'https://youtu.be/QVvrdVbq9qs'),
  ('Double Kettlebell Outside Swing', 'https://youtu.be/zrvtXpwVTOI'),
  ('Double Kettlebell Outside Half Snatch', 'https://youtu.be/Fx-qV1dHGi4?feature=shared'),
  ('Double Kettlebell Outside Clean', 'https://youtu.be/QtlvLhVFR40'),
  ('Single Arm Kettlebell Side Swing', 'https://youtu.be/YBJnavxcbUA'),
  ('Kettlebell Feet Elevated Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Single Arm Kettlebell Half Kneeling Windmill', 'https://youtu.be/wjYNzITBDqg'),
  ('Kettlebell Horn Grip Skater Squat', 'https://youtu.be/q1TuasYdM2M'),
  ('Double Kettlebell Front Rack Pistol Squat', 'https://youtu.be/-A7yvmUv8Cw'),
  ('Single Arm Kettlebell Hollow Body Flutter Kicks', 'https://youtu.be/JGY8VuvaEHc?si=LVWYZO5Qt-3WONJf'),
  ('Ring Back Lever Pullout', 'https://youtu.be/FRBr2pomeOM?si=15TQvL3xIskTVzVA'),
  ('Double Kettlebell Clean to Overhead Press', 'https://youtu.be/5Fx69TRWARc'),
  ('Kettlebell Alternating Halo to Horn Grip Bottoms Up Squat', 'https://youtu.be/-0FIWmBbo9U'),
  ('Ring German Hang Pullout', 'https://youtu.be/J34xkKOc9GI'),
  ('Single Arm Kettlebell Bottoms Up Turkish Get Up', 'https://youtu.be/jpgvV6wdXVw'),
  ('Single Arm Kettlebell Thruster', 'https://youtu.be/vBkzGpZSEF4'),
  ('Alternating Double Kettlebell Thruster', 'https://youtu.be/AeK6i-5gvJ0'),
  ('Single Arm Kettlebell Bottoms Up Dead Clean to Overhead Press', 'https://youtu.be/EF4ep3h5Olk'),
  ('Single Arm Kettlebell Tactical Snatch', 'https://youtu.be/lWVxdK_AT2s?si=lgWC5CSMGVpQHo9t'),
  ('Single Arm Kettlebell Snatch to Overhead Contralateral Reverse Lunge', 'https://youtu.be/oReUJtUlMGU'),
  ('Double Kettlebell Snatch to Overhead Alternating Reverse Lunge', 'https://youtu.be/VpURrAKPhcE?si=gSYbC8kpIa5xMxr8'),
  ('Single Arm Kettlebell Clean to Front Rack Contralateral Reverse Lunge', 'https://youtu.be/oqjLx5Injps'),
  ('Single Arm Kettlebell Split Jerk', 'https://youtu.be/DeoexkyNuns?si=WrruI69jETw4SBe-'),
  ('Single Arm Ring Chin Up', 'https://youtu.be/S22n8oqcDSY?si=GFs-J_IAwjttVe0y'),
  ('Double Kettlebell Bottoms Up Overhead Squat', 'https://youtu.be/kSlZIksA8XQ'),
  ('Double Kettlebell Bottoms Up Thruster', 'https://youtu.be/ZjNbjnGz1Cg'),
  ('Ring Iron Cross', 'https://youtu.be/HZbee93OIdo'),
  ('Barbell Overhead Bulgarian Split Squat', 'https://youtu.be/F_t7_XRdLbs?si=moBf8_s1adbBBwRY'),
  ('Bodyweight Straddle Planche Push Up', 'https://youtu.be/qgNYrUdn1Oo?si=66l491gj5kmLLjA0'),
  ('Bodyweight Two Finger Full Planche Push Up', 'https://youtu.be/CGeBvG5XP7U?si=nGM9dXX2v8dyqJA_'),
  ('Bodyweight Push Up to Alternating Kick Through', 'https://youtu.be/wcBXDGhqnBU'),
  ('Bodyweight Standing Walkout Push Up', 'https://youtu.be/zR7oQp1Ucq8'),
  ('Ring Pull Up', 'https://youtu.be/cLqkGqiva1M'),
  ('Single Arm Plate Windmill', 'https://youtu.be/P-dqLz-r5po'),
  ('Single Arm Plate Turkish Get Up', 'https://youtu.be/4_RrnWT847k'),
  ('Bodyweight Pike Push Up', 'https://youtu.be/QIZ6RXq72ZI'),
  ('Parallette Feet Elevated Pike Push Up', 'https://youtu.be/EqXFl_YxF8k'),
  ('Barbell Sots Press', 'https://youtu.be/eJ9MLnNV6FY'),
  ('Double Kettlebell Bottoms Up Snatch', 'https://youtu.be/jcC9NyGLGyg'),
  ('Single Arm Kettlebell Around the World', 'https://youtu.be/6AzrdFj3Qfc?si=52vAx7-XXfvkSz_l'),
  ('Single Arm Dumbbell Z Press', 'https://youtu.be/Ib-8BOyAgTQ'),
  ('Parallette Feet Elevated Push Up', 'https://youtu.be/JtBPG6VeJ9Q'),
  ('Stability Ball Feet Elevated Diamond Push Up', 'https://youtu.be/-2fkjhJfcP8'),
  ('Bodyweight Tricep Extension', 'https://youtu.be/O8WGl4_aYTQ?si=eq7Ylf5fkEliBcxD'),
  ('Alternating Single Arm Kettlebell Around the World', 'https://youtu.be/ekR7MDSWwEQ'),
  ('Single Arm Kettlebell Tall Kneeling Around the World', 'https://youtu.be/9vZ0CU0dHcE'),
  ('Single Arm Kettlebell Waiter Clean', 'https://youtu.be/fLXYRpxW4FI?si=AjNKRKLLVjzA8Uow'),
  ('Alternating Single Arm Kettlebell Waiter Clean', 'https://youtu.be/eH7w5psLPpk?si=XnO0PygbF5fzKCsm'),
  ('Double Kettlebell Waiter Clean', 'https://youtu.be/K8atAt0LaTU?si=9XbtgY4Ntm5G8h7v'),
  ('Double Kettlebell Waiter Clean to Overhead Press', 'https://youtu.be/6yF_kl-76jw?si=rsxf0dRezcQc83ke'),
  ('Double Kettlebell Waiter Clean to Alternating Overhead Press', 'https://youtu.be/0WjMjA_4SoE?si=J46etYGhA2sshEat'),
  ('Barbell Seated Wrist Curl', 'https://youtu.be/k6F6ugHyTcA?si=XfnVnbcVgnDkbrFv'),
  ('Single Arm Dumbbell Hollow Body Chest Press', 'https://youtu.be/D82M_YDEGJ8'),
  ('Double Kettlebell Waiter Clean to Thruster', 'https://youtu.be/PX80lILLVhw?si=vmOhrWhU-xCpO4kr'),
  ('Kettlebell Start Stop Swing', 'https://youtu.be/cZSh_cYNXTw'),
  ('Double Kettlebell Dead Clean', 'https://youtu.be/qdMDbLUg9_w?si=9t5V4loMJW5VI5mV'),
  ('Bodyweight Windmill', 'https://youtu.be/87I2gbRgtUI?si=4hUJ0N3X8wu8MMKC'),
  ('Superband Isometric Split Squat Pallof Press', 'https://youtu.be/a4ctQ6GYixo?si=WP2e4CVK5KsFEluY'),
  ('Single Arm Barbell Turkish Get Up', 'https://youtu.be/VAFM8kbz8uA?si=UAPSMjiSnRLN3jl3'),
  ('Bodyweight Plate Plyometric Push Up', 'https://youtu.be/jmzZ2wQdXao'),
  ('Single Arm Dumbbell Single Leg Contralateral Bent Over Row', 'https://youtu.be/KsEBTYuqemI'),
  ('Double Dumbbell Single Leg Bent Over Row', 'https://youtu.be/LrbAy459jkg?si=UDFXUQgUuwN4hkBz'),
  ('Single Arm Kettlebell Bottoms Up Thruster', 'https://youtu.be/lbnYFCHrjvk'),
  ('Single Arm Kettlebell Dead Clean', 'https://youtu.be/Lcm7DcXbm-U'),
  ('Alternating Single Arm Kettlebell Dead Clean', 'https://youtu.be/FAtcUX6VxWo'),
  ('Single Arm Dumbbell Bird Dog Row', 'https://youtu.be/O1mck-Oil5Y'),
  ('Single Arm Kettlebell Bottoms Up Half Kneeling Windmill', 'https://youtu.be/U6kn-AypL7c'),
  ('Double Dumbbell Renegade Row', 'https://youtu.be/U_kv9LRu6_I?si=o6wONfSHOO4nrgpy'),
  ('Ring Kneeling Rollout', 'https://youtu.be/LMQIG45Wwd8'),
  ('Ring Standing Rollout', 'https://youtu.be/or7xH0BirKw?si=5oL6x2NsxvCfWaBo'),
  ('Single Arm Landmine Shoulder Press', 'https://youtu.be/5Cs27w8WVz4'),
  ('Alternating Single Arm Landmine Shoulder Press', 'https://youtu.be/owbzzfb-0PQ'),
  ('Single Arm Kettlebell Bent Press', 'https://youtu.be/xO7fmvTpy3M'),
  ('Double Kettlebell Front Rack Cossack Squat', 'https://youtu.be/sBuAJggOIxE?si=CST2KlC-8f_fnogp'),
  ('Double Kettlebell Front Rack Low Switch Cossack Squat', 'https://youtu.be/j9sFzOeMmxY?si=i2yJV3WJb2pBCf0X'),
  ('Single Arm Landmine Half Kneeling Contralateral Shoulder Press', 'https://youtu.be/ORoOn93dnh4'),
  ('Bodyweight Bulgarian Split Squat', 'https://youtu.be/kBQ1krvKFBU'),
  ('Plate Otis Up', 'https://youtu.be/vjAjAERSkIk'),
  ('Double Kettlebell Bottoms Up Front Rack Pistol Squat', 'https://youtu.be/WPIrFREyNaw'),
  ('Double Kettlebell Clean to Sots Press', 'https://youtu.be/NqZPSUqSJlA'),
  ('Single Arm Landmine Tall Kneeling Shoulder Press', 'https://youtu.be/TVTHezj2ZLg'),
  ('Single Arm Landmine Z Press', 'https://youtu.be/app94pzXOuU'),
  ('Barbell Z Press', 'https://youtu.be/D73Oy2m-Uoc'),
  ('Single Arm Suspension Bicep Curl', 'https://youtu.be/gn5Uy0z5DyY?si=cNwcH7q0lucOSGDX'),
  ('Suspension Atomic Push Up', 'https://youtu.be/qTD9lWjff84'),
  ('Double Kettlebell Clean to Thruster', 'https://youtu.be/J6xUudO95Gc'),
  ('Bodyweight Archer Push Up', 'https://youtu.be/_Qbz_54_9Sw'),
  ('Parallette Archer Push Up', 'https://youtu.be/Wg2mF-GjD10'),
  ('Single Arm Suspension Push Up', 'https://youtu.be/PenQnEuayM4'),
  ('Ring Skin the Cat', 'https://youtu.be/ABSpTs17ObA'),
  ('Single Arm Kettlebell Suitcase Contralateral Bulgarian Split Squat', 'https://youtu.be/DGzBcpLm8T4?si=VFc6IG7H7vAlBgxV'),
  ('Double Kettlebell Suitcase Bulgarian Split Squat', 'https://youtu.be/2mDqNOd-Pco?si=MiZ8nJsVAje_rZfb'),
  ('Ring Feet Elevated Row', 'https://youtu.be/u3XIZSv2Npw'),
  ('Ring Feet Elevated Bulgarian Row', 'https://youtu.be/k84lpDtf5kQ'),
  ('Ring Push Up', 'https://youtu.be/u8tOhNwiL70'),
  ('Ring Chest Fly', 'https://youtu.be/ytAxGbZ7g80'),
  ('Double Kettlebell Feet Elevated Push Up', 'https://youtu.be/kw3ht7nZbXs?si=9ZaHvZoUYJK9H_2w'),
  ('Single Arm Kettlebell Bottoms Up Half Kneeling Contralateral Overhead Press', 'https://youtu.be/DrpIWrG7rl8'),
  ('Parallette Alternating Shoulder Tap Push Up', 'https://youtu.be/NENoxvoyaTw'),
  ('Parallette Dive Bomber Push Up', 'https://youtu.be/tpCOg3ZKn3w?si=e_92TbjIAIy3thZh'),
  ('Barbell Front Rack Bulgarian Split Squat', 'https://youtu.be/kz5dpeSigAI'),
  ('Barbell Back Rack Bulgarian Split Squat', 'https://youtu.be/CeNiZ52DzU0'),
  ('Barbell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/QB9bEZQl6Mg'),
  ('Bodyweight Dragon Flag', 'https://youtu.be/LXmJg15hurY?si=kuUaXsoiL3fnTOE7'),
  ('Bodyweight Dive Bomber Push Up', 'https://youtu.be/y94uWhVJ3D4?si=TIKacdZm8d8i5e6M'),
  ('Parallette Full Planche', 'https://youtu.be/v6oj7ImoVP4?si=F3GtqX0vk8YHIyZm'),
  ('Double Dumbbell Renegade Row to Push Up', 'https://youtu.be/731lQp2shpY'),
  ('Ring Inverted Iron Cross', 'https://youtu.be/qO5ZqLJD_ZQ'),
  ('Barbell Reverse Grip Front Raise', 'https://youtu.be/b2ELsjM9KQQ'),
  ('Ring Tuck Planche', 'https://youtu.be/ch0kaD--kIA'),
  ('Bodyweight Full Planche', 'https://youtu.be/hTpQCPjYZ3w?si=jlVsTRhe4TDGXMhx'),
  ('Cable Quadruped Hip Abduction', 'https://youtu.be/MZi0M3OJEVw'),
  ('Barbell Reverse Grip Bench Press', 'https://youtu.be/a9IZD74jAfw?si=-nGBSNLL5nllir0b'),
  ('Double Kettlebell Turkish Get Up', 'https://youtu.be/q4JSQU9lyfs'),
  ('Single Arm Kettlebell Rotational Overhead Press', 'https://youtu.be/jtOoPLn8OEQ'),
  ('Single Arm Kettlebell Z Press', 'https://youtu.be/ygiRarZWXHw'),
  ('Parallette Straddle Planche', 'https://youtu.be/2qWMe_2rlFk?si=MrPXRqDAKW9xxM_5'),
  ('Single Arm Kettlebell Sots Press', 'https://youtu.be/1znq_EvBvCg'),
  ('Double Kettlebell Renegade Row', 'https://youtu.be/SUqsBTSldyk'),
  ('Barbell Turkish Sit Up', 'https://youtu.be/zCBlmAdxfI0'),
  ('Plate Turkish Sit Up', 'https://youtu.be/A7sXEmRwTQQ'),
  ('Double Kettlebell Renegade Row to Push Up', 'https://youtu.be/i8VL6OjVlCY'),
  ('Dumbbell Crush Grip Romanian Deadlift', 'https://youtu.be/SozT7TcG-p0?si=8DX3-uViiOfh2BvX'),
  ('Single Arm Kettlebell Half Kneeling Contralateral Overhead Press', 'https://youtu.be/wlAJN3GzJWA'),
  ('Single Arm Kettlebell Bottoms Up Z Press', 'https://youtu.be/XFxoHtiGZtw'),
  ('Double Kettlebell Bottoms Up Z Press', 'https://youtu.be/s2hAm9S-6fY'),
  ('Double Kettlebell Sots Press', 'https://youtu.be/D6UYO_ZbLJ8'),
  ('Alternating Double Kettlebell Sots Press', 'https://youtu.be/_Q2mHbn6ggA?si=QGGePHfV1X7MFEdF'),
  ('Double Kettlebell Seesaw Sots Press', 'https://youtu.be/L0DwNTS4psM'),
  ('Dumbbell Crush Grip Hollow Body Flutter Kicks', 'https://youtu.be/Btp-pKPfvEU'),
  ('Double Kettlebell Bottoms Up Seesaw Overhead Press', 'https://youtu.be/HDzbviKeH8A'),
  ('Parallette Crow Pose', 'https://youtu.be/JHYVvhWqNzE'),
  ('Barbell Overhead March', 'https://youtu.be/NJ4t_HAgJ0M'),
  ('Single Arm Kettlebell Half Kneeling Clean', 'https://youtu.be/2LM9Y67n6Aw'),
  ('Single Arm Kettlebell Half Kneeling Snatch', 'https://youtu.be/Ak5wI3oLbjA?si=ZcxpayHQ4EbHkxWD'),
  ('Double Kettlebell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/UnevKvSIDLo?si=Y2g3UwUxqNMlZHdo'),
  ('Slider Lateral Lunge', 'https://youtu.be/Gj12f62lLeM?si=VhTsZJu7DxtPvx73'),
  ('Double Kettlebell Dead Clean to Overhead Press', 'https://youtu.be/8xYUgNA1Hi0?si=B1HQJvZslYYHAgLt'),
  ('Double Kettlebell Dead Clean to Thruster', 'https://youtu.be/3p8swLoH5no'),
  ('Single Arm Kettlebell Dead Snatch', 'https://youtu.be/VfKFRnS5FDY'),
  ('Alternating Single Arm Kettlebell Dead Snatch', 'https://youtu.be/z0tHucwkYgM?si=VThu2f_wRIcFlNP3'),
  ('Double Kettlebell Dead Half Snatch', 'https://youtu.be/t8Z9LTj5b6Y'),
  ('Double Dumbbell Staggered Stance Romanian Deadlift', 'https://youtu.be/RFuCfiMfJ1w'),
  ('Barbell Staggered Stance Romanian Deadlift', 'https://youtu.be/UDKuhQqMIBs'),
  ('Ring Hanging Knees to Elbows', 'https://youtu.be/SxLuhaSaPM4'),
  ('Superband Assisted Nordic Hamstring Curl', 'https://youtu.be/4u74sLMSObs'),
  ('Bodyweight Alternating Shin Box Hip Extension', 'https://youtu.be/UZLEwSROzyQ?si=Pk3NabO_4gvYWivn'),
  ('Single Arm Kettlebell Turkish Sit Up to Z Press', 'https://youtu.be/FOdI5tm_JZs?si=-JnXwtZzA1jDzCcB'),
  ('Ring Chin Up', 'https://youtu.be/rJiYA9jn3YI'),
  ('Single Arm Kettlebell Rotational Thruster', 'https://youtu.be/jkbJFWzllH4'),
  ('Single Arm Dumbbell Suitcase Carry', 'https://youtu.be/mKfCI8ADAjQ?si=ZGUBS2ZPrlbJQKmA'),
  ('Double Dumbbell Glute Bridge Isometric Bench Press', 'https://youtu.be/CyHxva5XYYY'),
  ('Bodyweight Foot Elevated Cossack Squat', 'https://youtu.be/DgJtQJxYVTk'),
  ('Barbell Feet Elevated Inverted Row', 'https://youtu.be/6AptmglPQ30'),
  ('Double Kettlebell Windmill', 'https://youtu.be/t9S2E15cyTg?si=pUmpNP-D71uC7XAL'),
  ('Double Kettlebell Dragon Flag', 'https://youtu.be/8i1-ngFRLLs'),
  ('Barbell Staggered Stance Overhead Press', 'https://youtu.be/dnLBRh6bQJQ'),
  ('Kettlebell Dead Bug', 'https://youtu.be/pXcG0IH2Nkg'),
  ('Superband Standing Hip Adduction', 'https://youtu.be/O2fzFpGvDWI'),
  ('Superband Lateral Step Hip Adduction', 'https://youtu.be/9Ryl38GZHiI'),
  ('Kettlebell Dead Clean to Horn Grip Squat', 'https://youtu.be/Xo9kEM4A6ao?si=RzutoHlEo0zoz1LZ'),
  ('Double Kettlebell Bottoms Up Front Rack March', 'https://youtu.be/mLc2zI4rkMQ?si=bYMHmbsvqyX3__ZV'),
  ('Suspension Alternating Cossack Squat', 'https://youtu.be/ThQT_AIqcNU?si=Y06NKpeBBOkHRplH'),
  ('Battle Rope Single Leg Standing Alternating Wave', 'https://youtu.be/ynczWiOjUqE?si=TWU55ZzVAfcrcb5B'),
  ('Superband Assisted Dips', 'https://youtu.be/QjzY6vf495U?si=dG_1Ixlx0Man-AIC'),
  ('Alternating Single Arm Kettlebell Ballistic Row', 'https://youtu.be/ey7YgyPONOk'),
  ('Double Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/Pt-6EI8mcEU?si=Lxresx17SBitLvtO'),
  ('Suspension Split Squat', 'https://youtu.be/sng5EOSZSSo'),
  ('Single Arm Kettlebell Tactical Clean', 'https://youtu.be/dLyfCN_7JHw'),
  ('Suspension Cyclist Squat', 'https://youtu.be/dzbJzUQjDYA?feature=shared'),
  ('Macebell 360', 'https://youtu.be/WMog8YuuVaM?si=WsH2sh1FFH3SBamT'),
  ('Single Arm Suspension Contralateral Skater Squat', 'https://youtu.be/8pe73RwDAzY?si=ASSfIEGoxhWjeAi_'),
  ('Single Arm Macebell 360', 'https://youtu.be/ITUpuwk3odY?si=KGOrc3k9Flt-oF1v'),
  ('Bodyweight Cyclist Squat', 'https://youtu.be/BAlXJ5lLMAA?si=H1cfMWF52YWOMraL'),
  ('Kettlebell Half Kneeling Rotational Swing', 'https://youtu.be/_ChDukjxUag'),
  ('Double Kettlebell Clean to Push Jerk', 'https://youtu.be/_A6K7V6FHSM?si=uMrzYlHgGYbenNf1'),
  ('Kettlebell Isometric Split Squat Low to High Chop', 'https://youtu.be/ECAIMMQDUC4?si=WgJIciK_Kd14WYVj'),
  ('Double Kettlebell Front Rack March', 'https://youtu.be/aAbVFCqY4Ac'),
  ('Double Kettlebell Suitcase March', 'https://youtu.be/i-q8SKGy--Q'),
  ('Single Arm Kettlebell Rotational Half Snatch', 'https://youtu.be/KpDxyxOCjCE'),
  ('Slider Single Leg Hamstring Curl', 'https://youtu.be/MBoaZQwukmw?si=uMFzO0l7TuqVArPp'),
  ('Kettlebell Staggered Stance Rotational Swing', 'https://youtu.be/4SXAEL7ZdSk?feature=shared'),
  ('Barbell Low Bar Pause Back Squat', 'https://youtu.be/nknf16JJTZo?si=h2lVyRQ8npFOB0v4'),
  ('Barbell Front Rack Pause Squat', 'https://youtu.be/mN5Z5GH7ofM?si=5wK63ZJAw0Zc5Wti'),
  ('Single Arm Kettlebell Suitcase Walking Lunge Pass Through', 'https://youtu.be/yXwmVzRHPPw?si=K_LXsBOKmt9dza3B'),
  ('Macebell 10 to 2', 'https://youtu.be/6FjCQJRBNlo?si=RBXNRNqOkwVOMCGq'),
  ('Dumbbell Goblet Cyclist Squat', 'https://youtu.be/2WxpkosHXLg?si=kPBJD_6N8w568qJ-'),
  ('Barbell Overhead Alternating Cossack Squat', 'https://youtu.be/ulzoZOHicyU?si=OfrqYrKBRnV6RCrc'),
  ('Barbell Overhead Alternating Reverse Lunge', 'https://youtu.be/eqaz6nCxF8k?si=OEXiCUefeX011B_I'),
  ('Double Kettlebell Suitcase Carry', 'https://youtu.be/kaQWccrfY40'),
  ('Single Arm Kettlebell Suitcase Carry', 'https://youtu.be/HNgMpdUEpgw'),
  ('Double Kettlebell Bottoms Up Front Rack Cossack Squat', 'https://youtu.be/hTNWWqL9oc8?si=cTXB5vGf2EIHhx3r'),
  ('Alternating Single Arm Kettlebell Knee Hover Quadruped Pull Through', 'https://youtu.be/WQyNCzqNqso'),
  ('Single Arm Kettlebell High Pull', 'https://youtu.be/mP1BHxBeAEM'),
  ('Double Indian Club Outer Heart Shaped Swing', 'https://youtu.be/52D7xnpFFGY?si=UBcZ3G1BNtRbk97O'),
  ('Suspension Alternating Curtsy Lunge', 'https://youtu.be/jNjDO9lEenw?si=Ci4DITj3193GY1tI'),
  ('Single Arm Kettlebell Single Leg Balance Transfer', 'https://youtu.be/_uJQvQG57Y8'),
  ('Barbell Front Rack Alternating Forward Lunge', 'https://youtu.be/whSju0ip_78?si=emNV0JUVUhF8Qrf1'),
  ('Barbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/dpBy5qAG2Hs?si=x6xfYJbZr1Bols2r'),
  ('Barbell Overhead Alternating Forward Lunge', 'https://youtu.be/9eDpB8LJLgQ?si=CKsCerZuXFHay_Dr'),
  ('Single Arm Clubbell Shield Cast', 'https://youtu.be/W2slZ8Mmyvs?si=CDhf0Oi-nPW136Jx'),
  ('Macebell Barbarian Squat', 'https://youtu.be/Gj3ancpDFKU?si=TKfk3RmqTwztmb1j'),
  ('Alternating Double Clubbell Shield Cast', 'https://youtu.be/L1pxDgvsT9s?si=ajAmx9ThwNQY_hj2'),
  ('Clubbell Mill', 'https://youtu.be/uIqkGCpjsx8?si=_GzAaZAVU4-bAgla'),
  ('Double Clubbell Iron Cross', 'https://youtu.be/ekVV4qI2q9A?si=E3yTJpSwWDur0p82'),
  ('Double Clubbell Side Flag Press', 'https://youtu.be/_bnWJymK0tU?si=vYh91PF76xgOyPll'),
  ('Single Arm Kettlebell Suitcase Contralateral Knee Over Toe Split Squat', 'https://youtu.be/eGYP6B7LKtY?si=OkQLiBCrooH2qA67'),
  ('Double Indian Club Inner Heart Shaped Swing', 'https://youtu.be/If9fXNTF4wI?si=Lk9xqqbULe2D5Xbs'),
  ('Alternating Double Indian Club Inner Heart Shaped Swing', 'https://youtu.be/M_uslqzI28g?si=0zmBqTp2C8IMe5gJ'),
  ('Single Arm Clubbell Side Flag Press', 'https://youtu.be/uuLZZUozsdM?si=IcPMq75KQuzVIQM5'),
  ('Single Arm Clubbell Inside Circle', 'https://youtu.be/n8S_z0p25jA?si=fak8MwjeEUMtDoZ2'),
  ('Barbell Reverse Grip Bicep Curl', 'https://youtu.be/TUX58GM5fRQ?si=D4ei3VOcTd3GzGQn'),
  ('Single Arm Clubbell Reverse Mill', 'https://youtu.be/sdICKS1Hsl8?si=TQcKHRoyYYB_DXgZ'),
  ('Single Arm Clubbell Mill', 'https://youtu.be/JL7-80LGmmU?si=wgcrQiv7L3ETryrv'),
  ('Double Kettlebell Suitcase Deadlift', 'https://youtu.be/aXwilZfmDyo'),
  ('Double Kettlebell Bottoms Up Clean', 'https://youtu.be/iPSx3HFBDJQ?si=yE7krt1ftsmuaend'),
  ('Double Clubbell Mill', 'https://youtu.be/vwRppLKenzw?si=lWbUFOXUJgHzwIVl'),
  ('Alternating Single Arm Clubbell Mill', 'https://youtu.be/p8aWK-U6uVQ?si=uIoHZ9IRigICcYkI'),
  ('Macebell Alternating 360 to Ballistic Curl', 'https://youtu.be/dAeNDa33dCg?si=DOdJKyHWeDTnUFjC'),
  ('Bar Chin Up', 'https://youtu.be/8mryJ3w2S78?si=feHRqrceUl_6Xatw'),
  ('Bar Pull Up', 'https://youtu.be/HRV5YKKaeVw?si=2FwPXMnKZC4QXyAO'),
  ('Single Arm Clubbell Inside Pendulum', 'https://youtu.be/9JrqgpJfxFs?si=ltubZdnwDPFzi-8r'),
  ('Double Clubbell Swipe', 'https://youtu.be/IABFtVxvqdo?si=Krk5vT1xDU9YcRb2'),
  ('Single Arm Clubbell Swipe', 'https://youtu.be/EZNev-kvl6A?si=GsKx6-ERsaOYXjDd'),
  ('Bar Scapular Pull Up', 'https://youtu.be/pE8PJsWEV7k?si=sXWG_h39gmTbgsNw'),
  ('Clubbell Barbarian Squat', 'https://youtu.be/SnRUNmL46So?si=LiGATOKJlrhb676E'),
  ('Bar Skin the Cat', 'https://youtu.be/mqZDdpFh1gA?si=5Sz7M4RZJh4kpYFa'),
  ('Single Arm Kettlebell Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/fyC2FBk2vho?si=9A4Unc4H-ndiHFMC'),
  ('Barbell Hang Squat Clean', 'https://youtu.be/DaKC_BEN5bk?si=-Q3RkXcSiRxscR4n'),
  ('Alternating Single Arm Kettlebell Feet Elevated Plank Pull Through', 'https://youtu.be/178a2eYjaow?si=5BIFyTIH_gQo8ef1'),
  ('Miniband Supine Alternating Hip Flexion', 'https://youtu.be/hcB3BdFBk9o?si=NCYoHHaTofHXzx2y'),
  ('Double Kettlebell Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/zlosFkTwleE?si=kPNf5P_AJZd7Sqrn'),
  ('Double Kettlebell Bottoms Up Half Kneeling Overhead Press', 'https://youtu.be/IoGfLT_8cPA?si=0w2tJHQG6XulCr7c'),
  ('Alternating Single Arm Macebell 10 to 2', 'https://youtu.be/7DW72Ft1LEo?si=kejdZkBMg1CFxl99'),
  ('Single Arm Kettlebell Bottoms Up Arm Bar Rotation', 'https://youtu.be/dlqDSzgxNwM?si=_l4eia6JX0ovy0ss'),
  ('Double Kettlebell Push Up', 'https://youtu.be/80WFnCM9Kbo?si=kxvBbrzAla92I6YM'),
  ('Bodyweight Pseudo Planche Lean', 'https://youtu.be/KMCZ6Pjg9_k?si=qLUPw94vxQVVs7nw'),
  ('Tire Feet Elevated Decline Push Up', 'https://youtu.be/-S5Zz3Hl6a4?si=8XSysf7jjGJx2X07'),
  ('Bodyweight Bench Feet Elevated Decline Push Up', 'https://youtu.be/1ZTYpiJJDZ8?feature=shared'),
  ('Bodyweight Box Feet Elevated Decline Push Up', 'https://youtu.be/5DTn4Euw6To?si=Qt5r8kEOx3ZW_AO9'),
  ('Bodyweight Feet Elevated Pike Push Up', 'https://youtu.be/s5VyQrNhEYY?si=9tSA6c3bjeje5MfX'),
  ('Single Arm Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/J5LEpIZSDS0?si=SukDsqWl5cS7XyF-'),
  ('Single Ring Rotational Row', 'https://youtu.be/1PiO_woAgDc?si=-nYhvQs3zKrAR7im'),
  ('Trap Bar Bottoms Up Tall Kneeling Overhead Press', 'https://youtu.be/yQToM9xx5Y4?si=AAnvcezbT07hvy8I'),
  ('Trap Bar Z Press', 'https://youtu.be/nz99ncuEEt4?feature=shared'),
  ('Trap Bar Bottoms Up Bench Press', 'https://youtu.be/I8WCjE1hTPM?si=riNSekDaoROPTCoF'),
  ('Bulgarian Bag Alternating Spin to Side Swing Squat', 'https://youtu.be/2UpONYbzL7c?si=C2NbwmasH7LSljdz'),
  ('Bulgarian Bag Swipe', 'https://youtu.be/qFNcznHSBo8?si=5hfD700tGnPBWD3l'),
  ('Bulgarian Bag Snatch', 'https://youtu.be/9-gxBjR4OyE?si=Z1RZknDb7e1_9QmD'),
  ('Bulgarian Bag Alternating Side Swing Squat', 'https://youtu.be/KCyWRqPHOCQ?si=bsZ5UbqpPjccsnEp'),
  ('Bulgarian Bag Swing', 'https://youtu.be/Q7rAfqN-NH0?si=zEMPL2_L-ZEUhtLj'),
  ('Bulgarian Bag Front Rack Squat', 'https://youtu.be/jAo338cgsmU?si=1dPZPEL1g1HDUuIC'),
  ('Bulgarian Bag Back Rack Squat', 'https://youtu.be/ctrXJi1QgEQ?si=O95czG8N3RjyL-Y-'),
  ('Bulgarian Bag Swing Squat', 'https://youtu.be/gVYqz0SXsXE?si=WX6MR6-rxwXauydO'),
  ('Battle Rope Single Leg Standing Double Wave', 'https://youtu.be/6d6b8cx0pO0?si=NKi1a2se39GGFRx3'),
  ('Landmine V Grip Tall Kneeling Chest Press', 'https://youtu.be/FFWOG7Xk5RE?si=JwIHWZtHK6_oDHhQ'),
  ('Battle Rope Single Leg Standing Clap', 'https://youtu.be/bB3WGOVrqAg?si=Pby2lcyL_Cq98LT9'),
  ('Dumbbell Goblet Low Switch Cossack Squat', 'https://youtu.be/ggVuR079WHM?si=QWRGadB6a4zrJrLz'),
  ('Double Dumbbell Front Rack Cossack Squat', 'https://youtu.be/ZxjMX7k3Zp0?si=pZtrI1oUYV-FsjgX'),
  ('Double Dumbbell Low Hold Alternating Cossack Squat', 'https://youtu.be/k6L3kWztcNs?si=GiG4ZJIK5HCWo7Rm'),
  ('Suspension Cossack Squat', 'https://youtu.be/kZdZsw22lU4?si=Y2-3ATlU1R18Acir'),
  ('Barbell Back Rack Cossack Squat', 'https://youtu.be/pOSa7abtPaQ?si=RtB71Qujc9eZBx-J'),
  ('Landmine Goblet Cossack Squat', 'https://youtu.be/DYVAGWST-E8?si=NbgYbTD-kINhnv6a'),
  ('Dumbbell Goblet Cossack Squat', 'https://youtu.be/qxb36LOiBsc?si=9n0Wr7YfIHCom-_w'),
  ('Single Arm Dumbbell Front Rack Contralateral Cossack Squat', 'https://youtu.be/cmB4dq8MgVk?si=s0qFLxm2MDbbX3dw'),
  ('Double Dumbbell Front Rack Foot Elevated Cossack Squat', 'https://youtu.be/d0gACX9heHk?si=U0snvFOFoR0LH9Ne'),
  ('Dumbbell Low Hold Cossack Squat', 'https://youtu.be/k4p89WEkl58?si=S4JsgnfzWmFK3l4G'),
  ('Heavy Sandbag Bear Hug Carry', 'https://youtu.be/jb9Ge6SP8IA?si=FgQecwjAUfv-teLv'),
  ('Dumbbell Hip Thrust', 'https://youtu.be/LxdfGyNBuRU?si=x25Sk4tkkLiyY4t2'),
  ('Double Dumbbell Overhead Carry', 'https://youtu.be/dpVFicHv1PY?si=vQiTWZmKGTiqkHiH'),
  ('Single Arm Kettlebell Bottoms Up Clean', 'https://youtu.be/kMTZwJnCyjw?si=i72hlbqfO-UgCiPw'),
  ('Heavy Sandbag Shoulder Carry', 'https://youtu.be/35IarWLcV0s?si=4lqKX0sntuR1xdEa'),
  ('Double Dumbbell Front Rack Carry', 'https://youtu.be/dDq_T_H8h5E?si=g4wZK9kvKsPxqI3d'),
  ('Single Arm Dumbbell Front Rack Carry', 'https://youtu.be/5rsJK_z8nkY?si=CD5k3-b0r_JJpfHM'),
  ('Barbell Overhead Carry', 'https://youtu.be/ULpnqrFng5I?si=fKiyqdRwBpIeRaEx'),
  ('Barbell Front Rack Carry', 'https://youtu.be/ofwpNdE8yZU?si=T8V1vgUvY8g4tAZ9'),
  ('Double Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/FKrUoffD_W4?si=d07P0wkoguJqTTRV'),
  ('Alternating Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/BoihxFxtsyY?si=kZuvg9gJ179nJ1Xh'),
  ('Single Arm Kettlebell Suitcase March', 'https://youtu.be/Pjxd7M8bNU0?si=OeEny9WikOBA8B3P'),
  ('Double Kettlebell Half Snatch', 'https://youtu.be/5NV0b_RCWKk?si=LoNm1gGN8i-9QLGP'),
  ('Single Arm Kettlebell Half Snatch', 'https://youtu.be/iVaFwCBP1GM?si=9YPJCkbg5ckTydxm'),
  ('Heavy Sandbag Bear Hug Squat', 'https://youtu.be/ymSWvrARnCo?si=wSCDvQEQ8xPtVqbn'),
  ('Heavy Sandbag Shoulder Squat', 'https://youtu.be/VhCVdzYN820?si=07qvbVC4lpqJVZxR'),
  ('Heavy Sandbag Turkish Get Up', 'https://youtu.be/nUjB7PY_ch8?si=qTE38YBxSMytqVEV'),
  ('Heavy Sandbag Bear Hug Alternating Forward Lunge', 'https://youtu.be/68d5tiCgUy8?si=QZZ5qWDdvMU5WTQ_'),
  ('Heavy Sandbag Bear Hug Alternating Reverse Lunge', 'https://youtu.be/dd8M3MLhfjc?si=C40Jnp1OsYedBuT1'),
  ('Heavy Sandbag Shoulder Alternating Forward Lunge', 'https://youtu.be/2EkAq9e24EY?feature=shared'),
  ('Heavy Sandbag Shoulder Alternating Reverse Lunge', 'https://youtu.be/T4jp-7X-ai8?feature=shared'),
  ('Heavy Sandbag Shoulder Walking Lunge', 'https://youtu.be/YSd_xma0esE?si=1LEK7NMY3heh6sof'),
  ('Heavy Sandbag Shoulder Clean', 'https://youtu.be/cB7KJj-wqA4?si=_9jU8-LRtzGAT3e7'),
  ('Heavy Sandbag Over the Shoulder', 'https://youtu.be/fqzGFACRFWU?si=AdAu_hY9NYrlY8DS'),
  ('Heavy Sandbag Bear Hug Walking Lunge', 'https://youtu.be/X5s18gG7cJc?si=P3v8_2nsYkNdk5D7'),
  ('Bodyweight Hand Assisted Sissy Squat', 'https://youtu.be/nNAssQ-4HjA?si=wsCriUBiz-jLsGEk'),
  ('Bodyweight Sissy Squat', 'https://youtu.be/GHvRU4-Guuw?si=NJtNhZAAV3mKCcG-'),
  ('Bodyweight Hand Assisted Knee Over Toe Split Squat', 'https://youtu.be/gBSQOdjjKcc?si=oEXgjHk6m5c-o7MS'),
  ('Superband Sissy Squat', 'https://youtu.be/T2caG3uW8sA?si=AD_PdOw0tzZSfl3p'),
  ('Double Dumbbell Front Rack Walking Lunge', 'https://youtu.be/i3qlK1vA0z4?si=LCNdYUF9IbCDWnYm'),
  ('Single Arm Dumbbell Suitcase Walking Lunge', 'https://youtu.be/QR1CViFqmmc?si=4Lxq-QIIZ55jvMdx'),
  ('Single Arm Dumbbell Overhead Walking Lunge', 'https://youtu.be/lcCEvbAGHC8?si=Ri750XsY--4dDnB_'),
  ('Single Arm Dumbbell Front Rack Walking Lunge', 'https://youtu.be/GGjKBYEkZ-A?si=faI8XOKTHMInvAqG'),
  ('Barbell Front Rack Walking Lunge', 'https://youtu.be/ntGrVrVVNU0?si=3gtiQIlGPGnTePEX'),
  ('Kettlebell Goblet Horse Stance Squat', 'https://youtu.be/ZZ1piVHgy_8?si=I9HrW8xbkLx_UyJS'),
  ('Bodyweight Box Jump', 'https://youtu.be/-IzhFO7lOEU?si=Aftwsw6k2KY2-jf0'),
  ('Bodyweight Lateral Box Jump', 'https://youtu.be/GFdBbtdUfIU?si=GoMi96WWph2nlJpr'),
  ('Bodyweight Alternating Lateral Box Jump', 'https://youtu.be/kJqEVtWkYHo?si=aVVrhRraXLtyjPfg'),
  ('Bodyweight Straddle Planche', 'https://youtu.be/-huk0Idtr6M?si=mLwa_8pXggDXuFgO'),
  ('Macebell Single Leg Offset Bent Over Row', 'https://youtu.be/xpa6f9sJmiQ?si=gJH8lq53_OwgQY8F'),
  ('Single Arm Kettlebell Bird Dog Row', 'https://youtu.be/TBtjuZR8Dvo'),
  ('Single Arm Suspension Ipsilateral Pistol Squat', 'https://youtu.be/5G-vWzfeTy4?si=J9YetG0ZnmrQ6H76'),
  ('Kettlebell Single Leg Standing Hip Flexion', 'https://youtu.be/djxTlEIJdqc?si=IDadWzv3enNpiltr'),
  ('Kettlebell Goblet Alternating Cossack Squat', 'https://youtu.be/wrYqfSLWqdE'),
  ('Barbell Zercher Carry', 'https://youtu.be/yqtWcL9-1_k?si=q_p_4kAujNiWzCVq'),
  ('Double Kettlebell Bottoms Up Seated Overhead Press', 'https://youtu.be/7uS_6AgHk28?si=jXJ8ZwIqz_-aAInK'),
  ('Single Arm Kettlebell Bottoms Up Seated Overhead Press', 'https://youtu.be/f8Mgse4j3uc?si=GV-Q36irrQm7tYhE'),
  ('Macebell Offset Overhead Press', 'https://youtu.be/aOIjzeK24fY?si=HuhPoFZBScLorUuf'),
  ('Single Arm Dumbbell Sots Press', 'https://youtu.be/cc1TZmreJWE?si=aBzThLfX3rm5V3c1'),
  ('Double Dumbbell Sots Press', 'https://youtu.be/IjmQgS0bDao?si=wKCRqF1MeVyvhSwR'),
  ('Single Arm Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/JqoC2gQ1MRE'),
  ('Single Arm Kettlebell Ipsilateral Cossack Squat Thruster', 'https://youtu.be/_D87kNsSdv0'),
  ('Kettlebell Goblet Foot Elevated Cossack Squat', 'https://youtu.be/fhkFo0BxF5k'),
  ('Double Dumbbell Overhead Alternating Step Up', 'https://youtu.be/bYd08tHBi3c?si=jxsjM2VGsZK9-fBt'),
  ('Single Arm Dumbbell Overhead Contralateral Step Up', 'https://youtu.be/XJmnB32JJVw'),
  ('Barbell Overhead Alternating Step Up', 'https://youtu.be/ozPUu1GnFTI?si=mWpQsYkoy7akxELn'),
  ('Barbell Overhead Step Up', 'https://youtu.be/2rYLwmQGZXg?si=FC91EHLdOWAxPSXL'),
  ('Single Arm Dumbbell Suitcase Contralateral Step Up', 'https://youtu.be/23z9Mb4sMVk?feature=shared'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Step Up', 'https://youtu.be/fWhOG_9eHdE?feature=shared'),
  ('Single Arm Dumbbell Overhead Ipsilateral Step Up', 'https://youtu.be/8G0AKIfWSBs?si=A1jj7DSnbvZ7u7t-'),
  ('Kettlebell Goblet Low Switch Cossack Squat', 'https://youtu.be/Eod-qE6O33E?si=6CUX35luY_zr0tT_'),
  ('Kettlebell Low Hold Cossack Squat', 'https://youtu.be/svU3rff73Mo?si=wBPTEMnydOoIKHgd'),
  ('Kettlebell Low Hold Alternating Cossack Squat', 'https://youtu.be/ZclBW2lK-lY?si=fR_4w2NKvW_BzggV'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Cossack Squat', 'https://youtu.be/AYgBothlkOA?si=hiSrcI8KbslXlQrq'),
  ('Double Kettlebell Front Rack Carry', 'https://youtu.be/iD8tG0qfztk?si=Z2QMS4VxJJkJ-kUk'),
  ('Double Kettlebell Overhead Carry', 'https://youtu.be/7JUe6YXSM3g?si=TrnVTv62WQxSpsZ1'),
  ('Double Kettlebell Bottoms Up Overhead Carry', 'https://youtu.be/sUaLKjZx4X0?si=tcwai7A-NJGrnfYn'),
  ('Single Arm Kettlebell Overhead Carry', 'https://youtu.be/UTV5o4Oi2KM?si=RDXt3oFCH3cgDQiw'),
  ('Single Arm Kettlebell Bottoms Up Overhead Carry', 'https://youtu.be/m7e4dzCqoGA?si=wc7zBINGvkkas6BV'),
  ('Single Arm Kettlebell Half Kneeling Bent Press', 'https://youtu.be/AIMfooNNmvw?si=QCorVlRf7tHTepHu'),
  ('Bar Advanced Tuck Back Lever', 'https://youtu.be/ixeU8JtnItE?si=yeqNnWyHu_lYZQay'),
  ('Alternating Double Dumbbell Sots Press', 'https://youtu.be/YLxytoB3RN4?si=bzXKJBCQCbLTNZhd'),
  ('Suspension Single Leg Standing Bent Knee Mid Row', 'https://youtu.be/mZJieN2H4PM?si=gtPnQWWttdqNc67H'),
  ('Bar Circle Front Lever', 'https://youtu.be/ZiUXNRmnC9o?si=H4E1QFrZ06yPO-Jz'),
  ('Suspension Single Leg Standing Bent Knee Low Row', 'https://youtu.be/PaYajo0NIjs?si=BnxQHt0l6HLbbkgL'),
  ('Single Arm Suspension Rotational Row', 'https://youtu.be/EOjx-EK_91I?si=RWxX91ZewMkt9AFa'),
  ('Alternating Double Indian Club Outer Heart Shaped Swing', 'https://youtu.be/3j-GT-SlBj4?si=UkgK_A3tck5Lm2rK'),
  ('Double Indian Club Parallel Swing', 'https://youtu.be/nDugTXCHzFY?si=NQvVJIZJswsF1HNn'),
  ('Suspension Feet Elevated Decline Push Up', 'https://youtu.be/rZ2F0Fo1Cts?si=ki-LUP1NvXaLVXL3'),
  ('Bar Full Back Lever', 'https://youtu.be/I5pStn4M6AU?si=xYguBx9qhd3Movl6'),
  ('Bar Full Front Lever', 'https://youtu.be/1QCwhp_WlEA?si=wXgs8tAgUOVzgUhI'),
  ('Slider Atomic Push Up', 'https://youtu.be/XsU1dAVQ04M?si=xZbKraABgDpY1zUM'),
  ('Slider Reach Push Up', 'https://youtu.be/7OwOfbA13Nw?feature=shared'),
  ('Bar Half Lay Back Lever', 'https://youtu.be/mT2_DYAVu8c?si=shnn4gm9QMQ0x3Y5'),
  ('Bar Half Lay Front Lever', 'https://youtu.be/z-zP32fnugI?si=38IL3ATf8aLehR74'),
  ('Bar Hanging Knee Raise', 'https://youtu.be/KNzJ3GuIpB8?si=va7oq1yMev2p_dQ2'),
  ('Bar Hanging Toes to Bar', 'https://youtu.be/xX9Hzi7Onnw?si=DF7ySd87D6LcLvwN'),
  ('Bar Hanging Oblique Knee Raise', 'https://youtu.be/sqDdHFC1KYk?si=VwW9AhJxnFtKqLWf'),
  ('Bar Hanging L Sit Flutter Kicks', 'https://youtu.be/MGBT77oSGiA?si=AGhUTOg_vYJNxD4y'),
  ('Single Arm Kettlebell Half Kneeling Ipsilateral Overhead Press', 'https://youtu.be/6p9PqTZuhcg?si=nxxkNsm2jrR22MT1'),
  ('Slider Alternating Reach Push Up', 'https://youtu.be/Rz_FBXCafls?si=wfY5MWfyEHQ-ZbZR'),
  ('Bar Single Leg Out Back Lever', 'https://youtu.be/3M3VxKm08cs?si=dt2GQl57ObWtHdOH'),
  ('Bar Single Leg Out Front Lever', 'https://youtu.be/HzcWRdP78Wo?si=l0PzesASSgyca9XI'),
  ('Bar Straddle Back Lever', 'https://youtu.be/-H0jvoX9D4U?si=JgYHw7fT5duJS_3Q'),
  ('Alternating Double Kettlebell Bottoms Up Overhead Press', 'https://youtu.be/xjbycsKgqjQ?si=LkTmhk8Js8iT50DU'),
  ('Bar Tuck Back Lever', 'https://youtu.be/LfyGMZh-Bz4?si=6Cp5HCRlHxaaAXAk'),
  ('Double Kettlebell Bottoms Up Seesaw Overhead Press', 'https://youtu.be/HDzbviKeH8A?si=B97qZHv-l5DP5Zwg'),
  ('Bar Tuck Front Lever', 'https://youtu.be/BDYs4d0-dbs?si=xhEemMS0ZwEdNi-P'),
  ('Bodyweight Fingertip Full Planche Push Up', 'https://youtu.be/kw0kXtvOpfU?si=l1qrLXesjuSAv8NK'),
  ('Ring Grip Push Up', 'https://youtu.be/d305HI37Rc0'),
  ('Single Arm Barbell Overhead Press', 'https://youtu.be/Oz--LasDphM?si=JVdkguhnIxf9Ho8X'),
  ('Ring Shoulder Stand', 'https://youtu.be/_Jf4hAHEwm8'),
  ('Ring Strap Handstand', 'https://youtu.be/3cLo1dWPqis'),
  ('Ring Strap Handstand Push Up', 'https://youtu.be/nUt-_d3zP2w'),
  ('Bodyweight Straddle Press Handstand', 'https://youtu.be/olR47A-UOYU?si=XvqzFclDvXSJPmsi'),
  ('Bodyweight Alternating Step Up', 'https://youtu.be/lUSmIRNqt9w?si=2Uzz5dQAroAGZKAK'),
  ('Bodyweight Step Up', 'https://youtu.be/V9ButqpLLcw?si=W7rot5ocLsfGP3zd'),
  ('Bodyweight Pike Press Handstand', 'https://youtu.be/5qjQF8Bwk9Y?si=hKn5hERkDvTWUSxe'),
  ('Parallette L Sit to Straddle Press Handstand', 'https://youtu.be/Hx31luas38Q'),
  ('Heavy Sandbag Clean to Push Press', 'https://youtu.be/AVH3_x1LZA4?si=xUfQv7BiQgAH0riW'),
  ('Ring Tuck Front Lever Pull Up', 'https://youtu.be/7gLyX3Q1KJA'),
  ('Double Kettlebell Suitcase Walking Lunge', 'https://youtu.be/OFSepehKEsg?si=cACSI6X-vniOrBik'),
  ('Single Arm Ring Push Up', 'https://youtu.be/9sjQEtGoScA'),
  ('Ring L Sit Muscle Up', 'https://youtu.be/CP4kwFLxRYg'),
  ('Ring Strict Muscle Up', 'https://youtu.be/vJTJFc2wmk4'),
  ('Single Arm Kettlebell Suitcase Walking Lunge', 'https://youtu.be/ojCvehn5SjY?si=tdD_tXPCt_VXy9h3'),
  ('Single Arm Kettlebell Front Rack Walking Lunge', 'https://youtu.be/9C-hKwyOaE4?si=SpYmw0aHIO29g-Cj'),
  ('Single Arm Kettlebell Overhead Walking Lunge', 'https://youtu.be/ApTlAc-7lGY?si=SjnB0ffZ9Ws6qo9D'),
  ('Single Arm Kettlebell Bottoms Up Overhead Walking Lunge', 'https://youtu.be/0D5CejWdGE4?feature=shared'),
  ('Clubbell Inside Pendulum', 'https://youtu.be/KPxWt4X3CYQ?si=LHuzEfvY58pZcQ4P'),
  ('Kettlebell Romanian Deadlift', 'https://youtu.be/keiZFdUgvKQ?si=dkMliNkbyV8fodl2'),
  ('Barbell Snatch Balance', 'https://youtu.be/XuFaD1sAVGI?si=TR-XC6iaJP514gda'),
  ('Parallette Straddle Press to Handstand', 'https://youtu.be/DRYQDMUVgYE'),
  ('Double Dumbbell Suitcase March', 'https://youtu.be/Yz0g3nK0UH8?si=uzYt2n3dgbhVRnnW'),
  ('Single Arm Dumbbell Suitcase March', 'https://youtu.be/l5n8bNkwXFo?si=N5Nmp5n6RrmLD2uu'),
  ('Double Dumbbell Front Rack March', 'https://youtu.be/46yupJpHPBM?feature=shared'),
  ('Single Arm Dumbbell Front Rack March', 'https://youtu.be/x_pMZHT1PJI?si=gXaoVxcFe0j1mtPQ'),
  ('Double Dumbbell Overhead March', 'https://youtu.be/Iqc40RmX2t8?si=6XNRQXHsREEsYjGr'),
  ('Single Arm Dumbbell Overhead March', 'https://youtu.be/6Yw94hTsI2s?si=oPrzNDtNw4g-Xhy-'),
  ('Barbell Front Rack March', 'https://youtu.be/dSSBwrzbtGI?feature=shared'),
  ('Barbell Back Rack Alternating Forward Lunge', 'https://youtu.be/H8YHDNCH5-o?si=niOwS0JaOXdOT4Ip'),
  ('Barbell Back Rack Alternating Reverse Lunge', 'https://youtu.be/fP3L8yqDaYo?si=xq03w4XotIlArOk3'),
  ('Kettlebell Single Leg Romanian Deadlift', 'https://youtu.be/wacHvU9ISqQ?si=6Hco-OabboEOEO3N'),
  ('Single Arm Ring Eccentric Chin Up', 'https://youtu.be/Vg0K1uuNQLI'),
  ('Parallette Freestanding Handstand', 'https://youtu.be/Qoyxwu0i5Og?si=v6_bUX0l76eWrYRZ'),
  ('Ring Gironda Sternum Chin Up', 'https://youtu.be/PUjiG2iQHzk?si=OVi5AVNaOFs0SP5b'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Pistol Squat', 'https://youtu.be/RHj4ErHsJAw?si=ZUMLXqjq5pmMSAf_'),
  ('Kettlebell Horn Grip Pistol Squat', 'https://youtu.be/L0S7ATOR1Rw?si=KpjiKwE_QaiTxnfw'),
  ('Double Kettlebell L Sit', 'https://youtu.be/AOjVLnxbmHU?si=LVrFAJ6HK8bfJmCb'),
  ('Double Kettlebell L Sit Lift Over', 'https://youtu.be/FNsKwVfAF2A?si=ZLDbQY35pGpv6Wk5'),
  ('Single Arm Kettlebell Bottoms Up Windmill', 'https://youtu.be/sGgI_gV85Zs?si=0_msxxqLJEv8yQl7'),
  ('Double Kettlebell Overhead March', 'https://youtu.be/R2nuXQJt-08?si=ZZwubaIV-9OycLD5'),
  ('Single Arm Kettlebell Overhead March', 'https://youtu.be/GL4yx2rQpIs?si=lvmUx2j0LaKZx4RZ'),
  ('Double Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/oeyAEgHBVYc?si=mHjzSFPeM2YyoC0H'),
  ('Double Kettlebell Suitcase Alternating Lateral Lunge', 'https://youtu.be/zO8xPAa4-cY?si=bSfD4Gd8EdQ631Hq'),
  ('Double Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/TzuHADj8h4M?si=tAyLqN0pCIXqxity'),
  ('Double Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/KIDRnwRAKAY?si=b00pYocO2xqWBGiJ'),
  ('Double Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/JKk87eVdbG8?si=Est-myfua9sI06NN'),
  ('Double Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/A4SnLhdMKu4?si=AWoi6qQOHivzUZeZ'),
  ('Double Dumbbell Suitcase Alternating Lateral Lunge', 'https://youtu.be/GkgTBlp417A?si=2RKL7GSC-wlwXQrE'),
  ('Double Dumbbell Front Rack Alternating Lateral Lunge', 'https://youtu.be/V-crv5-Tqbg?si=k00dfu1tLmH4-h3a'),
  ('Double Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/Ambx6K-_AfY?si=2pUqPVUnlmZLMMwH'),
  ('Double Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1iT74xBv0LA?si=vNMiZEtQ8W3QCkqc'),
  ('Double Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/8OZUh9sHk-8?si=euVM8-cldcw4zaJf'),
  ('Double Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/eK7AzF0-rt4?si=0L-vfrm5QmGhcV2l'),
  ('Single Arm Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/DbANzYj8EWQ?si=NULTCgfWBvm6vNpX'),
  ('Single Arm Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/kTfl5mhcwso?si=iDo9iOmHhKSZIQlN'),
  ('Single Arm Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/b3ewFBSqc9k?si=l6I7tV4HN4z6vcCS'),
  ('Single Arm Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1uuCmY9bVao?si=0iam54INq6LqKgrV'),
  ('Single Arm Dumbbell Overhead Alternating Forward Lunge', 'https://youtu.be/RNdGRLDFZ_E?si=ViWm3Cym-_kPAyPr'),
  ('Single Arm Dumbbell Overhead Alternating Reverse Lunge', 'https://youtu.be/y6Z1csYJqI8?si=VJQkALrooI76ZWQ9'),
  ('Double Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/iPBOqxEBcto?si=yJqaSgMnybSQX6Oy'),
  ('Double Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/HFjBFM1Fswo?si=BiUd6crmcvrtRZx2'),
  ('Dumbbell Goblet Alternating Lateral Lunge', 'https://youtu.be/xFvob3P7I74?si=o6y90mzLlkb5kjLo'),
  ('Dumbbell Goblet Alternating Forward Lunge', 'https://youtu.be/MjHkEW-AMQI?si=EyW7vqzwyfCJv1bN'),
  ('Dumbbell Goblet Alternating Reverse Lunge', 'https://youtu.be/YidVOnuiDfc?si=ECuN-ZTMBkyH_maZ'),
  ('Landmine Goblet Alternating Lateral Lunge', 'https://youtu.be/-hWgE1P2aAA?si=7mOaE_-aBxpQNBSX'),
  ('Landmine Goblet Alternating Reverse Lunge', 'https://youtu.be/VI0GDe_doBk?si=U14f8Dk6Ly1aMzBr'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/aopAoW1cmUk?si=EyVEsJC9bLaQC6ND'),
  ('Double Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/QV4DL31Ch94?si=6O9QTMoEB9MtwsZY'),
  ('Single Arm Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/eGKpS3AxCVA?si=-uyv4kyU-FY0yBfB'),
  ('Single Arm Dumbbell Overhead Cyclist Squat', 'https://youtu.be/Fm-EgA1xP4g?si=TXFdciSwYJ3flVng'),
  ('Bodyweight Alternating Lateral Lunge', 'https://youtu.be/FvJS_MSN4Lo?si=Z7h-t5HEEQC6trw6'),
  ('Bodyweight Alternating Forward Lunge', 'https://youtu.be/0RqJM6GM5bg?si=eL5TvNrMzUaI1oOW'),
  ('Bodyweight Alternating Reverse Lunge', 'https://youtu.be/OX0fKkaY6_c?si=T0Ta2iyvXrGIGA7w'),
  ('Double Dumbbell Overhead Squat', 'https://youtu.be/iGLwbS5aHY4?si=f7TNizeYPw8xX1xR'),
  ('Single Arm Dumbbell Overhead Squat', 'https://youtu.be/SokWJEUYgfc?si=OWsmg8u6_2Xz09z9'),
  ('Double Dumbbell Front Rack Bulgarian Split Squat', 'https://youtu.be/6DO1p1pOAwM?si=zeLSk3SSoVkoP_B9'),
  ('Double Dumbbell Overhead Bulgarian Split Squat', 'https://youtu.be/7rGFnvK6KkE?si=SL3VLXM4o_8TDV_0'),
  ('Single Arm Dumbbell Suitcase Contralateral Bulgarian Split Squat', 'https://youtu.be/iylKd9ymBQE?si=D_mNdhDHgU7B8xbD'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Bulgarian Split Squat', 'https://youtu.be/7oQoOglG_cA?si=JLNoB9O2s2KyOAf1'),
  ('Single Arm Dumbbell Front Rack Contralateral Bulgarian Split Squat', 'https://youtu.be/-vKdvtdkRRc?si=CPo0dP5KaIc0TJu5'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Bulgarian Split Squat', 'https://youtu.be/pEZWYmpCzu8?si=i70Ip_o4npwew5bY'),
  ('Suspension Alternating Lateral Lunge', 'https://youtu.be/0bqrj4BimaI?si=03pxBE_5_ozxIivb'),
  ('Bulgarian Bag Back Rack Alternating Lateral Lunge', 'https://youtu.be/fJePN1sD5ok?si=g-YYXG1x8L53Vuv-'),
  ('Bulgarian Bag Back Rack Walking Lunge', 'https://youtu.be/FNr5JBGrJTU?si=bn24rl-sBOt5WTfx'),
  ('Bulgarian Bag Back Rack Alternating Forward Lunge', 'https://youtu.be/a8y1Qwir7YQ?si=izeBmxPLl4E0ekvy'),
  ('Sandbag Front Rack Alternating Lateral Lunge', 'https://youtu.be/0el8H9fy3g0?si=BdlZ75xoh6Xq1wpJ'),
  ('Sandbag Front Rack Walking Lunge', 'https://youtu.be/mGwXPP-QKko?si=pUfEZOZPOOYaTV3n'),
  ('Sandbag Front Rack Alternating Forward Lunge', 'https://youtu.be/1L2HnCKmsRs?si=fIVyc7oXYDkkRzgJ'),
  ('Sandbag Front Rack Alternating Reverse Lunge', 'https://youtu.be/SJe_O4NPU-E?si=OKoj1OGsurlSWTEA'),
  ('Plate Overhead Walking Lunge', 'https://youtu.be/hVIaVvyY-H8?si=HsyRlDh-j--gHbsk'),
  ('Plate Overhead Alternating Forward Lunge', 'https://youtu.be/k6pHuYm2nV8?si=ttotAgiXtgPihuX3'),
  ('Plate Overhead Alternating Reverse Lunge', 'https://youtu.be/X5UicuSpd-g?si=vkWg2RXcC-HFi6Pk'),
  ('Bodyweight Tuck Planche', 'https://youtu.be/VFYZh24e0RI?si=_Vjvy9tWBn4nc7l_'),
  ('Double Kettlebell Push Up to L Sit', 'https://youtu.be/V-157r2C-qU'),
  ('Bar Hanging L Sit', 'https://youtu.be/WHi1bvZLwlw?si=NKvlsqG8aI-wDQfJ'),
  ('Ring Hanging L Sit', 'https://youtu.be/8DMns2IRlg4?si=hbMMsP9DfSOthR7b'),
  ('Single Arm Bar Hanging L Sit', 'https://youtu.be/HvdS2ClV9KU?feature=shared'),
  ('Single Arm Ring Hanging L Sit', 'https://youtu.be/_o_4N2yJwAw?si=Hum3bBKngYoqfDUc'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/CQR7UUijw38?si=ncO4L8hVq2h4htQQ'),
  ('Parallette L Sit Flutter Kicks', 'https://youtu.be/zDRj6Sw6tw8?si=Fp368ZWQaw_YDQay'),
  ('Bodyweight Single Arm Contralateral Single Leg Push Up', 'https://youtu.be/I6f7uUmozDY'),
  ('Parallette Tuck Planche Push Up', 'https://youtu.be/hFHpQAqqMDA'),
  ('Ring Maltese Push Up', 'https://youtu.be/kpOpHoywVKU'),
  ('Bar Advanced Tuck Front Lever Pull Up', 'https://youtu.be/cVdb8oUGKAw?si=tC4dDZ3QsBtE_4_m'),
  ('Bar Gironda Sternum Chin Up', 'https://youtu.be/58QkcGVA12A?si=ddrndE8UqnvYVadB'),
  ('Bar Strict Muscle Up', 'https://youtu.be/t8_M2aHiNDk?si=s9zri6LcdUJrvwbV'),
  ('Bodyweight Tuck Planche Push Up', 'https://youtu.be/U-MgWVM_2-Y?si=-XnkVL5OAVXtyCPu'),
  ('Double Clubbell Asynchronous Mill', 'https://youtu.be/2t7u5sapU1Q?si=KigwClnysDsb8CGJ'),
  ('Bodyweight L Sit', 'https://youtu.be/pO4BH0dKCIY?si=qKwpWcDltQZ0K61z'),
  ('Bodyweight Single Arm L Sit', 'https://youtu.be/l-7PDo_nf-c?si=SV8BnhirXI2QflsN'),
  ('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/X8I4Uq4QgYE?si=0ZNJz2TPEC0nSZaa'),
  ('Single Arm Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/vVElqek25fI?si=4-FGE3vFSRTkYdG4'),
  ('Single Arm Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/oOB02xJgzrA?si=IO-ooFFstcNesTGD'),
  ('Single Arm Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/tildBryP8bI?si=mIky-m7uqR4kMvB3'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Forward Lunge', 'https://youtu.be/q7sQB0_p7XQ?feature=shared'),
  ('Parallette V Sit to Pike Press Handstand', 'https://youtu.be/i3tkgdhZuj0?si=lupWBeLYXNXi2bV0'),
  ('Ring Pseudo Planche Push Up', 'https://youtu.be/f09iB8jbioo?si=MFJiOigiohOtQybY'),
  ('Stability Ball Feet Elevated Glute Bridge', 'https://youtu.be/8Ta_A9vAEGs?si=pSj3gDFijzwcALE4'),
  ('Bodyweight Mountain Climber', 'https://youtu.be/kLh-uczlPLg?si=WfwS9PlCOc9d1t1N'),
  ('Suspension Feet Elevated Mountain Climber', 'https://youtu.be/XiB48dLaB9g?si=RkTU535X9lQ-XULA&amp;utm_source=MTQxZ'),
  ('Bodyweight Straddle L Sit', 'https://youtu.be/XS7Y1jQ-kxs?si=hFDuiao7cTRRHUCT'),
  ('Single Arm Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge', 'https://youtu.be/xhyigP6lpAM?feature=shared'),
  ('Bodyweight Cossack Squat', 'https://youtu.be/lyMHR7F8lPA?si=An72TBlVkZQu4GMO'),
  ('Bodyweight Wall Facing Handstand Push Up', 'https://youtu.be/ZDhNSacJLEE?si=aGw3Fw5a7Q34pWuk'),
  ('Ring Pelican Push Up', 'https://youtu.be/4zSzWYRiBGI?si=NqLN5I_ZFwPkfPXM'),
  ('Barbell Back Rack Alternating Step Up', 'https://youtu.be/_iZ9bGw84H8?si=4Ff3XGU-WRY1uN0k'),
  ('Barbell Front Rack Alternating Step Up', 'https://youtu.be/b8ldbeOnJEI?si=PBXslcF1v1YEXgGU'),
  ('Ring Feet Elevated Pelican Push Up', 'https://youtu.be/HdaAXHcN0-M?si=fT7_2ec7wdcSALfm'),
  ('Ring Tuck L Sit', 'https://youtu.be/Vuc-nodHS0Y?si=S81fiCUEtPrZUe6Z'),
  ('Ring Hanging Tuck L Sit', 'https://youtu.be/SLyOG8ujcu0?si=IAzc53JTuuKNMz90'),
  ('Bar Hanging Tuck L Sit', 'https://youtu.be/QA_dH6cjbw0?si=29xMuvVPe0ttRvvK'),
  ('Single Arm Kettlebell Overhead Alternating Forward Lunge', 'https://youtu.be/LMStE_hD9E4?si=_iskUn08-BQH0mYu'),
  ('Ring Mountain Climber', 'https://youtu.be/5BaV4f58I3c?si=LhV-BmrDvHK1G_uI'),
  ('Ring Feet Elevated Mountain Climber', 'https://youtu.be/kbPOFMH-Ivk?si=ftd7bXesKjVBgNrW'),
  ('Single Arm Kettlebell Overhead Alternating Reverse Lunge', 'https://youtu.be/neuw_JknIms?si=QPBFpV8bvbtlFLfL'),
  ('Ring Dead Hang', 'https://youtu.be/uMcoQ-ijpsk'),
  ('Parallette Kneeling Push Up', 'https://youtu.be/iHR7BprMyEc'),
  ('Clubbell Outside Circle', 'https://youtu.be/9lVJZ8o8nzM?si=4NnTRdg9x60PkNsZ'),
  ('Single Arm Kettlebell Bottoms Up Overhead Alternating Reverse Lunge', 'https://youtu.be/N4GPqbj8Nds?feature=shared'),
  ('Stability Ball T''s Y''s I''s', 'https://youtu.be/1jP1PR9Gls0?si=esOirS5dWd5oUqG0'),
  ('Resistance Band Reverse Fly', 'https://youtu.be/C2wsrjVHvuA'),
  ('Resistance Band Lateral Raise', 'https://youtu.be/1feV0cW5U60?si=e6dhNFXt6CLSbkRE'),
  ('Double Dumbbell Lateral Raise', 'https://youtu.be/XPPfnSEATJA?si=yNFrwT2Aj4G98NVF'),
  ('Double Dumbbell Seated Lateral Raise', 'https://youtu.be/GBo4Cj8i9VI?si=_ZCYRalndjXZl58y'),
  ('Single Arm Dumbbell Side Lying Shoulder External Rotation', 'https://youtu.be/_qPQKid-LRs'),
  ('Miniband Standing Shoulder External Rotation', 'https://youtu.be/4cpQr1VbcEU'),
  ('Stability Ball Double Dumbbell Seated Arnold Press', 'https://youtu.be/4Hwcp9HP9D4'),
  ('Single Arm Cable Lateral Raise', 'https://youtu.be/9s0F9lgTG0E?si=hlzVQJ0I5qgbvM45'),
  ('Double Dumbbell Seated Overhead Press', 'https://youtu.be/3GFZpOYu0pQ'),
  ('Double Dumbbell Overhead Press', 'https://youtu.be/AqzDJHxynwo?si=FpgeOvlc1u-WxGMb'),
  ('Double Dumbbell Shrug', 'https://youtu.be/llSrlpd7TEE?si=7L7ARn0S6ByQmI59'),
  ('Double Dumbbell Standing Scaption', 'https://youtu.be/bhemEvr0qiM?si=WahKrQS3-uEP1hYU'),
  ('EZ Bar Kneeling Rollout', 'https://youtu.be/qGVLUwKTvTw?si=wziniMZUeqke6bE4'),
  ('EZ Bar Standing Rollout', 'https://youtu.be/zGZrhC_VWIQ?feature=shared'),
  ('Double Dumbbell Seated Scaption', 'https://youtu.be/Vn1cULRUhZI'),
  ('Stability Ball Double Dumbbell Seated Scaption', 'https://youtu.be/PKgkMmXAVUs'),
  ('Alternating Double Dumbbell Bicep Curl', 'https://youtu.be/WYezBGuUsdw'),
  ('Alternating Double Dumbbell Incline Bench Bicep Curl', 'https://youtu.be/bgYt7ZgFc9M'),
  ('Alternating Double Dumbbell Hammer Curl', 'https://youtu.be/h46ccQsXDEk'),
  ('Alternating Double Dumbbell Cross Body Hammer Curl', 'https://youtu.be/buP9fSqWcw4?si=-lKec0VHJ1XbZYRH'),
  ('Single Arm Dumbbell Incline Bench Preacher Curl', 'https://youtu.be/DPYrHeVKvQA'),
  ('Dumbbell Crush Grip Bicep Curl', 'https://youtu.be/at2g_OGyuDE'),
  ('Double Dumbbell Zottman Curl', 'https://youtu.be/wrjEdVZrkhk'),
  ('Dumbbell Waiter Curl', 'https://youtu.be/DjgrEWlgGaY'),
  ('Cable Straight Bar Drag Curl', 'https://youtu.be/s_5mJUQqQpY?si=4zKcXdHvIHVCrn6n'),
  ('Cable Rope Hammer Curl', 'https://youtu.be/BXcSLzXrab4?si=KZPHi7uurh7Nb31j'),
  ('Kettlebell Goblet Alternating Lateral Lunge', 'https://youtu.be/Z8dcGhS8giQ?si=iQZ35AJwvoHewxyk'),
  ('Suspension Bicep Curl', 'https://youtu.be/nipJ27JfpUI'),
  ('Double Dumbbell Tricep Kickback', 'https://youtu.be/m_UlDFNX4mk?si=FAleOyAOFc4IiSBT'),
  ('Tire Jump', 'https://youtu.be/yrNR2OK50Lw?si=o9UhhO3HdGYOlRvS'),
  ('Tire Jump Through', 'https://youtu.be/1DBz3vodUUc?feature=shared'),
  ('Tire Broad Jump', 'https://youtu.be/juTI6wnRiZ8?si=AItO7HER5TxfhHc9'),
  ('Tire Step Up', 'https://youtu.be/4RsPF6KynpE?feature=shared'),
  ('Tire Alternating Step Up', 'https://youtu.be/JdYIi6Vedy8?si=XLKOd1kgeuZgH3Wp'),
  ('Tire Alternating Toe Taps Around the World', 'https://youtu.be/diT5j5QRKhs?si=KBmQGQunZ8mtj5zz'),
  ('Dumbbell Seated Overhead Tricep Extension', 'https://youtu.be/-aBcUgsn8Dc'),
  ('Tire Lateral Jump Through', 'https://youtu.be/H80_t9poKQo?si=eTIuIU_bwT40hUvJ'),
  ('Tire Carry', 'https://youtu.be/QskOD3ROxGs?si=Vh3moyP5PVPO8sMy'),
  ('Dumbbell Overhead Tricep Extension', 'https://youtu.be/7h3lG2WnLXg'),
  ('Double Dumbbell Close Grip Floor Press', 'https://youtu.be/s6ydoB3ktlI'),
  ('Barbell Back Rack Carry', 'https://youtu.be/c2D4GkTgyo4?si=s6c03eCCz8TWg7br'),
  ('Single Arm Barbell Suitcase Carry', 'https://youtu.be/-FZcqOBDphU?si=FQJnUQP2TsxKmhRA'),
  ('Suspension Bulgarian Split Squat', 'https://youtu.be/BnLkbAGE4b4?si=mRL2wc8pDdJKZNbY'),
  ('Suspension Bulgarian Split Squat Jump', 'https://youtu.be/ABtwgwo4zyQ?si=eWDNpXtH8qJ31y72'),
  ('Bodyweight Lateral Bear Crawl', 'https://youtu.be/JLtXEZAwNxQ?feature=shared'),
  ('Bodyweight Step Up Jump', 'https://youtu.be/bZYAKXoBXGs?si=HbHeFnXtAvKsYndx'),
  ('Bodyweight Alternating Step Up Jump', 'https://youtu.be/vX2vagAc8Mw?si=UH9R_7g0TbIQyHja'),
  ('Barbell Power Clean to Push Press', 'https://youtu.be/4ws-kHR5NaU?si=3YQjL6sBFZ3aL-hW'),
  ('Double Dumbbell Close Grip Bench Press', 'https://youtu.be/bo6bVNho2v8?si=hNk_wo1PWsqhkRyo'),
  ('Single Arm Clubbell Outside Pendulum', 'https://youtu.be/nDGz-drTS1E?si=phIMAk1VibF9KzwH'),
  ('Clubbell Outside Pendulum', 'https://youtu.be/8v5XgK3oeeE?si=kU1NrAcgDEWvlUj6'),
  ('Double Dumbbell Close Grip Incline Bench Press', 'https://youtu.be/a2RWkUS7ja4?si=MlLBdANbCwT-w0d1'),
  ('Cable Rope Tricep Pushdown', 'https://youtu.be/e5aj8hhCPkA'),
  ('Barbell Incline Push Up', 'https://youtu.be/CKKfNBe687Q'),
  ('Bodyweight Kneeling Push Up', 'https://youtu.be/TBpk09QuVN8'),
  ('Suspension Push Up', 'https://youtu.be/cp_Hl7qd7CI?si=Tw8VVXnhtyW9vra4'),
  ('Suspension Chest Fly', 'https://youtu.be/ELmdfR9JvEA'),
  ('Stability Ball Double Dumbbell Chest Fly', 'https://youtu.be/pHsw9uHVXWA?si=0LlXNPKcyTKyfgU4'),
  ('Stability Ball Dumbbell Pullover', 'https://youtu.be/TI1gb3GFUVA'),
  ('Double Dumbbell Incline Bench Chest Fly', 'https://youtu.be/JSDpq14vCZ8?si=DX2UhxTVlOLFkyF3'),
  ('Suspension Low Row', 'https://youtu.be/hULU2N_9qjk?si=XmozOzBr-Uny0t4A'),
  ('Tire Flip', 'https://youtu.be/44E5KRVFWVQ?si=M9W-NS9JbwJV8hDU'),
  ('Tire In and Out Squat Jump', 'https://youtu.be/4h3cIxkFwlI?si=s_iXYmvt1ljfSFML'),
  ('Kettlebell Goblet Alternating Forward Lunge', 'https://youtu.be/wkMhmQ5wVWY?si=kFZCkvoaBfUNdjvU'),
  ('Double Dumbbell Suitcase Feet Elevated Calf Raise', 'https://youtu.be/UCfMPCfug60?si=hzjhqnpt1-9bHCWt'),
  ('Double Dumbbell Suitcase Calf Raise', 'https://youtu.be/wsOcmGYOn3M?si=2w1Cs0RdcdjnHLYG'),
  ('Suspension Mid Row', 'https://youtu.be/W-nnq0Ks1A0'),
  ('Double Dumbbell Seated Calf Raise', 'https://youtu.be/3ZRe_QpvRPg?si=X5ees0OsHDogPrA9'),
  ('Barbell Seated Calf Raise', 'https://youtu.be/hv00OCqm0HI?feature=shared'),
  ('Bodyweight Hand Assisted Feet Elevated Calf Raise', 'https://youtu.be/JUDbOvgH6AQ?si=p3CkDDLIlKjuufVF'),
  ('Bodyweight Hand Assisted Calf Raise', 'https://youtu.be/HwG4_WIMB7g?si=ly2SGRWM5lHuzOHF'),
  ('Bodyweight Calf Raise', 'https://youtu.be/tg3HcGWhGN8?si=i7ZBKBUTgTovDmeO'),
  ('Bodyweight Hand Assisted Foot Elevated Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=gPxN6_F1w9qQdHvy'),
  ('Bodyweight Hand Assisted Single Leg Calf Raise', 'https://youtu.be/5hkhz_nMuws?si=M_cdEJeEYZLJJD6j'),
  ('Bodyweight Single Leg Calf Raise', 'https://youtu.be/AWBGE0PlYkI?si=INJvlHfbZ6BpG0RT'),
  ('Kettlebell Goblet Alternating Reverse Lunge', 'https://youtu.be/Q8s5KVgRjsI?si=LU2DAUzkwtjOm87N'),
  ('Double Kettlebell L Sit Flutter Kicks', 'https://youtu.be/bNmYhWaTtDE?si=0pRJsSgsFQN8tX9D'),
  ('Double Dumbbell Front Rack Calf Raise', 'https://youtu.be/nDJ9cjw2J7Y?feature=shared'),
  ('Barbell Back Rack Feet Elevated Calf Raise', 'https://youtu.be/-zJsdaS13fk'),
  ('Tire Mountain Climber', 'https://youtu.be/-ouYHaP9g9g?si=qc9f_XLeK0tBdsDc'),
  ('Bodyweight Wall Supported Tibialis Raise', 'https://youtu.be/nQKgHwi8W9E?si=h2cdsN6y8_YWkxWd'),
  ('Cable Seated Tibialis Raise', 'https://youtu.be/XPrwraNV8zU?si=uYKDsDSy6F1lqx7L'),
  ('Cable Seated Single Leg Tibialis Raise', 'https://youtu.be/tSDRe05L18Q?si=tzWWp_aDlp6K7_QS'),
  ('Kettlebell Goblet Walking Lunge', 'https://youtu.be/oV97EckMQlo?si=-UB0G60JaIQ6f-4v'),
  ('Dumbbell Seated Tibialis Raise', 'https://youtu.be/2amvxbpU20c?si=ymK8PzcHyFCMv-oX'),
  ('Kettlebell Horn Grip Alternating Lateral Lunge', 'https://youtu.be/hP0wET7bCog?si=trU9Rde7VACKCuEn'),
  ('Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/w6vfiCgfbXA?si=RhaJhv_PYjW4LLj5'),
  ('Double Dumbbell Seated Feet Elevated Calf Raise', 'https://youtu.be/W5FNgQSaDfU?si=mrb4anmAuXMyWfuC'),
  ('Barbell Seated Feet Elevated Calf Raise', 'https://youtu.be/TyJOknODp8g?si=lIKKdyiWkncjpZtZ'),
  ('Kettlebell Horn Grip Alternating Forward Lunge', 'https://youtu.be/fZeR04SyMnM?si=PcC3GMitpRy-d_N5'),
  ('Tire Leg Press', 'https://youtu.be/YtKIXuPCj1M?si=ng5HKT4Y_EUFLk95'),
  ('Cable Isometric Split Squat Pallof Press', 'https://youtu.be/zMR-P_9GGKE?feature=shared'),
  ('Bodyweight Isometric Split Squat Calf Raise', 'https://youtu.be/pM_ycFCgDxU?si=YT2fo22-rIu4kKPM'),
  ('Bodyweight Isometric Split Squat Foot Elevated Calf Raise', 'https://youtu.be/mdl2K7zkcQ8?si=HIQ62ZGgxGxvMCfb'),
  ('Kettlebell Horn Grip Alternating Reverse Lunge', 'https://youtu.be/hn0H9wrT7I0?si=2puOZbS5dzRQTGh6'),
  ('Kettlebell Horn Grip Walking Lunge', 'https://youtu.be/d7cVOMtyjS8?si=-LwL939gyb_zs3lu'),
  ('Single Arm Dumbbell Suitcase Hand Assisted Ipsilateral Foot Elevated Single Leg Calf Raise', 'https://youtu.be/xASrMCHjL4M?si=-Ue1QOKJH5pRPoTH'),
  ('Bodyweight Squat Jump', 'https://youtu.be/YGGq0AE5Uyc?si=or6Xddi0YaAkHuXV'),
  ('Double Dumbbell Suitcase Alternating Step Up', 'https://youtu.be/R61TjoYofDE?si=sA8kbakWIt24ow1A'),
  ('Double Dumbbell Front Rack Step Up', 'https://youtu.be/hKLIHPXmPA4?si=mk9hkktF_4qw0okV'),
  ('Cable V Grip Seated Low Row', 'https://youtu.be/EhAho9Szp-0'),
  ('Resistance Band Half Kneeling Face Pull', 'https://youtu.be/pxnaBaRRZiY'),
  ('Bodyweight Prone Cobra', 'https://youtu.be/NZSBjpVpvw8?si=lyk8zIAtzX2ETUc_')
) AS v(name, url)
WHERE LOWER(TRIM(e.name)) = LOWER(v.name);