UPDATE exercises SET video_url = 'https://youtu.be/SreLOxzaIX4' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Turkish Sit Up');
UPDATE exercises SET video_url = 'https://youtu.be/_FjMUe0AhTY' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/PSRoSLw3GME' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/JFeG8YiLYmk' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Front Rack Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/TysYZ7rKhpM' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Horn Grip Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/x8bLCSXTChA' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/-MwL_9KOv7U?si=z-KgUayvNC37N78i' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Seated Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/2U58iHm7oSM' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Suitcase Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/yoS-cVxq28Q?si=hPjefaZ8jY6Ugoh_' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Close Grip Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/PEH5Ncie81g?si=F2eXxzjoehGGc9Bb' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Close Grip Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/K40CGYdAysc?si=AY-3wTXsp03-uRQ_' WHERE LOWER(TRIM(name)) = LOWER('EZ Bar Close Grip Decline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/7JBR6JGE1hY' WHERE LOWER(TRIM(name)) = LOWER('Cable Half Kneeling Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/AEfj6Lnn0Ao' WHERE LOWER(TRIM(name)) = LOWER('Barbell Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/ZO_ALQcMaq4?si=Sv5NmxfQj3aIKU84' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/EtEPKajf0PE' WHERE LOWER(TRIM(name)) = LOWER('Cable Tall Kneeling Pallof Press');
UPDATE exercises SET video_url = 'https://youtu.be/ykhGpORlJ4Y?si=6hFSwmMbG1lGLXki' WHERE LOWER(TRIM(name)) = LOWER('Tire Sledge Hammer Staggered Stance Slam');
UPDATE exercises SET video_url = 'https://youtu.be/0aP3tgKZcHQ' WHERE LOWER(TRIM(name)) = LOWER('Barbell Hang Power Clean');
UPDATE exercises SET video_url = 'https://youtu.be/N549md2Wu2A' WHERE LOWER(TRIM(name)) = LOWER('Landmine Goblet Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/PnBI0wLBZIg' WHERE LOWER(TRIM(name)) = LOWER('Landmine Low Hold Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/_l3ySVKYVJ8?si=PZh3DAAcRNF9txaZ' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/wbI4qof1454?si=WRjRCDTcll5n5uKu' WHERE LOWER(TRIM(name)) = LOWER('Barbell Close Grip Incline Bench Press');
UPDATE exercises SET video_url = 'https://youtu.be/JqztIwOb4Hs?si=89lHhxGXew7SEPqj' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/-TVuoR8URxg?si=RsWhCdjyNahveL9y' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/Kn3oZ9MNAhg?si=j1DYyyohu1ImlWt4' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Push Press');
UPDATE exercises SET video_url = 'https://youtu.be/cDMXXH7Y9AM?si=pObK3p_2FqS0HqbC' WHERE LOWER(TRIM(name)) = LOWER('Cable Rope Tall Kneeling Overhead Tricep Extension');
UPDATE exercises SET video_url = 'https://youtu.be/4wXnxXq4hX4?si=21E2nrYJROeQgBUm' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/oWfLP7JFwTg?si=UbP4KHHXrg5hVRnc' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/KMKqAY-T3wE?si=DccwyejeKVDgXRV-' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Kettlebell Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/r-yDtVg8Yf0?si=XQ5L1OU_VTCHZWRf' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Dumbbell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/ZQ653_FImKw?si=O2ttj0r4a_Nbkwq1' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Dumbbell Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/BDCAkIEOPvE?si=ouPFKCSuMS-REkBT' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/uk39UR9K25Y?si=s6ejJf9GtQ4llbjw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/aNllFax4shk?si=J0w79P4ud8wpm67U' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bent Over Row');
UPDATE exercises SET video_url = 'https://youtu.be/d5rLWfIN9fo?si=iiKqMHW4Xr9OMyaR' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Pendlay Row');
UPDATE exercises SET video_url = 'https://youtu.be/DjFdFkeXSDM?si=RIA3ok7NhzuAj8LK' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Shrug');
UPDATE exercises SET video_url = 'https://youtu.be/U9Z7WWNm1d4?si=pWSS4MOr8iZXWiNj' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/F6o417SxU1g' WHERE LOWER(TRIM(name)) = LOWER('Parallette Straddle L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/7wDx6mZDxA8?si=rDE21yzc81AXz5sw' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Power Slam');
UPDATE exercises SET video_url = 'https://youtu.be/L7reIo5f6uo' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Manna');
UPDATE exercises SET video_url = 'https://youtu.be/SZV1-ts76CM' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/ZFEy1s_N820' WHERE LOWER(TRIM(name)) = LOWER('Ring Full Back Lever');
UPDATE exercises SET video_url = 'https://youtu.be/4C4LDf-eZ5A?si=Uh-L_Lu-0xta0H-S' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Floor Press');
UPDATE exercises SET video_url = 'https://youtu.be/Vorw1hVd_Dc?si=CRIVCwpCzzeBwN26' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/JxlKAuD9gkA' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/eI-15uPc0yE' WHERE LOWER(TRIM(name)) = LOWER('Ring Straddle Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/rB9EcLohiVs' WHERE LOWER(TRIM(name)) = LOWER('Ring Full Front Lever');
UPDATE exercises SET video_url = 'https://youtu.be/txtXtF2-4S0' WHERE LOWER(TRIM(name)) = LOWER('Ring Inverted Hang');
UPDATE exercises SET video_url = 'https://youtu.be/i-JO6pBsKWk' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Barbell Kneeling Rollout');
UPDATE exercises SET video_url = 'https://youtu.be/ILFSDv6TaiY?si=0iUQUtwUMsGFbVuI' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Tall Kneeling Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/8TIFsF_HU_8?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Trap Bar Bench Press');