UPDATE exercises SET video_url = 'https://youtu.be/ThQT_AIqcNU?si=Y06NKpeBBOkHRplH' WHERE LOWER(TRIM(name)) = LOWER('Suspension Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ynczWiOjUqE?si=TWU55ZzVAfcrcb5B' WHERE LOWER(TRIM(name)) = LOWER('Battle Rope Single Leg Standing Alternating Wave');
UPDATE exercises SET video_url = 'https://youtu.be/QjzY6vf495U?si=dG_1Ixlx0Man-AIC' WHERE LOWER(TRIM(name)) = LOWER('Superband Assisted Dips');
UPDATE exercises SET video_url = 'https://youtu.be/ey7YgyPONOk' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Ballistic Row');
UPDATE exercises SET video_url = 'https://youtu.be/Pt-6EI8mcEU?si=Lxresx17SBitLvtO' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Overhead Press');
UPDATE exercises SET video_url = 'https://youtu.be/sng5EOSZSSo' WHERE LOWER(TRIM(name)) = LOWER('Suspension Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/dLyfCN_7JHw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Tactical Clean');
UPDATE exercises SET video_url = 'https://youtu.be/dzbJzUQjDYA?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Suspension Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/WMog8YuuVaM?si=WsH2sh1FFH3SBamT' WHERE LOWER(TRIM(name)) = LOWER('Macebell 360');
UPDATE exercises SET video_url = 'https://youtu.be/8pe73RwDAzY?si=ASSfIEGoxhWjeAi_' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Suspension Contralateral Skater Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ITUpuwk3odY?si=KGOrc3k9Flt-oF1v' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Macebell 360');
UPDATE exercises SET video_url = 'https://youtu.be/BAlXJ5lLMAA?si=H1cfMWF52YWOMraL' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/_ChDukjxUag' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Half Kneeling Rotational Swing');
UPDATE exercises SET video_url = 'https://youtu.be/_A6K7V6FHSM?si=uMrzYlHgGYbenNf1' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Clean to Push Jerk');
UPDATE exercises SET video_url = 'https://youtu.be/ECAIMMQDUC4?si=WgJIciK_Kd14WYVj' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Isometric Split Squat Low to High Chop');
UPDATE exercises SET video_url = 'https://youtu.be/aAbVFCqY4Ac' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Front Rack March');
UPDATE exercises SET video_url = 'https://youtu.be/i-q8SKGy--Q' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase March');
UPDATE exercises SET video_url = 'https://youtu.be/KpDxyxOCjCE' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Rotational Half Snatch');
UPDATE exercises SET video_url = 'https://youtu.be/MBoaZQwukmw?si=uMFzO0l7TuqVArPp' WHERE LOWER(TRIM(name)) = LOWER('Slider Single Leg Hamstring Curl');
UPDATE exercises SET video_url = 'https://youtu.be/4SXAEL7ZdSk?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Kettlebell Staggered Stance Rotational Swing');
UPDATE exercises SET video_url = 'https://youtu.be/nknf16JJTZo?si=h2lVyRQ8npFOB0v4' WHERE LOWER(TRIM(name)) = LOWER('Barbell Low Bar Pause Back Squat');
UPDATE exercises SET video_url = 'https://youtu.be/mN5Z5GH7ofM?si=5wK63ZJAw0Zc5Wti' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Pause Squat');
UPDATE exercises SET video_url = 'https://youtu.be/yXwmVzRHPPw?si=K_LXsBOKmt9dza3B' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Walking Lunge Pass Through');
UPDATE exercises SET video_url = 'https://youtu.be/6FjCQJRBNlo?si=RBXNRNqOkwVOMCGq' WHERE LOWER(TRIM(name)) = LOWER('Macebell 10 to 2');
UPDATE exercises SET video_url = 'https://youtu.be/2WxpkosHXLg?si=kPBJD_6N8w568qJ-' WHERE LOWER(TRIM(name)) = LOWER('Dumbbell Goblet Cyclist Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ulzoZOHicyU?si=OfrqYrKBRnV6RCrc' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Alternating Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/eqaz6nCxF8k?si=OEXiCUefeX011B_I' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/kaQWccrfY40' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/HNgMpdUEpgw' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Carry');
UPDATE exercises SET video_url = 'https://youtu.be/hTNWWqL9oc8?si=cTXB5vGf2EIHhx3r' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Bottoms Up Front Rack Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/WQyNCzqNqso' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Knee Hover Quadruped Pull Through');
UPDATE exercises SET video_url = 'https://youtu.be/mP1BHxBeAEM' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell High Pull');
UPDATE exercises SET video_url = 'https://youtu.be/52D7xnpFFGY?si=UBcZ3G1BNtRbk97O' WHERE LOWER(TRIM(name)) = LOWER('Double Indian Club Outer Heart Shaped Swing');
UPDATE exercises SET video_url = 'https://youtu.be/jNjDO9lEenw?si=Ci4DITj3193GY1tI' WHERE LOWER(TRIM(name)) = LOWER('Suspension Alternating Curtsy Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/_uJQvQG57Y8' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Single Leg Balance Transfer');
UPDATE exercises SET video_url = 'https://youtu.be/whSju0ip_78?si=emNV0JUVUhF8Qrf1' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/dpBy5qAG2Hs?si=x6xfYJbZr1Bols2r' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/9eDpB8LJLgQ?si=CKsCerZuXFHay_Dr' WHERE LOWER(TRIM(name)) = LOWER('Barbell Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/W2slZ8Mmyvs?si=CDhf0Oi-nPW136Jx' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Shield Cast');
UPDATE exercises SET video_url = 'https://youtu.be/Gj3ancpDFKU?si=TKfk3RmqTwztmb1j' WHERE LOWER(TRIM(name)) = LOWER('Macebell Barbarian Squat');
UPDATE exercises SET video_url = 'https://youtu.be/L1pxDgvsT9s?si=ajAmx9ThwNQY_hj2' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Clubbell Shield Cast');
UPDATE exercises SET video_url = 'https://youtu.be/uIqkGCpjsx8?si=_GzAaZAVU4-bAgla' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Mill');
UPDATE exercises SET video_url = 'https://youtu.be/ekVV4qI2q9A?si=E3yTJpSwWDur0p82' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Iron Cross');
UPDATE exercises SET video_url = 'https://youtu.be/_bnWJymK0tU?si=vYh91PF76xgOyPll' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Side Flag Press');
UPDATE exercises SET video_url = 'https://youtu.be/eGYP6B7LKtY?si=OkQLiBCrooH2qA67' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Contralateral Knee Over Toe Split Squat');
UPDATE exercises SET video_url = 'https://youtu.be/If9fXNTF4wI?si=Lk9xqqbULe2D5Xbs' WHERE LOWER(TRIM(name)) = LOWER('Double Indian Club Inner Heart Shaped Swing');
UPDATE exercises SET video_url = 'https://youtu.be/M_uslqzI28g?si=0zmBqTp2C8IMe5gJ' WHERE LOWER(TRIM(name)) = LOWER('Alternating Double Indian Club Inner Heart Shaped Swing');
UPDATE exercises SET video_url = 'https://youtu.be/uuLZZUozsdM?si=IcPMq75KQuzVIQM5' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Side Flag Press');
UPDATE exercises SET video_url = 'https://youtu.be/n8S_z0p25jA?si=fak8MwjeEUMtDoZ2' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Clubbell Inside Circle');
UPDATE exercises SET video_url = 'https://youtu.be/TUX58GM5fRQ?si=D4ei3VOcTd3GzGQn' WHERE LOWER(TRIM(name)) = LOWER('Barbell Reverse Grip Bicep Curl');