UPDATE exercises SET video_url = 'https://youtu.be/V-157r2C-qU' WHERE LOWER(TRIM(name)) = LOWER('Double Kettlebell Push Up to L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/WHi1bvZLwlw?si=NKvlsqG8aI-wDQfJ' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/8DMns2IRlg4?si=hbMMsP9DfSOthR7b' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/HvdS2ClV9KU?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Bar Hanging L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/_o_4N2yJwAw?si=Hum3bBKngYoqfDUc' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Ring Hanging L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/CQR7UUijw38?si=ncO4L8hVq2h4htQQ' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Suitcase Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/zDRj6Sw6tw8?si=Fp368ZWQaw_YDQay' WHERE LOWER(TRIM(name)) = LOWER('Parallette L Sit Flutter Kicks');
UPDATE exercises SET video_url = 'https://youtu.be/I6f7uUmozDY' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Arm Contralateral Single Leg Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/hFHpQAqqMDA' WHERE LOWER(TRIM(name)) = LOWER('Parallette Tuck Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/kpOpHoywVKU' WHERE LOWER(TRIM(name)) = LOWER('Ring Maltese Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/cVdb8oUGKAw?si=tC4dDZ3QsBtE_4_m' WHERE LOWER(TRIM(name)) = LOWER('Bar Advanced Tuck Front Lever Pull Up');
UPDATE exercises SET video_url = 'https://youtu.be/58QkcGVA12A?si=ddrndE8UqnvYVadB' WHERE LOWER(TRIM(name)) = LOWER('Bar Gironda Sternum Chin Up');
UPDATE exercises SET video_url = 'https://youtu.be/t8_M2aHiNDk?si=s9zri6LcdUJrvwbV' WHERE LOWER(TRIM(name)) = LOWER('Bar Strict Muscle Up');
UPDATE exercises SET video_url = 'https://youtu.be/U-MgWVM_2-Y?si=-XnkVL5OAVXtyCPu' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Tuck Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/2t7u5sapU1Q?si=KigwClnysDsb8CGJ' WHERE LOWER(TRIM(name)) = LOWER('Double Clubbell Asynchronous Mill');
UPDATE exercises SET video_url = 'https://youtu.be/pO4BH0dKCIY?si=qKwpWcDltQZ0K61z' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/l-7PDo_nf-c?si=SV8BnhirXI2QflsN' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Single Arm L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/X8I4Uq4QgYE?si=0ZNJz2TPEC0nSZaa' WHERE LOWER(TRIM(name)) = LOWER('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/vVElqek25fI?si=4-FGE3vFSRTkYdG4' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Alternating Lateral Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/oOB02xJgzrA?si=IO-ooFFstcNesTGD' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/tildBryP8bI?si=mIky-m7uqR4kMvB3' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/q7sQB0_p7XQ?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/i3tkgdhZuj0?si=lupWBeLYXNXi2bV0' WHERE LOWER(TRIM(name)) = LOWER('Parallette V Sit to Pike Press Handstand');
UPDATE exercises SET video_url = 'https://youtu.be/f09iB8jbioo?si=MFJiOigiohOtQybY' WHERE LOWER(TRIM(name)) = LOWER('Ring Pseudo Planche Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/8Ta_A9vAEGs?si=pSj3gDFijzwcALE4' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball Feet Elevated Glute Bridge');
UPDATE exercises SET video_url = 'https://youtu.be/kLh-uczlPLg?si=WfwS9PlCOc9d1t1N' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/XiB48dLaB9g?si=RkTU535X9lQ-XULA&amp;utm_source=MTQxZ' WHERE LOWER(TRIM(name)) = LOWER('Suspension Feet Elevated Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/XS7Y1jQ-kxs?si=hFDuiao7cTRRHUCT' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Straddle L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/xhyigP6lpAM?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Front Rack Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/lyMHR7F8lPA?si=An72TBlVkZQu4GMO' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Cossack Squat');
UPDATE exercises SET video_url = 'https://youtu.be/ZDhNSacJLEE?si=aGw3Fw5a7Q34pWuk' WHERE LOWER(TRIM(name)) = LOWER('Bodyweight Wall Facing Handstand Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/4zSzWYRiBGI?si=NqLN5I_ZFwPkfPXM' WHERE LOWER(TRIM(name)) = LOWER('Ring Pelican Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/_iZ9bGw84H8?si=4Ff3XGU-WRY1uN0k' WHERE LOWER(TRIM(name)) = LOWER('Barbell Back Rack Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/b8ldbeOnJEI?si=PBXslcF1v1YEXgGU' WHERE LOWER(TRIM(name)) = LOWER('Barbell Front Rack Alternating Step Up');
UPDATE exercises SET video_url = 'https://youtu.be/HdaAXHcN0-M?si=fT7_2ec7wdcSALfm' WHERE LOWER(TRIM(name)) = LOWER('Ring Feet Elevated Pelican Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/Vuc-nodHS0Y?si=S81fiCUEtPrZUe6Z' WHERE LOWER(TRIM(name)) = LOWER('Ring Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/SLyOG8ujcu0?si=IAzc53JTuuKNMz90' WHERE LOWER(TRIM(name)) = LOWER('Ring Hanging Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/QA_dH6cjbw0?si=29xMuvVPe0ttRvvK' WHERE LOWER(TRIM(name)) = LOWER('Bar Hanging Tuck L Sit');
UPDATE exercises SET video_url = 'https://youtu.be/LMStE_hD9E4?si=_iskUn08-BQH0mYu' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Alternating Forward Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/5BaV4f58I3c?si=LhV-BmrDvHK1G_uI' WHERE LOWER(TRIM(name)) = LOWER('Ring Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/kbPOFMH-Ivk?si=ftd7bXesKjVBgNrW' WHERE LOWER(TRIM(name)) = LOWER('Ring Feet Elevated Mountain Climber');
UPDATE exercises SET video_url = 'https://youtu.be/neuw_JknIms?si=QPBFpV8bvbtlFLfL' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/uMcoQ-ijpsk' WHERE LOWER(TRIM(name)) = LOWER('Ring Dead Hang');
UPDATE exercises SET video_url = 'https://youtu.be/iHR7BprMyEc' WHERE LOWER(TRIM(name)) = LOWER('Parallette Kneeling Push Up');
UPDATE exercises SET video_url = 'https://youtu.be/9lVJZ8o8nzM?si=4NnTRdg9x60PkNsZ' WHERE LOWER(TRIM(name)) = LOWER('Clubbell Outside Circle');
UPDATE exercises SET video_url = 'https://youtu.be/N4GPqbj8Nds?feature=shared' WHERE LOWER(TRIM(name)) = LOWER('Single Arm Kettlebell Bottoms Up Overhead Alternating Reverse Lunge');
UPDATE exercises SET video_url = 'https://youtu.be/1jP1PR9Gls0?si=esOirS5dWd5oUqG0' WHERE LOWER(TRIM(name)) = LOWER('Stability Ball T''s Y''s I''s');
UPDATE exercises SET video_url = 'https://youtu.be/C2wsrjVHvuA' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Reverse Fly');
UPDATE exercises SET video_url = 'https://youtu.be/1feV0cW5U60?si=e6dhNFXt6CLSbkRE' WHERE LOWER(TRIM(name)) = LOWER('Resistance Band Lateral Raise');
UPDATE exercises SET video_url = 'https://youtu.be/XPPfnSEATJA?si=yNFrwT2Aj4G98NVF' WHERE LOWER(TRIM(name)) = LOWER('Double Dumbbell Lateral Raise');